= K

k   simbol   (dise ‘ka’)
La letera 11 de la alfabeta roman
en   k

Kalahari, Deserto   nom
Un plano alta, vasta e seca en Africa sude, a norde de la Rio Orania
en   Kalahari Desert

Kansas   nom
Un stato en la SUA sentral
en   Kansas (US state)

Karakum, Deserto   nom
Un deserto en Asia sentral, a este de la Mar Caspio
en   Karakum Desert, Gara-Gum Desert

Karimata, Streta   nom
Un streta entre Sumatra e Borneo
en   Karimata Strait

Kattegat   nom
Un streta entre Noria e Danmarc
en   Kattegat

Kentucky   nom   (dise ‘centaci’)
Un stato en la SUA sude-este
en   Kentucky (US state)

Kerguelen, Isolas   nom, plural
Un grupo de isolas en la sude de la Mar Indian
en   Kerguelen Islands

Kilimanjaro, Monte   nom
Un volcan estinguida en Tanzania norde
en   Mount Kilimanjaro

Kivu, Lago   nom
Un lago en Africa sentral, entre Ruanda e la Republica Democrata de Congo
en   Lake Kivu

Kizilkum, Deserto   nom
Un deserto en Asia sentral, entre la Rio Amudarya e Rio Syrdarya
en   Kyzylkum, Qyzylqum

Kobenhavn   nom
La site capital de Danmarc
en   Copenhagen

Kongzi   nom   (dise ‘kongtsi’)
Un filosofiste e politiciste de Jonguo antica e la fundor de la filosofia sosial la plu influente en Jonguo (551-479 aec)
→ confuzisme
en   Confucius (philosopher)

Kyushu   nom
La isola la plu sude de Nion
en   Kyushu
