= H

h   simbol   (dise ‘hax’)
La letera oto de la alfabeta roman
en   h

ha   esclama
Espresante ce on es surprendeda, ce on ia vinse, ce on ia fa un descovre, o un otra reata simil
en   ha

»  ha ha   esclama
Espresante un rie
en   ha ha (laughing)
es   ja, ja, ja (riendo)

haca   ajetivo
Pertinente a un popla de Jonguo sude-este, o a sua dialeto de xines
en   Hakka (person, language)

»  haca   nom
en   Hakka (person, language)

haca   nom
Un dansa ritual de gera maori, con canta lenta
en   haka (dance)

hadj   nom
La peregrina muslim a Makka cual aveni en la mense final de la anio, obligante per cada muslim a minima un ves en sua vive
en   hajj (pilgrimage)
es   hach (peregrinación)

hadji   nom
Un muslim ci ia vade ja a Makka como un peregrina
en   hajji (pilgrim)
es   hach (peregrino)

hadrosauro   nom
Un dinosauro grande, erbivor e xef bipede de la cretasica, con un mandibula plata como la beco de un pato
Hadrosauridae
en   hadrosaur, hadrosaurus
es   hadrosaurio

hafnio   nom   «Hf»
La elemento cimical con numero atomal 72
en   hafnium (element)
es   hafnio (elemento)

hagis   nom
Un plato scotes, composada de la organos de un ovea o boveta, miscada con gras de ren, gaxa de avena e spises, e bolida en un saco, tradisional preparada de la stomaco de la animal
en   haggis (food)
es   haggis (comida)

Haiastan   nom
Un pais sin costa en la Caucasos en Asia sude-ueste
(capital: Ierevan)
→ Armenia
en   Armenia
es   Armenia

»  haiaren   ajetivo
→ armenian
en   Armenian (person, language)
es   armenio (persona, lengua)

»  haiaren   nom
en   Armenian (person, language)
es   armenio (persona, lengua)

haicu   nom
Un poesia nion con tre linias de sinco, sete e sinco silabas
en   haiku (poetry)
es   haiku (poema)

haida   ajetivo
Pertinente a un popla de americanes orijinal de la costas de Columbia Brites e Alaska sude-este, o a sua lingua
en   Haida (person, language)

»  haida   nom
en   Haida (person, language)

Hainan   nom
Un isola en la Mar Xina Sude cual es un rejion autonom de Jonguo
en   Hainan (island)

halal   ajetivo
Pertinente a carne preparada en la modo prescriveda par lege muslim
en   halal

»  halal   nom
en   halal meat

halter   nom
Un bara corta con un pesa a cada fini, levada per crese la musculos de braso
en   dumbbell

halter   nom
Un de la du organos de ecuilibra de un mosca
en   halter, haltere

halumi   nom
Un ceso blanca, blanda e firma de Cipros
en   halloumi

halux   nom
La diton de la pede
en   hallux, big toe (technical)

»  halux valga   nom
en   bunion

Hampshire Nova   nom   (dise ‘hámpxer’)
Un stato en la SUA norde-este
en   New Hampshire (US state)

han   nom
La titulo de renores e ofisiores en Asia sentral e alga otra nasiones muslim; la titulo de la imperores mongol
en   khan, khagan (governor)

»  hania   nom
La impero o otra rena de un han
en   khanate, khaganate

han   ajetivo
Pertinente a la dinastia cual ia rena Jonguo de 206 aec a 220 ec
en   Han (dynasty)

handbal   nom
Un sporte en cual du ecipos usa sua manos per colpa un bal en dirije a goles
en   handball (sport)

hangugo   ajetivo
Pertinente a la popla de Tehan o Txoson, o a sua lingua
→ corean
en   Korean (person, language)

»  hangugo   nom
en   Korean (person, language)

hangul   nom
La alfabeta usada per scrive hangugo
en   hangul, hangeul (writing system)
fr   hangul, hangeul

hantavirus   nom
Un virus transportada par rodentes, cual causa alga maladias con febre e emoraje, tipal con dana a o fali de la renes
en   hantavirus (medical)

hanuca   nom
Un festa iudi de oto dias en desembre, recordante la rededica de la Templo en 165 aec
en   Hanukkah (Jewish festival)

haraciri   nom
Un suiside ritual nion, fada par desventri con un spada, istorial praticada par samurais como un alternativa de desonora o esecuta
en   harakiri (disembowelment)

hascala   nom
Un promove de moderni e seculari entre iudis european en la sentenios 18 e 19
en   Haskalah, Jewish Enlightenment

hasidisme   nom
Un seta fundaliste de iudisme, derivada de un seta mistica de Polsca de la sentenio 18
en   Hasidism (Judaism)

»  hasidiste   ajetivo
en   Hasidic

»  hasidiste   nom
en   Hasid

hasio   nom   «Hs»
La elemento cimical con numero atomal 108
en   hassium (element)

hausa   ajetivo
Pertinente a un popla de Nijeria norde e rejiones prosima, o a sua lingua txadica
en   Hausa (person, language)

»  hausa   nom
en   Hausa (person, language)

Hawaii   nom
Un stato en la SUA, composada de un grupo de isolas en la Mar Pasifica norde
en   Hawaii (US state)

»  hawaian   ajetivo
en   Hawaiian

»  hawaian   nom
en   Hawaiian

»  Isolas Hawaian   nom, plural
Un arcipelago de isolas en la Mar Pasifica norde cual formi la stato Hawaii
en   Hawaiian Islands

haxix   nom
Un droga recreal en familia de canaba
en   hashish

hazar   nom
Pertinente a un tribu turcica de relijio iudi cual ia ocupa Hazaria
ca   khàzar
de   Chasar
en   Khazar
es   jázaro
fr   Khazar
it   cazaro
pt   cazar
ru   хазар

Hazaria   nom
Un parte istorial de Rusia sude-ueste e Ucraina
en   Khazaria

he   esclama
Atraente la atende de algun
en   hey, ahoy

Hebrides   nom, plural
en   Hebrides

»  Hebrides Esterna   nom, plural
Un cadena de isolas a la costa ueste de Scotland
en   Outer Hebrides

»  Hebrides Interna   nom, plural
Un arcipelago a la costa ueste de Scotland, a sude-este de la Hebrides Esterna
en   Inner Hebrides

Hecate, Streta   nom
Un streta a ueste de Columbia Brites
en   Hecate Strait

hemicordato   nom
Un membro de un filo de deuterostomios de mar, solitar e formida como vermes
Hemichordata
en   hemichordate (organism)

hena   nom
La folias polvida de un arboreta tropical, usada como un tinjente per colori la capeles e decora la corpo; la arboreta cual produi esta
Lawsonia inermis
en   henna (plant, dye)

henri   nom
La unia internasional per mesura indui eletrical
en   henry (unit of inductance)

hentai   nom
Un anime o manga pornografial
ca   hentai
en   hentai (manga)
es   hentai
fr   hentai
it   hentai

Hercule   nom
(En mitos elinica e roman) un eroe con coraje e fortia supraumana ci ia fa 12 taxes grande e, pos mori, ia deveni un dio; un constela norde grande
en   Hercules (mythology, constellation)

»  herculin   ajetivo
en   Herculean

Hersegovina   nom
Un rejion en la Balcanes, la parte sude de Bosnia e Hersegovina
en   Herzegovina

»  hersegovasce   ajetivo
en   Herzegovinian

»  hersegovasce   nom
en   Herzegovinian

herze   nom
La unia internasional per mesura frecuentia, egal a un sicle per secondo
en   hertz

hi hi   esclama
Espresante un rieta nervosa o ascondeda
en   hee-hee, tee-hee (giggling)

hibatxi   nom
Un casola o brasador nion en cual on arde carbon de lenio per caldi un casa; un aparato simil per coce
en   hibachi (heater)

hidjab   nom
Un covrente per la testa, portada par alga femes muslim estra casa
en   hijab (garment)

hidjra   nom
La vade de Makka a Medina par Muhammad en 622; la eda muslim cual ia comensa alora
en   hejira (Islam)

hifa   nom
Un de la filetas raminte cual composa la miselio de un fungo
en   hypha

Himalaia   nom
Un rejion montaniosa en Asia sude cual estende de Caxmir en la ueste a Assam en la este
en   Himalayas (region)

»  himalaian   ajetivo
en   Himalayan

»  Montes Himalaia   nom, plural
Un cadena de montes multe alta en Himalaia
en   Himalaya Mountains, Himalayas

hindi   ajetivo
Pertinente a la lingua industani la plu comun parlada en Barat norde, scriveda en devanagari con multe parolas prendeda de sanscrito
en   Hindi (language)

»  hindi   nom
en   Hindi (language)

hiolito   nom
Un membro de un clase de animales con concas peti e cono, conoseda como fosiles paleozoica
hyolitha
en   hyolith (fossil)

hiphop   ajetivo
Un moda de musica creada par americanes negra e latina, cual inclui rap con fondo eletronical; un forma de dansa relatada a esta
en   hip-hop (dance, music)

hipi   nom
Un person de aspeta nonconformante, tipal con capeles longa e vestes diferente, de un sucultur pasiste cual rejeta valuas abitual e usa drogas alusinojen
en   hippy, hippie

Hipocrate   nom
Un mediciste famosa de Elas antica
en   Hippocrates

»  jura de Hipocrate   nom
en   Hippocratic oath

hiragana   nom
La forma la plu comun de la du formas de scrive silabal usada en Nion
en   hiragana (writing system)

hitita   ajetivo
Parteninte a un popla antica ci ia fundi un impero en Anatolia e Suria cual ia flori de 1700 a 1200 aec, o a sua lingua
en   Hittite (person, language)

»  hitita   nom
en   Hittite (person, language)

hm   esclama
Espresante ce on considera o vole atrae atende
en   hmm (thinking); ahem (clearing throat)

ho ho ho   esclama
Espresante un rie basa, asosiada con San Nicolas (acc Santa Claus), spesial en America Norde
en   ho ho ho

hobit   nom
Un membro de un raza de umanas peti en la obras de JRR Tolkien
en   hobbit

hoci   nom
Un jua de ecipos, en cual on usa bastos oncida per gida un bal a goles a finis oposada de la campo
en   hockey, field hockey

»  hoci de campo   nom
en   field hockey

»  hoci de jelo   nom
Un varia de esta jua, fada sur jelo en patines, con un disco de cauxo
en   ice hockey

»  hoci eres   nom
en   hurling

Hokkaido   nom
La isola la plu norde de la cuatro isolas de Nion
en   Hokkaido (island)

holding   nom
Un compania creada per compra e posese asiones de otra companias, per controla estas
en   holding company
eo   holdingo
fr   holding

holmio   nom   «Ho»
La elemento cimical con numero atomal 67
en   holmium (element)

holo   ajetivo
Pertinente a un popla de Taiuan, o a sua lingua
en   Hoklo, Taiwanese Hokkien (person, language)

»  holo   nom
en   Hoklo, Taiwanese Hokkien (person, language)

holozon   nom
Un membro de un clado de organismes cual inclui animales e sua relatadas uniselulal la plu prosima, ma cual esclui fungos
en   holozoon (pl. holozoa) (organism)

holstain   nom
Un bove de un raza de Holstein en Deutxland, elevada per lete, tipal blanca-negra
en   holstein (cow)

Homero   nom
Un poesiste elinica antica de la sentenio 8 aec, a ci on atribui tradisional la Iliada e la Odisea
en   Homer

»  homeral   ajetivo
en   Homeric

Hongkong   nom
Un rejion cuasi autonom a la costa sude-este de Jonguo
en   Hong Kong

Honshu   nom
La plu grande de la cuatro isolas major de Nion
en   Honshu (island)

hopi   ajetivo
Pertinente a un popla de americanes orijinal de un rejion de Arizona norde-este en la SUA, o a sua lingua
en   Hopi (person, language)

»  hopi   nom
en   Hopi (person, language)

Hormuz   nom
en   Hormuz

»  Streta Hormuz   nom
Un streta a la boca de la Golfo Persian
en   Strait of Hormuz

hornpip   nom
Un dansa vivosa de Britan, asosiada con marinores; un musica per esta
en   hornpipe (dance, music)

Huanghai, Mar   nom
Un parte de la Mar Xina Este entre Corea e Jonguo
→ Jala
en   Huang Hai, Yellow Sea

Huanghe, Rio   nom
Un rio en Jonguo cual comensa en la montanias de Jonguo ueste-sentral e fini en la Mar Huanghai
en   Huang He, Yellow River

Hudson   nom
en   Hudson

»  Baia Hudson   nom
Un mar a norde de Canada, ensircada par Canada e sua isolas norde
en   Hudson Bay

»  Rio Hudson   nom
Un rio en York Nova este cual flue a lado de Manhattan
en   Hudson River

»  Streta Hudson   nom
Un streta entre Quebec e la Isola Baffin
en   Hudson Strait

hula   nom
Un dansa de Hawaii cual inclui ses pasos fundal, ancas ondante e jestis simbolinte
en   hula (dance)

hun   ajetivo
Pertinente a un popla nomada de Asia ci ia ataca Europa entre 300 e 500, ativinte la move de multe otra poplas e ultima la fini de la Impero Roman antica
en   Hunnic

»  hun   nom
en   Hun

huri   nom
Un fem joven e bela, tipal un de la virjines cual acompania la fidosas en la paradiso muslim
en   houri (Islam)

Huron, Lago   nom
Un de la sinco Lagos Grande de America Norde, entre Canada e la SUA
en   Lake Huron

husar   nom
Un cavalor lejera armada de Magiar en la sentenio 15
en   hussar (soldier)

husci   nom
Un can forte con pelo duple, tipal gris, usada en zonas artica per tira trenos tra neva
en   husky (dog)

husisme   nom
Un promove relijiosa inisiada en Txesco par Jan Hus, ci ia es ardeda en 1415
en   Hussitism (Christianity)

»  husiste   ajetivo
en   Hussite

»  husiste   nom
en   Hussite

huterita   ajetivo
Pertinente a un varia de cristianisme fundida en Moravia en la sentenio 16, o a la comunia en America Norde con credes simil cual pratica un modo de vive simple e comunial
en   Hutterite (Christianity)

»  huterita   nom
en   Hutterite (Christianity)

huti   ajetivo
Pertinente a un tribu de xias de Iaman, cual ia saisi cuasi un controla completa de Iaman en 2015
en   Houthi (Islam)

»  huti   nom
en   Houthi (Islam)

hutu   ajetivo
Pertinente a la popla major de Ruanda e Burundi, o a sua lingua bantu
en   Hutu (person, language)

»  hutu   nom
en   Hutu (person, language)
