= M

m   simbol   (dise ‘em’)
La letera 13 de la alfabeta roman
en   m

ma   conjunta
Introduinte alga cosa cual contrasta con lo cual es ja diseda
en   but, whereas
fr   mais

maa   esclama
La sona fada par un ovea o capra
→ bala
en   baa

Maca   nom
Un site en Arabia Saudi, regardada par muslimes como la site la plu santa de islam
en   Mecca

macabre   ajetivo
Asustante e repulsante par sua descrive o presenta de mori e feri
en   macabre, grim, ghoulish, ghastly, grisly, gruesome

macaca   nom
Un simia de grandia media, con fas longa e poxes en sua jenas per porta comedas
Macaca
en   macaque

»  macaca resus   nom
Macaca mulatta
en   rhesus monkey, rhesus macaque

macadamia   nom
Un arbor de Australia; la noza de esta
Macadamia
en   macadamia (tree)

macaron   nom
Un biscoto de blanca de ovo, zucar, e tipal amandas moleda o coco
en   macaroon

macaroni   nom
Un pasta con forma de tubos streta
en   macaroni

Macau   nom
Un parte de Jonguo a la costa sude-ueste, un dependente de Portugal ante 1999
en   Macau, Macao

»  macau   ajetivo
en   Macanese

»  macau   nom
en   Macanese

Macedonia   nom
Un pais sin costa en la Balcanes; un pais antica en Europa sude-este, a norde de Elas antica
(capital: Scopie)
en   Macedonia

»  macedonsce   ajetivo
en   Macedonian

macero   nom
Un pex migrante, comersial importante como un comeda
Scombridae, Carangidae
en   mackerel
fr   maquereau

macia   verbo transitiva
Aplica polvos o cremas colorida a (la fas) per boni o cambia la aspeta
en   make up, apply cosmetics to
fr   maquiller

»  macia   nom
en   makeup, cosmetics
fr   maquillage

»  macia de teatro   nom
en   greasepaint

»  desmacia   verbo transitiva
en   remove makeup from

»  desmaciante   nom
en   cleanser

»  maciste   nom
en   makeup artist
fr   maquilleur, maquilleuse

macina   nom
Un aparato, tipal con multe partes, cual usa o aplica potia macinal per un taxe spesifada
en   machine, mechanism
fr   machine

»  macina de fili   nom
en   spinning wheel

»  macina de soma   nom
en   adding machine

»  macina de tempo   nom
en   time machine

»  macina de vapor   nom
en   steam engine

»  macinal   ajetivo
en   mechanical, clockwork

»  macinas   nom, plural
en   machines, machinery

»  macineta   nom
en   device, gadget, contraption

»  macini   verbo transitiva
en   mechanize

»  maciniste   nom
en   mechanic, machinist; artificer

macrame   nom
La arte de usa nodas en motifes per composa ojetos ornal
en   macrame (art)

macro   ajetivo
en   closeup (image)

»  macro   nom
Un foto, filma o video cual mostra sua sujeto como prosima; un descrive detaliosa o intima; (en informatica) un regula per cambia un enflue spesifada a un comanda o esflue spesifada
en   closeup; macro (software)

»  macro-   prefisa
Grande
en   macro- (large)

macrocosmo   nom
La intera de un strutur complicada, spesial si esemplida par un parte peti de se
en   macrocosm

macrofago   nom
Un fagosite trovada en un forma nonmovente en la texedas o como un selula blanca de sangue, tipal a locas de un infeta
en   macrophage (biology)

macrosefalia   nom
Un malformi jenetical, marcada par un testa nonormal grande
en   macrocephaly (medical)

»  macrosefalica   ajetivo
en   macrocephalic, macrocephalous

macula   nom
Un area jala e oval sirca la fovea, prosima a la sentro de la retina, cual es la area de vide plu agu
en   macula, macula lutea (anatomy)

»  maculal   ajetivo
en   macular

Madagasicara   nom
Un isola e pais en la Mar Indian, a este de Africa este
(capital: Antananarivo)
→ malagasi
en   Madagascar

»  malagasi   ajetivo
→ Madagasicara
en   Malagasy

»  malagasi   nom
en   Malagasy

madalena   nom
Un torta peti, tipal fornida en molda concin e decorada con coco e jalea
en   madeleine (cake)

Madera   nom
en   Madeira (island)

»  Isolas Madera   nom, plural
Un grupo de isolas en la Mar Atlantica prosima a la costa de Africa norde-ueste, e un rejion autonom de Portugal
en   Madeira Islands

madjong   nom
Un jua xines, normal per cuatro persones, con 136 o 144 telias retangulo de cual on atenta colie grupos
en   mahjong (game)

madona   nom
La virjin Maria; un imaje de el; un fem virtuosa
en   madonna

madras   nom
Un stofa de coton, forte ma con trama delicata, con bandetas o cuadros
en   madras (fabric)

madre   nom
Un fem o animal fema en relata a un enfante o enfantes ci el ia pari; un fem o animal fema ci cura un enfante o enfantes en la mesma modo
en   mother
fr   mère

»  madre de batiza   nom
en   godmother
fr   marraine

»  madre e padre   nom
en   mother and father, parents

»  madre futur   ajetivo
en   mother-to-be
fr   future mère

»  madre par sposi   nom
en   mother-in-law
fr   belle-mère (la mère du conjoint)

»  madre sin sposo   nom
en   single mother
fr   mère célibataire

»  estramadre   nom
en   stepmother
fr   belle-mère (par remariage du père)

»  madral   ajetivo
en   maternal; maternity (leave, dress)

»  madria   nom
en   motherhood, maternity
fr   maternité

»  madrin   ajetivo
en   motherly
fr   maternel

»  madrin   nom
en   mother figure, godmother
fr   marraine

»  madron   nom
en   matriarch
fr   matriarche

»  sin madre   ajetivo
en   motherless

madrigal   nom
Un forma de canta de la Renase, con plu ca un vose ordinada en contrapunto, tipal sin strumentos
en   madrigal (music)

madriside   verbo transitiva
Mata (sua propre madre)
en   commit matricide

»  madriside   nom
en   matricide (action)

»  madrisidor   nom
en   matricide (person)

mafia   nom
Un organiza internasional de criminales, orijinal de Sisilia e aora en Italia e la SUA, notable per sua condui cruel; cualce grupo con condui simil
en   mafia

»  mafior   nom
en   mafioso, member of a mafia

Magallanes, Streta   nom
Un streta cual separa la Tera de Foco de la resta de America Sude
en   Strait of Magellan

Magiar   nom
Un pais sin costa en Europa sentral
(capital: Budapest)
→ Ungaria
en   Hungary
fr   Hongrie

»  magiar   ajetivo
en   Hungarian
fr   hongrois

»  magiar   nom
en   Hungarian
fr   Hongrois

magma   nom
Materia fluente o partal licuida su o en la crosta de la Tera, de cual lava e otra roca magmal deriva pos fri
en   magma (geology)

»  magmal   ajetivo
en   magmatic, igneous

magnesio   nom   «Mg»
La elemento cimical con numero atomal 12, un metal arjentin
en   magnesium

magnete   nom
Un peso de fero cual atrae otra ojetos conteninte fero, e cual alinia se en un campo magnetal esterna
en   magnet
fr   aimant

»  magnetal   ajetivo
en   magnetic
fr   magnétique

»  magneti   verbo nontransitiva
en   magnetize/magnetise

»  magneti   verbo transitiva
en   magnetize/magnetise

»  magneti   nom
en   magnetization/magnetisation

»  magnetia   nom
en   magnetism
fr   magnétisme

magnetometre   nom
Un aparato usada per mesura fortes magnetal, tipal de la Tera
en   magnetometer

»  magnetometria   nom
en   magnetometry

magnolia   nom
Un arbor o arboreta con flores ros grande
Magnolia
en   magnolia

magra   ajetivo
Con lados oposada cual es prosima a lunlotra
en   thin, slim, slender, svelte, lean, willowy, skinny, narrow, fine, gracile; gaunt, paltry, meager/meagre
fr   maigre, mince

»  magri   verbo nontransitiva
en   thin, slim, emaciate

»  magri   verbo transitiva
en   thin, slim, constrict

»  magri   nom
en   thinning, emaciation, constriction

»  magria   nom
en   thinness, slimness, slenderness

Magrib   nom
Un pais en Africa norde-ueste, con costas a la Mar Mediteraneo e la Mar Atlantica
(capital: Rabat)
→ Maroco
en   Morocco
fr   Maroc

»  magribi   ajetivo
en   Moroccan
fr   marocain

»  magribi   nom
en   Moroccan
fr   Marocain

mahaiana   ajetivo
Un seta de budisme comun en Jonguo, Corea e Nion
en   Mahayana (Buddhism)

maharaja   nom
Un prinse barati
en   maharajah (Indian prince)

maharani   nom
Un prinsesa barati
en   maharani (Indian princess)

maharixi   nom
Un saja induiste
en   maharishi (Hinduism)

mahatma   nom
(En Asia sude) un person adorada per sua virtua
en   mahatma (holy person)

mahimahi   nom
Un pex grande con pinas raiosa
Coryphaena hippurus
en   mahi-mahi, dolphinfish

Mahore   nom
Un isola en la Mar Indian, a este de Comori
en   Mahore (island)

»  mahores   ajetivo
en   Mahoran

»  mahores   nom
en   Mahoran

maia   ajetivo
Pertinente a un de la tribus orijinal de Yucatan e rejiones prosima
en   Mayan

»  maia   nom
en   Mayan

maiasauro   nom
Un dinosauro grande e erbivor, con testa cual aspeta como un pato
en   maiasaurus (dinosaur)

Maine   nom   (dise ‘mein’)
Un stato de la SUA norde-este, a la costa de la Mar Atlantica
en   Maine (US state)

»  Golfo Maine   nom
Un golfo a este de Maine, un estende de la Mar Atlantica
en   Gulf of Maine

mainel   nom
Un bara vertical cual divide partes de un fenetra
en   mullion (architecture)

maio   nom
La mense sinco de la calendario gregorian
en   May
fr   Mai

maiones   nom
Un salsa densa e cremin, preparada de jalas de ovos bateda con olio e vinagra e spisida
en   mayonnaise, mayo

maior   nom
La xef elejeda de un site, vila o otra munisipa
en   mayor
fr   maire

»  maioral   ajetivo
en   mayoral

»  vismaior   nom
en   vice-mayor, alderman

mais   nom
Un planta sereal con granes grande; esta granes, usada per comeda de umanas e bestias
Zea mays
en   corn, maize
fr   maïs

»  mais moleda   nom
en   hominy

maitili   ajetivo
Pertinente a la popla de Bihar norde e rejiones prosima
en   Maithil, Maithili (person, language)

»  maitili   nom
en   Maithil, Maithili (person, language)

maitnerio   nom   «Mt»
La elemento cimical con numero atomal 109, nomida per Lise Meitner
en   meitnerium (element)

majel   ajetivo
en   Marshallese

»  majel   nom
en   Marshallese, Marshall Islander

»  Isolas Majel   nom, plural
Un pais de du cadenas de isolas en la Mar Pasifica norde-ueste
(capital: Majuro)
en   Marshall Islands

majenta   ajetivo
Con color pal purpurin roja
en   magenta

»  majenta   nom
en   magenta

»  majenti   verbo nontransitiva
en   turn magenta

»  majenti   verbo transitiva
en   turn magenta

majia   nom
La potia de afeta avenis par metodos supranatural; trucos cual pare nonposible, presentada como un diverti
en   magic, sorcery
fr   magie

»  majia de mano   nom
en   sleight of hand, prestidigitation
fr   prestigitation

»  majial   ajetivo
Pertinente a majia
en   magic
fr   magique

»  majiosa   ajetivo
Plen de majia; funsionante par majia
en   magic, magical
fr   magique

»  majiste   nom
en   magician, conjuror
fr   magicien

majo   nom
Un membro de la casta de pretes de Persia antica
en   mage, magus (pl. magi)

major   ajetivo
Multe importante, grave o potiosa; (un person con la mesma nom como un otra) la plu vea
en   major, key; great; senior, the elder

»  major   nom
en   major (officer)
fr   commandant (officier)

»  majori   verbo nontransitiva
en   capitalize/capitalise, convert to uppercase

»  majori   verbo transitiva
en   capitalize/capitalise, convert to uppercase

»  majoria   nom
en   majority, preponderance
fr   majorité

majoran   nom
Un planta en familia de menta, usada en cosini
Origanum majorana
en   marjoram (plant)
fr   origan, marjolaine

Makasar, Streta   nom
Un streta entre Borneo e Sulawesi
en   Makassar Strait

mal   ajetivo, prenomal
Con cualia basa; con capasia minima; nonmoral; nonvalida; noncoreta
en   bad, invalid, wrong
fr   mauvais

»  mal   averbo
en   badly, wrongly
fr   mal

»  mal-   prefisa
Ajuntada a un verbo per formi un verbo per un ata plu mal, tipal spesialida
‹ malodori; maldise ›
en   mis-, bad-, ill- (added to verbs: a worse variant of the action, often a specialized sense)

»  fa mal   verbo
en   do wrong

»  mal fa   nom
en   wrongdoing, bad deed

»  mali   verbo nontransitiva
en   turn bad, become corrupt; worsen, degenerate, deteriorate, spoil

»  mali   verbo transitiva
en   make bad, corrupt; worsen, exacerbate, aggravate

»  mali   nom
en   worsening, degeneration, deterioration, corruption, exacerbation

»  malia   nom
en   evil

»  malida   ajetivo
en   deteriorated, corrupt, degenerate, spoiled (food)

»  nonmalida   ajetivo
en   unspoiled, uncorrupted, unsullied

»  plu mal   ajetivo
en   worse
fr   pire

malacita   nom
Un mineral verde, composada de carbonato de cupre
en   malachite (mineral)

malada   ajetivo
No sana; con mal state de corpo o mente
en   sick, ill, unwell, indisposed
fr   malade

»  malada   nom
en   invalid

»  malada de ama   ajetivo
en   lovelorn, lovesick
fr   qui se languit d’amour, éperdument amoureux, follement amoureuse

»  malada de cor   ajetivo
en   heartsick

»  malada de mar   ajetivo
en   seasick

»  malada de posenebria   ajetivo
en   hung over
fr   qui a la gueule de bois

»  maladeria   nom
en   infirmary, sick bay

»  maladerior   nom
en   infirmary nurse

»  maladi   verbo nontransitiva
en   sicken, become sick, fall ill
fr   tomber malade

»  maladi   verbo transitiva
en   make ill
fr   rendre malade

»  maladia   nom
en   disease, illness, sickness, ailment, malady
fr   maladie

»  maladia de altia   nom
en   altitude sickness

»  maladia de ama   nom
en   lovesickness

»  maladia de bestias   nom
en   murrain

»  maladia de descompresa   nom
en   decompression sickness, the bends

»  maladia de dormi   nom
en   sleeping sickness, trypanosomiasis
fr   maladie du sommeil

»  maladia de mar   nom
en   seasickness
fr   mal de mer

»  maladia de Parkinson   nom
en   Parkinson’s disease, parkinsonism

»  maladia de vola   nom
en   airsickness

»  maladiosa   ajetivo
en   sickly
fr   maladif

malagatani   nom
Un sopa de gal o otra carne con cari, orijinante en Barat brites
en   mulligatawny (soup)

malaialam   ajetivo
Pertinente a la popla de la stato barati Kerala, o a sua lingua dravidian
en   Malayalam (person, language)

»  malaialam   nom
en   Malayalam (person, language)

Malaisia   nom
Un pais en Asia sude-este, a sude de la Mar Xina Sude
(capital: Kuala Lumpur)
en   Malaysia

»  malaisian   ajetivo
Pertinente a Malaisia
en   Malaysian

»  malaisian   nom
en   Malaysian

Malaka, Streta   nom
Un streta entre Sumatra e Malaisia
en   Strait of Malacca

malaria   nom
Un febre causada par plasmodio parasital cual invade la selulas roja de sangue, transmeteda par moscitos en rejiones tropical
en   malaria

»  antimalarial   nom
Un medisin per combate malaria
en   antimalarial

Malaui   nom
Un pais sin costa en Africa sude-sentral, a ueste de la Lago Niasa
(capital: Lilongwe)
en   Malawi

»  malaui   ajetivo
en   Malawian

»  malaui   nom
en   Malawian

»  Lago Malaui   nom
Un lago en Africa este-sentral, entre Malaui e Tanzania e Mosambic
en   Lake Malawi, Lake Nyasa

Maldives   nom, plural
Un otra nom per Divehi
→ Divehi
en   Maldives

Mali   nom
Un pais sin costa en Africa ueste, a sude de Jazair
(capital: Bamako)
en   Mali

»  malian   ajetivo
en   Malian

»  malian   nom
en   Malian

malie   nom
Armur flexable, fabricada de anelos metal liada a lunlotra
en   chain mail

malta   nom
Orzo o otra gran saturada, jermeda e secida, tipal usada per produi bir, uisce e vinagra
en   malt

»  malti   verbo transitiva
en   malt

Malta   nom
Un isola e pais en la Mar Mediteraneo sentral, a sirca 100 km a sude de Sisilia
(capital: Valletta)
en   Malta

»  malti   ajetivo
en   Maltese

»  malti   nom
en   Maltese

maltase   nom
Un enzima en saliva e jus de pancreas cual catalise la rompe de maltosa e zucares simil per formi glucosa
en   maltase (enzyme)

maltosa   nom
Un zucar produida par la descomposa de amidon; un disacarido de du glucosas juntada
en   maltose (sugar)

Maluku   nom
en   Maluku, Molucca

»  Isolas Maluku   nom, plural
Un grupo de isolas en Indonesia
en   Maluku Islands, Moluccas

»  Mar Maluku   nom
Un mar entre Sulawesi e la Isolas Maluku
en   Molucca Sea

maluro   nom
Un troglodite de Australia
Maluridae
en   Australian wren

malva   ajetivo
Con color pal purpur
en   mauve (color/colour)
fr   mauve

»  malva   nom
Un planta erbin con talos pelosa, flores ros o purpur, e frutas discin
Malva
en   mallow (plant)
fr   mauve

mama   nom
(Nonformal) madre
en   (colloquial) mum, mom, mummy, mommy, mama (mother)

mamal   nom
Un animal vertebrato, distinguida par ave capeles o pelo e par la secrete de lete par femas per nuri enfantes
Mammalia
en   mammal
fr   mammifère

mambo   nom
Un dansa de America latina, simil a la rumba; un prete fema de vudu
en   mambo (dance)

mamela   nom
La organo cual secrete lete en mamales fea; (nonformal) un seno
en   udder, mammary gland; (colloquial) boob, tit, knocker (breast)
fr   mammelle

»  a mamela   ajetivo
en   suckling

»  mamelal   ajetivo
en   mammary

mamograf   nom
Un radiograf usada per deteta tumores de seno
en   mammograph

»  mamografi   verbo transitiva
en   mammograph

»  mamografia   nom
en   mammography

mamogram   nom
Un imaje produida par un mamograf
en   mammogram

mamute   nom
Un elefante grande estinguida de la plestosene
Mammuthus
en   mammoth, mastodon
fr   mammouth

»  mamute lanosa   nom
Mammuthus primigenius
en   woolly mammoth

Man, Isola   nom
Un isola en la Mar Eres cual es un colonia de la Corona Brites con governa autonom
→ manes
en   Isle of Man

»  manes   ajetivo
→ Man
en   Manx

»  manes   nom
en   Manx

mana   nom
(En la Biblia) un comeda miraclosa furnida a la ivris en la tera savaje
en   manna (miracle food)

manacin   nom
Un avia peti de America tropical
Pipridae
en   manakin (bird)

manada   nom
Un grupo grande de animales; un grupo grande de umanas, tipal no gustada par la parlor
en   herd, drove, mob (people, monkeys), pack (wolves), pride (lions), flock (birds), gaggle (geese), school (fish), pod (whales), swarm (insects), horde (barbarians); rabble, riffraff, hoi polloi

»  manadi   verbo nontransitiva
en   flock
fr   troupeau, horde

»  manador   nom
en   drover, herdsman

manati   nom
Un mamal de mar con coda plata e ronda, cual abita la estuarios de la Mar Atlantica tropical
Trichechus
en   manatee, sea cow
fr   lamantin

manca   verbo nontransitiva
(Un person o cosa nesesada) es intera o partal asente
‹ me ia trova la rota mancante; un rota manca de la auto ›
en   be missing, be wanting, be lacking, fall short
fr   manquer

»  manca   nom
en   lack, deficiency, insufficiency, dearth, scarcity, deficit, shortage, shortfall, shortcoming
fr   manque

»  mancante   ajetivo
en   missing, wanting, lacking, scarce, scant, meager/meagre, sparse
fr   manquant

mancala   nom
Un de un grupo de juas en cual on move calculos sirca un table de cavetas per catura los de la otra juor
en   mancala (game)

mandala   nom
(En budisme e induisme) un desinia jeometrial cual representa la universo
en   mandala (Buddhism, Hinduism)

mandarin   nom
Un ofisior de Jonguo antica; un avia peti de Australia, con bandas blanca e negra a la fas
Taeniopygia guttata
en   mandarin (official); zebra finch (bird)

mandarino   nom
Un arbor cual produi mandarinas
Citrus reticulata
en   mandarin tree

»  mandarina   nom
Un fruta sitrica
en   mandarin, mandarine, clementine

Mandeb, Streta   nom
Un streta a la abri de la Mar Roja
en   Mandeb Strait, Bab-el-Mandeb

mandibula   nom
La osos de vertebratos cual formi la strutur de la boca
en   jaw, jawbone, mandible

mandinca   ajetivo
Pertinente a un popla abitante xef en Senegal, Gambia e Siera Leon, e sua lingua
en   Mandinka (person, language)

»  mandinca   nom
en   Mandinka (person, language)

Mandju   nom
Un rejion montaniosa de Jonguo norde-este
en   Manchuria (Chinese region)

»  mandju   ajetivo
en   Manchu

mandola   nom
Un strumento de cordetas cual sembla un mandolin grande
en   mandola (musical instrument)

mandolin   nom
Un strumento musical cual sembla un luto peti
en   mandolin (musical instrument)

mandragora   nom
Un planta mediteranean, con flores blanca o purpur, bacas grande e jala, e un radis cual pote sembla la forma de un person e ia es usada en sorsoria
Mandragora
en   mandrake (plant)

mandril   nom
Un babuin grande de Africa ueste, con un fas roja e blu, e la mas avente un posterior blu
en   mandrill (monkey)

maneja   verbo transitiva
Gida (un organiza), controla (suordinadas), opera (un macina), usa (un util)
en   manage, operate (machinery), run (organization/organisation), helm, administer, administrate, handle (tool); cope with

»  maneja de casa   nom
en   housekeeping
fr   ménage

»  maneja de contas   nom
en   account management

»  maneja de linguas   nom
en   language planning
eo   lingvoplanado

»  maneja sin   verbo
en   do without, manage without

»  malmaneja   verbo transitiva
en   mismanage, mishandle

»  manejable   ajetivo
en   manageable, tractable

»  manejablia   nom
en   manageability, tractability

»  manejal   ajetivo
en   administrative

»  manejor   nom
en   manager, administrator, operator, steward, seneschal

»  manejor de casa   nom
en   housekeeper

»  manejor de servores   nom
en   butler

»  nonmanejable   ajetivo
en   unmanageable

manera   nom
La modo en cual on condui, spesial la modo la plu bon
en   manner, way of behaving, mannerism

»  de bon maneras   ajetivo
en   well-mannered
fr   qui a de bonnes manières

»  de mal maneras   ajetivo
en   ill-mannered, uncouth
fr   qui a de mauvaises manières

manga   nom
La parte de un veste cual covre tota o un parte de la braso; un saco ensircante la braso cual mesura la presa de sangue
en   sleeve; cuff (blood pressure)
fr   manche

»  manga de camisa   nom
en   shirtsleeve

»  manga de venta   nom
en   windsock

»  la Manga   nom
en   English Channel
fr   la Manche

»  Isolas de la Manga   nom, plural
en   Channel Islands

»  sin manga   ajetivo
en   sleeveless
fr   sans manches

manga   nom
Un jenero de cartunes o leteratur grafica, orijinante en Nion
en   manga (cartoon)

manganes   nom   «Mn»
La elemento cimical con numero atomal 25, un metal dur e gris
en   manganese (element)

mangera   nom
Un tubo flexable, tipal usada per acui plantas o estingui focones
en   hose, hosepipe, flexible tube
fr   manchette

»  mangeri   verbo transitiva
en   hose, hose down

mango   nom
Un arbor de Barat; la fruta de esta
Mangifera
en   mango
fr   mangue, manguier

mangoste   nom
Un mamal peti e carnivor, con corpo e coda longa con pelo de bandas, de Africa e Asia tropical
Herpestidae
en   mongoose
fr   mangouste

Mani   nom
Un profeta de la rejion de Irac e Iran, 216-274 ec, ci ia fundi manisme
en   Mani (prophet)

»  manisme   nom
en   manicheanism/manichaeanism

»  maniste   ajetivo
en   manichean/manichaean

»  maniste   nom
en   manichean/manichaean

mania   nom
Un maladia mental, marcada par periodos de stimula, ajita, estasia, deludes e iperativia; un pasatempo abitual cual causa multe stimula
en   mania, addiction, fanaticism; craze, furore

»  -mania   sufisa, nom
Mania
en   -mania (medical, enthusiasm)

»  manica   ajetivo
en   manic, maniacal, fanatical; hectic, frantic

»  manica   nom
en   maniac, fanatic, junkie; addict; (colloquial) geek, nerd

»  -manica   sufisa, ajetivo
en   -manic

maniate   nom
Un person rica e potiosa, spesial un comersior
en   magnate, tycoon, mogul

manicin   nom
Un pupa usada per mostra vestes; un person ci porta vestes per mostra los a otras
en   mannequin (dummy, fashion model)

manico   nom
La parte de un cosa par cual on porta o controla lo
en   handle (for holding), hilt (sword, knife), grip; handlebar; handhold
fr   poignée

»  manico de porte   nom
en   door handle, doorknob
fr   poignée de porte

»  manico de scopa   nom
en   broomstick

»  manicos   nom, plural
en   handles, handlebars

manicura   nom
Un trata cosmetica de la manos, spesial la ditos
en   manicure
fr   manucure

»  manicuror   nom
en   manicurist

manioca   nom
Un arbor de America tropical; la radis de esta, usada como un comeda pos sutrae sianido de la pulpa
Manihot esculenta
en   manioc, cassava (tree, root)

manipula   verbo transitiva
Usa o controla en modo destrosa
en   manipulate
fr   manipuler

»  manipula   nom
en   manipulation
fr   manipulation

»  manipula de opina   nom
en   manipulation of opinion, spin

»  manipula distritos elejal   verbo
en   gerrymander

»  manipula par autoduta   verbo
en   gaslight

»  manipulor   nom
en   manipulator

Manitoba   nom
Un provinse de Canada sentral
en   Manitoba (Canadian province)

manitu   nom   (dise ‘manitú’)
(En alga poplas algoncian) la bon o mal spirito de vive
en   manitou (life force)

manivel   nom
Un parte ortogonal fisada a un ase, usada per turna la ase
en   crank, crank handle
fr   manivelle

»  arbor de maniveles   nom
en   crankshaft

»  maniveli   verbo transitiva
en   crank

Mannar, Golfo   nom
Un golfo entre Barat e Srilanca
en   Gulf of Mannar

mano   nom
La parte final de un braso, incluinte la palma e la ditos
en   hand; handful
fr   main

»  mano plen   nom
en   handful
fr   poignée

»  con mano destra   averbo
en   (done) right-handed
fr   avec la main droite

»  con mano en mano   ajetivo
en   hand in hand
fr   la main dans la main

»  con mano sinistra   averbo
en   (done) left-handed
fr   avec la main gauche

»  con manos libre   averbo
en   hands free
fr   avec les mains libres

»  de mano destra   ajetivo
en   right-handed (person)

»  de mano sinistra   ajetivo
en   left-handed (person)

»  fabricada par mano   ajetivo
en   made by hand, handmade

»  mani   verbo transitiva
Palpa o manipula par mano
en   handle

»  manodestra   nom, composada (nom+ajetivo)
en   right-hander

»  manosinistra   nom, composada (nom+ajetivo)
en   left-hander, southpaw

»  par mano   ajetivo
en   by hand, manual, freehand
fr   à la main

»  sur manos e jenos   ajetivo
en   on one’s hands and knees, on all fours

manobra   verbo transitiva
Move en un modo cual nesesa capasia e atende
en   maneuver/manoeuvre
fr   manœuvrer

»  manobra   nom
en   maneuver/manoeuvre
fr   manœuvre

»  manobra plu bon ca   verbo
en   outmaneuver/outmanoeuvre

manometre   nom
Un strumento per mesura la presa sur un colona de licuida
en   manometer (pressure-measuring tool)

manoscrito   nom
Un libro, documento o musica, scriveda par mano; un testo cual no es ancora publicida
en   manuscript, autograph, codex, typescript

manteni   verbo transitiva
Fa ce (un cosa o situa) continua con la mesma cualia, tipal bon; furni la nesesadas per vive o funsiona a (un person o cosa)
en   maintain, keep (in the same state), preserve; monitor
fr   maintenir

»  manteni   nom
en   maintenance, preservation, upkeep
fr   maintenance

»  mantenida   ajetivo
en   maintained, kept

»  mantenor   nom
en   janitor, caretaker, maintenance man, maintenance woman
fr   agent de maintenance

»  mantenor de eglesa   nom
en   sexton

manticor   nom
Un animal mital con corpo de leon, fas de umana, e picador de scorpion
en   manticore (mythology)

mantis   nom
Un inseto xasante, con brasos pliada como manos preante
Mantodea
en   mantis (insect)
fr   mante

mantra   nom
Un parola o sona repeteda per aida medita, orijinante en induisme e budisme
en   mantra (meditation)

manual   nom
Un libro de instruis
en   handbook, manual, reference book, guide, guidebook, vade mecum
fr   manuel (livre)

»  manual de instrui   nom
en   training manual, instruction book
fr   manuel d’instruction

»  manual de stilo   nom
en   style guide, stylebook

»  manual prima   nom
en   primer, basic guide

manxa   verbo transitiva
Marca (un cosa o person) en un modo cual mali sua aspeta
en   stain, blemish, blot, mar, tarnish, taint, sully, besmirch, stigmatize/stigmatise, deface, disfigure; smudge, smear
fr   tacher

»  manxa   nom
en   stain, blemish, blot, blotch, spot, fleck; smudge, smear; marking (animals, plants)
fr   tache

»  manxa de inca   nom
en   inkblot

»  manxa de larmas   nom
en   tearstain

»  manxa frotada   nom
en   smudge, smear

»  manxa solal   nom
en   sunspot

»  manxeta   nom
en   speckle

»  manxosa   ajetivo
en   blotchy, smudgy, mottled, dappled

»  nonmanxada   ajetivo
en   unmarked, unblemished, unsullied, untainted, immaculate, pristine
fr   immaculé

maoisme   nom   (dise ‘maoïsme’)
La ideas comuniste de Mao Zedong, cual la formi un politica pasada de Jonguo
en   Maoism (politics)

»  maoiste   ajetivo   (dise ‘maoïste’)
en   Maoist

maori   ajetivo
Pertinente a la popla orijinal de Zeland Nova, o a sua lingua polinesian
en   Maori

»  maori   nom
en   Maori

mapa   verbo transitiva
Crea un scema bidimensional per representa (un rejion de tera o mar)
en   map, chart

»  mapa   nom
en   map, mapping, chart
fr   carte

»  mapa de releva   nom
en   relief map

»  mapa linial   nom
en   linear mapping

»  mapada   ajetivo
en   mapped, charted

»  nonmapada   ajetivo
en   unmapped, uncharted

mar   nom
Un corpo grande de acua salin cual covre la plu de la surfas de la Tera
en   sea, ocean
fr   mer, océan

»  mar alta   nom
en   high seas, open ocean, open sea, main

»  a mar   averbo
en   at sea, offshore

»  en la mar   averbo
en   in the sea, overboard

»  maral   ajetivo
en   marine, oceanic, maritime, seagoing

»  mareria   nom
en   oceanarium

»  marin   ajetivo
en   sealike, salty, briny, brackish

»  marin   nom
Acua salosa, como en la mar
en   brine, salty water
fr   marinade

»  marini   verbo transitiva
en   marinate in brine, marinade, pickle, brine
fr   mariner

»  marinida   ajetivo
en   marinated, marinaded, pickled, brined
fr   mariné

»  maror   nom
en   seafarer, sailor

»  su mar   ajetivo
en   submarine, undersea

»  su mar   averbo
en   under the sea

»  transmaral   ajetivo
en   transoceanic

marabu   nom   (dise ‘marabú’)
Un siconia grande de Africa, con beco grande
Leptoptilos crumeniferus
en   marabou (bird)

marabut   nom
Un eremita o monce muslim, tipal en Africa norde
en   marabout (monk)

maraca   nom
Un strumento de percute, composada de un zuca vacuida, plenida con favas seca, calculos o ojetos simil
en   maraca (musical instrument)

Maracaibo, Lago   nom
Un lago grande en Venezuela, liada a la Mar Caribe
en   Lake Maracaibo

Marajo   nom
Un isola en la boca de la Rio Amazona en Brasil
en   Marajó (island)

marania   verbo transitiva
Trapi (alga cosa) en un masa complicada
en   entangle, tangle, mat, snarl, mess up
fr   emmêler, enchevêtrer, embrouiller

»  marania   nom
en   tangle, mess; thicket

»  desmarania   verbo transitiva
en   disentangle, untangle, unravel, unsnarl

»  maraniada   ajetivo
en   tangled, matted, messy

»  maraniada en jelo   ajetivo
en   icebound

»  maraniada en trafica   ajetivo
en   stuck in traffic

maranta   nom
Un erba de la isolas de la Mar Caribe, de cual on pote estrae amidon
Maranta arundinacea
en   arrowroot (plant)

marascino   nom
Un bevida alcolosa dulse e forte, preparada de serisas peti e amarga
en   maraschino (drink)

marati   ajetivo
Pertinente a la popla de Maharashatra en Barat sentral, o a sua lingua indoarian
en   Marathi (person, language)

»  marati   nom
en   Marathi (person, language)

maraton   nom
Un corsa de core de 26 milias e 385 iardes (42,195 cilometres); cualce taxe difisil cual ocupa un tempo longa
en   marathon
fr   marathon

marca   verbo transitiva
Decora (un cosa o person) con un manxa, figur o simbol per indica sua identia; (un cualia) es tipal de (un cosa o person); (en informatica) usa un mus o teclador per spesifa (alga cosa) como la ojeto de la opera seguente
en   mark, stamp, characterize/characterise, typify; select, flag, highlight (text)
fr   marquer

»  marca   nom
Un cualia o manxa distinguinte; un nom comersial de un organiza o corpora
en   mark, stamp, brand (commercial), characterization/characterisation, identifier; marking (animals, plants)
fr   marque

»  marca comersial   nom
en   trademark

»  marca de colpa   nom
en   weal, wheal, welt

»  marca de cualia   nom
en   hallmark

»  marca de orea   nom
en   earmark

»  marca de paia   nom
en   mark of payment, frank, franking mark

»  marca como paiada   verbo
en   frank, mark as paid

»  marca postal   nom
en   postmark

»  desmarca   verbo transitiva
en   unmark, deselect

»  marcada   ajetivo
en   marked

»  marcada par   ajetivo
en   characterized/characterised by, involving

»  marcador   nom
en   marker, stamp

Marcesas, Isolas   nom, plural
Un grupo de isolas volcanal en la Mar Pasifica sude, un parte de Polinesia Franses
en   Marquesas Islands
fr   Îles Marquises

marci   nom
(En alga nasiones european) un nobil de grado supra un conte e su un duxe
en   marquess, marquis, margrave
fr   marquis

»  marcesa   nom
en   marchioness, marquise
fr   marquise

»  marcia   nom
(Istorial) la area renada par un marci
en   march (land)
fr   marquisat

marea   verbo nontransitiva
Ave un sensa de jira e perde de ecuilibra
en   feel dizzy, feel giddy, feel woozy
fr   attraper le mal de mer

»  marea   verbo transitiva
en   make dizzy
fr   donner le mal de mer

»  mareada   ajetivo
en   dizzy, giddy, groggy, woozy
fr   qui a le mal de mer

»  mareante   ajetivo
en   dizzying
fr   qui donne le mal de mer

marea   nom
La leva e cade de la mar par la atrae de la Luna e la Sol
en   tide
fr   marée

»  marea alta   nom
en   high tide
fr   marée haute

»  marea basa   nom
en   low tide
fr   marée basse

»  marea forte   nom
en   riptide

»  mareal   ajetivo
en   tidal

marexal   nom
Un ofisior de grado la plu alta en la fortes militar de alga nasiones; un xef de polisia o de pompores; un ofisior xef de un aveni publica
en   marshal (officer)
fr   maréchal

marga   nom
Un tera composada de arjila e calce, usada en la pasada como fertilinte
en   marl (soil)

margarina   nom
Un sustitua per bur, preparada de olios vejetal o gras de animales
en   margarine, marge, oleo

margarita   nom
Un planta peti, con flores blanca con sentro jala
Bellis
en   daisy (plant)
fr   marguerite

margarita   nom
Un coctel preparada con tecila e jus sitrica
en   margarita (drink)

Margarita   nom
Un isola en la Mar Caribe, prosima a la costa de Venezuela
en   Margarita Island
fr   Île de Margarita

Mariana   nom
en   Mariana

»  Isolas Mariana   nom, plural
Un grupo de isolas en la Mar Pasifica ueste, incluinte Guam
en   Marianas
fr   Îles Mariannes

mariatxi   nom
Un stilo de musica mexican, tipal presentada par un grupo peti de musicistes vagante
en   mariachi (music)

marieta   nom
Un scarabe peti con dorso cupolin, tipal roja o jala con marcas negra
Coccinellidae
en   ladybird, ladybug, lady beetle
fr   coccinelle

marimba   nom
Un xilofon african
en   marimba (musical instrument)

marina   nom
La ramo de la fortes militar cual opera a mar; un grupo multe grande de barcones, su un comandor; un grupo de veculos simil
en   navy, fleet, armada
fr   marine

»  marinal   ajetivo
en   naval

»  marineta   nom
en   flotilla
fr   flotille

»  marinor   nom
en   sailor, seaman, mariner; marine
fr   marin

»  nonmarinor   nom
en   non-sailor, landlubber

marinara   nom
Un salsa italian preparada de tomates, oniones e spises
en   marinara (sauce)

marioneta   nom
Un pupa operada de supra par cordetas fisada a sua membros
en   marionette
fr   marionnette

»  marionetor   nom
en   marionettist
fr   marionnettiste

marjin   nom
Un borda streta, tipal a lado de un paje primida
en   margin
fr   marge

»  marjinal   ajetivo
en   marginal
fr   marginal

»  marjini   verbo transitiva
en   marginalize/marginalise

»  marjini   nom
en   marginalization/marginalisation

marlin   nom
Un pex grande e comable de mares calda, con corpo longida, beco con forma de lansia, e pina dorsal longa e rijida cual formi un cresta a ante
Istiophoridae
en   marlin (fish)

Marmara   nom
en   Marmara (island)

»  Mar Marmara   nom
Un mar peti entre Turcia european e Turcia asian
en   Marmara Sea

marmelada   nom
Un comeda de frutas sitrica, preparada par boli en zucar
en   marmalade

marmo   nom
Un forma cristal de calcario, usada en sculta e arciteta
en   marble
fr   marbre

»  de marmo   ajetivo
en   (made of) marble
fr   en marbre

marmota   nom
Un rodente grande, sosial e tunelinte, tipal abitante montania
en   marmot (rodent)

Maroco   nom
Un otra nom per Magrib
→ Magrib
en   Morocco

»  marocan   ajetivo
en   Moroccan

»  marocan   nom
en   Moroccan

marolojia   nom
La ramo de siensa cual studia la cualias e fenomenos fisical e biolojial de la mar
en   oceanology, oceanography

»  marolojiste   nom
en   oceanologist, oceanographer

marsupio   nom
Un pox cual proteje ovos, enfantes o strutures de reprodui, spesial la pox de un marsupial fema
en   marsupium, pouch

»  marsupial   ajetivo
en   marsupial

»  marsupial   nom
Marsupialia
en   marsupial

Marte   nom   «♂»
La planeta cuatro de la Sol, peti e roja; la dio de gera de la romanes antica
en   Mars (mythology, planet)
fr   Mars

»  martan   ajetivo
en   Martian
fr   martien

»  martan   nom
en   Martian

martedi   nom
La dia entre lundi e mercurdi en cada semana
en   Tuesday
eo   mardo
fr   mardi

martel   nom
Un util con testa metal pesosa, usada per rompe cosas, colpa clos, etc; un parte de un fusil o otra macina cual colpa un otra per funsiona lo; un oso peti en la orea media cual transmete vibras de la timpan a la inco
en   hammer, mallet; hammer, dog, cock (gun); malleus
fr   marteau; chien (d’arme à feu)

»  martel de aira   nom
en   pneumatic drill, jackhammer

»  martel mol   nom
Un spesie de martel, usada con un sisel o per colpa lenio sin marca lo
en   mallet

»  martelable   ajetivo
en   malleable

»  marteleta   nom
Un basto con testa cuxinida, usada per jua alga strumentos de percute
en   mallet; gavel

»  marteli   verbo transitiva
en   hammer
fr   marteler

»  martelon   nom
en   sledgehammer

martes   nom
Un mamal mustelin, cual abita arbores e es xasada per sua pelo
Martes
en   marten (animal)

martin   nom
Un avia insetivor cual vola rapida, en familia de rondin
Hirundinidae
en   martin (bird)
fr   martinet

martini   nom
Un coctel de jin o vodca e vermute, tipal con un oliva o peso de limon
en   martini (drink)

Martinic   nom
Un isola franses en la Mar Caribe
en   Martinique (island)

»  martinices   ajetivo
en   Martiniquan

»  martinices   nom
en   Martiniquan

martir   nom
Un person matada per sua relijio o otra credes
en   martyr

»  martiri   verbo nontransitiva
en   martyr

»  martiri   verbo transitiva
en   martyr

»  martiria   nom
en   martyrdom

marto   nom
La mense tre de la calendario gregorian
en   March
eo   marto
fr   Mars

marxisme   nom
en   Marxism

»  marxiste   nom
en   Marxist

marxa   verbo nontransitiva
Pasea en modo militar; pasea rapida con intende; prosegue en modo organizada
en   march; stride

»  marxa   nom
en   march

»  marxa funeral   nom
en   funeral march

Maryland   nom
Un stato en la SUA norde-este, a la Baia Chesapeake
en   Maryland (US state)

mas   ajetivo
De la seso cual produi spermas capas de fertili ovos de un fema matur; (un planta) cual ave androseos ma no ave jineseos fertil
en   male

»  mas   nom
en   male

»  desmasi   verbo nontransitiva
en   emasculate

»  desmasi   verbo transitiva
en   emasculate

»  desmasi   nom
en   emasculation

»  masia   nom
en   maleness, masculinity, machismo

»  masin   ajetivo
en   masculine, boyish, butch

»  masiosa   ajetivo
en   macho, virile

masa   nom
Un corpo de materia coerente ma sin forma definida; (en fisica) la cuantia de materia contenida par un corpo, mesurada par sua aselera su un forte spesifada o par la forte aplicada a lo par un campo de gravita
en   mass, lump, clot, clod, blob (shapeless piece); mass (physics)

»  maseta   nom
en   small mass, lump, clot

»  masi   verbo nontransitiva
en   form lumps, become lumpy, clot up

»  masi   verbo transitiva
en   make lumpy, clot up

»  masosa   ajetivo
en   massive, bulky, unwieldy, cumbersome

masacra   verbo transitiva
Mata intendente e violente (multe persones)
en   massacre, slaughter, bloodbath

»  masacra   nom
en   massacre, slaughter, bloodbath

masai   ajetivo
Pertinente a la popla pastoral de Tanzania e Cenia, o a sua lingua nilotica
en   Maasai, Masai (person, language)

»  masai   nom
en   Maasai, Masai (person, language)

masaje   verbo transitiva
Frota e amasa (un person o un parte de corpo) con la manos
en   massage

»  masaje   nom
en   massage

»  masajor   nom
en   masseur, masseuse

masapan   nom
Un pasta dulse de color jala o blanca, preparada de amandos moleda, zucar e blancas de ovo, usada per covre tortas o crea confetos
en   marzipan

masca   nom
Un covrente per tota o un parte de la fas, tipal como un desembla o per asusta o diverti otra persones; un covrente per la boca e nas per proteje contra polvo, contamina o maladia, o per furni aira filtrida o medisin gasosa; un covrente cual proteje la fas en sportes como scrima e hoci
en   mask, face mask
eo   masko

»  masca medical   nom
en   medical mask, face mask

»  desmasci   verbo transitiva
en   unmask
eo   senmaskigi

»  masci   verbo transitiva
en   mask
eo   maski

mascarpone   nom
Un ceso cremosa italian, usada en cosini
en   mascarpone (cheese)

mascita   nom
Un loca per prea e la adora de Dio en la relijio muslim
en   mosque

mascote   nom
Un person o cosa usada per simboli un organiza o aveni, tipal regardada como fortunosa
en   mascot

masi-   prefisa
La plu grande cual es posible
en   maxi-

masif   nom
Un strutur jeolojial de montes interliada como un unia
en   massif (geology)

masila   nom
Un oso supra la mandibula
en   maxilla (bone)

masima   ajetivo
Tan grande, alta, intensa o multe como posible, permeteda o atenida
en   maximum, maximal, most

»  masima   averbo
en   at most

»  masima   nom
en   maximum, most

»  masimi   verbo nontransitiva
en   maximize/maximise, optimize/optimise

»  masimi   verbo transitiva
en   maximize/maximise, optimize/optimise

»  masimi   nom
en   maximization/maximisation, optimization/optimisation

masis   nom
La covrente esterna roja e pulposa de un muscada, secida e usada como un spise
en   mace (spice)

masocisme   nom
La deriva de plaser, tipal sesal, par dole o vergonia se
en   masochism

»  masociste   ajetivo
en   masochistic

»  masociste   nom
en   masochist

Massachusetts   nom   (dise ‘masatxúsets’)
Un stato en la SUA norde-este, a la Mar Atlantica
en   Massachusetts (US state)

mastectomia   nom
Un sirurjia per sutrae un seno, tipal per limita canser
en   mastectomy (surgery)

mastica   verbo transitiva
Moli (un comeda) con sua dentes per fasili la engoli
en   chew, munch, masticate

»  remastica   verbo transitiva
en   ruminate, chew cud; brood, worry

»  remasticante   ajetivo
en   ruminant

mastica   nom
Un arbor mediteranean; la resina de la cortex de esta, usada per fabrica vernis e goma de mastica
Pistacia lentiscus
en   mastic (tree, resin)

mastin   nom
Un raza de can grande e forte
en   mastiff

»  mastin deutx   nom
en   Great Dane

masto   nom
Un palo vertical e alta cual teni un vela sur un barco o barcon; un palo simil sur la tera, usada per transmete ondas de radio, televisa, etc
en   mast

»  masto florinte   nom
Un spiga vertical e grande de flores
en   spike, flower cluster

»  masto posmedial   nom
en   mizzenmast

»  masto xef   nom
en   mainmast

mastoide   ajetivo
en   mastoid (anatomy)

»  mastoide   nom
La bulto de la oso tempal pos la orea, a cual la musculos de la col es juntada, e cual conteni spasios de aira liada a la orea media
en   mastoid process

mastosite   nom
Un selula plenida con granes basofilica cual relasa istamina e otra cimicales en reatas inflamante o alerjica
en   mast cell, mastocyte (biology)

masturba   verbo transitiva
Stimula la jenitales de (se o un otra) per plaser sesal
en   masturbate

»  masturba   nom
en   masturbation, onanism

mata   verbo transitiva
Causa la mori de (un person, animal o otra organisme)
en   kill, exterminate, execute, slaughter, butcher, slay

»  mata   nom
en   killing, extermination, execution, slaughter

»  mata la debiles   verbo
en   cull

»  mata sin intende   verbo
en   manslaughter

»  mata sin intende   nom
en   manslaughter

»  mataderia   nom
en   abattoir, slaughterhouse

»  matador   nom
en   killing machine

»  matante   ajetivo
en   deadly, fatal, lethal, mortal, homicidal

»  matas per venja   nom, plural
en   tit-for-tat killings, retaliation killings

»  mator   nom
en   killer; matador

»  mator en serie   nom
en   serial killer

»  nonmatante   ajetivo
en   non-fatal

matajoia   nom, composada (verbo+nom)
Un person ci preveni la plaser de otras; un descrive de un novela o filma cual revela un elemento major de la trama
en   killjoy, spoilsport, wet blanket; (plot) spoiler

mate   ajetivo
(Un color, pinta o surfas) sombre, sin brilia
en   matte, matt (dull)

mate   nom
Un bevida infusada tradisional de America Sude, conteninte multe cafina
en   maté (drink)

matematica   nom
La siensa astrata de numeros, cuantia e spasio
en   mathematics

»  matematica computal   nom
en   computational mathematics

»  matematical   ajetivo
en   mathematical

»  matematiciste   nom
en   mathematician

materas   nom
Un cuxin grande e plata, plenida con materia mol, sur cual on dormi
en   mattress

»  materas de palia   nom
en   straw mattress, pallet

»  materas de plumas   nom
en   feather mattress, featherbed

»  materas inflable   nom
en   air mattress, air bed, lilo

»  materasi   verbo transitiva
en   pad, upholster

materia   nom
Lo cual esiste en spasio e ave masa, tipal contrastada con enerjia; un cosa de cual otra cosas o organismes es composada, tipal contrastada con mente e spirito
en   matter, substance, material, stuff

»  materia combustable   nom
en   combustable material

»  materia fisionable   nom
en   fissionable material

»  materia flamable   nom
en   inflammable material

»  materia usosa   nom
en   useful material, grist

»  antimateria   nom
en   antimatter

»  desmateri   verbo nontransitiva
en   dematerialize/dematerialise

»  desmateri   verbo transitiva
en   dematerialize/dematerialise

»  desmateri   nom
en   dematerialization/dematerialisation

»  materi   verbo nontransitiva
en   materialize/materialise

»  materi   verbo transitiva
en   materialize/materialise

»  materi   nom
en   materialization/materialisation

»  material   ajetivo
en   material

»  materialisme   nom
en   materialism

»  materialiste   ajetivo
en   materialistic, acquisitive

»  materialiste   nom
en   materialist

»  nonmaterial   ajetivo
en   immaterial, insubstantial, intangible

matina   nom
La periodo entre medianote e mediadia, spesial pos la leva de sol
en   morning, morn

»  a esta matina   averbo
en   this morning

»  a matina   averbo
en   in the morning

»  a matina doman   averbo
en   tomorrow morning

»  a matina ier   averbo
en   yesterday morning

»  a matina oji   averbo
en   this morning

»  matini   verbo nontransitiva
en   dawn, become day, become morning

»  matini   nom
en   dawn, daybreak; threshold (metaphor)

matriarca   nom
Un fem, tipal vea, ci es la xef de un familia o tribu, o ci es potiosa en un familia o organiza
en   matriarch
fr   matriarche

»  matriarcia   nom
Un sistem de sosia o governa cual es renada par un fem o femes; un organiza sosial en cual desendentes es en un linia fema
en   matriarchy

»  matriarcial   ajetivo
en   matriarchal

matrilinia   nom
Un linia de familia cual segue la madres
en   matrilineage

»  matrilinial   ajetivo
en   matrilineal

matrioxca   nom
Cada de un colie de pupas de lenio vacuida e colorosa pintida, desiniada afin cada pote es caxida en un otra, tipal fabricada en Rusia o otra paises slavica
en   matryoshka (doll)

matris   nom
Un table de cuantias o espresas en linias e colonas, regardada como un cosa singular
en   matrix (mathematical), two-dimensional array

matur   ajetivo
Completa developada; adulte; capas de reprodui; (fruta, gran, ceso, uisce, etc) sufisinte developada per es colieda o comeda
en   mature, ripe; adult, grown-up; aged

»  maturi   verbo nontransitiva
en   mature, ripen; grow up

»  maturi   verbo transitiva
en   mature, ripen; grow up

»  maturi sesal   nom
en   puberty

»  maturia   nom
en   maturity

»  maturinte   ajetivo
en   maturing, ripening

»  nonmatur   ajetivo
en   immature, unripe, callow

»  nonmaturia   nom
en   immaturity

»  prematur   ajetivo
da   tidlig, for tidlig
de   vorzeitig
en   premature
eo   antaŭtempa, trofrua
es   temprano, prematuro, primitivo, primigenio, demasiado pronto
fr   tôt
it   presto
nl   vroeg
pt   precoce, prematuro

»  prematur   nom
en   premature baby, preemie

»  sesal matur   ajetivo
en   sexually mature, nubile

»  sesal maturinte   ajetivo
en   pubescent

»  temprana matur   ajetivo
en   precocious

»  tro matur   ajetivo
en   overripe

matxete   nom
Un cotel pesosa e larga, usada como util o arma, orijinante en America Sentral e la Isolas Caribe
en   machete (knife)

maurian   ajetivo
Pertinente a la dinastia cual ia rena Barat norde de 321 aec a 184 aec
en   Mauryan (dynasty)

»  maurian   nom
en   Mauryan (dynasty)

Mauris   nom
Un pais de isolas en la Mar Indian, a sirca 850 km a este de Madagasicara
(capital: Porto Louis)
en   Mauritius

»  maurisian   ajetivo
en   Mauritian

»  maurisian   nom
en   Mauritian

mausoleo   nom
Un construida, tipal grande, per conteni un tomba o tombas
en   mausoleum

max   nom
Un concurso de sporte, usual con du juores o ecipos
en   match, game

»  max desidente   nom
en   play-off

maxa   verbo transitiva
Redui (un comeda o otra materia) a un masa uniforma par crase lo
en   mash, crush, pulp, squash, squish

»  maxador   nom
en   masher, crusher, pulper

»  maxador de patata   nom
en   potato masher

maxia   nom
La salvor prometeda de la nasion iudi, prediseda en la Atesta Vea de la Biblia; Jesus regardada par cristianes como la salvor prometeda
en   messiah

»  maxial   ajetivo
en   messianic

maximin   nom
(En la teoria de juas) la plu alta de un colie de minimas
en   maximin (game theory)

maxo   ajetivo
Mostrante orgulo combatosa en sua masia
en   macho

mazaua   ajetivo
Pertinente a un popla orijinal de Mexico sentral, o a sua lingua relatada a otomi
en   Mazahua (person, language)

»  mazaua   nom
en   Mazahua (person, language)

mazurca   nom
Un dansa polsce vivosa en tempo truple; un musica per esta
en   mazurka (dance, music)

me   pronom
Usada par un parlor per refere a se
en   I; me
fr   je, me, moi

»  la plu joven de me   nom
en   my younger self

»  la mea   pronom
en   mine

»  la otras de me   nom
en   my other selves

»  mea   determinante
en   my
fr   mon, ma, mes

meato   nom
Un pasaje o abri cual gida a la interna de la corpo
en   meatus (anatomy)

mecanica   nom
La ramo de matematica aplicada cual studia moves e a fortes cual produi move
en   mechanics

»  mecanica cuantal   nom
en   quantum mechanics

»  mecanica de sielo   nom
en   celestial mechanics

»  mecanical   ajetivo
en   mechanical

»  mecanicisme   nom
en   mechanism (science, philosophy)

»  mecaniciste   ajetivo
en   mechanistic

»  mecaniciste   nom
en   mechanist

mecanoresetador   nom
Un neuron sensal cual responde a stimulas mecanical, como sonas o tocas
en   mechanoreceptor (neuron)

Mecong, Rio   nom
Un rio en Asia sude-este cual comensa en Bod, flue tra Jonguo, Lau, Camputxa e Vietnam, e fini en la Mar Xina Sude
en   Mekong River

mecotero   nom
Un inseto magra con alas membranin, gamas longa, beco dirijeda a su, e (en la mases) un adomen cual curvi a supra como la picador de un scorpion
Mecoptera
en   scorpion fly

medalia   nom
Un disco metal con enscrive o desinia, produida per onora un aveni o la capasia de algun como un soldato, atleta o erudita
en   medal

»  medalion   nom
en   medallion

»  medalion ronda   nom
en   roundel

»  medaliste   nom
en   medalist/medallist

»  medaliste de oro   nom
en   gold medalist/medallist

media   ajetivo
A distantia egal de ambos estremas; (un membro de un grupo o serie) con la mesma cuantia de otra membros a cada lado
en   middle, middling, medium, intermediate

»  media   nom
en   middle, center/centre, median, halfway point, midsection, midst

»  media-   prefisa
Ajuntada a un nom de un periodo o estende per nomi la punto media
‹ mediadia ›
en   mid- (added to nouns: midpoint)

»  media de anio   nom
en   midyear

»  media de barcon   nom
en   midship

»  media de matina   nom
en   midmorning

»  media de periodo   nom
en   midperiod, midterm

»  media de rio   nom
en   midstream

»  media de semana   nom
en   midweek

»  a media   averbo
en   in the middle, midway

»  a media de   preposada
en   in the middle of, midway through

»  posmedia   nom
da   eftermiddag
de   Nachmittag
en   afternoon
eo   posttagmezo
es   tarde
fr   après-midi
it   pomeriggio
nl   namiddag
pt   tarde

media   nom
Un ata o sistem par cual on ateni un resulta o comunica un mesaje
en   means (of doing); measure (course of action); medium (of communication)

»  medias   nom, plural
en   media (including mass communications)

»  medias fluente   nom, plural
en   streaming media

»  medias publica   nom, plural
en   mass media

»  medias sever   nom, plural
en   austerity measures

Media   nom
Un rejion antica de Asia, a sude-ueste de la Mar Caspio
en   Media (ancient region)

medica   nom
La siensa o pratica de la diagnose, trata e preveni de maladia
en   medicine (science, practice)

»  medical   ajetivo
en   medical

»  medica erbal   nom
en   herbal medicine, herbalism

»  mediciste   nom
en   medic, doctor, physician

»  mediciste abitante   nom
en   resident (medical graduate)

»  mediciste clinical   nom
en   clinician

»  mediciste comensante   nom
en   intern (medical graduate)

»  mediciste forense   nom
en   coroner

»  premedical   ajetivo
en   premedical, premed

medieval   ajetivo
Parteninte a la eda entre aprosima la sentenios 5 e 15
en   medieval

»  eda medieval   nom
en   middle ages

mediocre   ajetivo
Con cualia media o min ca media; no multe bon
en   mediocre, ordinary, average, middling, uninspired, undistinguished, indifferent, unexceptional, unexciting, unremarkable, run-of-the-mill, pedestrian, prosaic, lackluster/lacklustre, forgettable

»  mediocria   nom
en   mediocrity

»  obra mediocre   nom
en   mediocre work, potboiler

medisin   nom
Un droga usada per trata o preveni maladia
en   medicine (drugs), medication

»  medisin de fertilia   nom
en   fertility drug

»  medisin enspirable   nom
en   inhalant

»  medisin erbal   nom
en   herbal medicine

»  medisin inferior   nom
en   nostrum

»  medisin lejerinte   nom
en   palliative

»  automedisini   verbo
en   self-medicate

»  automedisini   nom
en   self-medication

»  medisinal   ajetivo
en   medicinal

»  medisini   verbo transitiva
en   medicate

»  medisinida   ajetivo
en   medicated, on medication

»  nonmedisinida   ajetivo
en   unmedicated

medita   verbo nontransitiva
Pensa profonda o foca la mente per un periodo de tempo, silente o aidada par canta lenta, per destensa o per razonas relijial o spirital
en   meditate

»  medita   nom
en   meditation

Mediteraneo   nom
La rejion de la Mar Mediteraneo e la paises bordante
en   Mediterranean (region)

»  Basin Mediteraneo   nom
en   Mediterranean Basin

»  Mar Mediteraneo   nom
Un mar grande, cuasi ensircada par tera, entre Europa sude, Africa norde e Asia sude-ueste
en   Mediterranean Sea

»  mediteranean   ajetivo
Pertinente a la Mediteraneo o a sua poplas
en   Mediterranean

medula   nom
La interna de un organo o texeda, spesial cuando distinguable de la area esterna; texeda mol o sponjin en plantas o animales
en   marrow, medulla, pith

»  medula de oso   nom
en   bone marrow

»  medula spinal   nom
en   spinal cord

»  medulosa   ajetivo
en   pithy

medusa   nom
Un cnidario maral con corpo con forma de campana o plateta, tipal diafana e con tentaculos picante a la borda
Medusozoa
en   jellyfish, medusa

Medusa   nom
Un monstro mital umanin, con serpentes en loca de capeles
en   Medusa (mythology)

mega-   prefisa
Grande; 10^6
en   mega- (large, a million)

megafon   nom
Un aparato embutin per grandi e dirije la vose
en   megaphone, bullhorn, loudhailer

megalito   nom
Un petra grande cual formi tota o un parte de un monumento preistorial, tipal en Europa ueste
en   megalith

»  megalital   ajetivo
en   megalithic

megalo-   prefisa
Nonormal grande
en   megalo- (large)

megalomania   nom
La crede ce on es multe importante o omnipotente, tipal como un sintom de un maladia mental
en   megalomania

»  megalomanica   ajetivo
en   megalomaniacal

»  megalomanica   nom
en   megalomaniac

megatero   nom
Un balena con jiba en loca de pina dorsal e aletas blanca longa, notada per sua vosis longa cual on nomi cantas
Megaptera novaeangliae
en   humpback whale

meiose   nom
Un tipo de divide selulal cual produi cuatro selulas de cual cada ave la dui de la cuantia de cromosomas de la selula orijinal
en   meiosis (biology)

melaiu   ajetivo
en   Malay (person, language)

»  melaiu   nom
Un lingua austronesian major
en   Malay (person, language)

melamina   nom
Un composada cristal blanca, usada en la fabrica de plasticas; un plastica fabricada de esta
en   melamine (plastic)

melancolia   nom
Un senti de tristia pensosa, tipal sin causa clar
en   melancholy, melancholia

»  melancolica   ajetivo
en   melancholy, melancholic, melancholiac

»  melancolica   nom
en   melancholiac

Melanesia   nom
La isolas de un parte de la Mar Pasifica ueste, a sude de Micronesia e a ueste de Polinesia
en   Melanesia

»  melanesian   ajetivo
en   Melanesian

melanin   nom
Un pigmento brun oscur, trovada en la capeles, pel e iris de la oio en umanas e animales, cual bronzi la pel cuando esposada a lus de sol
en   melanin

melano-   prefisa
Negra
en   melano- (black)

melanoma   nom
Un tumor de la selulas cual produi melanin, tipal un tumor canserosa de la pel
en   melanoma, melanocarcinoma (tumor/tumour)

melanose   nom
La produi de cuantias nonormal o suprabundante de melanin en la pel o otra texeda
en   melanosis (medical)

melanosite   nom
Un selula cual produi melanin, tipal en la pel
en   melanocyte (biology)

melasa   nom
Un xirope densa e brun oscur, derivada de zucar cru
en   molasses, treacle

»  melasa oro   nom
en   golden syrup

»  melasin   ajetivo
en   treacly

melatonina   nom
Un ormon secreteda par la glande pineal, cual retarda la produi de melanin
en   melatonin (hormone)

melma   nom
Cualce materia mol, umida e liscosa, comun persepida como repulsante
en   slime, scum, gunge, gunk, goo, goop, gloop, glop

»  melmi   verbo transitiva
en   slime, gunge

»  melmosa   ajetivo
en   slimy, scummy, gungy, gooey, goopy, gloopy

melodia   nom
Un serie de notas cual es musical divertinte
en   melody, tune

»  melodiosa   ajetivo
en   melodious, melodic, tuneful, singsong

melodica   nom
Un strumento con teclador peti cual controla un linia de anxas, con beco per sofla a un fini
en   melodica (musical instrument)

melodrama   nom
Un drama con carateres esajerada e avenis stimulante e emosiosa
en   melodrama

»  melodramosa   ajetivo
en   melodramatic

»  melodramosia   nom
en   melodramatics, histrionics

melon   nom
Un planta en familia de zuca; la fruta grande e ronda de esta
Cucumis
en   melon

»  melon acuosa   nom
Citrullus lanatus
en   watermelon

»  melon de inverno   nom
en   honeydew melon

melonjena   nom
Un planta orijinante en Asia sude e este; la fruta grande de esta, con forma de ovo, tipal oscur purpur
Solanum melongena
en   aubergine, eggplant

mem   nom
Un elemento de un cultur o sistem de condui cual pote pasa un person a un otra en modo nonjenetical, per esemplo par imita; un imaje, video, testo, etc, cual es copiada (tipal con varias peti) e rapida sperdeda par usores de la interede
en   meme

membrana   nom
Un strutur pliable e telonin cual ata como un borda, fore o divide en un organisme; un telon o pel comun usada per tamisi o separa
en   membrane, web

»  membrana mucosa   nom
en   mucous membrane

»  membranin   ajetivo
en   membranous, membranelike

»  membranosa   ajetivo
en   membranous, webbed

membro   nom
Un person, cosa o organiza cual parteni a un grupo; un person ci partisipa en la prosedes de un organiza; un peso de un strutur complicada; un braso o gama
en   member (group), fellow (society), affiliate; limb (arm, leg)

»  desmembri   verbo transitiva
en   dismember

memoria   nom
La capasia par cual la mente reteni e recorda informa; la parte de un computador en cual datos o programes es retenida
en   memory (as a capacity; including computer)

»  memoria de dura corta   nom
en   short-term memory, STM

»  memoria de dura longa   nom
en   long-term memory, LTM

»  memoria de state solida   nom
en   solid-state drive

»  memoria flax   nom
en   flash memory

»  memoria sensal   nom
en   sensory memory, very-short-term memory, VSTM

»  memoria vivin   nom
en   eidetic memory

»  de memoria   nom
en   from memory (without notes), by rote

»  memorable   ajetivo
en   memorable

»  memori   verbo transitiva
→ recorda
en   memorize/memorise, remember, commit to memory

»  memori   nom
en   memorization/memorisation

»  prememoria   nom
en   cache, cache memory (software)

»  prememori   verbo transitiva
en   cache

menasa   verbo transitiva
Espresa un intende per ata violente contra (algun); (un situa) pare ce lo va produi un resulta mal o perilosa
‹ el ia menasa me con colpa ›
en   threaten, menace, intimidate, loom, browbeat

»  menasa   nom
en   threat, menace, intimidation, duress

»  menasante   ajetivo
en   threatening, ominous, forbidding, portentous

»  su menasa de fusil   averbo
en   at gunpoint

mendelevio   nom   «Md»
La elemento cimical con numero atomal 101, nomida per Dmitri Mendeleev
en   mendelevium (element)

mendelisme   nom
La teoria de erita proposada par Gregor Mendel en la sentenio 19
en   mendelianism (genetics)

»  mendeliste   nom
en   mendelian, mendelianist

mendica   verbo transitiva
Solisita umil (alga cosa, tipal mone o comeda) de algun
en   beg, scrounge, panhandle

»  mendica   nom
en   begging

»  mendicor   nom
en   beggar

»  mendicorin   ajetivo
en   beggarly, beggarlike

menestrel   nom
Un cantor e musiciste, comun vagante, de la eda medieval
en   minstrel, troubadour

meninje   nom
Un de la tre membranas cual fore la cranio e la canal vertebral e enclui la serebro e medula spinal
en   meninge (anatomy)

»  meninjal   ajetivo
en   meningeal

meninjite   nom
Un inflama de la meninjes causada par un infeta virusal o baterial, marcada par dole estrema de la testa, febre, sensosia a lus, e rijidia musculal, cual pote causa convulsas, delirio e mori
en   meningitis

menir   nom
Un roca vertical e alta, como los erijeda en la eda preistorial en Europa ueste
en   menhir (standing stone)

menisco   nom
La surfas curva de un licuida en un tubo; un lente cual es convesa a un lado e concava a la otra; un cartilaje magra e fibrosa entre la surfases de alga juntas
en   meniscus

»  meniscal   ajetivo
en   meniscal

menonita   ajetivo
Pertinente a la seta protestante ci ia veni de Frisland en la sentenio 16, nomida per Menno Simons
en   Mennonite

»  menonita   nom
en   Mennonite

»  menonitisme   nom
en   Mennonitism (Christianity)

menopausa   nom
La sesa de menstrua; la eda de la vive de un fem en cual esta aveni, tipal entre 45 e 50 anios
en   menopause

»  posmenopausal   ajetivo
en   postmenopausal

menora   nom
Un candelabro santa con sete ramos, usada en iudisme
en   menorah (candelabrum)

menorea   nom
La flue de sangue menstrual
en   menorrhea/menorrhoea

mense   nom
Un de la 12 periodos nomida a cual un anio es divideda; la longia aprosima de un de esta periodos
‹ la mense agosto ›
en   month

»  dumensal   ajetivo
en   bimonthly (once every two months)

»  mensal   ajetivo
en   monthly

»  per mense   averbo
en   per month, a month

menstrua   nom
La descarga de sangue e otra materia de la utero de un fem, a intervales de sirca un mense lunal
en   menstruation, period

»  menstrua prima   nom
en   menarche

»  menstrual   ajetivo
en   menstrual

»  menstrui   verbo transitiva
en   menstruate

»  premenstrual   ajetivo
en   premenstrual

mensula   nom
Un strutur cual protende de un mur per suporta un strutur a supra
en   corbel (architecture)

menta   nom
Un planta bonodorosa, tipal usada como un spise
Mentha
en   mint (plant)

»  menta fresca   nom
Un menta usada en cosina e como un saborinte per confetos
Mentha spicata
en   spearmint

»  menta peperin   nom
en   peppermint

»  mentin   ajetivo
en   minty

mentalisme   nom
La teoria ce fenomenos fisical e psicolojial es ultima esplicable sola como efetos de un mente creosa e interpretente; la arte de presenta capasias parente psicica per diverti
en   mentalism (philosophy, psychic)

»  mentaliste   ajetivo
en   mentalistic

»  mentaliste   nom
en   mentalist

mente   nom
La parte de un person cual permete ce el persepi, pensa e senti
en   mind

»  con mente clar   ajetivo
en   clear-headed

»  de la mesma mente   ajetivo
en   like-minded

»  de mente debil   ajetivo
en   weak-minded, feeble-minded

»  de mente simple   ajetivo
en   simple-minded

»  mental   ajetivo
en   mental

menti   verbo transitiva
Espresa o intende (un declara falsa)
en   lie, tell a lie

»  menti   nom
en   lie; mendacity

»  menti jigante   nom
en   whopper

»  menteta   nom
en   fib, white lie

»  mentinte   ajetivo
en   lying, untruthful, mendacious

»  mentor   nom
en   liar

mento   nom
La parte de la fas su la boca, formida par la apico de la mandibula
en   chin

mentol   nom
Un composada cristal, con sabor e odor fresca e mentin
en   menthol

menu   nom   (dise ‘menú’)
Un lista de comedas otenable a un restorante; (en informatica) un lista de comandas o elejes disponable; (metafor) cualce lista de avenis o elejes
en   menu; program/programme, agenda

»  menu cadente   nom
en   drop-down menu

»  menu cascadente   nom
en   cascading menu

menur   nom
Un avia grande de Australia, de cual la mas ave un coda longa con forma de lira, notada per sua canta e esibi
Menura
en   lyrebird

mera   ajetivo
Asentuante ce un person o cosa es peti o nonimportante, o ce sua presentia sufisi per influe un situa
‹ nos es mortales mera; la pensa mera de comeda ia repulsa el ›
en   mere

»  mera   averbo
No plu ca, o apena plu ca
‹ la sona ia es mera la tona ›
en   merely, only, just, simply, purely, not much more than

merbromina   nom
Un composada usada como un antisepsica
en   merbromin, mercurochrome (antiseptic)

mercato   nom
Un asembla de persones per compra e vende furnis, bestias e otra benes; la spasio o construida en cual esta aveni
en   market, emporium, mart

»  mercato de pulgas   nom
en   flea market

»  mercato emerjinte   nom
en   emerging market

»  mercato otimiste   nom
en   bull market

»  mercato pesimiste   nom
en   bear market

»  mercatiste   ajetivo
en   marketing (company, expert)

»  mercator   nom
en   merchant, market trader

»  supramercato   nom
en   supermarket

mercurdi   nom
La dia entre martedi e jovedi en cada semana
en   Wednesday
eo   merkredo
fr   mercredi

Mercurio   nom   «☿»
La dio roman de bonparla, capasia, comersia e fura, e la eraldo e mesajor de la dios; la planeta peti la plu prosima a la Sol
en   Mercury (mythology, planet)

»  mercurio   nom   «Hg (hydrargyrum)»
La elemento cimical con numero atomal 80, un metal licuida a temperatures comun
en   mercury, quicksilver

merda   nom
(Nonformal) fece; un person o cosa sin valua
en   (colloquial) shit, crap, turd (dung, anything worthless); (insult) asshole/arsehole

»  merda de bove   nom
en   (colloquial) bullshit, bollocks (nonsense)

»  merdi   verbo transitiva
en   (colloquial) shit

merenge   nom
Un comeda, tipal de deser, preparada de un misca de zucar e blanca de ovos bateda, fornida asta cuando lo es cracosa, e cisa plenida con fruta o crema bateda
en   meringue (dessert)

merenge   nom
Un stilo de musica e dansa de la Republica Dominican
en   meringue (Dominican dance, music)

»  merenge aitian   nom
en   méringue (Haitian dance, music)

meridiano   nom
Un sirculo de lonjitude constante tra la polos norde e sude
en   meridian

merita   verbo transitiva
Mostra condui o cualias sufisinte per reseta (un premio, recompensa, amira, puni o desonora)
en   deserve, merit, be worthy of, warrant, justify, be due, be owed, be entitled to

»  merita   nom
en   merit, worth; entitlement, desert

»  meritada   ajetivo
en   deserved, merited, justified

»  meritante   ajetivo
en   deserving, worthy, entitled

»  meritante la labora   ajetivo
en   worthwhile, worth the effort, worth the trouble

»  nonmeritada   ajetivo
en   undeserved, unmerited, unwarranted, unjustified, undue

»  nonmeritante   ajetivo
en   unworthy

meritocrata   ajetivo
Pertinente a un sistem de governa par la persones la plu meritante
en   meritocratic

»  meritocrata   nom
en   meritocrat

»  meritocratia   nom
en   meritocracy

merlan   nom
Un pex magra en familia de gado
Merlangius merlangus
en   whiting (fish)

merlo   nom
Un avia comun, con plumas xef negra
Turdus merula, Agelaius phoeniceus
en   blackbird

merlon   nom
Cada de la partes levada de un parapeto entre indentes periodal de la mesma estende, usada per defende o decora
en   merlon, battlement, embattlement, crenellation, castellation (architecture)

»  merloni   verbo transitiva
en   crenellate, castellate

»  merlonida   ajetivo
en   crenellated, castellated

»  merlonin   ajetivo
en   crenellated

merlusa   nom
Un pex longa con testa grande, mandibula longa e dentes forte
Merluccius
en   hake (fish)

mero   nom
Un pex grande de mar, con testo grande e boca larga
Serranidae
en   grouper (fish)

mersenaria   nom
Un spesie de bivalvo trovada a la costa atlantica de America Norde
Mercenaria mercenaria
en   quahog, hard clam (mollusk/mollusc)

mersenario   nom
Un soldato profesal empleada per servi en un armada stranjer
en   mercenary (soldier)

mertensia   nom
Un planta en familia de boraja, cual produi grupos de flores blu e campanin en la primavera
Mertensia
en   bluebell (plant)

mervelia   verbo nontransitiva
Senti un surprende amirante par causa de un esperia bela, nonespetada, nonconoseda o nonesplicable
en   marvel, wonder, be astonished

»  mervelia   verbo transitiva
en   astonish, amaze

»  mervelia   nom
en   marvel, miracle

»  merveliosa   ajetivo
en   marvelous/marvellous, wonderful, awe-inspiring, awesome, majestic, magnificent, glorious, superb, splendid, sublime

mesaje   nom
Un comunica parlada, scriveda o rejistrada, enviada o lasada per un resetor ci on no pote contata direta
en   message

»  mesaje pronto   nom
en   instant message

»  mesajeta   nom
en   text message, text, SMS

»  mesaji   verbo transitiva
en   message, send as a message, text

»  mesaji   nom
en   messaging, texting

»  mesaji pronto   nom
en   instant messaging

»  mesajor   nom
en   messenger, courier

mescal   nom
Un bevida de alcol, distilada de la sava de un agave
en   mescal, mezcal (drink)

mescalina   nom
Un droga enebriante cual produi alusinas, preparada de la cacto peote
en   mescaline (drug)

mescite   nom
Un arboreta spinosa en familia de piso, trovada en la SUA sude-ueste e Mexico
Prosopis
en   mesquite, mezquite (plant)

mesensefalo   nom
Un parte de la sistem de nervos, asosiada con vide, oia, controla de move, velia, e regula de temperatur
en   midbrain, mesencephalon (anatomy)

mesenterio   nom
Un plia de la peritoneo cual afisa la stomaco, intestin magra, pancreas, spleno e otra organos a la mur posterior de la adomen
en   mesentery (anatomy)

mesma   ajetivo, prenomal
No diferente; no cambiada
nb   "Mesma" es tipal presededa par "la", "esta" o "acel".
en   same, identical

»  mesma   averbo
No otra ca (la presedente)
nb   La averbo "mesma" asentua forte la nom o pronom cual presede direta lo.
en   -self (emphasising the preceding noun or pronoun)

»  el mesma   pronom
en   he himself, she herself (non-reflexive)

»  en la mesma modo   averbo
en   in the same way

»  la re mesma   nom
en   the king himself

»  lo es la mesma per cadun   espresa
en   one size fits all

»  lo mesma   pronom
en   it itself (non-reflexive)

»  los mesma   pronom
en   they themselves (non-reflexive)

»  me mesma   pronom
en   I myself (emphatic)

»  nos mesma   pronom
en   we ourselves (emphatic)

»  par sola se mesma   averbo
en   singlehandedly

»  se mesma   pronom
en   himself, herself, itself, themselves (emphatically reflexive)

»  tu mesma   pronom
en   you yourself

»  vos mesma   pronom
en   you yourselves

meso-   prefisa
Media
en   meso- (middle)

Mesoamerica   nom
La rejion sentral de America, de Mexico sentral a Nicaragua, spesial como un rejion de sivilias antica e cultures nativa ante la ariva de la espanioles
en   Mesoamerica

mesofilia   nom
La prefere par un organisme per abita en un ambiente de temperatur media
en   mesophilia (biology)

»  mesofilica   ajetivo
en   mesophilic

»  mesofilica   nom
en   mesophile

mesolitica   ajetivo
Pertinente a la parte media de la eda de petra, entre la paleolitica e la neolitica
en   Mesolithic (geology)

»  mesolitica   nom
en   Mesolithic (geology)

mesomisetozon   nom
Un membro de un grupo peti de organismes entre fungos e animales, de cual la plu es parasitos de pexes o otra animales
Mesomycetozoea
en   mesomycetozoon (pl. mesomycetomozoea) (organism)

meson   nom
Un particula suatomal cual ave un masa entre los de un eletron e un proton, e cual produi un interata forte cual lia nucleones a lunlotra en la nucleo atomal
en   meson (particle)

Mesopotamia   nom
Un rejion de Asia sude-ueste antica, spesial entre la rios Tigris e Eufrates
en   Mesopotamia

mesotelio   nom
La epitelio cual fore la pleuras, peritoneo e pericardio
en   mesothelium (anatomy)

»  mesotelial   ajetivo
en   mesothelial

mesotelioma   nom
Un canser de la texeda mesotelial, asosiada con esposa a asbesto
en   mesothelioma

mesozoica   ajetivo
Pertinente a la eda entre la paleozoica e senozoica, conteninte la triasica, jurasica e cretasica
en   Mesozoic (geology)

»  mesozoica   nom
en   Mesozoic (geology)

mesozon   nom
Un verme pico cual es un parasito interna de nonvertebratos maral
en   mesozoan (worm)

mestre   nom
Un person con capasia en un arte o otra ativia, tipal instruinte otras; (istorial) un person per ci sclavos labora
en   master; teacher, mentor; maestro, virtuoso

»  mestre de selebras   nom
en   master of ceremonies, MC, emcee, showman

»  mestral   ajetivo
en   master

»  mestresa   nom
(Istorial) un mestre fema
en   mistress

»  mestri   verbo transitiva
en   master

»  mestria   nom
en   mastery

»  mestrin   ajetivo
en   masterful, masterly

mesura   verbo transitiva
Trova la grandia, cuantia o grado de (alga cosa) par usa un strumento o aparato marcada con unias normal o par compara lo con un ojeto de grandia conoseda
en   measure

»  mesura   nom
en   measure, measurement, dimension; bar (music)

»  mesurable   ajetivo
en   measurable

»  mesurador   nom
en   measuring device, meter

»  mesuras   nom, plural
en   measurements, dimensions

»  nonmesurable   ajetivo
en   immeasurable, unfathomable

»  nonmesurada   ajetivo
en   unmeasured

met-   prefisa
Nominte alcanos e otra idrocarbonos con un atom de carbono
en   meth- (chemistry)

meta-   prefisa
Indicante un nivel plu alta o transendente; ance usada en modos diversa en termas tecnical
en   meta-

metaboli   verbo nontransitiva
(Comeda) muta en la corpo per manteni la vive
en   metabolize/metabolise

»  metaboli   verbo transitiva
en   metabolize/metabolise

»  metaboli   nom
en   metabolism

»  metabolal   ajetivo
en   metabolic

metabolite   nom
Un materia formida en o nesesada per metaboli
en   metabolite (biology)

metacarpo   nom
La grupo de sinco osos en la mano, entre la polso e la ditos
en   metacarpus (bones)

»  metacarpal   ajetivo
en   metacarpal

metacualona   nom
Un medisin calminte e adorminte
en   methaqualone, quaalude (drug)

metadatos   nom, plural
Datos cual descrive e furni informa sur otra datos, per esemplo en un catalogo de documentos
en   metadata

metadon   nom
Un paradole sinteseda, simil a morfina, usada per trata la usa abitual de morfina o eroina
en   methadone (painkiller)

metafase   nom
La fase du de la divide de selulas
en   metaphase

metafisica   nom
La ramo de filosofia cual studia la prinsipes prima de cosas, incluinte consetas astrata como esiste, sabe, materia, causa, identia, tempo e spasio
en   metaphysics

»  metafisical   ajetivo
en   metaphysical

»  metafisiciste   nom
en   metaphysician

metafor   ajetivo
(Un parola o espresa) pertinente a un ojeto a cual lo no es leteral aplicable; (un cosa) videda como un representa o simbol de un otra, tipal astrata
en   metaphorical, metaphoric, figurative

»  metafor   nom
en   metaphor, trope

metal   ajetivo
(Un materia) solida, tipal dur, briliante, martelable, fusable, e formable sin rompe o frati
en   metal, metallic

»  metal   nom
en   metal

»  metal resiclable   nom
en   scrap, scrap metal

»  arte de metal   nom
en   metalwork, metalworking

»  metalin   ajetivo
en   metallic, metal-like

»  metalor   nom
en   metalworker

»  nonmetal   ajetivo
en   non-metal

»  nonmetal   nom
en   non-metal

metalurjia   nom
La ramo de siensa e tecnolojia cual studia la cualias de metales e sua produi e puri
en   metallurgy

»  metalurjial   ajetivo
en   metallurgical

»  metalurjiste   nom
en   metallurgist

metamfetamina   nom
Un droga sinteseda con efetos plu forte ca amfetamina
en   methamphetamine, meth

metano   nom
Un gas flamable sin color e odor, cual es la composante xef de gas natural
en   methane

metanol   nom
Un alcol venenosa, flamable, volatil e sin color, fabricada par distila de lenio o par osidi metano
en   methanol

metastase   verbo nontransitiva
(Un canser) apare como un crese nova, a distantia de la loca de la crese prima
en   metastasize/metastasise (medical)

»  metastase   nom
en   metastasis

metatarso   nom
La grupo de osos en la pede, entre la talo e la ditos
en   metatarsus (bones)

»  metatarsal   ajetivo
en   metatarsal

metatese   verbo nontransitiva
(Fonemes o leteras) intercambia sua locas en un parola; (du composadas cimical) intercambia iones
en   metathesize/metathesise

»  metatese   nom
en   metathesis

metazon   nom
Un divide major de la rena de animales, composada de tota animales estra la protozones e sponjas, per dise animales multiselulal con texedas distinguida
Metazoa, Animalia
en   metazoon (pl. metazoa) (member of the animal kingdom)

meteor   nom
Un corpo peti de materia de spasio cual entra a la atmosfera de tera, incandesente como un resulta de frica e aspetante como un banda de lus
en   meteor

»  meteorin   ajetivo
en   meteoric

meteorite   nom
Un meteor cual ia survive sua pasaje tra la atmosfera e ia colpa la tera
en   meteorite

meteorolojia   nom
Un siensa cual studia la prosedes e fenomenos de la atmosfera, tipal per predise la clima local
en   meteorology

»  meteorolojial   ajetivo
en   meteorological

»  meteorolojiste   nom
en   meteorologist

metil   nom
La radical -CH3, derivada de metano e presente en multe composadas organica
en   methyl (chemistry)

metodo   nom
Un modo spesifada per fa alga cosa, tipal sistemosa o bon fundida
en   method, manner, way, technique, means

»  metodisme   nom
en   Methodism (Christianity)

»  metodiste   ajetivo
en   Methodist

»  metodiste   nom
en   Methodist

»  metodosa   ajetivo
en   methodical

»  par sua propre metodo   averbo
en   on one’s own terms

metodolojia   nom
Un sistem de metodos usada en un campo de studia o investiga
en   methodology

metonim   ajetivo
(Un parola, nom o espresa) sustituinte per un otra cosa con cual lo es prosima asosiada
en   metonym (substitution of name)

»  metonimia   nom
en   metonymy

metraje   nom
Un colie de pesos de filma rejistrada, tipal ante edita los
en   footage (film)

metre   nom
La unia fundal de longia en la sistem internasional; la ritmo de un poesia
en   meter/metre (unit of length, poetry)

»  cilometre   nom
en   kilometer/kilometre

»  cilometres   nom, plural
en   mileage (distance traveled/travelled)

»  decametre   nom
en   decameter/decametre

»  desimetre   nom
en   decimeter/decimetre

»  ectometre   nom
en   hectometer/hectometre

»  metral   ajetivo
en   metric

»  micrometre   nom
Un milioni de un metre; un aparato per mesura distantia o angulos multe peti, usante un spesie de vise
en   micrometer/micrometre (unit of length); micrometer (measuring tool)

»  milimetre   nom
en   millimeter/millimetre

»  nanometre   nom
en   nanometer/nanometre

»  nonmetral   ajetivo
en   non-metric, imperial

»  sentimetre   nom
en   centimeter/centimetre

metro   nom
Un ferovia su tera
en   underground, subway (railway)

metronomo   nom
Un aparato usada par musicistes per indica la tempo par tictacis o luses periodal
en   metronome

mexa   nom
Un colie peti de capeles, fibres, erba, etc; un banda de materia porosa tra cual licuida combustable es traeda a la flama de un candela, lampa, etc; un banda de materia longo cual un flama move per esplode un bomba o foco artal
en   lock (hair), tuft, hank, wisp; wick; fuse (bomb)

»  con mexa   ajetivo
en   tufted

»  mexin   ajetivo
en   tuftlike, tufty

»  mexon   nom
en   tress, long lock (hair)

Mexico   nom
Un pais en America Norde sude-ueste con costas longa a la Mar Mexico e la Mar Pasifica, a sude de la SUA
(capital: la Site Mexico)
en   Mexico

»  Golfo Mexico   nom
Un estende grande de la Mar Atlantica ueste, con la SUA a norde, Mexico a ueste e sude, e Cuba a sude-este
en   Gulf of Mexico

»  mexican   ajetivo
en   Mexican

»  mexican   nom
en   Mexican

»  Mexico Nova   nom
Un stato en la SUA sude-ueste, bordante Mexico
en   New Mexico (US state)

mezuza   nom
Un pergamin enscriveda con testos relijiosa e afisada en un caxa a la palo de porte de un casa iudi
en   mezuzah (parchment)

mi   nom
La nota tre de la scala de C major, E, en la sistem de solfejo
en   mi (musical note)
fr   mi

Miama   nom
Un pais en Asia sude-este a la Golfo Bengala
(capital: Nay Pyi Taw)
→ Burma
en   Myanmar, Burma

»  miama   ajetivo
→ burman
en   Burmese (person, language)

»  miama   nom
en   Burmese (person, language)

miasma   nom
Un aira nonsana, odorosa e contaminada
en   miasma (vapor/vapour)

miastenia   nom
Un malada cual causa un debilia nonormal de alga musculos
en   myasthenia (medical)

miau   esclama
La sona fada par un gato
en   miaow, meow

»  miaui   verbo nontransitiva
en   miaow, meow, mew

miau-iau   ajetivo
Pertinente a un popla tradisional abitante en viletas isolida en la montanias de Asia sude-este, o a sua lingua
en   Miao-Yao, Hmong-Mien (person, language)

»  miau-iau   nom
en   Miao-Yao, Hmong-Mien (person, language)

mica   nom
Un mineral briliante de silica, con stratos peti, usada como un isolinte
en   mica (mineral)

Michigan   nom   (dise ‘míxigan’)
Un stato en la SUA norde-sentral, con bordas a la Lago Michigan e la Lago Superior
en   Michigan (US state)

»  Lago Michigan   nom
Un de la sinco Lagos Grande de America Norde
en   Lake Michigan

micolojia   nom
La studia siensal de fungos
en   mycology

»  micolojial   ajetivo
en   mycological

»  micolojiste   nom
en   mycologist

micose   nom
Un maladia de infeta par un fungo
en   mycosis

»  micosica   ajetivo
en   mycotic

micro-   prefisa
Peti; 10^-6
en   micro- (small, a millionth)

microarciteta   nom
(En informatica) la desinia de la reali de la lojica fundal en un prosedador
en   microarchitecture

microbio   nom
Un organisme multe peti, como un ameba, bateria o virus; un malfunsiona de un aparato, subita e tipal tempora
en   microbe, bug, germ, virus; glitch, defect (electronic)

»  antimicrobial   ajetivo
en   antimicrobial, antibiotic, antiseptic, germicide

»  antimicrobial   nom
Un medisin per mata microbios
en   antimicrobial, antibiotic, antiseptic, germicide

»  sin microbios   ajetivo
en   germfree

microbiolojia   nom
La ramo de siensa cual studia microbios
en   microbiology

»  microbiolojiste   nom
en   microbiologist

microcosmo   nom
Un loca, situa o comunia regardada como un esemplo miniatur de un cosa multe plu grande
en   microcosm

microcredito   nom
La presta de cuantias peti de mone con interesa basa a un comersia nova en la mundo developante
en   microcredit

microfilma   nom
Un filma conteninte fotos peti de pajes de un jornal, catalogo o otra documento, multe usada per arcivi informas ante la eda de computadores
en   microfilm

microfon   nom
Un aparato per cambia ondas de sona a varias de enerjia eletrical, cual pote alora es grandida, transmeteda o rejistrada
en   microphone, mic, mike

microlito   nom
Un petra peti, formida per usa como un parte de un util como un lansia
en   microlith (geology)

micron   nom
Un unia de longia egal a un milioni de un metre, usada en alga campos de siensa e tecnolojia, e formal nomida un micrometre
en   micron (unit of length)

Micronesia   nom
Un colie de isolas en la Mar Pasifica a norde de Melanesia e a ueste de Polinesia
en   Micronesia

»  micronesian   ajetivo
en   Micronesian

»  micronesian   nom
en   Micronesian

»  Statos Federada de Micronesia   nom, plural
Un pais composada de sentos de isolas en Micronesia
(capital: Palikir)
en   Federated States of Micronesia

microonda   nom
Un onda eletromagnetal con longia de onda entre 0,001 e 0,3 metres, plu corta ca ondas de radio ma plu longa ca ondas infraroja, usada en comunica e per coce
en   microwave

microplastica   nom
Pesos pico de plastica dejetada en la ambiente
en   microplastic

microscopio   nom
Un aparato otical, usada per vide ojetos multe peti, como selulas, tipal grandinte los a alga sentos de veses
en   microscope

»  Microscopio   nom
Un constela minor en la sielo sude
en   Microscopium (constellation)

»  microscopi   verbo transitiva
en   examine with a microscope

»  microscopi   nom
en   microscopy

»  microscopial   ajetivo
en   microscopic

microsefalia   nom
Un malformi jenetical, marcada par un testa nonormal peti e un developa noncompleta de la serebro
en   microcephaly (medical)

»  microsefalica   ajetivo
en   microcephalic, microcephalous

microsirurjia   nom
Sirurjia usante un microscopio e strumentos peti
en   microsurgery

microtelia   nom
Un telieta de materia semicondutante, usada per fabrica un sircuito integrada
en   microchip, chip

microtomo   nom
Un strumento per talia sesiones multe magra per esamina su un microscopio
en   microtome (slicing tool)

»  microtomia   nom
en   microtomy

miel   nom
Un licuida viscosa, dulse e jalin brun, produida par abeas e otra insetos, de netar colieda de flores
en   honey

»  mielin   nom
en   honey, sweetheart

mielada   nom
Un sustantia dulse e viscosa escreteda par afidos sur folias e talos
en   honeydew (substance)

mielifaje   nom
Un avia cantante de Australasia con lingua longa e brosin per come netar
Meliphagidae
en   honeyeater (bird)

mielin   nom
Un gaina blanca e isolinte sirca multe fibres neuronal, cual grandi la rapidia de transmete impulsas
en   myelin (biology)

mieloide   ajetivo
Pertinente a la medula de osos; (leucemia) marcada par la sperde nonormal de limfosites orijinante en la medula de osos
en   myeloid (anatomy)

mieloma   nom
Un tumor canserosa de la medula de oso
en   myeloma (medical)

mielosite   nom
Un selula joven, tipal locada en la medula de osos
en   myelocyte (biology)

migra   verbo nontransitiva
Move de un parte o situa a un otra; (un animal, tipal un avia o pex) move de un rejion a un otra, tipal periodal e seguente la saisones; (un person) move de un rejion o pais per relocali en un otra, spesial per trova emplea
en   migrate

»  migra   verbo transitiva
en   migrate

»  migra   nom
en   migration, immigration, emigration

»  migra a   verbo
en   immigrate to

»  migra de   verbo
en   emigrate from

»  migrante   ajetivo
en   migrating

»  migrante   nom
en   migrant

»  migror   nom
en   immigrant, emigrant

migrania   nom
Un dole de testa palpitante e reveninte cual afeta tipal un lado de la testa e es comun acompaniada par nausea e disturbas de vide
en   migraine

mil   determinante
1000, 10^3
en   (a) thousand

»  mil   ajetivo
en   thousandth (ordinal)

»  desmili   verbo nontransitiva
en   split into ten thousand

»  desmili   verbo transitiva
en   split into ten thousand

»  desmili   nom
en   ten-thousandth (fraction)

»  miles   nom, plural
en   thousands

»  mili   verbo nontransitiva
en   split into a thousand parts

»  mili   verbo transitiva
en   split into a thousand parts

»  mili   nom
en   thousandth (fraction)

»  mili-   prefisa
Un mili de
en   milli- (a thousandth)

milan   nom
Un avia xasante con alas longa e coda divideda
Elaninae, Milvinae
en   kite (bird)

milenio   nom
Un periodo de mil anios
en   millennium

»  milenialisme   nom
en   millennialism

milflor   nom
Un motif de flores e folias usada en tapetos, porselana o otra ornas; un tipo de vitro ornal, fabricada par fusa e talia bastos de vitro diversa
en   millefleurs, millefiori (art)

milfolia   nom
Un planta eurasian en familia de margarita, con folias plumin e flores peti, bonodorosa e blanca, jala o rosa
Achillea millefolium
en   yarrow (plant)

milia   nom
Un unia per mesura distantia
en   mile

»  milia engles   nom
Un unia de 1,609 km
en   English mile

»  milia maral   nom
en   nautical mile

»  milia roman antica   nom
Un unia de 1000 pasos par la pede sinistra, egal a 1,481 km
en   Roman mile

milio   nom
Un planta sereal cual crese rapida e es cultivada en paises calda e rejiones con tera povre
Gramineae, spesial
en   millet (plant)

milion   determinante
1 000 000, 10^6
en   (a) million

»  milion   ajetivo
en   millionth (ordinal)

»  miliones   nom, plural
en   millions

»  milioni   verbo nontransitiva
en   split into a million parts

»  milioni   verbo transitiva
en   split into a million parts

»  milioni   nom
en   millionth (fraction)

»  milionor   nom
en   millionaire

milipede   nom
Un nonvertebrato con corpo longa de multe sesiones, de cual la plu ave du duples de gamas
Diplopoda
en   millipede

militar   ajetivo
Pertinente a soldatos o fortes armada
en   military, militaristic

»  militar   nom
en   serviceman, servicewoman; (the) military (organization/organisation)

»  artes militar   nom
en   martial arts

»  desmilitari   verbo nontransitiva
en   demilitarize/demilitarise

»  desmilitari   verbo transitiva
en   demilitarize/demilitarise

»  desmilitari   nom
en   demilitarization/demilitarisation

»  militares   nom, plural
en   (the) military

»  militari   verbo nontransitiva
en   militarize/militarise

»  militari   verbo transitiva
en   militarize/militarise

»  militari   nom
en   militarization/militarisation

»  militarisme   nom
en   militarism

»  militariste   ajetivo
en   militant

»  militariste   nom
en   militarist, militant

»  nonmilitar   ajetivo
en   civilian

»  nonmilitar   nom
en   civilian

»  servi militar   nom
en   military service

militia   nom
Un forte militar asemblada de la popla nonmilitar per aida la militar normal en un crise; un forte militar de rebelores o teroristes, tipal oposante la militar normal
en   militia

»  militior   nom
en   militiaman, militia member, minuteman

mima   verbo transitiva
Usa moves e jestis per sujesta (atas e emosias) en presentas divertinte
en   mime, pantomime, imitate

»  mima   nom
en   mime, pantomime, mimesis, mimicry, imitation

»  mimor   nom
Un person ci mima; un avia cantante, notada per sua capasia de mima
Mimidae
en   mime, mimer (person); mockingbird, catbird, thrasher

mimeograf   nom
Un macina istorial cual produi documentos par copia los de un stensil
en   mimeograph

»  mimeografia   nom
en   mimeography

mimosa   nom
Un planta en la familia Leguminosae cual responde a tocas par curvi sua folias; un arbor acasia con folias delicata e flores jala; un bevida de xampania con jus de orania
Mimosa, Acacia dealbata
en   mimosa (plant)

min   determinante
Con cuantia plu peti; no tan multe
‹ min enerjia; min persones ›
en   less, fewer

»  min   averbo
‹ min alta ca ›
en   less

»  min   conjunta
en   minus (arithmetic)

»  min ... min   espresa
‹ min lo pluve, min la teto gotea; min bon es la problem, plu bon es la solve; min los ave, plu los vole ›
en   the less ... the less
eo   ju malpli ... des malpli

»  min ca nun   espresa
en   second to none

»  min e min   averbo
en   less and less, ever less

»  a la min   averbo
en   at least, as a minimum

»  la min   averbo
‹ la lia la min forte ›
en   least

»  la min de   espresa
en   least, fewest, the minority of

mina   verbo transitiva
Oteni (carbon o otra minerales) par escava
en   mine

»  mina   nom
en   mining

»  mina de datos   verbo
en   data mining

»  mineria   nom
en   mine

»  sumina   verbo transitiva
en   undermine

minareta   nom
Un tore alta e magra, normal como parte de un mascita, con un balcon de cual un cantor clama a muslimes per prea
en   minaret (mosque tower)

Mindanao   nom
Un isola en la Pilipinas, numero du en grandia
en   Mindanao (island)

Mindoro   nom
en   Mindoro

»  Streta Mindoro   nom
Un streta a ueste de Mindoro
en   Mindoro Strait

mineral   ajetivo
(Un materia) solida, nonorganica e natural aveninte, tipal otenida par mina
en   mineral

»  mineral   nom
en   mineral, ore

»  minerali   verbo nontransitiva
en   mineralize/mineralise

»  minerali   verbo transitiva
en   mineralize/mineralise

»  minerali   nom
en   mineralization/mineralisation

mineralojia   nom
La studia siensal de minerales
en   mineralogy

»  mineralojial   ajetivo
en   mineralogical

»  mineralojiste   nom
en   mineralogist

ming   ajetivo
Pertinente a la dinastia cual ia rena Jonguo de 1368 ec a 1644
en   Ming (dynasty)

mini-   prefisa
La plu peti cual es posible
en   mini-

miniatur   ajetivo
Con grandia multe plu peti ca normal
en   miniature

»  miniatur   nom
en   miniature

»  miniaturi   verbo transitiva
en   miniaturize/miniaturise

»  miniaturi   nom
en   miniaturization/miniaturisation

»  miniaturiste   nom
en   miniaturist

minibus   nom
Un bus peti per sirca 10 a 15 pasajores
en   minibus

minifalda   nom
Un falda multe corta
en   miniskirt

minima   ajetivo
La plu peti, la plu basa
en   minimum, minimal, least; nominal (cost)

»  minima   averbo
A la min
en   at least

»  minima   nom
en   minimum, least

»  minimi   verbo nontransitiva
en   minimize/minimise, downplay, understate
es   minimizar
fr   minimiser
it   minimizzare
pt   minimizar

»  minimi   verbo transitiva
en   minimize/minimise, downplay, understate

»  minimi   nom
en   minimization/minimisation

»  minimisme   nom
en   minimalism

»  minimiste   ajetivo
en   minimalist

»  minimiste   nom
en   minimalist

minimax   nom
(En la teoria de juas) la plu basa de un colie de masimas
en   minimax (game theory)

minimoto   nom
Un motosicle miniatur
en   minibike (motorcycle)

minio   nom
Un forma roja de osido de plomo, usada como un pigmento
en   minium, red lead (pigment)

minipantala   nom
Un pantala estrema corta; un vesteta de forma simil
en   hotpants, short shorts, booty shorts; (underwear) boyshorts, boxer briefs

miniserie   nom
Un serie corta de programes de televisa
en   miniseries

minislip   nom
Un spesie de slip con lados alta taliada o asente
en   minibriefs, bikini briefs, tanga briefs

ministro   nom
La xef de un departe de la governa
en   minister (government)

»  ministro de esternas   nom
en   foreign minister, foreign secretary, secretary of state for foreign affairs

»  ministro de internas   nom
en   home secretary, secretary of state for internal affairs

»  ministro xef   nom
en   prime minister, chancellor

»  ministral   ajetivo
en   ministerial

»  ministreria   nom
en   ministry

Minnesota   nom
Un stato en la SUA norde-sentral, bordante Canada
en   Minnesota (US state)

minor   ajetivo
Min importante; (un person con la mesma nom como un otra) la plu joven
en   minor, slight; junior, the younger (in names)

»  minor   nom
en   minor

»  minori   verbo nontransitiva
en   convert to lowercase

»  minori   verbo transitiva
en   convert to lowercase

»  minoria   nom
en   minority

minotauro   nom
Un monstro mital umanin, con testa de bove
en   minotaur

minueto   nom
Un dansa de bal per du persones, popular en la sentenio 18; un musica en tempo truple per esta
en   minuet (dance, music)

minuto   nom
Un periodo de tempo egal a 60 secondos o un sesdesi de un ora; un sesdesi de un grado angulo
en   minute

mio-   prefisa
Musculos
en   myo- (muscle)

miocardial   ajetivo
Pertinente a la texeda musculosa de la cor
en   myocardial

miope   ajetivo
No capas de vide clar, estra cuando cosas es prosima a la oios
en   near-sighted, short-sighted, myopic

»  miopia   nom
en   near-sightedness, short-sightedness, myopia

miosene   ajetivo
Pertinente a la epoca cuatro de la periodo tre de jeolojia, entre la oligosene e la pliosene
en   Miocene (geology)

»  miosene   nom
en   Miocene (geology)

miosite   nom
Un tipo de selula en texeda musculal
en   myocyte (biology)

mira   nom
Un arbor de cual on oteni un resina bonodorosa usada en parfum, insenso e medisin; esta resina
Commiphora myrrha
en   myrrh (tree, resin)

miracle   nom
Un bon aveni nonesplicable par siensa e donce regardada como un ata divin; un bon aveni nonprobable o estracomun; un produida o ateni stonante bon
en   miracle

»  miraclor   nom
en   miracleworker

»  miraclosa   ajetivo
en   miraculous

miraje   nom
Un ilude de vide causada par la state de la atmosfera, tipal la apare de acua en un deserto o sur un via calda
en   mirage

mirandes   ajetivo
Pertinente a la popla de un parte peti de Portugal norde-este, o a sua lingua
en   Mirandes (person, language)

»  mirandes   nom
en   Mirandes (person, language)

miriapodo   nom
Un artropodo con multe pedes, como la sentopede o milipede
en   myriapod (arthropod)

mirica   nom
Un arboreta de America Norde, con folias cuorin e bonodorinte e bacas sirin
Myrica gale
en   bayberry (plant, berry)

miror   nom
Un surfas, tipal vitro combinada con metal, cual refleta un imaje clar
en   mirror

»  miror de retrovista   nom
en   rear-view mirror

»  mirori   verbo transitiva
en   mirror

mirto   nom
Un arboreta perene con folias briliante e bonodorosa, e flores blanca segueda par bacas oval e purpurin negra
Myrtus
en   myrtle (plant)

misa   nom
Un rituo de comunia santa, tipal de la Eglesa Catolica Roman
en   mass (religious)

»  misa de moria   nom
en   requiem

»  misal   ajetivo
en   (of) mass

»  misal   nom
en   missal (book)

misantrope   ajetivo
Odiante umanas
en   misanthropic

»  misantrope   nom
en   misanthrope, misanthropist

»  misantropia   nom
en   misanthropy

misca   verbo transitiva
Combina (cosas) per forma un masa; reordina (cosas) en modo acaso
en   mix, blend, jumble, scramble, intersperse; mingle; shuffle (reorder)

»  misca   nom
en   mixture, miscellany, jumble, admixture, hodgepodge, hotchpotch, medley, melange, potpourri

»  misca de razas   nom
en   interbreeding, miscegenation

»  desmisca   verbo transitiva
en   unmix, unscramble

»  intermisca   verbo nontransitiva
en   intermingle

»  intermisca   verbo transitiva
en   intermingle

»  miscable   ajetivo
en   miscible

»  miscada   ajetivo
en   mixed, miscellaneous, assorted

»  miscador   nom
en   blender, mixer, mixing machine

»  miscador de beton   nom
en   cement mixer

»  premisca   verbo transitiva
en   premix

»  remisca   verbo transitiva
en   remix

miselio   nom
La parte de un fungo cual reprodui nonsesal, composada de un rede de filetas blanca e delicata
en   mycelium (biology)

misera   ajetivo
Multe triste e noncomfortosa; causante compatia
en   miserable, abject, wretched, piteous, pitiful, downtrodden, pathetic, squalid, crummy, lousy

»  misera   nom
en   wretch; fleabag

»  miseria   nom
en   misery, abjection, abjectness, squalor/squalour

misil   nom
Un arma, tipal autopropulsada, cual es xutada a un ojeto
en   missile, projectile

»  misil cruser   nom
en   cruise missile

»  misil de tera a aira   nom
en   surface-to-air missile

»  misil intercontinental   nom
en   intercontinental missile

»  misil luminante   nom
en   flare

mision   nom
Un asinia importante, tipal nesesante un viaja
en   mission, expedition

»  mision fol   nom
en   fool’s mission, fool’s errand

»  misioneria   nom
en   mission (station)

»  misioneta   nom
en   errand

»  misionor   nom
en   missionary

miso   nom
Un sopa de pex e soia fermentada, orijinante en Nion
en   miso (soup)

miso-   prefisa
Odiosa
en   miso- (hate)

misojine   ajetivo
Odiante femas
en   misogynistic

»  misojine   nom
en   misogynist

»  misojinia   nom
en   misogyny

Misre   nom
Un pais en Africa norde-este, bordante la Mar Mediteraneo
(capital: Qahira)
→ Egipte
en   Egypt

»  misri   ajetivo
en   Egyptian

»  misri   nom
en   Egyptian

Mississippi   nom
Un stato de la SUA sude-sentral
en   Mississippi (US state)

»  Rio Mississippi   nom
Un rio major en America Norde, cual comensa en Minnesota, prosima a la borda de Canada, e flue a sude asta la Mar Mexico
en   Mississippi River

Missouri   nom
Un stato en la rejion sentral de la SUA
en   Missouri (US state)

»  Rio Missouri   nom
Un rio major en America Norde, cual comensa en la Montes Rocosa en Montana e fini en la Rio Mississippi en la SUA sentral
en   Missouri River

misterio   nom
Cualce cosa difisil o nonposible per esplica o comprende; un novela, presenta o filma sur un crimin confondente
en   mystery, enigma; whodunnit

»  desmisteri   verbo nontransitiva
en   demystify

»  desmisteri   verbo transitiva
en   demystify

»  desmisteri   nom
en   demystification

»  misteriosa   ajetivo
en   mysterious, uncanny

mistica   ajetivo
Pertinente a la crede ce on pote aprende direta sabes divin o deveni unida con un dio
en   mystic, mystical, esoteric

»  mistica   nom
en   mystic

»  misticisme   nom
en   mysticism

mistral   nom
Un venta forte e fria de la norde-ueste cual sofla tra Frans sude a la Mediteraneo, tipal en la inverno
en   mistral (wind)

mito   nom
Un nara o colie de naras tradisional, spesial sur la istoria primitiva de un popla o esplicante avenis natural o sosial, tipal con carateres e avenis supranatural
en   myth, legend

»  desmiti   verbo nontransitiva
en   demythologize/demythologise

»  desmiti   verbo transitiva
en   demythologize/demythologise

»  mital   ajetivo
en   mythical, mythic

mitocondrio   nom
Un organeta trovada en cuantias grande en la plu de selulas, la loca per la prosedes biocimical de respira e produi de enerjia
en   mitochondrion (pl. mitochondria) (biology)

»  mitocondrial   ajetivo
en   mitochondrial

mitolojia   nom
Un colie de mitos, tipal parteninte a un tradision relijial o cultural; la studia de mitos
en   mythology

»  mitolojial   ajetivo
en   mythological

mitose   nom
Un tipo de divide selulal cual produi du selulas de cual cada ave la mesma cuantia de cromosomas como la selula orijinal
en   mitosis (biology)

mitra   nom
Un xapo alta, portada par bispos como un simbol de sua rol
en   mitre (hat)

»  mitral   ajetivo
Pertinente a un valva entre la atrio sinistra e la ventriculo sinistra de la cor
en   mitral (anatomy)

Mitra   nom
La dio de lus, veria e onora, e la figur sentral de la relijio mitraisme
en   Mithras, Mithra

»  mitraisme   nom   (dise ‘mitraïsme’)
en   mithraism

»  mitraiste   ajetivo   (dise ‘mitraïste’)
en   mithraist

»  mitraiste   nom
en   mithraist

mitralia   verbo transitiva
(Un avion volante prosima a la tera) ataca repetente, con bombas o mitraliadores
en   strafe

»  mitraliador   nom
Un fusil cual xuta repetente en cuando la gatilio es presada
en   machine gun

»  mitralior   nom
en   machine gunner

mixino   nom
Un pex primitiva, sin mandibula e con corpo angilin
en   hagfish

mixna   nom
Un colie autoriosa de testos representante la tradision bocal de lege iudi, forminte la parte prima de la Talmud
en   Mishnah, Mishna (Judaism)

mm   esclama
Espresante pensa, o reatante a un bon sabor
en   hmm (thinking); mmm, yum (tasty)

moa   nom
Un avia grande e nonvolante, orijinal de Zeland Nova ma aora estinguida
Dinornithidae
en   moa (bird)

mobila   nom
Un cosa alga grande ma movable, como un table, seja o leto, usada per fa ce un casa, ofisia o otra spasio conveni per abita o labora
en   piece of furniture, item of furniture

»  mobila de vaso de note   nom
en   commode

»  mobilas   nom, plural
en   furniture, furnishings

»  mobileta   nom
Un ojeto manipulada par atores en un sena
en   prop

»  mobili   verbo transitiva
en   furnish

»  remobili   verbo transitiva
en   refurnish

moca   nom
Un cafe refinada o otra bevida simil; la color brun oscur de esta cafe
en   mocha (coffee)

mocasin   nom
Un sapato de cuoro suave, sin talon, simple coseda, en un stilo de la americanes orijinal
en   moccasin (shoe)

moda   nom
Un tende popular, spesial en stilo de vestes, decora, capeles o condui; un forma cual indica esce un verbo espresa un fato, comanda, demanda, espera o constrinje; la state de un program cual defini como lo va trata sua enflue; la valua la plu frecuente en un colie de datos
en   fashion, style, vogue, trend, fad; mood (grammar); mode (software, statistics)

»  moda de capeles   nom
en   hairstyle

»  moda dependente   nom
en   conditional mood, irrealis mood

»  moda indicativa   nom
en   indicative mood

»  moda refinada   nom
en   haute couture

»  moda sujuntiva   nom
en   subjunctive mood

»  a la moda   ajetivo
en   in fashion, cool, fashionable, stylish, trendy, chic, hot

»  bolsa de moda   nom
en   designer handbag

»  de moda   ajetivo
en   in fashion, cool, fashionable, stylish, trendy, chic, hot

»  de moda pasada   ajetivo
en   outdated, outmoded, out of fashion, old-fashioned

»  modal   ajetivo
en   modal; sartorial

»  modiste   nom
en   fashion designer, milliner, modiste, follower of fashion, fashionista

»  modosa   ajetivo
en   fashionable, stylish, chic, groovy, snazzy

»  nonmodosa   ajetivo
en   unfashionable, unstylish, dowdy, frumpy

model   ajetivo
Servinte como un esemplo per imita; representante la plu bon de sua tipo
en   model, exemplary, archetypal

»  model   nom
en   model, prototype, exemplar, example, archetype, pattern, standard, template, paradigm, mock-up; model (art, fashion)

»  model proportial   nom
en   scale model

»  modeli   verbo transitiva
en   model (make a model of; display clothes)

»  modeli   nom
en   modeling/modelling

modem   nom
Un aparato per modula e desmodula, per esemplo entre la datos dijital de un computador e la sinial analoja de un telefon
en   modem

modera   verbo transitiva
Fa ce (alga cosa) deveni min estrema, intensa, sever o violente
en   moderate, temper, mitigate

»  modera   nom
en   moderation, mitigation

»  moderada   ajetivo
en   moderate, sparing, tempered, mitigated

»  moderante   ajetivo
en   moderating, moderating

»  moderante   nom
en   moderator (substance)

»  moderor   nom
en   moderator (person)

»  nonmoderada   ajetivo
en   immoderate, intemperate

moderna   ajetivo
Pertinente a la presente o la eda la plu resente
en   modern

»  moderni   verbo nontransitiva
en   modernize/modernise, update, rework

»  moderni   verbo transitiva
en   modernize/modernise, update, rework

»  moderni   nom
en   modernization/modernisation, retrofit

»  modernia   nom
en   modernness, modernity

»  modernisme   nom
en   modernism

»  moderniste   nom
en   modernist

»  modernor   nom
en   modernizer/moderniser

modesta   ajetivo
Umil sur sua propre capasias o atenis; conduinte o vestinte se en un modo cual evita atrae atende sesal
en   modest (humble, avoiding impropriety), unpretentious

»  nonmodesta   ajetivo
en   immodest

»  tro modesta   ajetivo
en   prudish

modo   nom
Un ata o sistem par cual un cosa aveni o on reali un resulta
‹ en modo interesante ›
en   manner, means, way (of doing)

»  modo de parla   nom
en   way of speaking, parlance

»  modo de susta   nom
en   livelihood, living

»  modo de vive   nom
en   way of life, lifestyle, approach to life

»  en multe modos   averbo
en   in many ways, multiply

»  en no modo   averbo
en   by no means, in no way

»  en no otra modo ca   averbo
en   in no other way than, just, simply, purely

»  en otra modo   averbo
en   in another way, otherwise

modula   verbo transitiva
Controla la intensia, fortia, tono o altia de (un vose, strumento o otra cosa); controla la altia o frecuentia de un onda eletrical o otra osila, seguente la varias de un sinial du con frecuentia plu basa
en   modulate

»  modula   nom
en   modulation

»  desmodula   verbo transitiva
en   demodulate

»  modulador   nom
en   modulator

modulo   nom
Cada de un grupo de partes cual on pote combina per construi un strutur plu complicada; un numero usada como un dividente per esamina la cuantia restante
en   module; modulus

»  modulo   preposada
‹ 17 modulo 5 es 2 ›
en   modulo (mathematics)

»  modulal   ajetivo
en   modular

»  modulo estendente   nom
en   extension module

mofeta   nom
Un mamal american con pelo raiosa e blanca-negra, cual pote jeta un licuida iritante e malodorosa de sua glandes anal
Mephitidae
en   skunk

mofo   nom
Un crese pelin de fungos pico, tipal en ambientes umida e calda
en   mold/mould, mildew

»  mofosa   ajetivo
en   moldy/mouldy

mogano   nom
Un arbor de la tropicos american cual produi un lenio dur e brun rojin, tipal usada per mobilas de bon cualia; esta lenio
Swietenia
en   mahogany (tree, wood)

»  de mogano   ajetivo
en   (made of) mahogany

mohair   nom
La pelo longa e sedin de un capra ancaran; un filo o stofa fabricada de esta, tipal miscada con lana
en   mohair

Mohave, Deserto   nom
Un deserto en California sude, en la SUA ueste
en   Mojave Desert, Mohave Desert

moia   verbo transitiva
Toca o covre con licuida, spesial con acua
en   wet

»  moia   nom
en   wetting

»  moiada   ajetivo
en   wet, soaked, drenched

moisme   nom   (dise ‘moïsme’)
Un filosofia xines developada par la seguores de Mozi
en   Mohism (philosophy)

»  moiste   ajetivo   (dise ‘moïste’)
en   Mohist

»  moiste   nom
en   Mohist

mol   ajetivo
No dur; fasil moldida, cortida, compresada o pliada
→ suave
en   soft (not hard or tough), squishy; tender

»  moli   verbo nontransitiva
en   soften; relent

»  moli   verbo transitiva
en   soften; tenderize/tenderise

»  molia   nom
en   softness

mol   nom
Un unia internasional de cuantia de materia, egal a la cuantia conteninte tan multe unias fundal como la cuantia de atomes en 0,012 kg de carbono-12
en   mole (chemistry)

mola   nom
Un aparato, tipal spiral elica metal, cual reveni rapida a sua forma orijinal pos es presada o tirada
en   spring

»  cargada par mola   ajetivo
en   spring-loaded

mola   nom
Un pex grande de mares calda, con pinas alta dorsal e anal prosima a sua retro, e con coda multe corta
Mola mola
en   ocean sunfish, common mola

molda   nom
Un contenador vacua cual es usada per formi un materia fondeda como sira o metal cuando lo fri e duri
en   mold/mould, cast (container)

»  molda per pan   nom
en   bread pan

»  molda per tartes   nom
en   pie pan, pie tin

»  molda per tortas   nom
en   cake pan

»  moldi   verbo transitiva
en   mold/mould, cast

»  moldida   nom
en   molding/moulding, casting; mold/mould, cast (molded/moulded object)

Moldova   nom
Un pais sin costa en Europa sude-este, entre Romania e Ucraina
(capital: Chisinau)
en   Moldova, Moldavia

»  moldovan   ajetivo
en   Moldovan

»  moldovan   nom
en   Moldovan

moldur   nom
Un strutur cual formi la borda de un porte, fenetra, miror, depinta o simil; un orna de lenio, plastica o roca, usada per decora la bordas de un construida
en   frame (picture), molding/moulding, cornice
fr   moulure

»  moldur cablin   nom
en   cable molding/moulding

»  moldur de solo   nom
en   baseboard, skirting board

»  moldur merlonin   nom
en   dentil (architecture)
fr   denticule

»  moldurador   nom
en   router (carpentry tool)
fr   défonceuse

mole   verbo transitiva
Redui (alga cosa) a polvo o particulas peti par crase
en   grind, pound, pulverize/pulverise, reduce to powder; gnash (teeth)

»  molador   nom
en   grinder

molecula   nom
Un grupo de atomes liada a lunlotra como la unia la plu fundal de un composada cimical capas de partisipa en reatas cimical
en   molecule

»  moleculal   ajetivo
en   molecular

molesta   verbo transitiva
Ataca o menasa (algun), tipal en modo violente o persistente
en   molest, harass, harry, hassle

»  molesta   nom
en   molestation, harassment

molibdeno   nom   «Mo»
La elemento cimical con numero atomal 42, un metal arjentin gris e frajil
en   molybdenum (element)

molin   nom
Un aparato per mole gran o otra cosas; un construida conteninte xef un tal aparato; un parte musculosa de la stomaco de un avia, con mures spesa, per moli comedas
en   mill; gizzard

»  molin de carne   nom
en   meat grinder

»  molin de gran   nom
en   gristmill

»  molin de mano   nom
en   handmill, quern

»  molin de peper   nom
en   pepper mill, pepper grinder

»  molin de rio   nom
en   water mill

»  molin de venta   nom
en   windmill

»  molineta   nom
en   toy windmill, pinwheel; turnstile

»  molini   verbo transitiva
en   mill

»  molinor   nom
en   miller

molo   nom
Un strutur cual protende de la costa a en un mar o lago
en   pier, jetty, quay, quayside, wharf

molotro   nom
Un avia cantante de la mundo nova, con plumas negra e beco relativa corta, cual pone tipal sua ovos en la nido de un otra avia
Molothrus
en   cowbird

molusco   nom
Un membro de un filo grande de animales nonvertebrato, incluinte polpos, calamares, limasas e caracoles
Mollusca
en   mollusk/mollusc, shellfish

momento   nom
Un periodo de tempo estrema corta; un punto esata en tempo; la cuantia de move de un cosa, mesurada como sua masa multiplida par sua rapidia; la enerjia ganiada par un cosa movente
en   moment, instant, jiffy, juncture; momentum

»  de la momento   ajetivo
en   of the moment, du jour

»  momento angulo   nom
en   angular momentum

»  momento de torse   nom
en   torque

»  momento linial   nom
en   linear momentum

»  la bon momento   nom
en   the right moment, the opportunity, the chance

»  momental   ajetivo
en   momentary

momia   nom
La corpo de un umana o animal conservada par estrae de sua organos interna, trata con natron e resina, e envolve en bandas de stofa, comun en Egipte antica
en   mummy (preserved)

»  momi   verbo nontransitiva
en   mummify

»  momi   verbo transitiva
en   mummify

»  momi   nom
en   mummification

Monaco   nom
Un pais peti a la costa de la Mar Mediteraneo encluida par Frans
(capital: Vila Monaco)
en   Monaco

»  monaces   ajetivo
en   Monacan

»  monaces   nom
en   Monacan

monarca   nom
La xef de un stato, spesial un re, rea, imperor o imperoresa; un papilio grande, orania e negra, de America Norde
Danaus plexippus
en   monarch, sovereign; monarch butterfly

»  monarcal   ajetivo
en   monarchic, monarchical, monarchistic

»  monarcia   nom
en   monarchy, sovereignty

»  monarcisme   nom
en   monarchism, royalism

»  monarciste   ajetivo
en   monarchist, royalist

monax   nom
Un marmota de Norde America con corpo spesa e gamas corta
Marmota monax
en   woodchuck, groundhog, whistlepig (rodent)

monce   nom
Un membro de un comunia relijiosa, tipal jurante povria, obedi e asteni de seso
en   monk, nun

»  monce fema   nom
en   nun

»  monce mas   nom
en   monk

»  monce sever   nom
en   ascetic

»  moncal   ajetivo
en   monastic

»  monceria   nom
en   monastery, convent, abbey, cloister, nunnery, priory

»  moncin   ajetivo
en   monkish

»  moncisme   nom
en   monasticism

mone   nom
Un media de intercambia cual ave la forma de pesos de metal impresada o paperes prometente de un banco sentral
en   money, cash, currency

»  mone blancida   nom
en   laundered money

»  mone de jua   nom
en   play money, monopoly money

»  mone falsa   nom
en   counterfeit money

»  mone fisical   nom
en   cash, physical currency

»  mone lavada   nom
en   laundered money

»  mone sanguosa   nom
en   blood money

»  mone susia   nom
en   dirty money, lucre

»  con mone   averbo
en   in cash

»  monal   ajetivo
en   monetary

»  moneria   nom
en   mint (money)

»  moneta   nom
en   coin

monedula   nom
Un corvo peti e gris
Coloeus monedula
en   jackdaw

Mongol   nom
Un pais en Asia este cual inclui la Deserto Gobi, a sude de Sibir e a norde de Jonguo
(capital: Ulanbatar)
en   Mongolia

»  mongol   ajetivo
en   Mongolian

»  mongol   nom
en   Mongolian

mongoloide   ajetivo
(Ofendente e no plu usada) de la raza de Asia este; con sindrom de Down
en   mongoloid

monisme   nom
Un filosofia cual rejeta un distingui o dualia entre spirito e materia, o entre Dio e la mundo
en   monism (philosophy)

»  moniste   nom
en   monist

monito   nom
Un marsupio peti, nativa de la montanias de Txile e Arjentina
Dromiciops gliroides
en   monito del monte, chumaihuén, colocolo opossum (marsupial)

monitor   nom
Un aparato usada per oserva, esamina o manteni un rejistra continuante de un prosede o cuantia
en   monitor

»  monitor de glucosa   nom
en   glucose monitor, blood-sugar monitor

»  monitori   verbo transitiva
en   monitor, keep an eye on

»  monitori   nom
en   monitoring, surveillance

mono-   prefisa
Un, sola
en   mono- (one)

monoamina   ajetivo
Un composada con sola un grupo amina en sua molecula
en   monoamine (chemistry)

»  monoamina   nom
en   monoamine (chemistry)

monoblasto   nom
Un selula en la medula de oso, cual deveni monosites e ultima macrofagos
en   monoblast (biology)

monocini   nom
Un veste de nada per femes, egal a la dui basa de un bicini
en   monokini (garment)

monocota   nom
Un clado multe grande de plantas florinte, incluinte orcideas, erbas, bambus, bananas, oniones, liles, etc
en   monocot, monocotyledon (botany)

monocromata   ajetivo
Con sola un color; (un retina) capas de responde a sola un color; (un imaje) composada de tonos diversa de un color, o sola de negra e blanca
en   monochrome, monochromatic, black and white

monoculo   nom
Un sola lente per boni la vide, tenida ante la oio par la musculos sirca la oio
en   monocle

»  monoculal   ajetivo
en   monocular

monocultiveria   nom
Un cultiveria con un sola produida; un propria grande en cual on cultiva cosas como cafe, zucar o tabaco
en   monoculture, plantation

monoftongo   nom
Un vocal con sola un cualia persepida, contrastada con diftongos e triftongos
en   monophthong

»  monoftongi   verbo nontransitiva
en   monophthongize/monophthongise

»  monoftongi   nom
en   monophthongization/monophthongisation

monogama   ajetivo
Sposida a sola un person a la mesma tempo
en   monogamous

»  monogamia   nom
en   monogamy

»  monogamiste   nom
en   monogamist

monografia   nom
Un studia detaliosa, publicida sur un tema spesialida
en   monograph

»  monografi   verbo transitiva
en   monograph

»  monografiste   nom
en   monographer

monolingual   ajetivo
Capas de parla fluente sola un lingua; (un testo o ata) scriveda o fada en sola un lingua
en   monolingual
eo   unulingva

»  monolingual   nom
en   monolingual, monolingual person
eo   unulingvulo

monolito   nom
Un roca grande e vertical, comun como un monumento; (metafor) un strutur sosial o political cual es grande, nonpersonal e difisil per cambia
en   monolith

»  monolitin   ajetivo
en   monolithic

monologo   nom
Un parla longa par un sola ator en un presenta o filma; (metafor) un parla longa e monotonosa
en   monolog/monologue, soliloquy

monomania   nom
Un preocupa o zelo osesente sur sola un cosa
en   monomania

»  monomanica   ajetivo
en   monomaniacal

»  monomanica   nom
en   monomaniac

monomer   nom
Un molecula cual pote es liada a otra moleculas identica per formi un polimer
en   monomer (chemistry)

monomio   nom
Un espresa aljebral, composada de sola un terma
en   monomial (mathematics)

»  monomial   ajetivo
en   monomial (mathematics)

mononucleose   nom
Un cuantia nonormal alta de monosites en la sangue
en   mononucleosis (medical)

monopolio   nom
La posese o controla escluinte de la furni o comersia de un ben o servi; un compania o grupo con esta potia
en   monopoly

»  antimonopolial   ajetivo
en   antitrust

»  monopoli   verbo transitiva
en   monopolize/monopolise, corner the market

monopolo   nom
Un particula ipotesal cual es un magnete con sola un polo
en   monopole (particle)

monorel   nom
Un ferovia con sola un rel, tipal altida, con trenes suspendeda o suportada
en   monorail

monosacarido   nom
Cualce de la clases de zucar, como glucosa, cual no pote es idroliseda per deveni un zucar plu simple
en   monosaccharide, simple sugar

monosicle   nom
Un veculo simil a un bisicle ma con un sola rota
en   unicycle, monocycle

monosido   nom
Un osido con un atom de osijen en sua molecula o formula empirical
en   monoxide

»  monosido de carbono   nom
en   carbon monoxide

monosilaba   nom
Un parola con sola un silaba
en   monosyllable

»  monosilabal   ajetivo
en   monosyllabic

monosite   nom
Un selula blanca de sangue, grande e fagosital, con nucleo oval e sitoplasma clar e grisin
en   monocyte (biology)

monositopoiese   nom
Un prosede cual causa la produi de monosites e ultima macrofagos
en   monocytopoiesis (biology)

monoteisme   nom   (dise ‘monoteïsme’)
La prinsipe o crede ce sola un dio esiste
en   monotheism

»  monoteiste   ajetivo   (dise ‘monoteïste’)
en   monotheistic

»  monoteiste   nom
en   monotheist

monotono   nom
Un sona continuante, spesial de vose, cual no cambia la altia de sua tono
en   monotone

»  monotonia   nom
en   monotony

»  monotonosa   ajetivo
en   monotonous, dull, tedious, boring, stodgy

monson   nom
Un venta saisonal en Asia sude e sude-ueste, ventante de la sude-ueste entre maio e setembre e traente multe pluve, o de la sude-este entre otobre e april e traente aira seca
en   monsoon
fr   mousson

monstro   nom
Un animal imajinada cual es tipal grande, fea e asustante; (metafor) un person multe cruel o mal
en   monster

»  monstro de Gila   nom
Un lezardo venenosa de Mexico e la SUA sude-ueste
Heloderma suspectum
en   Gila monster (lizard)

»  monstro jigante   nom
en   behemoth

»  monstrin   ajetivo
en   monstrous

»  monstrinia   nom
en   monstrosity

monta   verbo transitiva
Senta sur (un animal, bisicle o otra veculo); senta o sta con un gama a cada lado de; (metafor) estende a cada lado de
en   mount, ride, sit on, straddle

»  monta la dorso   verbo
en   piggyback

»  desmonta   verbo transitiva
en   dismount

»  montante   ajetivo
en   riding, straddling, astride; horseback, on horseback

»  remonta   verbo transitiva
en   remount

Montana   nom
Un stato en la SUA norde-sentral, bordante Canada
en   Montana (US state)

montania   nom
Un rejion distinguida par la presentia de montes, tipal difisil per traversa
en   mountains, mountainous area, highlands

»  montanial   ajetivo
Pertinente a la montania
en   mountain, highland

»  montanior   nom
en   mountain dweller, highlander, hillbilly

»  montaniosa   ajetivo
en   mountainous

monte   nom
Un area de tera natural levada a un altia grande
en   mount, mountain

»  a monte   averbo
en   up, uphill, upstream, upward, upwards

Montenegro   nom
Un otra nom per Tsernagora
→ Tsernagora
en   Montenegro

»  montenegrin   ajetivo
en   Montenegrin

»  montenegrin   nom
en   Montenegrin

monton   nom
Un masa ronda cual protende supra un surfas; un masa de cosas poneda sur lunlotra; (nonformal) un cuantia grande de alga cosa
en   heap, pile, mound; (colloquial) bunch, heap, host, load, shedload, ton (large quantity)

»  monton de dejetadas   nom
en   garbage heap, rubbish heap, midden

»  monton de fece   nom
en   dunghill, midden

»  monton de feno   nom
en   haystack

»  monton de formicas   nom
en   anthill

»  monton de neva   nom
en   snowdrift

»  un monton de   nom
en   a lot of, a load of, lots of, loads of

»  un monton de mone   nom
en   a fortune

»  un monton de ricia   nom
en   a fortune

Montserat   nom
Un isola en la Mar Caribe e un teritorio ultramar de Britan
en   Montserrat (island)

»  montseratian   ajetivo
en   Montserratian

»  montseratian   nom
en   Montserratian

montur   nom
Un strutur metal o plastica cual teni la lentes de un oculo; un peso metal en cual un jem es fisada per formi un joala; un anelo metal cual teni la la vitro de un orolojeta o otra strumento
en   mount, frame (lens), setting, bezel

»  monturi   verbo transitiva
en   mount (one thing on another)

monumento   nom
Un sculta, construida o otra strutur erijeda per onora un person o aveni; un ojeto o parte de un vista o vila cual es fasil per vide e reconose; (metafor) un paso o aveni importante en la developa de alga cosa
en   monument, memorial, landmark, sight; milestone

»  monumento de rocas   nom
en   cairn

»  monumental   ajetivo
en   monumental, landmark

mor   ajetivo
No vivente
en   dead, deceased

»  mor   nom
en   dead person, deceased, casualty

»  moreria   nom
en   morgue, mortuary

»  mori   verbo nontransitiva
en   die, perish, pass away

»  mori   verbo transitiva
en   deaden

»  mori   nom
en   death, dying, decease, demise, fatality, casualty, mortality

»  mori de famia   verbo
en   starve

»  mori de famia   nom
en   starvation

»  mori e destrui   nom
en   death and destruction, carnage

»  mori fetal   nom
en   stillbirth

»  moria   nom
en   death (being dead)

»  morida   ajetivo
en   deadened

»  morinte   ajetivo
en   dying, moribund

»  nonmorinte   ajetivo
en   undying

»  pos mori   ajetivo
en   posthumous

»  Mar Mor   nom
Un lago salosa, bordada a este par Urdun e a ueste par Israel e Filastin
en   Dead Sea

mora   nom
Un arboreta en familia de rosa; la baca comable de esta
Rubus
en   blackberry (plant, berry)

moral   ajetivo
Pertinente a la prinsipes de bon e mal condui, e jeneral a la bonia e malia de umanas
en   moral

»  moralia   nom
en   morality, morals

»  moralisme   nom
en   moralism, moralizing/moralising, priggery

»  moraliste   ajetivo
en   moralistic, sanctimonious, self-righteous, priggish, puritanical

»  moraliste   nom
en   moralist, prig, prude

»  nonmoral   ajetivo
en   immoral, unprincipled, unprofessional, unscrupulous

»  nonmoralia   nom
en   immorality, iniquity

»  premoral   ajetivo
en   premoral, innocent

»  prinsipe moral   nom
en   moral principle, moral

»  regula moral   nom
en   moral rule, moral

»  sin moralia   ajetivo
en   amoral

morbilio   nom
Un maladia virusal e comunicable cual causa febre e erutas roja sur la pel, tipal aveninte en enfantia
en   measles

morbosa   ajetivo
Con natur de maladia o indicante maladia; interesada sur temas disturbante e nonplasente, spesial maladia e moria
en   morbid

»  morbosia   nom
en   morbidity

morde   verbo transitiva
Usa la dentes per talia o corti (alga cosa) per feri, mata o come lo
en   bite

»  morde de pulga   nom
en   fleabite

»  morde de serpente   nom
en   snakebite

»  supramorde   nom
en   overbite

moren   nom
Un masa de rocas e deponeda transportada par un glasia, tipal como crestas a sua bordas o fini
en   moraine (geology)

morena   nom
Un pex angilin, xasante e noturna, de mares calda, cual asconde tipal en fesures de cual lo protende sola sua testa
en   moray

morero   nom
Un arbor caduca con folias larga, orijinal de Asia este; la baca roja o purpur de esta
Morus
en   mulberry (tree)

»  morera   nom
en   mulberry (berry)

morfem   nom
Un unia de sinifia en un lingua, cual on no pote divide plu
en   morpheme

morfina   nom
Un paradole e narcotica otenida de opio
en   morphine

morfo-   prefisa
Forma
en   morpho-

morfolojia   nom
(En biolojia) la studia de la formas de organismes e la relatas entre sua strutures; (en linguistica) la studia de la formas de parolas
en   morphology

»  morfolojial   ajetivo
en   morphological

mormon   ajetivo
Pertinente a la Eglesa de Jesus Cristo de Santas de Dias Ultima, un relijio fundida en la SUA en 1830 par Joseph Smith
en   Mormon

»  mormon   nom
en   Mormon

»  mormonisme   nom
en   Mormonism, Latter-day Saints

moro   ajetivo
Pertinente a un popla muslim de Africa norde-ueste, desendente de berberes e arabis, en la eda medieval; pertinente a persones muslim de la Pilipinas
en   Moorish (medieval); Moro, Bangsamoro (Philippine Muslim)

»  moro   nom
en   Moor; Moro

»  Golfo Moro   nom
Un golfo a ueste de Mindanao
en   Moro Gulf

morsa   nom
Un mamal de mar, grande e sosial, relatada a la foca, con du dentones grande e puntida a su, trovada en la Mar Artica
en   walrus

morso   nom
Un cosa, tipal metal, liada a un brida e poneda en la boca de un cavalo per controla el
en   bit (bridle)

mortal   ajetivo
Capas de mori
en   mortal, perishable

»  mortalia   nom
en   mortality

»  nonmortal   ajetivo
en   immortal, imperishable, non-perishable

»  nonmortali   verbo nontransitiva
en   immortalize/immortalise

»  nonmortali   verbo transitiva
en   immortalize/immortalise

»  nonmortalia   nom
en   immortality

mortasa   nom
Un abri, tipal retangulo, cual reseta un protende conveninte
en   mortise (of dovetail joint)

»  mortasi   verbo transitiva
en   mortise

mortero   nom
Un misca de calce con semento, arena e acua, usada per lia brices o petras; un fusil corta con cano lisa, per xuta cartuxes a angulos alta
en   mortar, grout (substance); mortar (gun)

»  morteri   verbo transitiva
en   mortar, grout

morva   nom
Un maladia virusal de canes e otra animales, causante febre, tose e cataro
en   distemper (disease)

mos   nom
Un planta peti sin flores e radises, cresente con forma de tapeto basa o cuxin ronda
Bryophyta
en   moss

»  mosin   ajetivo
en   mosslike

»  mososa   ajetivo
en   mossy

mosaica   ajetivo
Pertinente a imajes o motifes produida par posa pesos peti de petra, telia, vitro, etc
en   mosaic

»  mosaica   nom
en   mosaic

Mosambic   nom
Un pais a la costa este de Africa sude
(capital: Maputo)
en   Mozambique

»  mosambican   ajetivo
en   Mozambican

»  mosambican   nom
en   Mozambican

»  Streta Mosambic   nom
Un streta entre Mosambic e Madagasicara
en   Mozambique Channel

mosarabi   ajetivo
en   Mozarabic

»  mosarabi   nom
en   Mozarab

mosca   nom
Un inseto volante de un ordina grande, con du alas diafana e un boca spesialida per suca
Brachycera
en   fly (insect)

»  mosca de carne   nom
en   blowfly

»  mosca de casa   nom
en   housefly

»  Mosca   nom
Un constela peti en la sielo sude
en   Musca (constellation)

»  mosceta   nom
Un mosca multe peti, tipal videda en manadas prosima a acua
Nematocera
en   midge, gnat

moscete   nom
Un fusil lejera de antecarga, con cano longa e tipal lisa
en   musket (gun)

»  mosceti   verbo transitiva
en   shoot with a musket

»  mosceti   nom
en   musketry

»  moscetor   nom
en   musketeer

moscito   nom
Un familia de moscetas de cual multe spesies morde, suca sangue e transmete baterias
Culicidae
en   mosquito, gnat

moscovio   nom   «Mc»
La elemento cimical con numero atomal 115
en   moscovium (element)

Moscva   nom
La site capital de Rusia
en   Moscow

mostarda   nom
Un planta con flores jala; un pasta jala o brun, preparada de la semes craseda de esta planta, usada como un spise
Brassica hirta, nigra, juncea
en   mustard

mostra   verbo transitiva
Permete o fa ce (alga cosa) es vidable; ofre, esibi, presenta o produi (alga cosa) per oserva o esamina
en   show, exhibit, display, reveal, demonstrate, illustrate

»  mostra   nom
en   exhibition, illustration, audition, demonstration, demo, sample, manifestation

»  mostra e dise   verbo
en   show and tell

»  mostra e dise   nom
en   show and tell

»  mostra emosia   nom
en   show emotion, emote

»  mostra prima   nom
en   premiere, opening, first showing

»  mostra sua autoria   nom
en   assert one’s authority

»  mostra un video   verbo
en   show a video, play a video

»  mostrable   ajetivo
en   demonstrable

»  mostrada   ajetivo
en   shown, revealed, manifest

»  mostral   ajetivo
en   demonstrative

»  mostrante   ajetivo
en   illustrative

»  nonmostrada   ajetivo
en   unshown, unscreened

»  premostra   verbo transitiva
en   presage, augur, portend, foreshadow, forebode, bode

»  remostra   verbo transitiva
en   replay

motasila   nom
Un avia cantante con coda longa cual el secute frecuente
Motacillidae
en   wagtail (bird)

motel   nom
Un otel desiniada per motoristes, tipal un construida longa de un o du niveles con un parce de autos direta a estra
en   motel

motif   nom
Un desinia decorante e tipal repeteda; un melodia o ritmo corta de cual pasajes de musica es plu developada
en   motif, trope, (repeating) pattern

»  motif caxmiri   nom
en   paisley pattern

»  motif de puntos   nom
en   polka dots

»  motif spiral   nom
en   spiral pattern, scrollwork

»  sin motif   nom
en   blank, plain

motiva   verbo transitiva
Stimula la interesa o zelo de (algun) per fa alga cosa, tipal par furni un razona
en   motivate

»  motiva   nom
en   motive, motivation, incentive

»  motiva ascondeda   nom
en   ulterior motive

»  automotiva   verbo nontransitiva
en   motivate oneself

»  automotiva   nom
en   self-motivation

»  automotivada   ajetivo
en   self-motivated, showing initiative

»  desmotiva   verbo transitiva
en   demotivate

»  desmotiva   nom
en   disincentive

»  motivante   ajetivo
en   motivating, motivational

moto-   prefisa
Motorida, propulsada par motor
en   motor-

motor   nom
Un macina cual furni la potia per move un veculo o per opera un otra macina con partes movente
en   motor, engine

»  motor de combusta interna   nom
en   internal combustion engine

»  motor esterna   nom
en   outboard motor

»  motor interna   nom
en   inboard motor

»  motori   verbo transitiva
en   motorize/motorise

»  motorisme   nom
La ativia o pasatempo de dirije un veculo motorida
en   motoring, driving

»  motoriste   nom
en   motorist, driver

move   verbo nontransitiva
Vade en un modo o dirije spesifada; cambia sua loca o posa
en   move, shift, budge

»  move   verbo transitiva
Fa ce alga cosa cambia sua loca o posa
en   move, shift, propel, transfer; shovel (snow, soil, etc.)

»  move   nom
en   movement, move, motion, locomotion; movement (music)

»  move ajitada   verbo
en   fidget

»  move caracolin   verbo
en   move at a snail’s pace, crawl along

»  move furtiva   verbo
en   slink

»  move laborosa   verbo
en   move laboriously, manhandle

»  move sua casa   verbo
en   move house, move

»  contramove   verbo nontransitiva
en   parry, counteract

»  de move   ajetivo
en   locomotory

»  de move lenta   ajetivo
en   slow-motion, in slow motion

»  desmovabli   verbo nontransitiva
en   immobilize/immobilise; demobilize/demobilise

»  desmovabli   verbo transitiva
en   immobilize/immobilise; demobilize/demobilise

»  desmovabli   nom
en   immobilization/immobilisation; demobilization/demobilisation

»  movable   ajetivo
en   mobile

»  movabli   verbo nontransitiva
en   mobilize/mobilise

»  movabli   verbo transitiva
en   mobilize/mobilise

»  movabli   nom
en   mobilization/mobilisation

»  movablia   nom
en   mobility

»  movente   ajetivo
en   moving, mobile, motile

»  nonmovable   ajetivo
en   immovable, immobile

»  nonmovente   ajetivo
en   motionless, unmoving, stationary, sessile, immobile, non-motile

moxa   verbo nontransitiva
Dansa en modo violente par salta e colide con otra dansores, tipal a consertas de roc metal
en   mosh (dance)

»  moxa   nom
en   moshing

»  moxeria   nom
en   mosh pit

Moxe   nom
Un profeta ivri, cisa vivente en la sentenio 14 o 13 aec, ci ia gida la sclavos ivri de Egipte; la scrivor de la Des Comandas de iudisme e cristianisme
en   Moses

mozabita   ajetivo
Pertinente a la popla ci abita en M'zab en la Sahara norde en Jazair, o a sua lingua en la familia berber
en   Mozabite (person, language)

»  mozabita   nom
en   Mozabite (person, language)

mozarela   nom
Un ceso italian, tipal blanca e mol, e fondeda sur otra comedas
en   mozzarella (cheese)

mu   nom   «Μ μ»
La letera 12 de la alfabeta elinica
en   mu (Greek letter)

mua   verbo nontransitiva
Presa sua labios a ante per espresa irita, mal umor o flirta
en   pout, sulk

»  mua   nom
en   pout, moue

mucilajo   nom
Un disolve viscosa, estraeda de plantas e usada en medisines e colas
en   mucilage

muco   nom
Un materia mol e viscosa, secreteda par membranas e glandes per lubrica, proteje, etc; cualce otra materia simil
en   mucus, phlegm; goo, goop, gloop, glop

»  muco acuin   nom
en   rheum

»  muco nasal   nom
en   nasal mucus, snot, bogey, booger

»  mucin   ajetivo
en   gooey, goopy, gloopy

»  mucosa   ajetivo
en   mucous, snotty

muda   ajetivo
Noncapas de parla; (metafor) tan xocada o emosiada ce on no pote parla
en   mute, dumb, speech-impaired; speechless

»  muda   nom
en   mute, speech-impaired person

»  mudi   verbo nontransitiva
en   mute

»  mudi   verbo transitiva
en   mute

»  mudia   nom
en   muteness, mutism, dumbness

muezin   nom
Un om ci sta en la minareta de un mascita e clama muslimes a prea
en   muezzin (caller to prayer)

mufin   nom
Un pan peti, tipal con bacas
en   muffin

»  mufin cavetin   nom
en   popover

»  mufinor   nom
en   muffin seller, muffinman

mufti   nom
Un esperta de lege muslim ci ave la potia de deside sur desacordas relijiosa
en   mufti (Islamic scholar)

mugre   nom
Cualce materia susia e repulsante, como fango o olio, o polvo cumulada
en   filth, grime, sludge, muck, mess

»  mugrosa   ajetivo
en   filthy, squalid, grimy, mucky, messy

mugul   ajetivo
Pertinente a la dinastia muslim de orijina mongol, fundida par la seguores de Timur, cual ia governa multe de Barat entre la sentenios 16 e 19
en   Mughal, Mogul (dynasty)

»  mugul   nom
en   Mughal, Mogul (dynasty)

Muhammad   nom
Un profeta arabi e la fundor de islam, vivente de sirca 570 a 632
en   Muhammad, Mohammed, Muhammed

mujil   nom
Un pex, xef trovada en mares, e un fonte importante de comeda per umanas
Mugilidae
en   mullet (fish)

mul   nom
Un bivalvo con concas brun o oscur purpur
Mytilidae
en   mussel (mollusk/mollusc)

mula   nom
Un muslim saja sur teolojia e leges
en   mullah (Islam)

muladi   nom
Un muslim, tipal con asendentes miscada, de Andalusia en la eda medieval
en   muladi (Islam)

mulato   nom
(Aora insultante) un person con jenitores o asendentes de razas blanca e negra
en   (derogatory) mulatto

muleta   nom
Un baston con un peso orizonal, usada par persones ci no pasea fasil per move sua pesa de la gamas a la corpo alta; (metafor) cualce otra cosa usada per suporta o calmi
en   crutch (support stick)

mulo   nom
Un enfante de asino mas e cavalo fema, normal steril e comun usada per tira aparatos de cultiva; cualce otra animal ibride e steril
en   mule

»  mulin   ajetivo
en   mulish, stubborn

»  mulor   nom
en   muleteer

multa   verbo transitiva
Puni (algun) par fa ce el paia un cuantia de mone, tipal per un ata criminal
en   fine, penalize

»  multa   nom
en   fine, penalty, ticket, forfeit, forfeiture

multe   determinante
Un cuantia grande de
en   many, much, numerous, myriad, a host of, a multitude of

»  multe   averbo
A grado forte
en   very, really, greatly

»  multe   pronom
en   much, many (singular or plural)

»  multes   pronom, plural
en   (people or things, optional plural pronoun)

»  multe min   ajetivo
en   many fewer, much less

»  multe min   averbo
en   much less

»  multe plu   ajetivo
en   many more, much more

»  multe plu   averbo
en   much more

»  es plu multe ca   verbo
en   outnumber

»  multia   nom
en   multitude, host

»  tan multe como posible   espresa
en   as many as possible, as much as possible

multi-   prefisa
Multe o plu ca un
en   multi-

multibandal   ajetivo
Pertinente a la misca de bandas de sona cual ia es rejistrada en modo separada
en   multitrack

multicanalal   ajetivo
Con multe canales de comunica o televisa
en   multichannel

multicolorosa   ajetivo
Con multe colores
en   multicolored/multicoloured, multicolor/multicolour, polychromatic, variegated, motley, mottled, pied, dappled

multicoral   ajetivo
(Un corda eletrical) composada de multe filos; (un computador) conteninte plu ca un prosedador e donce capas de esecuta plu ca un comanda a la mesma tempo
en   multicore

multicultural   ajetivo
Pertinente a plu ca un cultur
en   multicultural

multidimensional   ajetivo
Con plu ca un dimension
en   multidimensional

multidirijal   ajetivo
Con plu ca un dirije
en   multidirectional

multietnical   ajetivo
Pertinente a plu ca un etnico
en   multiethnic

multifasal   ajetivo
Con plu ca un fase
en   multiphase, multiphasic

multifasetal   ajetivo
Con multe fasetas
en   multifaceted

multigradal   ajetivo
Con multe grados o pasos
en   multistage

multiladal   ajetivo
Con multe lados
en   multilateral, many-sided

multilingual   ajetivo
Capas de parla, o presentada en, plu ca du linguas
en   multilingual

»  multilingual   nom
en   polyglot

multilinial   ajetivo
Con plu ca un linia
en   multilinial

multimedial   ajetivo
Presentada en plu ca un media
en   multimedia

»  multimedialia   nom
en   multimedia

multinasional   ajetivo
Incluinte plu ca un pais, o persones de plu ca un pais
en   multinational

»  multinasional   nom
Un compania cual opera en plu ca un pais
en   multinational

multinivelal   ajetivo
Con plu ca un nivel
en   multilevel, multistory/multistorey

multipartital   ajetivo
Con plu ca un partito
en   multiparty, multipartite

multiple   ajetivo
Con plu ca un parte, elemento o membro
en   multiple

»  multiple   averbo
en   multiply

»  multiple   nom
en   multiple (number)

»  multipli   verbo nontransitiva
en   become multiple

»  multipli   verbo transitiva
en   multiply

»  multipli   nom
en   multiplication; product

»  multiplida   nom
en   multiplicand

»  multiplida par   preposada
en   multiplied by, times

»  multiplinte   nom
en   multiplier

multipleso   nom
Un composada complicada con multe elementos
en   multiplex

»  multiplesal   ajetivo
en   multiplex

multipolal   ajetivo
Con multe polos o estremas; (un sosia) polalida en multe dirijes
en   multipolar

multirazal   ajetivo
Pertinente a plu ca un raza
en   multiracial

multiselulal   ajetivo
Composada de plu ca un selula
en   multicellular

multistratal   ajetivo
Con plu ca un strato
en   multilayered

multitaxal   ajetivo
Capas de fa plu ca un taxe a la mesma tempo
en   multitasking

»  multitaxia   nom
en   multitasking

multiterenal   ajetivo
(Un veculo) capas de funsiona en terenos cual no conveni a veculos normal
en   off-road, all-terrain

»  multiterenal   nom
en   off-road vehicle, all-terrain vehicle, sport utility vehicle, SUV, four-wheel drive, four-by-four

multiusal   ajetivo
Usable en multe modos
en   multipurpose, multifunctional, versatile, general-purpose

multiusoral   ajetivo
(Un sistem) capas de es usada par multe persones a la mesma tempo
en   multiuser

multivalente   ajetivo
Con multe aplicas, sinifias o valuas
en   multivalent

multivariante   ajetivo
Con plu ca un cuantia variable
en   multivariate, multivariant

multiverso   nom
Un colie ipotesal de universos posible, incluinte lo cual nos abita
en   multiverse

mundo   nom
La Tera, con tota sua paises, poplas e partes natural; un parte spesifada de esta, como la mundo antica, la mundo de animales, o un mundo de ideas strana; un otra planeta simil a la Tera; la fenomeno de interatas sosial umana
en   world

»  mundo consumiste   nom
en   material world

»  mundo de sonia   nom
en   dream world

»  de la mundo   ajetivo
en   cosmopolitan

»  la plu grande de mundo   ajetivo
en   the world’s largest

»  mundal   ajetivo
en   world, worldly (pertaining to the world)

»  nonmundal   ajetivo
en   unworldly

»  sumundo   nom
en   underworld

muni   verbo transitiva
Furni baletas, cartuxes o bombas a (algun)
en   supply with ammunition

»  muni   nom
en   ammunition, ammo, munition

munisipa   nom
Un site o vila corporada, con governa local
en   municipality

»  munisipal   nom
en   municipal, civic

munster   nom
Un ceso mol de Frans norde-este
en   munster, muenster (cheese)

muon   nom
Un particula suatomal e nonstable en la mesma clase como un eletron, ma con masa plu grande a sirca 200 veses
en   muon (particle)

mur   nom
Un lado vertical de un construida o sala; un strutur vertical e continuante de brices o petras cual ensirca o divide un area de tera; alga cosa usada como un parador per proteje o restrinje
en   wall; bulkhead (ship)

»  mur contra esplodes   nom
en   blast wall

»  muraliste   nom
en   muralist (artist)

»  mureta   nom
Un mur interna e lejera; un surfas vertical sur cual on afisa paperes o scrive
en   partition; board

»  mureta blanca   nom
en   whiteboard

»  mureta de avisas   nom
en   message board, bulletin board, noticeboard

»  mureta negra   nom
en   blackboard, chalkboard

»  muron   nom
en   rampart, defensive wall, city wall; bulkhead, retaining wall

»  muron de mar   nom
en   seawall

»  muron de tera   nom
en   earthwork

Muritania   nom
Un pais en Africa ueste con costa a la Mar Atlantica
(capital: Nuakshut)
en   Mauritania

»  muritani   ajetivo
en   Mauritanian

»  muritani   nom
en   Mauritanian

murmura   verbo nontransitiva
Produi un sona tan cuieta o basa ce lo es cuasi nonoiable
en   murmur, mumble, burble

»  murmura   verbo transitiva
en   murmur, mumble, burble

»  murmura   nom
en   murmur, mumble, burble

mus   nom
Un rodente peti con beco puntida, oreas e oios grande, e coda longa; un aparato peti cual on manipula per interata con un cursor a la scermo de un computador
Mus
en   mouse

»  musin   ajetivo
en   mouselike, mousy

musa   nom
Cualce de nove divas, fias de Zeus e Mnemosine, ci representa la artes e siensas; un person ci inspira un artiste
en   muse

musaca   nom
Un plato elinica de melonjena, tomates e oveta axida a picos, fornida o fritada, con salsa de ceso
en   moussaka (food)

musarania   nom
Un mamal insetivor, peti e musin, con beco longa e puntida e oios peti
Soricidae
en   shrew (animal)

muscada   nom
Un arbor de la isolas de Malucu; un spise preparada de la semes de esta
Myristica
en   nutmeg

muscari   nom
Un planta relatada a jasinto, con flores tipal blu e con forma de vaso
Muscari
en   grape hyacinth (plant)

muscatel   nom
Un varia de uva con odor muscosa; un vino fada de esta
en   muscat, muscatel (grape, wine)

musco   nom
Un mamal peti, solitar e servin de Asia, sin cornos, ma con dentones longa; un materia rojin brun con odor forte, secreteda par la musco mas, e usada en crea parfumes; un materia simil de otra animales
Moschus
en   musk deer; musk

»  muscosa   ajetivo
en   musky

musculo   nom
Un banda o faxo de texeda fibrosa en la corpo de un animal, capas de contrae per move o manteni la posa de partes de corpo
en   muscle

»  musculal   ajetivo
en   muscular

»  musculor   nom
en   muscleman, strongman, he-man

»  musculos   nom, plural
en   muscles, musculature

»  musculosa   ajetivo
Con musculos grande
en   muscular, muscly, brawny, musclebound

»  musculosia   nom
en   muscularity, brawn

musculosceletal   ajetivo
Pertinente a la sistem de musculos e sceleto
en   musculoskeletal

muse   nom
Un comeda lejera, preparada de crema e blanca de ovo bateda; cualce cosa con densia simil, tipal usada per lava o per stili capeles
en   mousse (food)

muselina   nom
Un stofa de coton multe lejera e simple texeda
en   muslin (fabric)

»  de muselina   ajetivo
en   (made of) muslin

museo   nom
Un construida en cual on conserva e esibi ojetos de interesa istorial, siensal, artiste o cultural
en   museum

musica   nom
Sonas de vose o strumentos, combinada en modo bela, armoniosa e emosial espresosa; un pasaje de esta
en   music

»  musica de asendador   nom
en   muzak, elevator music, lift music

»  musica de folclor   nom
en   folk music

»  musica de salon   nom
en   chamber music

»  musica en conserta   nom
en   live music

»  musica pop   nom
en   pop music

»  musica rap   nom
en   rap music

»  musica roc   nom
en   rock music

»  musical   ajetivo
en   musical

»  musiciste   nom
en   musician

»  musiciste suportante   nom
en   supporting musician, sideman

musicolojia   nom
La studia academial de musica
en   musicology

»  musicolojiste   nom
en   musicologist

musli   nom
Un misca de sereal (tipal avena), frutas secida e nozas, tipal comeda con lete a la come de matina
en   muesli, granola

mustang   nom
Un cavalo savaje american, desendente de los domada par colonistes espaniol en la sentenio 16
en   mustang (horse)

mustax   nom
Un banda de capeles cresente supra la labio alta
en   mustache/moustache

mustela   nom
Un mamal carnivor, peti e magra
Mustela
en   weasel

»  mustelin   ajetivo
en   weaselly, weasel-like

muta   verbo nontransitiva
Cambia sua forma o natur; (en biolojia) cambia sua jenes
en   mutate, transform, transmute

»  muta   verbo transitiva
en   mutate, transform, transmute, transfigure, transmogrify

»  muta   nom
en   mutation, transformation, metamorphosis, transmutation, transfiguration

»  muta sua pel   verbo
en   shed one’s skin

»  muta sua pelo   verbo
en   molt/moult

»  muta sua plumas   verbo
en   molt/moult

»  mutable   ajetivo
en   mutable, changeable

»  mutablia   nom
en   mutability

»  mutada   ajetivo
en   mutated

»  mutada   nom
en   mutant

»  mutador   nom
en   transformer

»  mutisme   nom
en   metamorphism (geology)

»  nonmutable   ajetivo
en   immutable

»  nonmutablia   nom
en   immutability

mutajen   ajetivo
Capas de inisia o aselera muta jenetical
en   mutagenic (genetics)

»  mutajen   nom
en   mutagen

mutila   verbo transitiva
Malformi (un person o cosa) par feri o dana
en   mutilate, mangle

»  mutila   nom
en   mutilation

mutua   ajetivo
Esperiada o fada par cada de du o plu persones o grupos a lunlotra
en   mutual, reciprocal

»  mutua   averbo
en   mutually, reciprocally, to each other, to one another

»  mutui   verbo nontransitiva
en   mutualize/mutualise

»  mutui   verbo transitiva
en   mutualize/mutualise

muu   esclama
La sona basa fada par un bove
en   moo (cow)

»  mui   verbo transitiva
en   moo, low

»  mui   nom
en   mooing, lowing

muxu   nom
Un comeda, orijinante en Jonguo norde, de porco trinxada e ovos, fritada en olio, con fungos e otra ingredientes
en   mu shu, moo shu (food)

