= U

u   simbol   (dise ‘u’)
La letera 21 de la alfabeta roman, e sua nom
en   u

u   ajetivo
Pertinente a la dialeto de xines parlada en la provinses Jiangsu e Zhejiang e la site Shanghai
en   Wu (language)

»  u   nom
en   Wu (language)
es   wu (idioma)

u   esclama
Diseda per espresa amira, surprende o mervelia
en   ooh, wow

ua   esclama
La sona de un bebe criante
en   wah (baby crying)

uacari   nom
Un simia con coda corta, pelo longa e ru, e fas roja, blanca o negra sin capeles, trovada en la foresta de la Rio Amazona
Cacajao
en   uakari (monkey)

uadi   nom
Un vale o foson cual es seca estra la saison pluvosa
en   wadi (valley)
es   uadi

uafel   nom
Un torta peti con esterna cracosa, fornida en un padela con surfas con forma de favo, e comeda con bur o xirope
en   waffle (food)
es   gofre

ualabi   nom
Un membro de un spesie de cangaru peti
Macropodidae
en   wallaby

Ualonia   nom
La parte de Beljia sude en cual la popla parla franses o un dialeto de franses
en   Wallonia
es   Valonia

»  ualon   ajetivo
en   Walloon
es   valón

»  ualon   nom
en   Walloon
es   valón

uampum   nom
Perletas, tipal forminte un cadena, usada par alga tribus de americanes orijinal como un media de intercambia o per rejistra avenis
en   wampum (beads)
es   wampum

uapiti   nom
Un servo roja grande de America Norde
Cervus canadensis
en   elk (US), wapiti

uarfarin   nom
Un composada usada per mata ratas e como un medisin per trata trombose
en   warfarin (drug)

uasabi   nom
Un planta nion con radis verde e spesa cual sabori como rabano forte e es usada en cosini, tipal con pexes cru; la salsa preparada de esta radis
Wasabia japonica
en   wasabi (plant, sauce)

uaua   nom
Un efeto musical fada par aplica e sutrae un sordador a un strumento de venta, o par controla la fortador de un strumento eletrical par un pedal
en   wah-wah (music)

uau-uau   esclama
La sona de la abaia de un can
en   woof, bow-wow (dog)

Ucraina   nom
Un pais en Europa este, a norde de la Mar Negra e a sude e ueste de Rusia
(capital: Ciiv)
en   Ukraine

»  ucrainsce   ajetivo
en   Ukrainian (person, language)

»  ucrainsce   nom
en   Ukrainian (person, language)

uculele   nom
Un gitar peti con cuatro cordetas, orijinante en Hawaii
en   ukulele (guitar)

ud   nom
en   oud
es   laúd, ud

ueb   ajetivo
Pertinente a la ipertesto de documentos e otra recursos en la interede
en   web (internet)

»  ueb   nom
en   web (internet)
es   web

uergeld   nom
La valua de alga cosa en la leges de la germanicas antica, spesial la valua de un person, cual debe es paiada a la proprior o a la familia de la vitim como compensa
en   wergeld, weregild (payment system)

ueste   ajetivo
(Un loca o parte de loca) situada en dirije a la punto do la Sol reposa a la ecuinotes; (un person, venta) veninte de esta dirije
en   west, western, occidental

»  ueste   nom
da   vest
de   West
en   west, occident
eo   okcidento
es   oeste, poniente
fr   ouest
it   ovest
nl   westen
pt   oeste, oriente, poente

»  ueste-norde-ueste   ajetivo
en   west-northwest

»  ueste-sentral   ajetivo
en   central west

»  ueste-sude-ueste   ajetivo
en   west-southwest

»  a ueste   averbo
en   westward, westwards

»  a ueste de   preposada
en   to the west of

»  uesti   verbo nontransitiva
en   westernize/westernise

»  uesti   verbo transitiva
en   westernize/westernise

»  uesti   nom
en   westernization/westernisation

Uganda   nom
Un pais sin costa en Africa este
(capital: Kampala)
→ luganda
en   Uganda

»  luganda   ajetivo
→ Uganda
en   Luganda

»  luganda   nom
en   Luganda

»  ugandan   ajetivo
en   Ugandan

»  ugandan   nom
en   Ugandan

ugonote   nom
Un protestante franses de la sentenios 16 e 17, de ci multe ia es persegueda par la catolicas
en   Huguenot

ugrica   ajetivo
Pertinente a la ramo de la familia de linguas uralica cual inclui magiar
en   Ugric (languages)

ui   esclama
Espresante joia, stimula o deleta
en   whee, whoopee

uica   nom
Un relijio cual atenta reconstrui la relijios pagan de Britan antica
en   Wicca (religion)

»  uican   ajetivo
en   Wiccan

»  uican   nom
en   Wiccan

uiguam   nom
Un cabana composada de un strutur oval covreda con erba o bastetas
en   wigwam, wickiup, wetu

uigur   ajetivo   (dise ‘wigur’)
Pertinente a un popla de Jonguo norde-ueste, o a sua lingua turcica
en   Uyghur, Uighur (person, language)

»  uigur   nom
en   Uyghur, Uighur (person, language)

uija   nom   (dise ‘wíja’)
Un tableta con leteras, numeros o otra sinias, sur cual on suposa ce lo comunica respondes de demandas a persones mor
en   ouija board

uin   nom   «Ƿ ƿ»
Un letera anglosason
en   wynn

uipet   nom
Un can de raza peti e magra, elevada per corsa
en   whippet (dog)

uisce   nom
Un bevida alcolosa distilada de gran maltida, tipal orzo o segal
en   whisky, whiskey

uist   nom
Un jua de cartas per du duples de juores, en cual on reseta puntos per la cuantia de prendes
en   whist (card game)

uistiti   nom
Un simia peti de America tropical con pelo sedin e coda longa e prensil
Callithrix
en   marmoset (monkey)

ulex   nom
Un arboreta con flores jala e folias como spinas, nativa de Europa ueste e Africa norde
Ulex
en   gorse, furze (plant)

ulna   nom
La oso la plu magra e longa de la du en la braso basa de umanas, a la lado oposante la diton; la oso corespondente en cuatropedes e avias
en   ulna (anatomy)

ulong   nom
Un te oscur de Jonguo, preparada par fermenta la folias secida a sirca un dui de la grado usual per tes negra
en   oolong (tea)

ulsera   verbo nontransitiva
(Un surfas esterna o interna de la corpo) deveni ferida par un rompe de la pel o membrana mucosa cual no sani
en   ulcerate

»  ulsera   verbo transitiva
en   ulcerate

»  ulsera   nom
en   ulcer, sore, ulceration

»  ulsera de leto   nom
en   bedsore

»  ulsera jelal   nom
en   frostbite

»  ulserada   ajetivo
en   ulcerated, frostbitten

»  ulsereta   nom
en   canker sore, aphthous ulcer

ultima   ajetivo
Esente o aveninte a la fini de un prosede; esente la esemplo la plu bon o la plu estrema
da   sidste
de   letzte
en   ultimate (final or most extreme), last; utmost, prime; eventual
eo   lasta, fina
es   último, final
fr   bout
it   ultimo
nl   laatste
pt   último
ru   окончательный, последний

»  ultima   averbo
ca   finalment
de   zuletzt
en   ultimately, eventually, after all
eo   laste, fine
es   finalmente
fr   enfin
ja   最後に
pt   finalmente

»  anteultima   ajetivo
en   penultimate, second from last, last but one

»  cuasi ultima   ajetivo
en   penultimate, second from last, last but one

»  du ante la ultima   ajetivo
en   antepenultimate, third from last, last but two

ultra   preposada
1   A la lado plu distante de; (un cualia o cuantia) esedente.   (Leje plu…)
‹ la eglesa es ultra la ponte; un taxe ultra mea capasia; viaja ultra la rapidia de sona ›
da   bagefter, længere end
de   weiter
en   beyond, past, across, on the other side of; more than, further than, farther than, exceeding
eo   preter, trans, aliflanke de
es   más allá de, fuera de, allende
fr   au delà de
it   oltre
nl   verder dan, voorbij
pt   além de, mais distante que
ru   за, вне
2   Movente a la lado plu distante de
‹ viaja ultra la montes ›
en   (moving) to beyond, to the other side of, across

»  ultra-   prefisa
Ultra, plu ca, estrema
en   ultra-

»  a ultra   preposada
‹ remi un barceta a ultra la lago ›
en   (moving) to beyond, to the other side of, across

»  a ultra   averbo
en   beyond

ultramar   ajetivo
Pertinente a, o vadente a, un pais stranjer, tipal ultra un mar
en   overseas

ultraortodox   ajetivo
Estrema ortodox
en   ultraorthodox

ultrasona   nom
Sonas o otra vibras con frecuentia multe alta, spesial como usada en ecografia
en   ultrasound

»  ultrasonal   ajetivo
en   ultrasonic

ultravioleta   ajetivo
Con frecuentia plu alta ca lo de la color violeta ma min ca lo de raios X
en   ultraviolet

»  ultravioleta   nom
en   ultraviolet

ulula   verbo transitiva
(Un animal) cria longa e forte, como un can o lupo; (un person) cria longa e forte, indicante dole, teme, coleria o un otra emosia forte
en   howl, wail, yowl

»  ulula   nom
en   howl, wail, yowl

umaian   ajetivo
Pertinente a un dinastia muslim cual ia rena la mundo muslim de 660 a 750 e Espania de 756 a 1031
en   Umayyad, Omayyad (dynasty)

umami   nom
(En comedas) un categoria de sabor (en ajunta a dulse, salosa, asida e amarga) cual coresponde a la sabor de glutamatos
en   umami (flavor/flavour)

Uman   nom
Un pais a la angulo este de la Penisola Arabi
(capital: Mascat)
en   Oman

»  Golfo Uman   nom
Un golfo entre Uman e Iran
en   Gulf of Oman

»  umani   ajetivo
en   Omani

»  umani   nom
en   Omani

umana   ajetivo
Pertinente a persones de la spesie Homo sapiens
en   human

»  umana   nom
en   human, human being, person

»  desumani   verbo nontransitiva
en   dehumanize/dehumanise

»  desumani   verbo transitiva
en   dehumanize/dehumanise

»  desumani   nom
en   dehumanization/dehumanisation

»  nonumana   ajetivo
en   inhuman, non-human

»  supraumana   ajetivo
en   superhuman, Übermensch

»  supraumana   nom
en   superhuman, Übermensch

»  suumana   ajetivo
en   subhuman

»  umanas   nom, plural
en   humans, humanity, mankind, people

»  umani   verbo nontransitiva
en   humanize/humanise, anthropomorphize/anthropomorphise

»  umani   verbo transitiva
en   humanize/humanise, anthropomorphize/anthropomorphise

»  umani   nom
en   humanization/humanisation, anthropomorphism

»  umania   nom
en   humanity (quality)

»  umanin   ajetivo
en   humanlike, humanoid, anthropoid

»  umanisme   nom
en   humanism

»  umaniste   ajetivo
en   humanitarian, humanist

»  umaniste   nom
en   humanitarian, humanist

umbreta   nom
Un avia brun de la pantanes de Africa, relatada a la siconias, con cresta cual pare un protende a retro de la testa
Scopus umbretta
en   hammerkop, hammerhead stork, anvilhead (bird)

Umbria   nom
Un rejion de Italia sentral, istorial e moderna
en   Umbria (Italian region)

»  umbrian   ajetivo
Pertinente a la popla e lingua antica de Umbria
en   Umbrian (person, language)

»  umbrian   nom
en   Umbrian (person, language)

umida   ajetivo
(Aira) con un cuantia alta de vapor de acua; moiada a grado peti
da   våd
de   nass
en   damp, moist, wet; humid (air), clammy, close, muggy, sultry
es   húmedo, mojado
fr   mouillé
it   bagnato, umido
nl   nat
pt   úmido, umidade, molhado

»  desumidador   nom
en   dehumidifier

»  desumidi   verbo nontransitiva
en   dehumidify, desiccate

»  desumidi   verbo transitiva
en   dehumidify, desiccate

»  umidador   nom
ca   humidificador
de   Luftbefeuchter
en   humidifier; humidor (tobacco box)
es   humidificador
fr   humidificateur
ja   加湿器
pt   umidificador
ru   увлажнитель (воздуха)

»  umidi   verbo nontransitiva
en   dampen, moisten, humidify

»  umidi   verbo transitiva
en   dampen, moisten, humidify

»  umidia   nom
en   dampness, moisture, wetness, humidity

umidistato   nom
Un aparato per mesura umidia
en   humidistat

umil   ajetivo
Avente o mostrante un estima basa de sua propre importa; no egosa o ostentosa
da   beskeden, ydmyg
de   demütig
en   humble, modest (humble), meek, mild, unassuming, unpretentious, demure
eo   humila
es   humilde, modesto
fr   humble
it   umile
nl   onderdanig, deemoedig, nederig
pt   humilde, modesto

»  umili   verbo nontransitiva
en   humble

»  umili   verbo transitiva
en   humble

»  umilia   nom
en   humility, modesty

umlaut   nom
Un sinieta scriveda supra un vocal en alga linguas, como deutx, per indica un cualia diferente, comun de fronti; (en linguas germanica) la prosede par cual un vocal retro deveni un vocal fronte en la contesto de un otra vocal fronte
en   umlaut

umo   nom
Un composante organica de tera, formida par la descomposa de folias e otra materia plantal par microbios
en   humus, mulch (soil)

umor   nom
Un state de mente, o un tende a un state de mente; la cualia de es divertinte o comica; (istorial) cada de cuatro licuidas xef de la corpo sur cual on ia crede ce los determina la cualias de persones
en   humor/humour, temper, mood; bodily fluid (historical)

»  bon umor   nom
en   good mood, good spirits

»  bonumorosa   ajetivo
en   in a good mood, cheerful, jovial, light-hearted, gay (dated); sanguine

»  de bon umor   ajetivo
en   in a good mood, cheerful, jovial, light-hearted, sanguine

»  de mal umor   ajetivo
en   in a bad mood, sulking, sulky, sullen, brooding, morose

»  de umor variable   ajetivo
en   moody

»  es malumorosa   verbo
en   be in a bad mood, sulk, brood, mope

»  mal umor   nom
en   bad mood, sulk, snit

»  malumorosa   ajetivo
en   in a bad mood, sulking, sulky, sullen, brooding, moping, morose; cranky, curmudgeonly, surly, petulant

»  malumorosa   nom
en   curmudgeon, grump, sourpuss

»  umoriste   nom
en   humorist

»  umorosa   ajetivo
en   humorous

umus   nom
Un pasta densa de xixes e semes de sesamo moleda, con olio de oliva, limon, e alio
en   hummus (food)

un   determinante
Indicante persones o cosas no ja notada o conoseda, en la cuantia contable la plu basa
ca   un, una
da   en, et
de   ein, eine; eins
en   a, an, one
es   un, una; uno
fr   un, une
it   un, una; uno
ja   一
nl   een
pt   um, uma
ru   один, одна, одно

»  un   ajetivo
nb   The adjective "prima" is usually preferable to the ordinal use of "un".
en   first

»  desuni   verbo nontransitiva
en   disunite

»  desuni   verbo transitiva
en   disunite

»  desuni   nom
en   disunion

»  reuni   verbo nontransitiva   (dise ‘reüni’)
en   reunite, reunify, regroup, congregate, convoke, convene, meet

»  reuni   verbo transitiva
en   reunite, reunify, regroup, congregate, convoke, convene, meet

»  reuni   nom
en   reunion, reunification, meeting, assembly, convocation, convention, session

»  uni   verbo nontransitiva
Deveni un intera; (person o organizas) alia con lunlotra per un intende o ata comun
da   forene
de   vereinigen
en   unite, unify
eo   unuiĝi
es   unir
fr   unir
it   unire
nl   verenigen
pt   unir

»  uni   verbo transitiva
en   unite, unify

»  uni   nom
en   union (action), unification; union (result), coalition, consortium

»  Uni de Republicas Sosialistes Soviet   nom
en   Union of Soviet Socialist Republics

»  Uni European   nom
en   European Union

»  Uni Soviet   nom
en   Soviet Union

»  unia   nom
en   oneness, solidarity, integrity, unity

»  unida   ajetivo
en   united, unified

»  unida   averbo
en   together

»  unidiste   ajetivo
en   unionist

»  unidiste   nom
en   unionist

Ungaria   nom
Un otra nom per Magiar
→ Magiar
en   Hungary

»  ungarian   ajetivo
en   Hungarian

»  ungarian   nom
en   Hungarian

Ungava, Baia   nom
Un baia a norde de Quebec e a sude de la Streta Hudson
en   Ungava Bay

ungia   nom
Un covrente cornin sur la surfas superior de la fini de la dito o orteo de umanas e otra animales
ca   ungla
da   negl
de   Nagel
en   nail
es   uña
fr   ongle
it   unghia
ja   爪
nl   nagel
pt   unha
ru   ноготь

»  ungia de dito   nom
en   fingernail

»  ungia de pede   nom
en   toenail

ungula   nom
La parte cornin de la pede de alga animales, spesial un cavalo
en   hoof

ungulato   nom
Un ordina de mamales con ungulas, aora divideda entre Artiodactyla e Perissodactyla
Ungulata
en   ungulate

uni-   prefisa
Un, singular, solitar
en   uni- (one)

unia   nom
Un cosa o person individua e completa cual pote es ance un composante de un cosa plu grande o plu complicada; un cuantia de mesura elejeda como un model per espresa otra cuantias
en   unit (of a larger whole, of measurement); monad

»  unia comersial   nom
en   commercial unit (of goods)

»  unia de mone   nom
en   unit of currency

»  unial   ajetivo
en   unitary

unica   ajetivo
Esente la sola esemplo de sua spesie o tipo; simil a no otra cosa o person
en   unique, sole, single, one-off, exclusive, idiosyncratic, inimitable

»  unica   nom
en   exclusive (news story)

unicorno   nom
Un organisme mital cavalin con corno a sua fronte, e a veses con barba de capra e coda de leon
en   unicorn

»  Unicorno   nom
en   Monoceros (constellation)

unidimensional   ajetivo
Avente o pertinente a un sola dimension; (un rol) sin profondia
en   one-dimensional

uniforma   ajetivo
Con la mesma forma o aspeta en tota casos e tempos
en   uniform, unitary, regular

»  uniforma   nom
Un colie de vestes identica portada par membros de la mesma profesa, organiza o scola
da   uniform
de   Uniform
en   uniform (dress), livery
es   uniforme
fr   uniforme
it   uniforme
nl   uniform
pt   uniforme

»  uniformi   verbo nontransitiva
en   become uniform

»  uniformi   verbo transitiva
en   make uniform; dress in uniform

»  uniformia   nom
en   uniformity

»  uniforminte   ajetivo
en   uniforming, procrustean

uniladal   ajetivo
Pertinente o afetante sola un lado de alga cosa; (un ata o deside) fada par o afetante sola un person, grupo o nasion en un situa spesifada, sin acorda de otras
en   unilateral; unrequited

uniselulal   ajetivo
Composada de sola un selula
en   unicellular

unisesal   ajetivo
(Vestes) desiniada per conveni a ambos sesos
en   unisex

unitarian   ajetivo
Pertinente a un seta cristian cual rejeta la idea de la trinia e prefere tipal developa credes par razona
en   Unitarian

»  unitarian   nom
en   Unitarian

»  unitarianisme   nom
en   Unitarianism (Christianity)

univalente   ajetivo
(Un cromosoma) restante estra la duples en meiose
en   univalent (biology)

universia   nom
Un institui de instrui avansada, tipal per adultes e culminante con un diploma
da   universitet
de   Universität
en   university, college, varsity
eo   universitato
es   universidad, tecnológico, politécnico
fr   université
it   università
nl   universiteit
pt   universidade

»  universia de diploma   nom
en   alma mater

universo   nom
La intera de la materia, enerjia e spasio cual esiste, regardada como un unia
da   univers, kosmos
de   Weltall, Universum
en   universe, cosmos
eo   universo, kosmo
es   universo, cosmos
fr   univers
it   universo
nl   heelal, universum
pt   universo

»  universal   ajetivo
en   universal; cosmic

»  universalisme   nom
en   universalism (philosophy, Christianity)

»  universaliste   ajetivo
en   universalist

»  universaliste   nom
en   universalist

unje   verbo transitiva
Marca con olio, tipal como parte de un rituo relijiosa
en   anoint

»  unje   nom
en   anointing, unction

»  unjente   nom
en   unguent, ointment, pomade, lotion

unsial   ajetivo
(Un scrive medieval) con leteras rondida de cual la leteras minor moderna es derivada
en   uncial (lettering)

uoc   nom
Un padela formida como un bol, usada en cosini xines
en   wok (pan)

uolfram   nom   «W (wolfram)»
La elemento cimical con numero atomal 74
en   tungsten, wolfram (element)

uolof   ajetivo
Pertinente a un popla de Senegal e Gambia, o a sua lingua
en   Wolof (person, language)

»  uolof   nom
en   Wolof (person, language)

uombata   nom
Un marsupio australian, erbivor e tunelinte cual sembla un urso peti con gamas corta
Vombatidae
en   wombat

uon   nom
La unia de mone en Corea Sude
en   won (currency)

uonton   nom
Un bal o enrola de pasta con pleninte saborosa, tipal de carne de porco e comeda pos boli en sopa
en   wonton (food)

upanixad   nom
Cada de un serie de testos santa induiste, scriveda en sanscrito
en   upanishad (scripture)

uple   nom
(En matematica) un lista ordinada de un cuantia spesifada de elementos; (en informatica) un strutur de datos con partes diversa, per esemplo la colie de campos cual composa un arcivo en un banco de datos
en   tuple (mathematics); record, struct (software)

upsilon   nom   «Υυ»
La letera 20 de la alfabeta elinica
en   upsilon (Greek letter)

ura   esclama   (dise ‘urá’)
Espresante joia o aproba
en   hooray, hurrah, whoopee

Ural, Montes   nom, plural
Un serie de montes en Rusia cual estende tra sirca 1600 km de la Mar Artica a la Mar Aral, e cual formi la frontera tradisional entre Europa e Asia
en   Ural Mountains

uralica   ajetivo
Pertinente a la familia de linguas parlada de Scandinavia norde a Sibir este, incluinte suomi, magiar e enets
en   Uralic (languages)

uranio   nom   «U»
La elemento cimical con numero atomal 92, un metal radioativa usada en reatadores nucleal
en   uranium

Urano   nom   «♅»
(En mitos elinica) la plu antica de la dios, un personi de la sielo e la renor prima de la universo; la planeta sete de la Sol
en   Uranus (mythology, planet)

urato   nom
Un sal o ester de asida urica
en   urate (chemistry)

»  urato de sodio   nom
en   sodium urate, chalkstone

urbe   nom
Un area multe poplada e plenida par construidas, per esemplo un site o vila, ma no sempre political definida
→ site
en   urban area, city area, metropolis

»  anteurbe   nom
en   outskirts, approaches

»  urban   ajetivo
en   urban, metropolitan

»  urban   nom
en   city dweller, urbanite

»  urbani   verbo nontransitiva
en   urbanize/urbanise, citify

»  urbani   verbo transitiva
en   urbanize/urbanise, citify

»  urbani   nom
en   urbanization/urbanisation

»  urbanisme   nom
en   city planning

»  urbaniste   nom
en   city planner

urbolojia   nom
La studia de la problemes de sites
en   urbanology

»  urbolojiste   nom
en   urbanologist

urdu   ajetivo
Pertinente a la dialeto de industani scriveda en la scrive farsi, con multe parolas derivada de farsi e arabi
en   Urdu (language)

»  urdu   nom
en   Urdu (language)

Urdun   nom
Un pais sin costa en Asia ueste, a este de Israel
(capital: Aman)
en   Jordan

»  urduni   ajetivo
en   Jordanian

»  urduni   nom
en   Jordanian

urea   nom
Un cimical cristal sin color, la produida nitrojenosa major de la metaboli de protena en mamales, escreteda en urina
en   urea (substance)

uremia   nom
Un cuantia plu ca normal de urea e otra cimicales nitrojenosa en la sangue, cual es normal eliminada par la renes
en   uremia/uraemia (medical)

uretan   nom
Un composada cristal sintesal, usada per produi pestisides e fungisides, e como un anestesente en la pasada
en   urethane (substance)

ureter   nom
La duto tra cual urina move de la ren a la vesica
en   ureter (anatomy)

uretra   nom
La duto tra cual urina es escreteda de la vesica e cual, en vertebratos mas, escrete ance semin
en   urethra (anatomy)

uria   nom
Un avia de mar con peto negra e beco magra e puntida, cual nidi tipal sur falesas
Uria
en   guillemot, murre (bird)

»  urieta   nom
Un avia peti de la Mar Pasifica norde, relatada a la uria
Synthliboramphus, Brachyramphus
en   murrelet (bird)

urina   nom
Un licuida acuin, tipal jala, retenida en la vesica e descargada tra la uretra
da   urin
de   Harn, Urin
en   urine
eo   urino
es   orina
fr   urine
it   urina, orina
nl   urine
pt   urina

»  urinal   ajetivo
en   urinary

»  urini   verbo transitiva
en   urinate, micturate

»  urini   nom
en   urination, micturation

urinalise   verbo transitiva
Analise la urina de (algun) per deteta maladias, drogas, etc
en   urinalyse

»  urinalise   nom
en   urinalysis

urje   verbo transitiva
Atenta forte o repeteda convinse (algun) ce el debe fa alga cosa
en   urge, exhort

»  urje   nom
en   urge, exhortation

»  urjente   ajetivo
en   urgent, pressing

»  urjente   nom
en   emergency

uro   nom
Un bove savaje grande de Eurasia, aora estinguida, cual ia es la asendente de boves domada
Bos primigenius
en   aurochs (ox)

urolito   nom
Un calculo en la vesica de un can, gato o otra animal
en   urolith, bladder stone

urolojia   nom
La ramo de medica cual studia e trata maladias de la sistem urinal
en   urology

»  urolojiste   nom
en   urologist

urso   nom
Un mamal grande e pesosa cual pote pasea sur la plantas de sua pedes, con pelo densa e coda multe corta
Ursidae
da   bjørn
de   Bär
en   bear
eo   urso
es   oso
fr   ours
it   orso
nl   beer
pt   urso
ru   медведь

»  urso blanca   nom
en   polar bear

»  urso-de-acua   nom
Tardigrada
en   water bear

»  urso de pelux   nom
en   teddy bear, teddy

»  Urso Grande   nom
en   Ursa Major (constellation)

»  urso gris   nom
en   grizzly bear

»  urso labiosa   nom
Melursus ursinus
en   sloth bear

»  Urso Peti   nom
en   Ursa Minor (constellation)

»  urseta   nom
en   bear cub

»  ursin   ajetivo
en   bearlike, ursine

URSS   corti
Uni de Republicas Sosialiste Soviet
en   USSR

urticaria   nom
Un eruta de bultetas ronda e sever prurinte sur la pel, con infla perilosa en alga casos, causada par un reata alerjica tipal a un comeda
en   urticaria, hives (rash)

Uruguai   nom
Un pais a la costa de la Mar Atlantica de America Sude, a sude de Brasil
(capital: Montevideo)
en   Uruguay

»  uruguaia   ajetivo
en   Uruguayan

»  uruguaia   nom
en   Uruguayan

usa   verbo transitiva
Prende, teni, aplica o ativi (alga cosa) per ateni un resulta intendeda; porta (un veste o simil) sur sua corpo
ca   usar, emprar
da   bruge, udnytte
de   gebrauchen, benutzen
en   use, utilize/utilise; apply, employ (force, tool, method); wear (clothes)
eo   uzi, utiligi
es   usar, utilizar, emplear, hacer uso de, servirse de, aprovechar
fr   employer, utiliser
it   usare, utilizzare
ja   使う
nl   gebruiken
pt   usar, utilizar
ru   использовать

»  usa   nom
en   use, employment, purpose, application; uptake

»  usa tro multe   verbo
en   overuse

»  comensa usa   verbo
en   start using, take up

»  de usa sever   ajetivo
en   heavy-duty

»  desusa   verbo transitiva
en   disuse, no longer use

»  desusa   nom
en   obsolescence

»  desusada   ajetivo
en   disused, obsolete, archaic, defunct

»  malusa   verbo transitiva
en   misuse, abuse

»  malusa de drogas   nom
en   drug abuse

»  nonusa   nom
en   disuse, desuetude

»  nonusable   ajetivo
en   unusable, useless

»  nonusada   ajetivo
en   unused, out of use

»  nonusosa   ajetivo
en   useless, idle, feckless

»  reusa   verbo transitiva
en   reuse

»  reusable   ajetivo
en   reusable

»  tro usada   ajetivo
en   overused, hackneyed, clichéd

»  usable   ajetivo
en   usable

»  usada   ajetivo
en   used, secondhand

»  usor   nom
en   user

»  usor de rede   nom
en   internet user, netizen

»  usosa   ajetivo
en   useful, utilitarian, purposeful

»  usosia   nom
en   usefulness, utility

usual   ajetivo
Fada o aveninte en modo abitual o tipal
en   usual, customary

»  usual   averbo
en   usually, customarily

»  nonusual   ajetivo
en   unusual, odd, different, unconventional, uncharacteristic, uncustomary

»  nonusual   averbo
en   unusually

usufruta   nom
La direto de usa la propria de un otra person, sin destrui o peri lo
en   usufruct (right)

usura   nom
La ata nonlegal de presta mone a taso de interesa nonjusta alta
en   usury

»  usuror   nom
en   usurer, loanshark

»  usurosa   ajetivo
en   usurous

usurpa   verbo transitiva
Saisi un posto de autoria par fortia o modo nonlegal
en   usurp

»  usurpor   nom
en   usurper

Utah   nom   (dise ‘yuta’)
Un stato en la SUA sude-ueste
en   Utah (US state)

utero   nom
La organo en la adomen de un fem o mamal fema do la feto es consepida e crese ante nase
en   uterus, womb

utia   nom
Un rodente con gamas e coda corta, trovada sola en la paises de la Mar Caribe
Capromyidae
en   hutia (rodent)

util   nom
Un cosa usada per ateni un resulta spesifada, tipal tenida en la mano o manos
da   redskab, værktøj
de   Werkzeug
en   tool, utensil, implement
eo   ilo
es   herramienta, utensilio, implemento, instrumento, apero, enser
fr   outil
it   utensile, strumento
nl   werktuig
pt   ferramenta, instrumento, utensílio, implemento

»  util de cosini   nom
en   cooking implement, kitchen utensil

»  util de scrive   nom
en   writing implement

»  furni utiles nova a   verbo
en   retool

»  utiles de arjento   nom, plural
en   silverware

»  utiles de come   nom, plural
en   cutlery, flatware, eating utensils

utilitarisme   nom
La filosofia ce atas es bon o coreta si los benefica la majoria de persones
en   utilitarianism

»  utilitariste   ajetivo
en   utilitarian

»  utilitariste   nom
en   utilitarian

utopia   nom
Un loca imajinada do tota es perfeta
en   utopia

»  utopial   ajetivo
en   utopian

»  utopisme   nom
en   utopianism

»  utopiste   nom
en   utopian

utriculo   nom
La plu grande de la du sacos de fluente cual es un parte de la labirinto de la orea interna
en   utricle

u-u   esclama
Un sona basa como lo fada par buos e pijones
en   coo (pigeon); twit-twoo, hoo, hoot (owl)

Uvea e Futuna   nom
Un teritorio de Frans, composada de du grupos de isolas a ueste de Samoa en la Mar Pasifica sentral
en   Wallis and Futuna

»  futuna   ajetivo
en   Futunan

»  futuna   nom
en   Futunan

»  uvea   ajetivo
en   Wallisian

»  uvea   nom
en   Wallisian

uvo   nom
Un planta cual produi uvas
Vitis
en   grape vine

»  uva   nom
Un baca, tipal verde, purpur, roja o negra, cresente en drupas de vites, comeda como un fruta o usada per fabrica vino
da   drue
de   Weintraube
en   grape
eo   vinbero
es   uva
fr   raisin
it   uva
nl   druif
pt   uva

»  uva seca   nom
en   raisin, currant

uvula   nom
Un protende de carne a retro de la velo, pendente supra la garga
en   uvula

»  uvulal   ajetivo
en   uvular

»  uvulal   nom
en   uvular (consonant)

Uzbecistan   nom
Un pais sin costa en Asia sentral a sude e sude-ueste de la Mar Aral
(capital: Taxcent)
en   Uzbekistan

»  uzbec   ajetivo
en   Uzbek, Uzbekistani (person, language)

»  uzbec   nom
en   Uzbek, Uzbekistani (person, language)

uzo   nom
Un distilada saborida con anis, orijinante en Elas
en   ouzo (drink)
