= E

e   simbol   (dise ‘e’)
La letera sinco de la alfabeta roman, e sua nom; la nota tre de la scala diatonica de C major
en   e
es   e

e   conjunta
Ance, en ajunta (juntante du espresas o frases cual es membros egal de un lista o grupo)
en   and
es   y, e

»  e ... e   espresa
‹ e esta e acel ›
en   both ... and

»  e/o   conjunta
en   and/or

e-   prefisa
en   e- (electronic)

ebano   nom
Un lenio negra o brun oscur; la arbor tropical cual produi esta
Ebenaceae
en   ebony
es   ébano

ebefrenia   nom
Un varia cronica de scizofrenia, marcada par rie e condui enfantin
en   hebephrenia (medical)
es   hebefrenia, esquizofrenia desorganizada

»  ebefrenica   ajetivo
en   hebephrenic
es   heefrénica

ebonita   nom
Cauxo vulcanida, cual deveni dur e negra
en   ebonite (rubber)
es   ebonita (caucho)

ec   corti
De la eda comun
en   CE, AD, anno domini
es   EC, d.C.

ecdisozon   nom
Un clado o suprafilo de animales cual inclui artropodos, nematodos e otras cual perde sua esosceleto
Ecdysozoa
en   ecdysozoon (pl. ecdysozoa) (organism)

ecg   corti
Eletrocardiograf
en   ECG, EKG

ecidna   nom
Un mamal spinosa e insetivor de Australia e Gine Nova, con beco e garas longa, cual produi ovos e come formicas
Tachyglossidae
en   echidna, spiny anteater

ecimose   nom
Un malcolori causada par la cumula de sangue su la pel, tipal de un contusa
en   ecchymosis (medical)

ecinodermato   nom
Un filo de nonvertebratos incluinte stelas-de-mar, erisos-de-mar e concombres-de-mar
Echinodermata
en   echinoderm (organism)

ecipo   nom
Un grupo de persones ci labora con lunlotra; un grupo de juores ci formi un lado en un jua o sporte; un grupo peti de soldatos con un taxe comun
da   team, hold, gruppe
de   Mannschaft, Team
en   crew, team, squad, cadre
eo   ekipo
es   equipo, partido, grupo, tripulación, cuadrilla, escuadrón
fr   équipe
it   squadra
nl   ploeg, groep, team
pt   equipe, time, esquadrão

»  ecipo prima   nom
en   first team, varsity

»  ecipi   verbo transitiva
en   crew, staff

»  ecipor   nom
en   crew member, team member

eclampsia   nom
Un maladia en cual convulsas aveni en un fem ensinta ci sufri de presa sangual alta, comun segueda par coma, e cual menasa la sania de la madre e la bebe
en   eclampsia (medical)

»  preeclampsia   nom
en   pre-eclampsia (medical)

ecler   nom
Un pasta dulse, peti e mol, plenida con crema
en   éclair (cake)

ecletica   ajetivo
Derivante ideas o stilo de fontes diversa e vasta; (en filosofia) pertinente a un grupo de filosofistes antica ci ia eleje ideas de fontes diversa en loca de segue un scola
en   eclectic, catholic

»  ecleticisme   nom
en   eclecticism

eclis   nom
Un oscuri de la lus de un ojeto sielal par la pasa de un otra entre lo e la oservor, o entre lo e sua fonte de lumina
en   eclipse

»  eclis anelo   nom
en   annular eclipse

»  eclisal   ajetivo
en   ecliptic

»  eclisal   nom
en   ecliptic

»  eclisi   verbo nontransitiva
en   eclipse

»  eclisi   verbo transitiva
en   eclipse

eco   nom
Un sona, o serie de sonas, causada par la refleta de ondas de sona de un surfas a la escutor; un refleta simil de un raio de ondas, como de radio o radar
en   echo

»  ecosa   ajetivo
en   echoic

»  fa un eco   verbo
en   echo

eco-   prefisa
Pertinente a ecolojia
en   eco-

ecograf   nom
Un aparato cual analise sona refletada e produi un representa grafica, tipal usada en medica, per esemplo per oserva la crese de un embrio
en   echograph, sonograph, ultrasonograph

»  ecografi   verbo transitiva
en   echograph, sonograph, ultrasonograph

»  ecografia   nom
en   echography, sonography, ultrasonography

ecogram   nom
Un imaje o graf produida par un ecograf
en   echogram, sonogram, ultrasonogram

ecolalia   nom
Un maladia de mente en cual on repete automata lo cual otras dise
en   echolalia (medical)

ecoloca   verbo transitiva
Descovre la loca de (un cosa) par deteta sonas refletada, como fada par delfines, ciroteros, etc
en   echolocate

»  ecoloca   nom
en   echolocation

ecolojia   nom
La ramo de biolojia cual studia la relatas entre organismes e entre los e sua ambiente fisical
da   økologi
de   Ökologie
en   ecology
es   ecología
it   ecologia

»  ecolojial   ajetivo
en   ecological

»  ecolojial sana   ajetivo
en   environmentally friendly, eco-friendly

»  ecolojiste   nom
en   ecologist

econometria   nom
La ramo de economia cual aplica metodos statistical a la studia empirical de teorias e relatas economial
de   Ökonometrie
en   econometrics
es   econometría
fr   économétrie

economia   nom
La ricia e recursos de un nasion o rejion, spesial notante la produi e consuma de benes e servis; la siensa e studia de esta
en   economy; economics
es   economía

»  economia de mercato   nom
Un sistem de economia cual depende de la interata de demanda e ofre
en   market economy

»  economia libraliste   nom
en   liberal economy, laissez-faire economy

»  economia matematical   nom
en   mathematical economy

»  economial   ajetivo
en   economic

»  economiste   nom
en   economist

ecoside   verbo transitiva
Destrui la ecolojia de (un loca), tipal con intende
en   commit ecocide, destroy the environment

»  ecoside   nom
en   ecocide

ecosistem   nom
Un comunia biolojial de organismes interatante e sua ambiente fisical
en   ecosystem

ecotono   nom
Un zona de cambia entre du comunias biolojial
en   ecotone (biology)

ectare   nom
Un unia metral per mesura area, egal a 100 ares
en   hectare (unit of area)

ecto-   prefisa
(Un mesura) multiplida par 100
en   hecto- (hundred)

ectoderma   nom
La strato de selulas la plu esterna, spesial en embrios temprana
en   ectoderm (anatomy)

ectopia   nom
Un loca o posa nonormal de un organo
en   ectopia (medical)

»  ectopica   ajetivo
en   ectopic

ectoplasma   nom
La strato esterna, clar e la plu viscosa de sitoplasma en selulas amebin
en   ectoplasm

Ecuador   nom
Un pais en America Sude norde-ueste, con costa a la Mar Pasifica
(capital: Quito)
en   Ecuador

»  ecuadoran   ajetivo
en   Ecuadoran

»  ecuadoran   nom
en   Ecuadoran

ecuator   nom
Un linia imajinada sirca la Tera, a distantia egal de ambos polos, cual divide la Tera entre la emisferas norde e sude; un linia simil sur un otra ojeto sielal
en   equator
eo   ekvatoro

»  ecuatoral   ajetivo
en   equatorial
eo   ekvatora

ecui-   prefisa
Egal
en   equi-

ecuidistante   ajetivo
(Du o plu locas) a distantias egal de un otra
en   equidistant

ecuiladal   ajetivo
(Un triangulo) con la mesma longia a cada lado
en   equilateral

ecuilibra   verbo nontransitiva
(Un person o cosa) ave un distribui egal de pesa cual permete ce lo resta stable; (un state) conteni elementos diversa en proportios egal o coreta
en   balance, poise

»  ecuilibra   verbo transitiva
en   balance, poise

»  ecuilibra   nom
en   balance, equilibrium, kilter

»  ecuilibra idrostatical   nom
en   hydrostatic balance, hydrostatic equilibrium

»  desecuilibra   verbo nontransitiva
en   imbalance, unbalance, throw off balance, tip over, topple, knock over, overbalance

»  desecuilibra   verbo transitiva
en   imbalance, unbalance, throw off balance, tip over, topple, knock over, overbalance

»  nonecuilibra   nom
en   imbalance

ecuinote   nom
La tempo o data (a du veses en cada anio, sirca 22 setembre e 20 marto) cuando la Sol traversa la ecuator de sielo, cuando la dia e la note es de longia egal
en   equinox

»  ecuinote de autono   nom
en   autumnal equinox

»  ecuinote de primavera   nom
en   vernal equinox

ecuisito   nom
Un planta sin flores, con tronceta vacua e sesionida, cual porta spirales de folias magra e produi sporas en conos a la estremas de la rametas
Equisetum
en   horsetail (plant)

ecumenisme   nom
La promove de unia entre la ramos de cristiania en la mundo
en   ecumenism

»  ecumeniste   ajetivo
en   ecumenical

eczema   nom
Un maladia en cual pesos de pel deveni ru e inflamada, con bulas cual causa pruri e sangui
en   eczema (medical)

ed   nom   «Ð ð»
Un letera anglosason e islansce, representante un fricante dental
en   eth, edh (letter)

eda   nom
La cuantia de tempo tra cual un person o organisme ia vive o un cosa ia esiste; un periodo spesifada de istoria; (en jeolojia) un divide major de tempo, min ca un epoca
en   age (measure of years); age, era

»  eda comun   nom
en   common era

»  eda de bronze   nom
en   bronze age

»  eda de fero   nom
en   iron age

»  eda de petra   nom
en   stone age

»  eda glasial   nom
en   ice age

»  eda grande   nom
en   longevity

»  eda matur   nom
en   old age

»  eda media   nom
en   middle age

»  eda oro   nom
en   golden age, heyday, halcyon days

»  eda scolal   nom
en   school age

»  ante la eda comun   ajetivo
en   before the common era (BCE), before Christ (BC)

»  de la eda comun   ajetivo
en   common era (CE), anno domini (AD)

»  edisme   nom
en   agism/ageism

»  ediste   ajetivo
en   agist/ageist

edema   nom
Un maladia marcada par la colie de tro multe licuida acuin en la cavetas o texedas de corpo
en   edema/oedema (medical)

Eden   nom
(En alga relijios) la loca do la umanas prima ia abita; (metafor) un loca o state de felisia grande, como un paradiso
en   Eden

eder   nom
Un pato de mares norde
Somateria
en   eider, eider duck

edera   nom
Un planta trepante e perene, tipal con folias verde oscur con sinco puntos
Hedera
en   ivy

ederdon   nom
La plumas peti e suave de la peto de un eder fema, usada per pleni covreletos
en   eiderdown

Edipo   nom
Un re elinica mital ci ia reali nonintendente un predise ce el va mata sua padre e sposi sua madre
en   Oedipus

»  edipal   ajetivo
en   Oedipal

edita   verbo transitiva
Prepara (scrivedas) per publici, par coreti, condensa o organiza los; eleje elementos per (un filma o simil) e organiza los a un unia coerente; cambia (un testo) a un computador
en   edit

»  edita   nom
en   editing; edit, edition

»  coedita   verbo transitiva
en   coedit

»  coeditor   nom
en   coeditor

»  editador   nom
en   (software) editor, editing program

»  editador de fasimil   nom
en   WYSIWYG editor

»  editor   nom
en   editor

editorial   nom
Un article en un jornal, espresante la opina de la editor sur un tema corente
en   editorial

edonisme   nom
La xasa de plaser
en   hedonism, sybaritism

»  edoniste   ajetivo
en   hedonistic

»  edoniste   nom
en   hedonist, sybarite

educa   verbo transitiva
Instrui (un person) en modos inteletal e sosial, tipal a un scola o universia
en   educate, school, edify

»  educa   nom
en   education, edification

»  educa ajuntada   nom
en   further education

»  educa coletiva   nom
en   mass education

»  educa de liseo   nom
en   secondary education

»  educa de universia   nom
en   higher education, tertiary education

»  educa prima   nom
en   primary education

»  coeduca   verbo transitiva
en   coeducate

»  coeduca   nom
en   coeducation

»  educable   ajetivo
en   educable

»  educada   ajetivo
en   educated, schooled, learned

»  educal   ajetivo
en   educational

»  educor   nom
en   educator

»  noneducada   ajetivo
en   uneducated, unschooled, uncultured, ignorant, unskilled, menial

»  reeduca   verbo transitiva
en   re-educate

Edward, Lago   nom
Un lago a la frontera entre Uganda e la Republica Democrata de Congo
en   Lake Edward

efedra   nom
Un arboreta perene de zonas calda e seca, con troncetas trepante e folias pico e scamin
Ephedra
en   ephedra (plant)

efedrina   nom
Un medisin otenida de alga efedras, usada per constrinje la tubos sangual e abri la broncos
en   ephedrine (drug)

efemera   ajetivo
Esistente o usada per un periodo multe corta
en   ephemeral

»  efemera   nom
Un inseto magra, con alas diafana e du o tre filetas longa a la coda, notada per sua vive multe corta
Ephemeroptera
en   mayfly

»  efemeras   nom, plural
en   ephemera

efeto   nom
Un cambia cual resulta de un ata o otra causa; un usa de sona o lumina per forti la ilude de un teatral o filma
en   effect; consequence, impact, footprint

»  efeto de Doppler   nom
Un cambia en frecuentia de sona, lus o otra ondas cuando la fonte e la oservor move a via de lunlotra
en   Doppler effect

»  efeto de moda   nom
en   bandwagon effect

»  efeto invernerial   nom
en   greenhouse effect

»  efeto spesial   nom
en   special effect

»  en efeto   averbo
en   in effect, effectively

»  posefeto   nom
en   aftereffect

efrata   verbo transitiva
Entra a (un construida) nonlegal con intende crimin, spesial de fura
en   burglarize/burgle

»  efrata   nom
en   burglary

»  efrator   nom
en   burglar

egal   ajetivo
Con la mesma cuantia, grandia, grado o valua; (un max) en cual la ecipos fini con un cuantia egal de puntos
en   equal, equivalent, tantamount; tied, drawn

»  egal   nom
en   tie, draw (match result); deuce (tennis); toss-up

»  atenta egali   verbo
en   try to catch up, play catch-up

»  egalador   nom
en   equalizer/equaliser (filter)

»  egali   verbo nontransitiva
en   equalize/equalise, become equal, catch up

»  egali   verbo transitiva
en   equalize/equalise, make equal

»  egali   verbo transitiva
en   match, rival, equate to, catch up with

»  egali   nom
en   equation

»  egali diferensial   nom
en   differential equation

»  egalia   nom
en   equality, parity, equivalence

»  egalinte   ajetivo
en   equalizing/equalising

»  egalinte   nom
en   equalizer/equaliser

»  egalisme   nom
en   egalitarianism

»  egaliste   ajetivo
en   egalitarian

»  nonegal   ajetivo
en   unequal, non-equivalent

»  nonegalia   nom
en   inequality, disparity, discrepancy

»  sin egal   ajetivo
en   without equal, unequaled/unequalled, unrivaled/unrivalled, unmatched, matchless, peerless, nonpareil, incomparable

Egipte   nom
Un otra nom per Misre
→ Misre
en   Egypt

»  Egipte antica   nom
en   Ancient Egypt

»  egiptian   ajetivo
en   Egyptian

»  egiptian   nom
en   Egyptian

egiptolojia   nom
La studia de la lingua, istoria e sivilia de Egipte antica
en   Egyptology

»  egiptolojiste   nom
en   Egyptologist

eglefin   nom
Un pex arjentin gris de la Mar Atlantica norde, relatada a la gado
Melanogrammus aeglefinus
en   haddock

eglesa   nom
Un construida usada par cristianes per adora publica; un organiza cristian spesifada; relijio organizada, regardada como un forsa political o sosial
en   church (building, organization/organisation)

»  eglesal   ajetivo
en   ecclesiastic

»  egleseta   nom
en   chapel

»  eglesor   nom
en   member of the clergy, clergyman, clergywoman, cleric, parson, pastor, minister, chaplain

»  eglesor alta   nom
en   prelate

»  eglesor fema   nom
en   clergywoman

»  eglesor mas   nom
en   clergyman

»  eglesores   nom, plural
en   clergy

ego   nom
La senti de respeta o importa cual un person ave en relata a se; (en psicoanalise) la parte de la mente cual razona e deside; (en filosofia) un sujeto consensa e pensante
en   ego, self

»  egoisme   nom   (dise ‘egoïsme’)
en   selfishness

»  egoiste   ajetivo   (dise ‘egoïste’)
en   selfish, egotistical

»  egoiste   nom
en   egoist

»  egosa   ajetivo
en   egotistical, arrogant, insolent, haughty, conceited, vainglorious, overweening, puffed-up, overbearing, pretentious, affected, ostentatious, full of oneself, conceited, stuck-up, bold, brash, high-handed, snippy, snotty, supercilious, uppity

»  egosia   nom
en   egotism, arrogance, insolence, conceit

»  nonegosa   ajetivo
en   unselfish

»  otra ego   nom
en   alter ego

»  sin ego   ajetivo
en   selfless

»  supraego   nom
en   superego (psychology)

egomania   nom
Un egosia osesente
en   egomania

»  egomanica   ajetivo
en   egomaniac, egomaniacal

egosentral   ajetivo
Pensante sola a se, sin regarda la emosias o desiras de otras; focada a o veninte de la perspetiva de un person
en   egocentric

egreta   nom
Un tipo de eron, tipal con plumas blanca
Egretta
en   egret (bird)

ejacula   verbo transitiva
Ejeta (semin) de la corpo a la momento de culmina sesal
en   ejaculate

»  ejacula   nom
en   ejaculation

ejemonia   nom
Gida o domina, spesial par un stato o grupo sosial
en   hegemony

Ejeo   nom
La rejion de la Mar Ejeo e la paises bordante
en   Aegean (region)

»  Mar Ejeo   nom
Un parte de la Mar Mediteraneo entre Elas e Turcia
en   Aegean Sea

»  ejean   ajetivo
De o pertinente a la rejion de la Mar Ejeo e sua costas e isolas
en   Aegean

ejeta   verbo transitiva
Forsa o lansa (un cosa) a estra, tipal en modo subita o forte
en   eject

»  ejeta   nom
en   ejection, ouster

»  ejetada   ajetivo
en   ejective

»  ejetada   nom
en   ejective (consonant)

ejitalido   nom
Un avia peti e pasarin de Eurasia, con color blanda e coda relativa longa
Aegithalidae
en   bushtit, long-tailed tit (bird)

el   pronom
Representante un person, un animal personin, o un cosa personin como un robot
en   he, she; him, her; it (animal or personified thing)

»  el ci   espresa
‹ el ci osa gania ›
en   he who, she who, the one who

»  elisme   nom
La abitua de refere a se par sua nom o como `el`
en   illeism (referring to oneself in the third person)

ela   pronom
Representante un person o animal fema
nb   On usa normal "el", egal per un fema o un mas. "Ela" es multe rara, ma on pote usa lo per claria e stilo si, per esemplo, on nara un conversa entre un fem ("ela") e un om ("elo").
en   she, her

Elam   nom
Un stato antica en Iran sude-ueste, fundida en la milenio 4 aec
en   Elam (ancient civilization/civilisation)

»  elaman   ajetivo
en   Elamite

»  elaman   nom
en   Elamite

Elas   nom
Un pais en Europa sude-este con costas a la Mar Ejeo, la Mar Ionica e la Mar Mediteraneo
(capital: Atina)
→ elinica
en   Greece

»  elinica   ajetivo
→ Elas
en   Greek, Grecian, Hellenic

»  elinica   nom
en   Greek, Hellene

»  elinici   verbo nontransitiva
(Istorial) (un otra popla) segue la cultur elinica antica
en   hellenize/hellenise

»  elinici   verbo transitiva
en   hellenize/hellenise

»  elinici   nom
ca   hel·lenització
de   Hellenisierung
en   hellenization/hellenisation
es   helenización
it   ellenizzazione
pt   helenização

elastan   nom
Un stofa elastica de poliuretan, tipal usada per calsas, vestetas e otra vestes abrasante
en   elastane, lycra, spandex

»  de elastan   ajetivo
en   (made of) elastane, lycra, spandex

elastica   ajetivo
(Un ojeto o materia) capas de reveni spontan a sua forma normal pos contrae, dilata o contorse
en   elastic, stretchy, stretch

»  elastica   nom
en   elastic

»  elasticia   nom
en   elasticity

»  nonelastica   ajetivo
en   inelastic

»  nonelasticia   nom
en   inelasticity

elefante   nom
Un mamal grande, pesosa e erbivor, con trompa prensil e dentones longa de ivor, nativa de Africa e Asia sude
Elephantidae
en   elephant
eo   elefanto

»  elefante-de-mar   nom
Un foca grande, cual reprodui a la costa ueste de America Norde e la isolas sirca Antartica, de cual la mas es multe plu grande ca la fema e ave un colo spesa e un beco inflable cual sembla la trompa de un elefante
Mirounga
en   elephant seal, sea elephant
eo   marelefanto

»  elefantin   ajetivo
en   elephantine
eo   elefanteca

elefantiase   nom
Un maladia en cual un membro o otra parte de corpo deveni multe grande par causa de la impedi de la dutos limfal, tipal par un nematodo parasital
en   elephantiasis

elefen   ajetivo
Pertinente a lingua franca nova
en   Elefen, Lingua Franca Nova

»  elefen   nom
en   Elefen, Lingua Franca Nova

»  elefeni   verbo nontransitiva
en   Elefenize/Elefenise, translate into Elefen

»  elefeni   verbo transitiva
en   Elefenize/Elefenise, translate into Elefen

»  elefeniste   nom
en   Elefenist, Elefen speaker, Elefen advocate

eleje   verbo transitiva
Deside ci o cual de du o plu alternativas es la plu bon o la plu conveninte
en   choose, select, pick, elect, opt

»  eleje   nom
en   choice, election, selection

»  eleje partisipa   verbo
en   opt in

»  eleje natural   nom
en   natural selection

»  eleje no partisipa   verbo
en   opt out

»  eleje par comite   verbo
en   co-opt

»  deseleje   verbo transitiva
en   deselect

»  elejable   ajetivo
en   electable, eligible, alternative, optional, discretionary

»  elejable   nom
en   option, alternative, choice

»  elejablia   nom
en   elegibility, electability

»  elejal   ajetivo
en   electoral, elective

»  elejedas   nom, plural
en   chosen ones, elect

»  elejente   ajetivo
en   discriminating, choosy

»  elejor   nom
en   elector

»  nonelejable   ajetivo
en   unelectable, ineligible

»  preelejal   ajetivo
Aveninte en la tempo ante un eleje
en   pre-election

»  preeleje   verbo transitiva
en   preselect

»  proelejal   ajetivo
en   pro-choice

»  reeleje   verbo transitiva
en   re-elect

elejia   nom
Un poesia de refleta seria, tipal un lamenta pos un mori; un poesia elinica o latina, scriveda en duples elejial
en   elegy

»  elejial   ajetivo
en   elegiac

elemento   nom
Un parte o aspeta fundal de alga cosa, spesial si esensal o tipal; cada de plu ca 100 materias cimical cual no pote es simplida e cual es la partes fundal de tota materias
en   element (basic part, including chemical); factor

eletrica   nom
Un forma de enerjia cual resulta de la presentia de particulas cargada, como un cumula statical de carga o como un corente dinamical
en   electricity

»  eletrical   ajetivo
en   electrical, electric

»  eletrici   verbo transitiva
en   electrify

»  eletrici   nom
en   electrification

»  eletricida   ajetivo
en   electrified, electric

»  eletricinte   ajetivo
en   electrifying

»  eletriciste   nom
en   electrician

eletrocardiograf   nom
Un aparato per mesura e rejistra la ativia eletrical en la cor
en   electrocardiograph, ECG scanner, EKG scanner

»  eletrocardiografia   nom
en   electrocardiography

eletrocardiogram   nom
Un rejistra creada par un eletrocardiograf
en   electrocardiogram, ECG scan, EKG scan

eletrocuta   verbo transitiva
Feri o mata (algun) par xoca eletrical
en   electrocute

»  eletrocuta   nom
en   electrocution

eletrodinamica   nom
La ramo de mecanica cual studia la interata de corentes eletrical con campos magnetal o con otra corentes eletrical
en   electrodynamics

»  eletrodinamical   ajetivo
en   electrodynamic

eletrodo   nom
Un condutador tra cual eletrica entra a o sorti de un ojeto, materia o area
en   electrode

eletroensefalograf   nom
Un aparato per rejistra la ativia eletrical de la serebro
en   electroencephalograph

»  eletroensefalografia   nom
en   electroencephalography

eletroensefalogram   nom
Un rejistra creada par un eletroensefalograf
en   electroencephalogram

eletrofisiolojia   nom
La ramo de fisiolojia cual studia la fenomenos eletrical asosiada con la funsiona de la nervos e corpo
en   electrophysiology

eletroforese   nom
La move de particulas cargada en un licuida o jelatin su influe de un campo eletrica
en   electrophoresis

eletrolise   verbo transitiva
Envia un corente eletrical tra (un licuida o disolve) cual conteni iones
en   electrolyze/electrolyse

»  eletrolise   nom
en   electrolysis

»  eletrolisal   ajetivo
en   electrolytic

eletrolito   nom
Un licuida o jelatin cual conteni iones e cual pote es descomposada par eletrolise
en   electrolyte

eletromagnete   nom
Un cor de metal mol, convertida a un magnete par la pasa de un corente eletrical tra un enrolada cual ensirca lo
en   electromagnet

»  eletromagnetal   ajetivo
en   electromagnetic

»  eletromagnetia   nom
en   electromagnetism

eletromecanica   nom
La siensa de aparatos macinal cual usa eletrica
en   electromechanics

»  eletromecanical   ajetivo
en   electromechanical

eletromotiva   ajetivo
Produinte un corente eletrical
en   electromotive

eletron   nom
Un particula suatomal e stable, con carga eletrical negativa, trovada en tota atomes e funsionante como la portante xef de eletrica en solidas
en   electron

eletronegativa   ajetivo
Eletrical negativa; (un elemento) tendente gania eletrones e formi iones negativa
en   electronegative

eletronica   nom
La ramo de fisica e tecnolojia cual pertine a la desinia de sircuitos con transistores e microtelias, e a la condui e move de eletrones en condutadores, semicondutadores, gases o un vacua
en   electronics (science)

»  eletronical   ajetivo
en   electronic

»  eletronicales   nom, plural
en   electronics (components)

eletroplaca   verbo transitiva
Placa (un cosa metal) par eletrolise
en   electroplate

»  eletroplaca   nom
en   electroplating

eletropositiva   ajetivo
Eletrical positiva; (un elemento) tendente perde eletrones e formi iones positiva
en   electropositive

eletrosirurjia   nom
Sirurjia cual usa un corente eletrical de frecuentia alta per caldi e talia texedas con multe esatia
en   electrosurgery

eletrostatica   nom
La studia de cargas o campos eletrical statical, contrastada con corentes eletrical
en   electrostatics

»  eletrostatical   ajetivo
en   electrostatic

eleva   verbo transitiva
Cura (un enfante) asta cuando el es matur; cura animales, spesial sua reprodui
en   bring up, raise, rear, nurture; breed (raise animals)

»  eleva   nom
en   upbringing, nurture; breeding, husbandry

»  eleva de abeas   nom
en   apiculture, beekeeping

»  eleva de animales   nom
en   raising animals, breeding animals, animal husbandry

»  eleva de enfantes   nom
en   parenting, raising children

»  eleva endogama   verbo transitiva
en   inbreed

»  eleveria   nom
en   farm, stud (breeding animals)

»  elevor   nom
en   breeder (animals)

elfo   nom
Un organisme mital con forma umana, comun peti, con oreas puntida e potias majiosa
en   elf, pixie, pixy, sprite, hobgoblin

»  elfin   ajetivo
en   elfin, elfish, pixieish

elianto   nom
Un planta alta de America Norde en familia de margarita, con flores jala grande
Helianthus annuus
en   sunflower (plant, bloom)

elica   ajetivo
Con forma enrolada o spiral; (un ase) portante du o plu lamas larga e angulida, como en un ventador
en   helical, helicoid

»  elica   nom
en   helix; propeller

»  elicador   nom
en   auger

»  elicador de Arcimede   nom
en   Archimedes’ screw

»  eliceta   nom
en   twiddly bit (curly decorative feature)

elicotor   nom
Un tipo de volador cual usa du o plu rotores per asende e propulsa se
en   helicopter

»  elicotor de ataca   nom
en   helicopter gunship

elidi   verbo transitiva
Omete (un sona o silaba) cuando on parla
en   elide

»  elidi   nom
en   elision

elimina   verbo transitiva
Sutrae o esclui completa
en   eliminate, annihilate, obliterate, eradicate, exterminate, extirpate, purge, expunge; knock out (from contest)

»  elimina   nom
en   elimination, annihilation, obliteration, eradication, extermination, extirpation, purge

elinisme   nom
La cultur de Elas antica entre la mori de Alexandro la Grande e la batalia de Action, o a la studia o imita de esta
en   Hellenism

»  eliniste   ajetivo
en   Hellenistic

»  eliniste   nom
en   Hellenist

elio   nom   «He (helium)»
La elemento cimical con numero atomal 2, un gas inerte
en   helium

eliofilia   nom
Un atrae a lus de sol
en   heliophilia (biology)

»  eliofilica   ajetivo
en   heliophilic

»  eliofilica   nom
en   heliophile

eliosentral   ajetivo
Con la Sol como sua sentro, como en la model moderna de la sistem solal; (en astronomia) mesurada de o regardada en relata a la sentro de la Sol
en   heliocentric

eliotropo   ajetivo
Un purpur pal
en   heliotrope (color/colour)

»  eliotropo   nom
Un planta en familia de boraja, cultivada per sua flores blu o purpur cual es usada en parfum
en   heliotrope (plant)

eliporto   nom
Un airoporto per elicotores
en   heliport

elise   ajetivo
Con forma de un sirculo platida, la resulta de talia un cono par un plano inclinada cual no crusa la funda
en   elliptic, elliptical

»  elise   nom
en   ellipse

elisoide   ajetivo
en   ellipsoid, ellipsoidal

»  elisoide   nom
Un forma tridimensional simetre a tre ases perpendicular, de cual sua talia traversal a un ase es un sirculo e tota otra talias es elises
en   ellipsoid

elisurfas   nom
Un atereria per elicotores
en   helipad

elite   ajetivo
Avente la autoria, favore, state o prestijia la plu grande en un sosia o asosia
en   elite

»  elitisme   nom
en   elitism

»  elitiste   ajetivo
en   elitist

elizabetan   ajetivo
Pertinente a la periodo de Rea Elizabeth 1 de England e Er (1558-1603)
en   Elizabethan

elminto   nom
Un verme parasital de clases diversa
Platielminto
en   helminth, parasitic worm

»  antielmintal   nom
Un medisin per elimina elmintos
en   anthelmintic, antihelminthic, vermifuge, vermicide, wormer, dewormer, drench (medicine)

»  deselminti   verbo transitiva
en   deworm, worm, drench

»  elmintose   nom
en   helminthiasis, helmintosis, worms

elmo   nom
Un xapo dur, portada par soldatos, polisiores, sportores, etc per proteje sua testa
en   helmet, hard hat

»  elmin   ajetivo
en   helmetlike, helmet-shaped

elo   pronom
Representante un person o animal mas
nb   On usa normal "el", egal per un mas o un fema. "Elo" es multe rara, ma on pote usa lo per claria e stilo si, per esemplo, on nara un conversa entre un om ("elo") e un fem ("ela").
en   he, him

em   esclama
Espresante esita
en   um, uh, er, erm (hesitation)

ematemese   nom
La vomiti de sangue
en   hematemesis/haematemesis (medical)

ematita   nom
Un mineral negra rojin, composada de osido ferica
en   hematite/haematite (mineral)

emato-   prefisa
Sangue
en   hemato-/haemato- (blood)

ematolojia   nom
La studia de la fisiolojia de sangue
en   hematology/haematology

ematoma   nom
Un infla solida de sangue coagulada en la texedas; dana cual apare como un area de pel malcolorida, causada par la rompe de dutos sangual
en   hematoma/haematoma, bruising

»  ematoma periorbital   nom
en   periorbital hematoma/haematoma, black eye

ematopoiese   nom
La produi de selulas de sangue e trombosites, cual aveni en la medulas de la osos
en   hematopoiesis/haematopoiesis, hemopoiesis/haemopoiesis (biology)

»  ematopoiesal   ajetivo
en   hematopoietic/haematopoietic, hemopoietic/haemopoietic

ematozon   nom
Un parasito cual vive en sangue
en   hematozoon/haematozoon (pl. hematozoa/haematozoa) (organism)

ematuria   nom
La presentia de sangue en urina
en   hematuria/haematuria (medical)

embarasa   verbo transitiva
Fa ce (algun) senti torpe, autoconsensa o vergoniosa
en   embarrass, mortify

»  embarasa   nom
en   embarrassment, chagrin

»  embarasada   ajetivo
en   embarrassed, sheepish

»  embarasante   ajetivo
en   embarrassing

embarca   verbo transitiva
Entra a (un veculo); comensa (un taxe o discute, tipal importante o difisil)
en   embark, board, go aboard, entrain; undertake, address oneself to (task); broach, bring up (topic)

»  desembarca   verbo transitiva
en   disembark, deplane

embargo   nom
Un proibi ofisial, tipal contra comersia con un nasion spesifada
en   embargo

emberiza   nom
Un avia cantante de la mundo vea en familia de pinson, ci come semes e ave plumas con bandas brun e un testa forte marcada
Emberiza, etc
en   bunting (bird)

embolo   nom
Un trombo, bola de aira o simil cual bloci un arteria
en   embolus (medical)

»  embolia   nom
Un bloci de un arteria par un embolo
en   embolism

embosce   verbo transitiva
Espeta ascondeda e ataca surprendente
en   ambush, waylay

»  embosce   nom
en   ambush

»  embosceda   ajetivo
en   ambushed, waylaid

embraje   nom
Un aparato per lia e deslia un motor e un engranador
en   clutch (mechanism)

»  desembraji   verbo transitiva
en   declutch

»  embraji   verbo transitiva
en   apply the clutch (to)

embrio   nom
Un enfante developante de cualce spesie, ante sua nase o emerji de ovo; un bebe umana ante sua nase, spesial en la oto semanas prima pos consepi, ante cuando tota organos developa; (en botanica) la parte de un seme cual va deveni un planta
en   embryo

»  embrial   ajetivo
en   embryonic, embryonal

embriolojia   nom
La ramo de biolojia e medica cual studia embrios e sua developa
en   embryology

»  embriolojial   ajetivo
en   embryological

»  embriolojiste   nom
en   embryologist

embuto   nom
Un tubo cual es larga a supra e magra a su, usada per gida licuidas o polvos tra un abri peti; cualce strutur o caveta con forma embutin
en   funnel (for pouring); infundibulum

»  embuti   verbo transitiva
en   funnel

»  embutin   ajetivo
en   funnel-like

Emelia   nom
Un rejion istorial de Italia norde, aora un parte de Emelia-Romagna
en   Emilia (Italian region)

»  emelian   ajetivo
en   Emilian

»  emelian   nom
en   Emilian

emeri   nom
Un spesie grisin negra de corindon conteninte osido de fero, tipal usada en forma moleda como un sustantia raspante
en   emery

emerji   verbo nontransitiva
Deveni vidable par move a estra o a via de alga cosa; (un animal) sorti de un ovo, cocon o crisalida; (metafor) deveni evidente, importante o conoseda
en   emerge, emanate, issue; surface; loom up; hatch

»  emerji   verbo nontransitiva
en   cause to emerge; bring to the surface; hatch

»  emerji   nom
en   emergence, emanation

»  emerjinte   ajetivo
en   emerging, emergent

»  nova emerjinte   ajetivo
en   newly emergent, up-and-coming

»  reemerji   verbo transitiva
en   re-emerge

emete   verbo transitiva
Produi e descarga (alga cosa, spesial gas o radioativia)
en   emit, effuse, give off

»  emete   nom
en   emission, emanation

»  emetador   nom
en   emitter; exhaust (system)

emfisema   nom
Un maladia en cual la alveolos de la pulmones es danada e grandida, causante respira difisil
en   emphysema (medical)

emi-   prefisa
Dui
→ semi-, dui-
en   hemi-

emiplejia   ajetivo
Un paralise de un lado de la corpo
en   hemiplegia

»  emiplejica   ajetivo
en   hemiplegic

emisfera   nom
Un dui de un sfera; un dui de la Tera, tipal o la parte norde e la parte sude como divideda par la ecuator, o la parte este o la parte ueste divideda par cualce linia entre la polos (per esemplo la mundos vea e nova); cada de la du partes, destra e sinistra, de la serebro
en   hemisphere

emo   corti
En mea opina
en   IMO, IMHO

emo-   prefisa
Sangue
en   hemo-/haemo- (blood)

emofilia   nom
Un state en cual la sangue no coagula bon, tal ce la sufror sangui grave an pos un feri minor
en   hemophilia/haemophilia

»  emofilica   ajetivo
en   hemophiliac/haemophiliac

»  emofilica   nom
en   hemophiliac/haemophiliac

emoglobina   nom
Un protena roja cual transporta osijen en la sangue de vertebratos
en   hemoglobin/haemoglobin

emoji   nom
Un imaje dijital e peti, usada per espresa un idea o emosia en comunica eletronical
ca   emoji
en   emoji
es   emoji
fr   emoji
it   emoji

emolitica   ajetivo
Pertinente a la rompe o destrui de selulas roja de sangue
en   hemolytic/haemolytic

emopatolojia   nom
La studia e trata de la selulas ematopoiesal
en   hemopathology/haemopathology

»  emopatolojial   ajetivo
en   hemopathological/haemopathological

emoraje   verbo transitiva
Un perde de sangue de un duto sangual rompeda, spesial cuando grave
en   hemorrhage/haemorrhage

»  emoraje   nom
en   hemorrhage/haemorrhage

»  emorajal   ajetivo
en   hemorrhagic/haemorrhagic

emoroide   nom
Un vena o grupo de venas inflada en la area anal
en   hemorrhoid/haemorrhoid

emosia   verbo transitiva
Afeta la sentis de (algun) par felisi, tristi, coleri, asusta, etc
en   affect, move (emotionally)

»  emosia   nom
en   emotion, sentiment, emotiveness, emotivity

»  emosial   ajetivo
en   emotional

»  emosiante   ajetivo
en   moving, emotive

»  emosiosa   ajetivo
en   sentimental, emotional, labile

»  emosiosia   nom
en   sentimentality

»  nonemosiada   ajetivo
en   unmoved

»  nonemosiosa   ajetivo
en   unemotional, unfeeling, cold

emosicon   nom
Un representa de un espresa de fas, tapeda como un serie spesial de sinias, usada per espresa emosias en comunica eletronical
en   emoticon

emosite   nom
Un selula de sangue
en   hemocyte/haemocyte, blood cell

emositoblasto   nom
Un de la selulas de sangue cual produi plu selulas de sangue, tipal en la medulas de la osos
en   hemocytoblast/haemocytoblast

emostase   nom
La sesa de un flue de sangue
en   hemostasis/haemostasis (medical)

»  emostasal   ajetivo
en   hemostatic/haemostatic

emostasiolojia   nom
en   hemostasiology/haemostasiology

emotoxina   nom
Un toxina cual afeta la sangue
en   hemotoxin/haemotoxin

empapa   verbo transitiva
Pone (un cosa) en un licuida cual lo va asorbe partal; (metafor) ensenia un dogma a (algun)
en   soak, drench, waterlog, macerate; indoctrinate

»  empapa   nom
en   soaking, drenching, maceration; indoctrination

»  empapada   ajetivo
en   soaked, drenched, sodden, soggy

empatia   verbo transitiva
Comprende e comparti la emosias de (un otra person)
en   empathize/empathise with

»  empatia   nom
en   empathy

»  empatica   ajetivo
en   empathic, empathetic

»  nonempatica   ajetivo
en   non-empathic, hard-hearted

empanada   nom
Un comeda de pasta plenida con carne, ceso, mais, etc, e fritada, comun en Espania e paises en Sude America
en   empanada
es   empanada

»  empanadeta   nom
en   empanadilla
es   empanadilla

empirical   ajetivo
Fundida sur esperias e oservas sertable, en loca de sola teoria o lojica
en   empirical, objective

»  empiricalia   nom
en   objectivity

»  empiricalisme   nom
en   empiricism

»  empiricaliste   nom
en   empiricist

emplea   verbo transitiva
Furni labora a (algun) e paia a el per lo
en   employ (person), hire

»  emplea   nom
en   employment, job

»  emplea a stranjer   verbo
en   outsource

»  emplea a stranjer   nom
en   outsourcing

»  emplea con salario   nom
en   salaried employment

»  autoempleada   ajetivo
en   self-employed

»  con tro multe empleadas   ajetivo
en   overstaffed

»  con tro poca empleadas   ajetivo
en   understaffed

»  desemplea   verbo transitiva
en   dismiss, fire, sack, lay off (employee)

»  desemplea   nom
en   dismissal, sacking, layoff

»  empleable   ajetivo
en   employable

»  empleablia   nom
en   employability

»  empleada   ajetivo
en   employed

»  empleada   nom
en   employee, hireling, staffer

»  empleada tempora   nom
en   temporary employee, temp

»  empleadas   nom, plural
en   employees, staff, personnel

»  empleor   nom
en   employer, boss

»  nonemplea   nom
en   unemployment

»  nonempleada   ajetivo
en   unemployed, jobless

emporta   verbo transitiva
(Un nasion) trae (un ben o servi) de un otra nasion per vende interna; introdui (un idea) de un loca o contesto diferente; (en informatica) usa (datos) produida par un otra program
en   import

»  emporta   nom
en   importation

»  emporta nonlegal   verbo
en   import illegally, bootleg

»  emportor   nom
en   importer

emprende   verbo transitiva
Dedica se a (un taxe o encarga) e comensa lo
en   undertake, take on, take over

»  emprende   nom
en   undertaking, venture, enterprise (project)

»  emprendor   nom
en   entrepreneur

empresta   verbo transitiva
Prende e usa (un cosa cual parteni a un otra person) con intende de redona lo a pos; prende e usa (mone) de un person o banco, con acorda ce on va repaia lo
en   borrow

»  emprestor   nom
en   borrower

emu   nom
Un avia grande de Australia, capas de core rapida ma no de vola, simil a un astruzo
Dromaius novaehollandiae
en   emu (bird)

emulsion   nom
Un sperde de gotas pico de un licuida en un otra en cual lo no es disolvable o miscable
en   emulsion

»  emulsioni   verbo nontransitiva
en   emulsify

»  emulsioni   verbo transitiva
en   emulsify

en   preposada
1   A interna de; esente (o parente es) encluida o ensircada par.   (Leje plu…)
‹ mea cor es en mea peto; ideas en la mente; nos es en peril; nos es en acorda; vive en felisia; los senta en un sirculo ›
en   in (a place or condition), inside, within
eo   en
2   Entrante a
‹ el ia cade en la rio ›
en   (moving) into
eo   en -n
3   Pos la comensa e ante la fini de (un aveni o situa)
‹ en la note; en febrero; en 1770; el ia scrive la libro en sola tre semanas; el ia spende du anios en scrive la prefas ›
→ cuando
en   in, during (a period of time)
eo   dum
4   Espresada o fada par usa (un lingua, media o modo)
‹ un jornal en franses; parla en modo aidosa ›
en   in (a language, medium or manner)
eo   en, per

»  a en   preposada
en   into

»  a en   averbo
en   within, inside, herein

»  de en   preposada
en   from within, coming out of

»  de en   averbo
en   from within

en   nom
La unia de mone en Nion
en   yen (currency)
eo   eno

en-   prefisa
En, a en
en   en-, in-

enaira   verbo nontransitiva
Comensa vola
en   take off, lift off, blast off

»  enaira   nom
en   take-off, lift-off, blast-off

enama   verbo transitiva
(Un person) fa ce (algun) comensa ama el
en   enamor/enamour, cause to fall in love, infatuate

»  enama   nom
en   infatuation

»  desenama   verbo transitiva
en   disenamor/disenamour, cause to fall out of love

»  desenamada   ajetivo
en   disenamored/disenamoured

»  deveni desenamada par   verbo
en   fall out of love with

»  deveni enamada par   verbo
en   fall in love with

»  enamada   ajetivo
en   enamored/enamoured, infatuated, in love, moonstruck, smitten

»  es desenamada par   verbo
en   be disenamored/disenamoured with

»  es enamada par   verbo
en   be enamored/enamoured with

encalia   verbo nontransitiva
(Un barco, viajor o animal) deveni trapida a un plaia sin modo de sorti
en   wash up, run aground, become beached, become stranded, become marooned

»  encalia   verbo transitiva
en   beach, strand, maroon

encanta   verbo transitiva
Deleta forte (algun); influe o controla (algun) par deleta el
en   enchant, bewitch, beguile, cast a spell, captivate, charm, enrapture, ravish, jinx, transfix

»  encanta   nom
en   spell, incantation, enchantment, charm, jinx, juju

»  desencanta   verbo transitiva
en   disenchant

»  desencanta   nom
en   disenchantment

»  encantada   ajetivo
en   enchanted, bewitched, spellbound

»  encantada   esclama
en   pleased to meet you

»  encantante   ajetivo
en   charming, engaging; gorgeous, breathtaking, ravishing

»  encantor   nom
en   charmer, enchanter, enchantress

encarga   verbo transitiva
Demanda o comanda ce (algun) emprende un rol o taxe per cual el va es culpable si el fali
‹ encarga algun a/con solve la problem ›
en   commission, order, entrust, charge, deputize/deputise

»  encarga   nom
en   commission, order, responsibility, onus

»  coencargada   ajetivo
en   collegial, with shared responsibility

»  encargada   ajetivo
en   entrusted, responsible, accountable, answerable, in charge

»  encargada   nom
en   commission (authorized/authorised group); deputy

encefalina   nom
Cada de du composadas cual esiste natural en la serebro, relatada a la endorfinas con efetos simil
en   enkephalin (biology)

enclave   nom
Un area o rejion ensircada par un teritorio plu grande, de cual sua abitores es distinguida par cultur, relijio, lingua o etnico; cualce loca o grupo cual difere de los cual ensirca lo
en   enclave

enclui   verbo transitiva
Ensirca a tota lados; restrinje (algun) par pone el en un sala cluida; separa (un comunia) de la mundo esterna
en   enclose, shut in, encapsulate, encase

encontra   verbo transitiva
Veni a la presentia o acompania de (algun), en modo acaso o organizada; (du cosas) deveni tocante lunlotra
en   meet, encounter, come across, hook up with

»  encontra   nom
en   meeting, date, appointment, rendezvous, encounter; briefing, assignation; session (therapy, music); match (sport)

»  encontra acaso   verbo
en   stumble upon

»  encontra acaso   nom
en   chance encounter

»  encontra romantica   nom
en   romantic rendezvous, tryst

endemica   ajetivo
(Un maladia o state) frecuente trovada en un popla o rejion spesifada; (un planta o animal) nativa de, o trovada sola en, un rejion o pais spesifada
en   endemic

»  endemica   nom
en   endemic

endo-   prefisa
En
en   endo- (inside)

endocrin   ajetivo
(Un glande) cual secrete ormones o otra produidas a direta en la sangue
en   endocrine (gland)

endocrinolojia   nom
La ramo de fisiolojia e medica cual studia la glandes endocrin e ormones
en   endocrinology

»  endocrinolojial   ajetivo
en   endocrinological

»  endocrinolojiste   nom
en   endocrinologist

endodontia   nom
en   endodontics

endogama   ajetivo
Sposinte un person de sua propre comunia, clan o tribu; reproduinte con un individua prosima relatada
en   endogamous, inbred

»  endogamia   nom
en   endogamy, inbreeding

endojenese   nom
en   endogeny

»  endojenesal   ajetivo
Con orijina o causa interna; cresente o orijinante a interna de un organisme
en   endogenous

endometrio   nom
La membrana mucosa cual fore la utero e spesi en la sicle menstrual per aseta posible la implanta de un embrio
en   endometrium

»  endometrial   ajetivo
en   endometrial

endometriose   nom
Un maladia causada par texedas endometrial estra la utero e causante dole de la pelvis
en   endometriosis

endonim   ajetivo
(Un nom de loca) usada par persones en acel rejion, per esemplo `Jonguo`
en   endonymous

»  endonim   nom
en   endonym (local place name)

endoplasma   nom
La strato la plu interna de la sitoplasma de selulas amebin
en   endoplasma

endorfina   nom
Cada de un grupo de ormones secreteda en la serebro e sistem de nervos, cual ave un efeto simil a opio
en   endorphin

endoscopio   nom
Un aparato medical cual on pote introdui en la corpo per regarda organos interna
en   endoscope

»  endoscopi   nom
en   endoscopy

»  endoscopial   ajetivo
en   endoscopic

endostilo   nom
(En alga animales primitiva, como lampreas) un ranur con silios a la mur ventral de la farinje, cual produi muco per colie particulas de nurintes
en   endostyle (anatomy)

endotelio   nom
La texeda cual formi un strato de selulas forente multe organos e cavetas de corpo, spesial la cor, la dutos sangual e la dutos limfal
en   endothelium (anatomy)

enebria   verbo transitiva
(Un droga o alcol) fa ce (algun) perde controla de sua condui e capasias
en   intoxicate, inebriate

»  enebria   nom
en   intoxication, inebriation, drunkenness

»  enebriada   ajetivo
en   intoxicated, inebriated, drunk, drunken, tipsy

»  enebriada   nom
en   drunk, drunkard

»  enebriante   ajetivo
en   intoxicating, inebriating

»  enebriante   nom
en   intoxicant

»  posenebria   nom
en   hangover

Eneida   nom   (dise ‘eneïda’)
Un poesia epica en latina, en dudes libros, par Vergilio, cual raconta la viajas de Enea pos la defeta de Troia
en   Aeneid (poem)

enema   nom
Un trata medical en cual licuida o gas es injetada en la reto, tipal per aida feci, ma ance per introdui drogas o permete radiografi
en   enema

enemi   nom   (dise ‘enemí’)
Un person o persones ci oposa o ataca un person o cosa
en   enemy, adversary, foe

»  enemia   nom
en   hostility (quality), enmity, malignity, acrimony

»  enemin   ajetivo
en   hostile, adverse, belligerent, antagonistic, inimical

enerjia   nom
La fortia nesesada per ativia fisical o mental; la potia derivada de recursos fisical o cimical, usada per furni lus o caldia o per opera macinas; (en fisica) la cualia de materia e radia cual mostra se como la capasia de fa labora; la grado o nivel de esta poseseda par alga cosa o nesesada per un prosede
en   energy, power; verve, vigor/vigour, pep

»  desenerji   verbo transitiva
en   de-energize/de-energise, enervate

»  desenerji   nom
en   enervation

»  enerji   verbo transitiva
en   energize/energise, vitalize/vitalise

»  enerjiosa   ajetivo
en   energetic, vigorous, brisk, lusty, vibrant

»  par enerjia de pilas   ajetivo
en   battery-powered

»  par enerjia solal   ajetivo
en   solar-powered

»  reenerji   verbo transitiva
en   re-energize/re-energise, rally

enets   ajetivo
Pertinente a un popla de Sibir norde ci es pastores de renos, o a sua linguas
en   Enets, Samoyed, Samoyedic (person, language)

»  enets   nom
en   Enets, Samoyed, Samoyedic (person, language)

enfante   ajetivo
en   child

»  enfante   nom
Un umana joven e sesal nonmatur; un animal sesal nonmatur; un fia o fio
en   child, kid, kiddie, kiddy, bairn, tyke

»  enfante con clave   nom
en   latchkey child

»  enfante de sinco anios   nom
en   five-year-old child, five-year-old

»  enfante misera   nom
en   urchin, guttersnipe

»  enfante unica   nom
en   only child

»  enfantes   nom, plural
en   children, offspring, progeny

»  enfantia   nom
en   childhood, girlhood, boyhood

»  enfantin   ajetivo
en   childish, childlike, innocent, infantile, puerile

»  enfantor   nom
en   childminder, nanny, nurse, nursemaid

»  estraenfante   nom
en   stepchild

enfantiside   verbo transitiva
Mata (un enfante)
en   commit infanticide

»  enfantiside   nom
en   infanticide (action)

»  enfantisidor   nom
en   infanticide (person)

enferno   nom
(En alga relijios) un loca spirital do persones mal es punida pos mori
en   hell, hellfire, inferno, perdition, underworld

»  enfernal   ajetivo
en   infernal

»  enfernin   ajetivo
en   hellish, damned, damn, blasted, bloody

enflue   verbo nontransitiva
Flue a en; (datos o testo) entra a un computador
en   flow in

»  enflue   verbo transitiva
en   input

»  enflue   nom
en   inflow, influx, input, intake; flow (tide)

enforsa   verbo transitiva
Forsa la obedi de (un lege, regula o obliga)
en   enforce, apply, implement, bring to bear

»  enforsa   nom
en   enforcement, application, implementation

»  enforsable   ajetivo
en   enforceable

»  enforsada   ajetivo
en   enforced, in effect

»  enforsor   nom
en   enforcer

»  enforsor de corte   nom
en   bailiff

»  nonenforsable   ajetivo
en   unenforceable

»  reenforsa   verbo transitiva
en   re-enforce

engana   verbo transitiva
Fa ce (algun) crede alga cosa cual no es vera, tipal per ateni un vantaje personal
en   deceive, hoax, bluff, bilk, trick, inveigle

»  engana   nom
en   deception, subterfuge, hoax, bluff, bunco, deceit, duplicity, con, feint, humbug, setup, skulduggery, wile

»  engana sposal   nom
en   cuckoldry

»  enganosa   ajetivo
en   deceitful, deceptive, duplicitous, devious, sneaky, underhanded, deceitful, duplicitous, illusive

»  nonenganante   ajetivo
en   guileless, artless

England   nom
Un pais de Europa cual formi la parte la plu grande e la plu sude de Britan
(capital: London)
en   England

»  engles   ajetivo
en   English (person, language)

»  engles   nom
en   English; Englishman, Englishwoman

»  engles estuarial   nom
Un dialeto fonetical de engles, parlada par un cuantia grande de persones de London e rejiones este longo la Rio Thames
en   Estuary English

»  engles prescriveda   nom
en   standard English

»  englesi   verbo nontransitiva
en   anglicize/anglicise

»  englesi   verbo transitiva
en   anglicize/anglicise

»  englesi   nom
en   anglicization/anglicisation

»  englesisme   nom
en   anglicism

engoli   verbo transitiva
Permete ce (un comeda, bevida o simil) desende la garga; (un sustantia o forte) covre o enclui completa (un person o cosa)
en   swallow, gulp, guzzle, scoff, swig, swill; engulf, envelop

engrana   verbo nontransitiva
(Piniones) interlia per move un macina o veculo; entra a un combate o batalia
en   engage (gear, enemy)

»  engrana   verbo transitiva
en   engage (gear, enemy)

»  engrana   nom
en   engagement (gear, combat); gear (setting)

»  engrana de avansa   nom
en   drive, forward gear

»  engrana de retira   nom
en   reverse, reverse gear

»  engrana mor   nom
en   neutral (gear)

»  engrana prima   nom
en   first gear

»  desengrana   verbo nontransitiva
en   disengage (gear, enemy)

»  desengrana   verbo transitiva
en   disengage (gear, enemy)

»  desengrana   nom
en   disengagement

»  engranada   ajetivo
en   engaged (gear)

»  engranada a cuatro rotas   nom
en   four-wheel drive, all-wheel drive, four-by-four

»  engranador   nom
en   gearbox, transmission

»  supraengrana   nom
en   overdrive

enigma   nom
Un person o cosa misteriosa o difisil per comprende
ca   endevinalla
en   enigma, conundrum, puzzle
es   adivinanza
fr   énigme
it   enigma
pt   enigma

»  enigmosa   ajetivo
en   enigmatic

enlinia   ajetivo
Liada a un computador o rede de computadores; (un servi o ata) disponable o fada en la interede
en   online

enorme   ajetivo
Con estracomun multe grandia, cuantia o estende
en   enormous, giant, huge, vast, immense, colossal, tremendous, prodigious, terrific

»  enorme   averbo
en   enormously, hugely, vastly

»  enormia   nom
en   vastness, enormity, immensity, bulk

enotera   nom
Un planta con flores jala cual abri en la sera e produi semes de cual on pote estrae un olio medical
Oenothera
en   evening primrose

enrola   verbo nontransitiva
Move en un curso torsente o spiral; fa ce (un aparato, tipal un orolojo) funsiona par turna un clave o manico; move se a un posa curva e comfortosa
en   wind, coil, wind up (mechanism); furl; curl up, snuggle

»  desenrola   verbo nontransitiva
en   unroll, unwind, uncoil, unfurl

»  enrola   nom
en   roll; coil, skein

»  enrola de piano   nom
Un enrola de paper perforada cual controla la moves de la teclas en un piano automata
en   piano roll

»  enrolador   nom
en   winch, capstan, windlass

enscrive   verbo transitiva
Scrive o siseli (parolas o simboles) sur alga cosa, spesial como un arcivo formal o permanente; organiza, par paia a ante, ce (algun) va reseta periodal un jornal o simil; rejistra (algun) per partisipa en alga cosa, spesial per deveni un soldato, un membro de un instituida, o un studiante en un curso
en   inscribe, subscribe, register (for activity), enlist, enroll/enrol, empanel, impanel, recruit, matriculate

»  enscrive   nom
en   inscription, subscription, sub, registration, enlistment, enrollment/enrolment, conscription

»  enscrive su direto de autor   verbo
en   copyright

»  enscrive de tomba   nom
en   epitaph

»  desenscrive   verbo transitiva
en   unsubscribe

»  enscriveda   ajetivo
en   inscribed, subscribed, registered, enrolled, recruited

»  enscriveda   nom
en   recruit, conscript, draftee

»  enscrivor   nom
en   subscriber

»  nonenscrivor   nom
en   non-subscriber

»  preenscrive   verbo transitiva
en   pre-register

»  reenscrive   verbo transitiva
en   resubscribe, re-enlist

ensefalite   nom
Un inflama de la serebro, causada par un infeta o un reata alerjica
en   encephalitis

ensefalograf   nom
Un aparato per rejistra la strutur o ativia de la serebro
en   encephalograph

»  ensefalografia   nom
en   encephalography

ensefalogram   nom
Un rejistra creada par un ensefalograf
en   encephalogram

ensefalomielite   nom
Un inflama de la serebro e medula spinal, tipal causada par un virus
en   encephalomyelitis

ensela   verbo transitiva
Pone un sela sur (un cavalo o otra animal)
en   saddle

»  desensela   verbo transitiva
en   unsaddle

ensende   verbo nontransitiva
Comensa arde; (un fusil) comensa xuta; (un lampa) comensa lumina
en   catch fire, light, ignite, kindle; fire (gun); turn on (light, person)

»  ensende   verbo transitiva
en   set fire to, light, ignite, kindle; fire (gun); turn on (light, person)

»  ensende   nom
en   ignition

»  ensende criminal   nom
en   arson

»  ensendador   nom
en   lighter

»  ensendelampa   nom
en   lamplighter

»  ensendente   ajetivo
en   igniting, incendiary

»  ensendor   nom
en   firestarter

»  ensendor criminal   nom
en   arsonist

»  malensende   verbo nontransitiva
en   misfire (gun)

»  malensende   verbo transitiva
en   misfire (gun)

»  reensende   verbo transitiva
en   reignite

ensenia   verbo transitiva
Mostra o esplica (alga cosa) a algun; dona informa sur (un capasia o sujeto) a algun
‹ ensenia a enfantes; ensenia la regulas a algun ›
→ instrui
en   teach (a subject)

»  ensenior   nom
en   teacher, lecturer, pedagog/pedagogue, schoolteacher, schoolmaster, schoolmistress

»  ensenior privata   nom
en   tutor

»  ensenior xef   nom
en   headteacher, headmaster, headmistress

ensiclica   ajetivo
Pertinente a un letera de la pape enviada a tota bispos de la Eglesa Catolica Roman
en   encyclical

»  ensiclica   nom
en   encyclical

ensiclopedia   nom
Un libro o colie de libros con informa sur multe sujetos o multe partes de un sujeto, tipal alfabetal ordinada
en   encyclopedia/encyclopaedia

ensinta   ajetivo
(Un fem o animal fema) con un feto developante en sua utero
en   pregnant, gravid

»  ensinti   verbo nontransitiva
en   become pregnant

»  ensinti   verbo transitiva
en   impregnate

»  ensintia   nom
en   pregnancy

»  ensintial   ajetivo
en   prenatal

ensirca   verbo transitiva
Estende sirca tota lados de (un cosa); inclui; pone un mano, o cosa simil, sirca (un cosa)
en   surround, encircle, enclose, frame, encompass, encapsulate, gird; cup (as with hands)

»  ensirca   nom
en   enclosure, compound, stockade

»  ensirca de bebe   nom
en   playpen

»  ensirca de bestias   nom
en   pen, corral, bullpen, stockyard, run

»  ensirca de canes   nom
en   dog pound, dog run

»  ensirca de cavalos   nom
en   paddock, corral, stockade

»  ensirca de gales   nom
en   chicken coop, hencoop

»  ensirca de oveas   nom
en   sheep pen, sheepcote, sheepfold, fold

»  ensirca de porcos   nom
en   pigpen, pig sty

»  ensircada   ajetivo
en   surrounded

»  ensircada par tera   ajetivo
en   landlocked

»  ensircante   ajetivo
en   encircling, peripheral

ensofla   verbo transitiva
Suca (aira, un odor, un sustantia) tra la nas, tipal con un sona
en   sniff, snort

»  ensofla   nom
en   sniff, snort, insufflation

»  ensoflable   ajetivo
en   sniffable

»  ensoflable   nom
en   snuff

enspira   verbo transitiva
Fa ce (aira, gas o fuma) entra a se par respira
en   inhale, breathe in, toke

»  enspira   nom
en   inhalation

»  enspira subita   verbo
en   gasp

»  enspira subita   nom
en   gasp

»  enspirable   ajetivo
en   inhalable

»  enspirador   nom
en   inhaler

»  enspireta   verbo transitiva
en   gasp

»  enspireta   nom
en   gasp

entablamento   nom
Un lintel continuante en un construida de stilo antica roman o elinica, suportada par colonas o un mur
en   entablature

entera   verbo transitiva
Pone o asconde (un cosa) su la tera; pone (un corpo mor) en la tera, un tomba o la mar, tipal con rituos funeral
en   bury, inter

»  entera   nom
en   burial

»  desentera   verbo transitiva
en   unearth, disinter, exhume, dig up

»  desentera   nom
en   unearthing, exhumation

»  entereria   nom
en   landfill (site)

»  enteror   nom
en   gravedigger

enterite   nom
Un inflama de la intestin, tipal en la intestin magra, comun causante diarea
en   enteritis

entomolojia   nom
La ramo de zolojia cual studia insetos
en   entomology

»  entomolojiste   nom
en   entomologist

entoprocto   nom
Un membro de un filo de animales acual, formida como copas con troncetas longa
Entoprocta
en   entoproct (organism)

entra   verbo nontransitiva
Veni o vade a en (un loca); presenta sua identia per comensa usa un program o loca de rede
‹ entra a un sala; entra a un loca de rede ›
en   enter, go in, come in; log in (software)

»  entra   verbo transitiva
Fa o permete ce (un person o cosa) entra a un local; fa ce (datos) entra a un aparato
en   admit (to place); enter, input

»  entra   nom
en   admission (to place), admittance; entrance, entry, entryway, ingress, check-in, threshold, concourse

»  entra par forsa   verbo
en   break in

»  entrada   nom
en   entry (in list)

»  reentra   verbo nontransitiva
en   re-enter, go back in

»  reentra   verbo transitiva
en   readmit

»  reentra   nom
en   re-entry; readmittance

»  suentrada   nom
en   subentry (in list)

entre   preposada
1   A, en o tra la spasio o tempo cual separa (du o plu ojetos, areas o avenis).   (Leje plu…)
‹ viaja entre Paris e Madrid; comunica entre comunias; tu es entre amis; entre la geras mundal ›
en   between, among, amongst, amid, amidst, betwixt, twixt; within (a group)
eo   inter
2   (Un cuantia) divideda par (un otra)
‹ 100 entre 4 es 25 ›
en   divided by, per, out of

»  entre-   prefisa
Entre
en   inter- (between)

»  entre cual   espresa
en   between which, within which (relative)

»  entre la du   averbo
en   between the two, in between

»  a entre   averbo
en   in between

entregama   nom
La parte de la corpo umana entre la gamas do los junta se a la tronco; la parte corespondente de un veste
en   crotch, crutch

entreseno   nom
La area entre la senos de un fem
en   cleavage

entretempo   averbo
En la periodo interveninte; en la mesma periodo (como un otra aveni ja descriveda)
en   meanwhile, meantime, in the meantime, in the interim

entretexe   verbo transitiva
Lia (cosas longa e magra, como filos, capeles, bandas o ditos) par texe los con lunlotra
en   interweave, interlace, interleave, interlock, intertwine, entwine, dovetail

»  entretexable   ajetivo
en   interlacing, interlocking

»  entretexeda   ajetivo
en   interwoven, interlaced

entropia   nom
(En fisica) un mesura de la cuantia de enerjia cual no es disponable per fa labora; (metafor) un desende a desordina o acasia en un sistem
en   entropy

enurese   nom
Urini nonvolente, tipal par enfantes a note
en   enuresis, bedwetting

envelopa   nom
Un paper pliada e selable per conteni un letera o documento
en   envelope

envia   verbo transitiva
Fa ce (un person o cosa) vade a un destina spesifada, incluinte par metodos eletronical
en   send, dispatch, transmit, transfer, submit

»  envia   nom
en   transmission

»  envia a mar   verbo
en   launch (a ship)

»  envia a via   verbo
en   send away, send off, dismiss

»  enviada   ajetivo
en   sent

»  enviada   nom
en   envoy, emissary

»  enviador   nom
en   transmitter

»  envior   nom
en   sender

»  nonreenviable   ajetivo
en   non-returnable, unreturnable

»  reenvia   verbo transitiva
en   send back, return, recommit, resubmit

»  reenviable   ajetivo
en   returnable

envolve   verbo transitiva
Covre o enclui (un person o cosa) en un materia mol, como paper o stofa; fa ce (un person o grupo) partisipa en alga cosa
en   wrap, wrap up, envelop, swaddle; involve, embroil, enlist, engage, commandeer

»  envolve   nom
en   involvement

»  envolve en leto   verbo
en   tuck into bed

»  desenvolve   verbo transitiva
en   unwrap

»  envolveda   ajetivo
en   wrapped; involved

»  es envolveda en   verbo
en   be involved in, be wrapped up in, be party to, be engaged in

»  reenvolve   verbo transitiva
en   rewrap; re-engage

entxilada   nom
Un tortilia plenida con carne o ceso e servida con salsa de txili
en   enchilada (food)

enzima   nom
Un materia produida par un organisme, cual funsiona como un catalisente per un reata biocimical spesifada
en   enzyme

»  enzimal   ajetivo
en   enzymatic

enzimolojia   nom
La ramo de biocimica cual studia enzimas
en   enzymology

eon   nom
Un periodo nondefinida ma multe longa de tempo; (en astronomia e jeolojia) un periodo de bilion anios; (en jeolojia) un divide major de tempo, plu ca un era
en   eon/aeon

eosene   ajetivo
Pertinente a la epoca du de la tersiaria, entre la paleosene e la oligosene
en   Eocene (geology)

»  eosene   nom
en   Eocene (geology)

eosin   nom
Un tinje roja e fluoresente
en   eosin (dye)

eosinofilia   nom
Un grandi de la cuantia de eosinofilicas en la sangue, cual aveni en responde a alga alerjenes, drogas, parasitos, e en alga tipos de leucemia
en   eosinophilia (medical)

»  eosinofilica   ajetivo
en   eosinophilic

»  eosinofilica   nom
Un selula blanca de la sangue cual conteni granetas fasil per tinje con eosin
en   eosinophil

eparina   nom
Un composada en la figato e otra texedas cual redui la coagula de sangue; un medisin con la mesma efetos
en   heparin (medical)

epatal   ajetivo
Pertinente a la figato
en   hepatic

epatica   nom
Un planta peti, verde e sin flores, con talos folin o folias lobosa, e cual abita en zonas moiada
Marchantiophyta, Hepaticae
en   liverwort, liverleaf, hepatic (plant)

epatite   nom
Un inflama de la figato, tipal causada par un virus transmeteda en comedas o sangue
en   hepatitis

epe   nom
Un spada magra con punto agu, usada en dueles e scrima
en   épée (sword)

epi-   prefisa
Sur, a supra, a contra
en   epi-

epica   ajetivo
Pertinente a o en la stilo de poesias longa, tipal sur la aventuras de un eroe
en   epic

»  epica   nom
en   epic

epicanto   nom
Un plia de pel cual estende de la palpebra superior per covre la angulo interna de la oio, tipal en multe persones de Asia este
en   epicanthus, epicanthic fold

Epicuro   nom
Un filosofiste de Elas antica e la fundor de epicurisme
en   Epicurus (philosopher)

»  epicurisme   nom
en   epicureanism

epidemica   ajetivo
Pertinente a un maladia comunicable cual vasti en un comunia a un ves spesifada; (cualce fenomeno nondesirada) aveninte subita e vasta
en   epidemic

»  epidemica   nom
en   epidemic

epidemiolojia   nom
La siensa de epidemicas
en   epidemiology

»  epidemiolojial   ajetivo
en   epidemiological

»  epidemiolojiste   nom
en   epidemiologist

epiderma   nom
La strato esterna de selulas covrente un organisme, como la surfas de la pel
en   epidermis

»  epidermal   ajetivo
en   epidermal

epididimo   nom
Un de du dutos serpentin pos la testiculos, tra cual spermas pasa a la dutos seminal media
en   epididymis (anatomy)

epifania   nom
Un apare de un spirito divin o supranatural; un aveni subita de intui o revela
en   epiphany

»  sera de epifania   nom
en   Epiphany Eve, Twelfth Night

epifenomeno   nom
Un state mental, regardada como un resulta ladal de la ativia de la serebro; un sintom ladal cual aveni simultan con un maladia, ma no es direta relatada a lo
en   epiphenomenon

epiglote   nom
Un ala de cartilaje a la radis de la lingua, cual es depresada per covre la abri de la tracea cuando on engoli
en   epiglottis

»  epiglotal   ajetivo
en   epiglottal

»  epiglotal   nom
en   epiglottal (consonant)

epigraf   nom
Un enscrive sur un construida o moneta; un sita corta a la comensa de un libro o capitol, sujestante la tema
en   epigraph

epigram   nom
Un comenta o poesia corta e astuta
en   epigram

»  epigramal   ajetivo
en   epigrammatic

»  epigramor   nom
en   epigrammatist

epilesia   nom
Un maladia de nervos, marcada par episodios subita de disturba de la sensas, perde de consensia, o convulsas, relatada a ativia eletrical nonormal en la serebro
en   epilepsy

»  antiepilesica   nom
Un medisin per combate epilesia
en   antiepileptic

»  epilesica   ajetivo
en   epileptic

epilogo   nom
Un parte o parla a la fini de un libro o presenta teatral, cual servi como un comenta sur o conclui per la avenis presedente
en   epilog/epilogue, afterword

epinefrina   nom
Un ormon secreteda par la glandes suprarenal, tipal en states de stresa, aumentante la rapidias de sirculi de sangue, respira e metaboli de carboidratos, e preparante la musculos per ativia
en   epinephrine, adrenaline, adrenalin

episcopalian   ajetivo
Pertinente a ramos de cristianisme cual promove governa par bispos, spesial lo en la SUA e Canada cual es derivada de la Eglesa Engles
en   Episcopalian

»  episcopalian   nom
en   Episcopalian

»  episcopalianisme   nom
en   Episcopalianism (Christianity)

episentro   nom
La punto sur la surfas de la Tera cual es vertical supra la foco de un trematera
en   epicenter/epicentre

episodio   nom
Un situa cual aveni como parte de un serie plu grande; cada de un serie de naras o programes de radio o televisa
en   episode, installment/instalment

»  episodio de caldi   nom
en   hot flash, hot flush

»  episodial   ajetivo
en   episodic

epistemolojia   nom
La teoria de sabe, spesial sua metodos, valuas e estende
en   epistemology

epistolografia   nom
La arte o pratica de scrive leteras
en   epistolography

epitelio   nom
La texeda magra cual formi la strato esterna de la surfas de la corpo, e cual fore la duto de dijesta o otra strutures vacua
en   epithelium (anatomy)

»  epitelial   ajetivo
en   epithelial

epiteto   nom
Un ajetivo o descrive cual espresa un cualia tipal de un person o cosa spesifada, comun negativa
en   epithet

epoca   nom
Un periodo de tempo en istoria o la vive de un person, tipal marcada par avenis notable o cualias spesial; (en jeolojia) un divide major de tempo, plu ca un eda ma min ca un periodo
en   epoch

eponim   ajetivo
(Un cosa) nomida per un person; (un person) donante sua nom a alga cosa
en   eponymous

»  eponim   nom
en   eponym

eposido   nom
Un composada organica de cual sua molecula conteni un anelo de tre membros
en   epoxide (chemistry)

»  eposidal   ajetivo
en   epoxy

epsilon   nom   «Ε ε»
La letera sinco de la alfabeta elinica
en   epsilon (Greek letter)

Er   nom
Un pais en la isola grande a ueste de Britan Grande; esta isola, conteninte Er e Er Norde
(capital: Dublin)
en   Ireland (island); Ireland (country), Republic of Ireland

»  eres   ajetivo
en   Irish, Gaelic (person, language)

»  eres   nom
en   Irish, Gaelic (person, language)

»  Mar Eres   nom
Un mar entre Er e Britan
en   Irish Sea

»  Er Norde   nom
La parte de la isola Er cual parteni a Britan
(capital: Belfast)
en   Northern Ireland

era   verbo nontransitiva
No es coreta; ata en modo mal o noncoreta
en   err, make a mistake

»  era   nom
en   error, mistake, solecism

»  era comica   nom
en   blooper, outtake

»  era grande   nom
en   big mistake, blunder

»  era sosial   nom
en   gaffe, faux pas, solecism

»  erante   ajetivo
en   mistaken, wrong, erroneous, fallacious

»  ereta   verbo nontransitiva
en   slip, slip up, make a small mistake

»  ereta   nom
en   slip, slip-up, booboo, boob, small mistake, glitch

»  ereta de parla   nom
en   slip of the tongue

»  erosa   ajetivo
en   very wrong, badly mistaken, riddled with errors

»  nonerante   ajetivo
en   inerrant, infallible, unerring

era   nom
(En jeolojia) un divide major de tempo, plu ca un periodo ma min ca un eon
en   era (geology)

eraldo   nom
Un mesajor ofisial cual trae novas; un person o cosa regardada como un indica de avenis seguente; (istorial) un ofisial ci supravide la rituos de la stato
en   herald

»  eraldia   nom
en   heraldry

»  eraldial   ajetivo
en   heraldic

erba   nom
Un planta, tipal corta, con folias longa e magra, cual crese savaje o es cultivada per nuri bestias o per crea campos sirca casas o de recrea; un area estendeda de estas; cualce planta de cual sua folias, semes o flores es usada en cosini o medica
Gramineae, Poaceae
en   grass; lawn; herb

»  erba de cosini   nom
en   herb

»  erba-de-mar   nom
Un planta erbin cual abita en o prosima a la mar
Posidoniaceae, Zosteraceae, Hydrocharitaceae, Cymodoceaceae
en   seagrass

»  erba-de-mate   nom
Un spesie de ilex de cual on prepara la bevida mate
Ilex paraguariensis
en   yerba maté

»  desmalerbi   verbo transitiva
en   weed

»  erbal   ajetivo
en   herbal

»  erbalisme   nom
en   herbalism

»  erbaliste   nom
en   herbalist

»  erberia   nom
en   herbarium

»  erbin   ajetivo
en   grasslike, herbaceous

»  erbosa   ajetivo
en   grassy

»  estrae malerbas de   verbo
en   weed

»  malerba   nom
en   weed

erbio   nom   «Er»
La elemento cimical con numero atomal 68
en   erbium (element)

erbiside   nom
Un materia venenosa a plantas, usada per destrui plantas nondesirada
en   herbicide, weedkiller

»  erbisidal   ajetivo
en   herbicidal

erbivor   ajetivo
(Un organisme) cual come sola plantas
en   herbivorous

»  erbivor   nom
en   herbivore

erbolojia   nom
La studia e pratica de la usa medical de plantas
en   herbology

»  erbolojiste   nom
en   herbologist

eremita   nom
Un person ci vive solitar como un disiplina relijiosa; cualce person ci vive solitar
en   hermit, hermitic, recluse, anchorite, anchoress

»  eremiteria   nom
en   hermitage

»  eremitia   nom
en   hermitry

erese   ajetivo
Con credes o praticas cual no acorda con la forma ofisial o jeneral asetada, tipal pertinente a relijio
en   heretical

»  erese   nom
en   heretic, infidel

»  eresia   nom
en   heresy

ergativa   ajetivo
Pertinente a un lingua como euscara o inuit, en cual la sujeto de un verbo nontransitiva condui gramatical como la ojeto de un verbo transitiva, e diferente de la sujeto de un verbo transitiva
en   ergative (grammar)

»  ergativa   nom
en   ergative (grammar)

ergonomia   nom
La studia de refina la desinia de ojetos per masimi la perosia de sua usores
en   ergonomics

»  ergonomial   ajetivo
en   ergonomic

ergote   nom
Un maladia fungal de sereales, venenosa si comeda
en   ergot (fungus)

»  ergotisme   nom
en   ergotism (medical)

erica   nom
Un arboreta peti, con folias peti e cuorin e flores formida como campanas peti ros o purpur
Erica
en   heath (plant)

»  erica arborin   nom
Erica arborea
en   white heather, brier, briar

Eridano   nom
Un constela en la sielo sude, nomida per un rio mital
en   Eridanus (constellation)

Erie, Lago   nom   (dise ‘iri’)
Un de la sinco Lagos Grande de America Norde, a la frontera entre Canada e la SUA
en   Lake Erie

erije   verbo nontransitiva
Deveni rijida e vertical
en   erect, prick up, put up, stand up straight

»  erije   verbo transitiva
en   erect, prick up, put up, stand up straight

»  erije   nom
en   erection

»  erijable   ajetivo
en   erectile

»  erijeda   ajetivo
en   erect, pricked up

eriso   nom
Un mamal peti e noturna de la mundo vea, con pelo spinosa e gamas corta, e capas de enrola se como un bal per defende se
Erinaceinae
en   hedgehog

»  eriso-de-mar   nom
Un ecinodermato con conca sfera o plata, covreda con spinas movable, con un boca a la fondo
Echinoidea
en   sea urchin

erita   verbo transitiva
Reseta (mone, propria o un titulo) cuando la proprior presedente mori; reseta (un cualia) jenetical de sua jenitores o asendentes
en   inherit

»  erita   nom
en   inheritance, heritage, heredity, patrimony, birthright, legacy
it   eredità

»  deserita   verbo transitiva
en   disinherit
it   diseredare

»  eritable   ajetivo
en   heritable, inheritable

»  eritada   ajetivo
en   inherited

»  eritada de familia   nom
en   heirloom

»  erital   ajetivo
en   hereditary

»  eritor   nom
en   heir, heiress, heritor, heritrix, scion

»  eritor legal   nom
en   heir apparent

eritema   nom
Un roji de la pel, tipal a multe areas peti, causada par un feri o irita cual ia dilata la capilares
en   erythema (medical)

»  eritema cutanea   nom
en   chilblain

eritro-   prefisa
Roja
en   erythro- (red)

eritroblasto   nom
Un eritrosite nonmatur, conteninte un nucleo
en   erythroblast (blood cell)

eritromisina   nom
Un antimicrobial usada per trata infetas causada par alga baterias, simil a penisilina
en   erythromycin (antibiotic)

eritropoiese   nom
La produi de eritrosites
en   erythropoiesis (biology)

eritrosite   nom
Un selula roja de la sangue, cual transporta osijen e diosido de carbono a e de la texedas
en   erythrocyte, red blood cell

ermino   nom
Un mamal peti e carnivor en familia de mustela, con coda negra, peto e adomen blanca, e pelo de color de castanias ma tipal intera blanca en inverno
Mustela erminea
en   ermine, stoat

ernia   verbo nontransitiva
(Un parte de un organo) protende tra la mur de la caveta conteninte, per esemplo la intestin a un punto debil de la mur de la adomen
en   herniate

»  ernia   nom
en   hernia, herniation, rupture

»  ernia femoral   nom
en   femoral hernia

»  ernia iatal   nom
en   hiatal hernia

»  ernia inguinal   nom
en   inguinal hernia

»  ernia ombilical   nom
en   umbilical hernia

erode   verbo transitiva
(Venta, acua o un otra fenomeno natural) causa la diminui gradal de (tera o roca) par frota continuante
en   erode, wear away, wear down, weather

»  erode   nom
en   erosion, attrition

»  erodente   ajetivo
en   eroding, erosive

eroe   nom
Un person ci es amirada o idealida per sua coraje, atenis eselente o cualias nobil; la carater xef en un libro, filma o presenta teatral, tipal con bon cualias e ci lejores o regardores pote compatia; un person mital de cualias supraumana, comun de orijina semidivin
en   hero, heroine, protagonist

»  antieroe   nom
en   antihero, antiheroine

»  eroin   ajetivo   (dise ‘eroïn’)
en   heroic

»  eroisme   nom   (dise ‘eroïsme’)
en   heroism

»  supraeroe   nom
en   superhero

eroina   nom   (dise ‘eroïna’)
Un paradole multe abituante, derivada de morfina, comun nonlegal usada per produi estasia
en   heroin (drug)

erojen   ajetivo
Sensosa a stimula sesal
en   erogenous

eron   nom
Un avia grande e vadante con gamas longa, colo longa con forma de S, e beco longa e puntida, cual come tipal pexes
Ardeidae
en   heron
fr   héron

Eros   nom
(En mitos elinica) la dio de ama e desira sesal
en   Eros (mythology)

erotica   ajetivo
Tendente stimula desira sesal
en   erotic, carnal

»  autoerotica   ajetivo
en   autoerotic

»  eroticas   nom, plural
en   erotica

erpes   nom
Cada de un grupo de maladias causada par alga viruses, afetante la pel, tipal con bulas, o la sistem de nervos
en   herpes

erpetolojia   nom
La ramo de zolojia cual studia retiles e amfibios
en   herpetology

»  erpetolojiste   nom
en   herpetologist

Ertra   nom
Un pais en Africa norde-este, a la Mar Roja
(capital: Asmara)
en   Eritrea

»  ertri   ajetivo
en   Eritrean

»  ertri   nom
en   Eritrean

erudita   ajetivo
Avente o mostrante sabes detaliosa sur sujetos academial
en   erudite, learned, scholarly
fr   érudit

»  erudita   nom
en   polymath, savant, scholar
fr   érudit, savant

»  eruditia   nom
en   erudition, learnedness, scholarliness, scholarship
fr   érudition

eruga   nom
La larva de un papilio, cual ave un corpo vermin e sesionida con tre duples de gamas vera e otra duples de membros cual pare como gamas
Lepidoptera
en   caterpillar
fr   chenille

»  eruga de jeometrido   nom
en   inchworm, looper

»  eruga de seda   nom
Bombyx mori
en   silkworm
fr   ver à soie

»  erugin   ajetivo
en   caterpillarlike

eruta   verbo nontransitiva
(Un volcan) deveni ativa e ejeta lava, sene e gases; (un situa nondesirada) aveni subita e dramosa; (un maladia) apare subita sur la pel o otra parte de la corpo
en   erupt; break out (in a rash)

»  eruta   nom
en   eruption; outbreak; rash (medical)

»  eruta de dentes   nom
en   teething
fr   éruption dentaire

es   verbo liante
Ave la state, cualia, identia, natur, rol, loca, etc, spesifada
‹ tu es bela; lo es un jua ›
en   be, is, are, am

»  esente   ajetivo
en   being

»  esente   nom
en   being, creature, entity

es-   prefisa
Estra, de en
en   ex- (outside)

esa-   prefisa
Ses
en   hex- (six)

esaedro   ajetivo
(Un ojeto) solida con ses fases plana
en   hexahedral

»  esaedro   nom
en   hexahedron

esagram   nom
Un stela con ses puntos, formida par la crusa de du triangulos ecuiladal; cada de 64 grupos de ses linias paralel, intera o rompeda, en la libro de divina Yì jīng
en   hexagram

esajera   verbo transitiva
Representa (alga cosa) como plu grande, plu bon o plu mal ca lo es en realia
en   exaggerate, overstate, overdo, caricature

»  esajera   nom
en   exaggeration, hyperbole; spoof

esajo   nom
Un scriveda corta sur un tema spesifada
en   essay

»  esajiste   nom
en   essayist

esamina   verbo transitiva
Oserva atendente (un person o cosa) per determina sua natur o state; investiga completa; dona un serie de taxes o demandas per determina la sabe o capasia de (algun)
en   examine, inspect, check, look over, peruse, investigate, scrutinize/scrutinise, probe, audit, vet, test

»  esamina   nom
en   examination, check-up, work-up, inspection; examination, exam, test, scrutiny, probe, audit

»  esamina de cualia   nom
en   quality test, benchmark test

»  esamina de elejes multiple   nom
en   multiple-choice examination

»  esamina de Pap   nom
nb   "Pap" es un corti de "Papanicolaou".
en   Pap test, Pap smear

»  esamina de sangue   nom
en   blood test

»  esamina parlada   nom
en   oral examination

»  esamina scriveda   nom
en   written examination

»  esaminada   nom
en   examinee

»  esaminor   nom
en   inspector, examiner, auditor

»  preesamina   verbo transitiva
en   precheck, pre-examine, pretest

»  reesamina   verbo transitiva
en   re-examine, reinspect, retest

»  reesamina   nom
en   re-examination, reinspection

esarca   nom
(En la eglesa ortodox) un bispo a un nivel plu basa ca un patriarca
en   exarch (bishop)

»  esarcia   nom
en   exarchate

esata   ajetivo
No aprosima en cualce modo; (detalias) intera coreta; (un siensa) usante mesuras detaliosa como un funda per teorias confirmable
en   exact, precise, particular, accurate

»  esata   averbo
en   exactly, precisely, just, verbatim

»  esata tal   averbo
en   just so

»  esatia   nom
en   accuracy, exactitude, precision, veracity

»  nonesata   ajetivo
en   inexact, imprecise, inaccurate

»  nonesata   averbo
en   not exactly, not quite

»  nonesatia   nom
en   inaccuracy

»  o plu esata   conjunta
en   or rather, or more precisely

esca   nom
Un materia seca e flamable, como lenio o paper, usada per inisia un foco
en   tinder

escara   nom
Pel mor desfisada de la surfas de la pel, plu comun en lesiones de arde, ma ance en gangrena, ulseras, etc.
en   eschar

escava   verbo transitiva
Rompe e move (tera) con un util o macina, o con manos, pedes, beco, etc; crea (un buco, cava, tomba o canal) en esta modo; oteni (minerales) en esta modo
en   dig, scoop, excavate, mine

»  escava   nom
en   excavation, dig

»  escavador   nom
en   digger, excavator (machine)

»  escaveria   nom
en   quarry

»  escavor   nom
en   miner, excavator (person)

esce   averbo
Lo es vera ce ...? (usada per introdui un demanda de veria)
en   (introducing a direct question)
eo   ĉu

»  esce   sujunta
en   whether, if (introducing an indirect question)

esclama   verbo transitiva
Dise o cria subita (alga cosa), spesial cuando on es surprendeda, coler o dolente
en   exclaim, blurt

»  esclama   nom
en   exclamation; interjection (grammar)

»  esclamante   ajetivo
en   exclaiming, exclamatory

esclui   verbo transitiva
Preveni ce (un person o cosa) entra a un loca; preveni ce (un person o cosa) deveni o resta un membro de un grupo; forsa ce (algun) parti de un loca, spesial un nasion
en   exclude, keep out; banish, exile, expel, oust, excommunicate, ostracize, disbar

»  esclui   nom
en   exclusion, banishment, excommunication, ostracism

»  escluida   ajetivo
en   excluded

»  escluida   nom
en   exile, outcast

»  escluinte   ajetivo
en   exclusive, clannish, cliquey

»  escluinte   preposada
en   excluding, other than

escota   verbo transitiva
Talia la colo de (un veste) en modo cual esposa alga de la peto o senos
en   cut low

»  escota   nom
en   neckline, cleavage

»  escota profonda   nom
en   decolletage

»  escota V   nom
en   V-neck

»  con escota V   ajetivo
en   V-necked

»  escotada   ajetivo
en   low-cut, plunging

escrete   verbo transitiva
(Un organisme) separa e dejeta (un materia, spesial un produida de metaboli)
en   excrete

»  escrete   nom
en   excrement; excretion

»  escretal   ajetivo
en   excretory

escretemania   nom
Un osese con escrete
en   scatology

»  escretemanica   ajetivo
en   scatological

escusa   verbo transitiva
Atenta minimi la culpablia cual resulta de (un fali o ofende); pardona (algun) per un fali o ofende
en   excuse

»  escusa   nom
en   excuse, apology, pretext, justification, rationalization/rationalisation

»  escusa se   verbo
en   apologize/apologise

»  escusable   ajetivo
en   excusable

»  nonescusable   ajetivo
en   inexcusable

escuta   verbo transitiva
Atende la parla o sona de (un person o cosa)
en   listen (to), hark, harken, hearken

»  escuta   nom
en   hearing (legal)

»  escuta musica   espresa
en   listen to music

»  escuta secreta   verbo
en   eavesdrop

»  escutador   nom
en   headphones, earphone, earphones, earpiece, earbuds, headset

»  escutador con microfon   nom
en   headset

»  escutador secreta   nom
en   wiretap

»  escutor   nom
en   listener

»  escutores   nom, plural
en   audience

»  reescuta   verbo transitiva
en   relisten, listen again to; listen back to (a recording)

esecuta   verbo transitiva
Comensa e completa (un comanda, taxe, projeta); mata (algun) en modo formal; inisia (un program de computador)
en   execute (including kill), enact (plan), perpetrate, carry out, fulfill/fulfil; run (software)

»  esecuta   nom
en   execution

»  esecuta fretada   nom
en   summary execution

»  esecutor   nom
en   executioner; executor, perpetrator

»  esecutor de atesta   nom
en   executor, executrix

esede   verbo transitiva
(Un cuantia o grandia) es plu ca
en   exceed, surpass

»  esede   nom
en   excess, surfeit

»  esedente   ajetivo
en   exceeding, excessive, supernumerary

»  nonesededa   ajetivo
en   unsurpassed

esele   verbo nontransitiva
Es spesial capas a un ata o sujeto
en   excel

»  esele   nom
en   excellence, eminence

»  eselente   ajetivo
en   excellent, great, wonderful, marvelous/marvellous, outstanding, eminent, prime, illustrious, fine, grand, terrific, top-notch

»  eselentia   nom
en   excellence, greatness

»  eselentia   esclama
en   your excellency, your grace

esemplo   nom
Un cosa cual representa sua spesie, tipo, grupo, etc, o cual mostra un regula jeneral
en   example, sample, exemplar, model, specimen

»  esempli   verbo transitiva
en   exemplify, illustrate, epitomize/epitomise

»  esemplo perfeta   nom
en   perfect example, paragon, quintessence

»  per esemplo   averbo   «pe»
en   for example, for instance

esense   nom
La cualia de alga cosa sin cual lo no pote esiste o es se; la parte o aspeta la plu importante de un problem o projeta
en   essence, quintessence, quiddity; crux, gist

»  esensal   ajetivo
en   essential, critical, crucial, inherent, intrinsic, pivotal

»  esensal   averbo
en   essentially

»  la esense de un arcitetor   nom
en   the quintessential architect, the architect par excellence

»  nonesensal   ajetivo
en   non-essential, extrinsic

esenta   verbo transitiva
Libre de un obliga o culpablia forsada a otras
en   exempt

»  esenta   nom
en   exemption, dispensation, impunity, immunity (legal)

»  esentada   ajetivo
en   exempt

eserse   verbo nontransitiva
Es fisical ativa per manteni o boni sua sania o capasia
en   exercise, work out, drill, train

»  eserse   nom
en   exercise, workout, drill, exertion

»  eserse adomenal   nom
en   abdominal exercise, sit-ups

»  eserse con pesas   nom
en   weight training

»  eserse fisical   nom
en   physical exercise, calisthenics

»  esersor   nom
en   exerciser

»  esersosa   ajetivo
en   strenuous

eseta   verbo transitiva
Spesifa (un person o cosa) como no parteninte a un categoria o grupo
en   except, spare

»  eseta   nom
en   exception; irregularity

»  con eseta de   preposada
en   except, except for, excepting, with the exception of

»  esetante   preposada
en   except, except for, excepting, with the exception of, other than

»  esetosa   ajetivo
en   irregular, full of exceptions

»  sin eseta   averbo
en   without exception, whatsoever, at all

esflue   verbo nontransitiva
Flue a estra; (datos o testo) es produida par un computador
en   flow out

»  esflue   verbo transitiva
Produi e emete
en   output, emit

»  esflue   nom
en   outflow, output; ebb (tide)

»  esfluente   nom
en   effluent

esibi   verbo transitiva
Mostra publica (un obra de arte o cosa interesante) en un museo, galeria o feria
en   exhibit

»  esibi   nom
en   exhibition; panoply

»  esiberia   nom
en   exhibition hall

»  esibisme   nom
en   exhibitionism

»  esibiste   nom
en   exhibitionist, flasher

»  esibor   nom
en   exhibitor

esije   verbo transitiva
Comanda (alga cosa) en modo insistente o obligante; demanda en modo brusca
en   demand, require, exact

»  esije   nom
en   demand, requirement

»  esije judal   nom
en   injunction

»  esije ultima   nom
en   ultimatum

»  con esije ce   sujunta
en   on condition that, provided that

»  esijente   ajetivo
en   demanding, bossy, exigent; picky, fussy, choosy, persnickety/pernickety, finicky, prissy

esiste   verbo nontransitiva
Es real
en   exist

»  esiste   nom
en   existence

»  esistal   ajetivo
en   existential

»  esistente   ajetivo
en   existing, existent, extant

»  esistentialisme   nom
en   existentialism

»  esistentialiste   ajetivo
en   existential, existentialist

»  esistentialiste   nom
en   existentialist

»  nonesiste   nom
en   non-existence

»  nonesistente   ajetivo
en   non-existent

»  preesiste   verbo nontransitiva
en   pre-exist

»  preesistente   ajetivo
en   pre-existing

esita   verbo nontransitiva
Pausa ante un dise o ata, tipal cuando on es nonserta; move o parla sin sertia; comensa perde fortia o momento
en   hesitate, falter, balk

»  esita   nom
en   hesitation

»  esita moral   nom
en   scruples

»  esitante   ajetivo
en   hesitant, reluctant, halting, faltering

»  esitosa   ajetivo
en   tentative

»  nonesitante   ajetivo
en   unhesitating, unfaltering, unflinching

esmalte   nom
Un materia vitrin e opaca o diafana, aplicada a un surfas dur per orna o proteje lo
en   enamel

»  esmalti   verbo transitiva
en   enamel

esmeralda   ajetivo
Briliante verde
en   emerald

»  esmeralda   nom
Un varia de beril con esta color, rica de cromo e valuada como un jem
en   emerald

eso-   prefisa
Estra, a estra, a estra de
en   eso-, exo- (outside)

esobiolojia   nom
La siensa cual studia la posiblia e natur probable de vive sur otra planetas o en spasio
en   exobiology

»  esobiolojial   ajetivo
en   exobiological

»  esobiolojiste   nom
en   exobiologist

esocrin   ajetivo
Pertinente a la glandes cual secrete sua produidas tra dutos cual abri a un epitelio e no direta en la sangue
en   exocrine (gland)

esofago   nom
La tubo entre la garga e la stomaco
en   esophagus/oesophagus, foodpipe

esogama   ajetivo
Sposinte un person de estra sua propre comunia, clan o tribu; reproduinte con un individua no prosima relatada
en   exogamous, outbred

»  esogamia   nom
en   exogamy, outbreeding

esojenese   nom
en   exogeny

»  esojenesal   ajetivo
Con orijina o causa esterna; cresente o orijinante estra un organisme
en   exogenous

esonim   ajetivo
(Un nom de loca) usada par persones estra acel rejion, per esemplo `Xina`
en   exonymous

»  esonim   nom
en   exonym (international place name)

esoplaneta   nom
Un planeta cual orbita un stela estra nosa sistem solal
en   exoplanet

esorsi   verbo transitiva
Forsa ce (un spirito mal) parti de un person o loca, usante rituos spesifada
en   exorcize/exorcise

»  esorsi   nom
en   exorcism

»  esorsiste   nom
en   exorcist

esosceleto   nom
Un covrente esterna e rijida cual suporta e proteje la corpo de alga animales nonvertebrato, tipal artropodos
en   exoskeleton
es   exoesqueleto

esosfera   nom
La parte la plu esterna de la atmosfera de un planeta
en   exosphere (atmosphere)

esotica   ajetivo
Con cualias tipal de paises stranjer distante; atraente o interesante car estracomun
en   exotic

»  esoticas   nom, plural
en   exotica

Espania   nom
Un pais en Europa sude-ueste, a sude de Frans e a este de Portugal
(capital: Madrid)
ca   Espanya
en   Spain
es   España
it   Spagna
pt   Espanha

»  espaniol   ajetivo
en   Spanish (person, language)
es   español

»  espaniol   nom
en   Spanish (person, language)
es   español

espera   verbo transitiva
Senti o espresa un desira forte per (alga cosa) o ce (alga cosa) va aveni
‹ espera un dia solosa; on espera ce lo no va pluve ›
en   hope for, wish for

»  espera   nom
en   hope, wish

»  esperable   averbo
en   hopefully

»  esperante   ajetivo
en   hoping, hopeful

»  on espera ce   espresa
en   hopefully, it is hoped that

»  sin espera   ajetivo
en   hopeless, forlorn

esperanto   ajetivo
Un lingua creada par Ludwik L Zamenhof en 1887 per comunica internasional
en   Esperanto

»  esperanto   nom
en   Esperanto

»  esperantiste   ajetivo
en   Esperantist

»  esperantiste   nom
en   Esperantist

esperia   verbo transitiva
Encontra o sufri (un aveni); senti (un emosia)
en   experience, undergo, witness

»  esperia   nom
en   experience

»  esperial   ajetivo
en   experiential

»  esperiosa   ajetivo
en   experienced

»  malesperia   nom
en   ordeal

»  nonesperia   nom
en   inexperience

»  reesperia   verbo transitiva
en   re-experience

»  sin esperia   ajetivo
en   inexperienced

esperimenta   verbo nontransitiva
Usa la metodos de siensa per proba e investiga; proba consetas o modos nova de fa alga cosa
en   experiment

»  esperimenta   nom
en   experiment, experimentation

»  esperimental   ajetivo
en   experimental

»  esperimentor   nom
en   experimenter, experimentalist

esperta   ajetivo
Ci ave o usa multe sabe, capasia o esperia en un campo spesifada
en   expert, consummate

»  esperta   nom
en   expert, specialist, consultant, authority, pundit, maven, whiz

»  esperta de cartas   nom
en   cardsharp, cardshark

»  esperta legal   nom
en   expert witness, legal expert

»  espertia   nom
en   expertise, authority, punditry

»  nonesperta   ajetivo
en   inexpert

espeta   verbo transitiva
Regarda (alga cosa) como probable; resta asta (un tempo o aveni spesifada, per esemplo la ariva de algun)
en   expect, anticipate, await, wait for

»  espeta   nom
en   expectation, expectancy, anticipation, waiting

»  espeta de vive   nom
en   life expectancy

»  espeta furtiva   verbo
en   lurk, skulk, loiter

»  espeta la bon momento   verbo
en   wait for the right moment, bide one’s time

»  espeta zelosa   verbo
en   eagerly await, look forward to

»  espetada   ajetivo
en   expected, due, payable

»  espetante   ajetivo
en   expecting, expectant, waiting

»  nonespetada   ajetivo
en   unexpected, unanticipated, unplanned, quirky

»  nonespetante   ajetivo
en   not expecting, unwitting

espetora   verbo transitiva
Tose o sputa (muco) de la garga o pulmones
en   expectorate, cough up

»  espetorante   ajetivo
en   expectorant

»  espetorante   nom
en   expectorant

espia   verbo transitiva
Fa alga cosa compensante afin on pardona (un peca, crimin o otra mal ata)
en   atone for, expiate, do penance

»  espia   nom
en   atonement, expiation, penance

espira   verbo transitiva
Forsa (alga cosa) a estra la pulmones; (en fonetica) produi (un sona) con un espira peti de aira
en   exhale, breathe out; aspirate

»  espira   nom
en   exhalation; aspiration (phonetics)

»  espirada   ajetivo
en   aspirated

»  espirada   nom
en   aspirate (consonant)

esplica   verbo transitiva
Clari (un idea, situa o problem) a algun par descrive plu detalias de lo o par mostra otra fatos o ideas pertinente; dona un razona, escusa o justi per (un condui o disposa)
en   explain, elaborate, elucidate, rationalize/rationalise, justify

»  esplica   nom
en   explanation, reason, justification, rationale, elaboration, rationalization/rationalisation, exposition; legend (diagram)

»  esplica tro   verbo transitiva
en   overexplain, overelaborate, belabor/belabour

»  autoesplicante   ajetivo
en   self-explanatory

»  esije un esplica   verbo
en   demand an explanation, call to account, hold to account

»  esplicable   ajetivo
en   explainable, explicable

»  nonesplicable   ajetivo
en   unexplainable, inexplicable

esplode   verbo nontransitiva
Rompe violente como la resulta de combusta rapida
en   explode, blow up, burst, fulminate

»  esplode   verbo transitiva
en   explode, blow up, blast

»  esplode   nom
en   explosion, blast, outburst, outpouring

»  esplode con rie   verbo
en   burst out laughing, hoot with laughter

»  esplodente   ajetivo
en   exploding, explosive; plosive

»  esplodente   nom
en   explosive; plosive (consonant)

esplora   verbo transitiva
Viaja en (un area nonconoseda) per aprende plu sur lo; investiga detaliosa (un sujeto)
en   explore

»  esplora   nom
en   exploration, excursion, reconnaissance

»  esplora de cavas   nom
en   caving, spelunking

»  esplorante   ajetivo
en   exploring, exploratory

»  esploror   nom
en   explorer, scout

esplota   verbo transitiva
Usa (un recurso) per benefica de lo; benefica de (un situa o la labora de algun) en modo nonjusta
en   exploit, take advantage of, avail oneself of, cash in on

»  esplota   nom
en   exploitation

»  esplota de forestas   nom
en   logging (industry)

»  esplotable   ajetivo
en   exploitable

»  nonesplotada   ajetivo
en   unexploited, untapped

esponente   nom
(En matematica) la potia a cual un numero es levada, tipal scriveda como un supraindise
en   exponent

»  esponental   ajetivo
(Un crese) sempre plu rapida en proportio a un cuantia o grandia cresente
en   exponential (growth)

»  esponenti   verbo transitiva
en   exponentiate (raise to a power)

»  esponenti   nom
en   exponentiation

esporta   verbo transitiva
(Un nasion) envia (benes o servis) a un otra nasion per vende; sperde o introdui (credes e ideas) a un otra comunia; (en informatica) move (datos) a un forma cual pote es lejeda par otra programes
en   export

»  esporta   nom
en   exportation

»  esportor   nom
en   exporter

esposa   verbo transitiva
Fa ce (alga cosa, spesial informa) deveni vidable o conoseda
en   expose; divulge, blab, leak (information)

»  esposa   nom
en   exposure; leak (information)

»  esposa a radia   verbo transitiva
en   irradiate

»  esposa lenta   nom
en   long exposure (photography)

»  esposa par mano   nom
en   manual exposure

»  autoesposa   nom
en   autoexposure

»  esposor   nom
en   exposer, blabbermouth

»  suesposa   verbo transitiva
en   underexpose

»  suesposa   nom
en   underexposure

»  supraesposa   verbo transitiva
en   overexpose

»  supraesposa   nom
en   overexposure

espresa   verbo transitiva
Comparti (un idea o senti) en parolas, jestis o condui
en   express, state, convey (meaning), assert, articulate

»  espresa   nom
en   expression, assertion; turn of phrase

»  espresa clar   verbo transitiva
en   express clearly, clarify, enunciate

»  espresa cortes   nom
en   pleasantry

»  espresa de fas   nom
en   facial expression, countenance

»  espresa tro usada   nom
en   cliché

»  clar espresada   ajetivo
en   clearly expressed, perspicuous

»  espresada   ajetivo
en   expressed

»  espresisme   nom
en   expressionism

»  espresiste   ajetivo
en   expressionist

»  espresiste   nom
en   expressionist

»  espresosa   ajetivo
en   expressive, demonstrative, soulful

»  malespresa   verbo transitiva
en   misexpress, misspeak

»  nonespresable   ajetivo
en   unspeakable, ineffable

»  nonespresosa   ajetivo
en   unexpressive, undemonstrative, reticent, taciturn, deadpan

»  reespresa   verbo transitiva
en   re-express, restate

»  sin espresa de fas   ajetivo
en   expressionless, blank, deadpan

espreso   nom
Cafe negra forte, preparada par forsa vapor tra favas de cafe moleda
en   espresso

espulsa   verbo transitiva
Lansa o forsa (un person o cosa) a estra o a via, tipal en modo subita o fortiosa
en   eject, expel, throw out, cast out, oust, evict, banish, unseat

»  espulsa   nom
en   expulsion, ejection, eviction, banishment

esta   determinante
Cual nos vide asi; cual nos veni de indica, o cual nos es a punto de indica
en   this, these (demonstrative)

»  esta   pronom
en   this, this one; the latter

»  estas   pronom, plural
en   these

»  a esta dias   averbo
en   nowadays, these days

»  a esta loca   averbo
en   here, hither, to this place

»  a esta ora   averbo
en   at this time

»  a esta ves   averbo
en   this time, this once, on this occasion

»  en esta   averbo
en   herein

»  en esta loca   averbo
en   here, in this place, at this place

»  en esta modo   averbo
en   in this way, in this manner, like this, thus, so

»  par esta   averbo
en   hereby

estasia   verbo nontransitiva
Senti o espresa felisia o joia estrema
en   be ecstatic, fly high

»  estasia   verbo transitiva
en   elate, enrapture

»  estasia   nom
en   ecstasy, bliss, rapture, euphoria, elation

»  estasiante   ajetivo
en   ecstatic, overjoyed, euphoric, elated, blissful

»  estasiosa   ajetivo
en   beatific

estate   nom
La saison la plu calda de la anio, entre primavera e autono
en   summer, summertime

»  estatal   ajetivo
en   summer, estival/aestival

»  estati   verbo transitiva
en   summer

»  estatin   ajetivo
en   summery, balmy

»  mediaestate   nom
en   midsummer

este   ajetivo
(Un loca o parte de loca) situada en dirije a la punto do la Sol leva a la ecuinotes; (un person o venta) veninte de esta dirije
en   east, eastern, oriental

»  este   nom
en   east, orient

»  este-norde-este   ajetivo
en   east-northeast

»  este-sentral   ajetivo
en   central east

»  este-sude-este   ajetivo
en   east-southeast

»  a este   averbo
en   eastward, eastwards

»  a este de   preposada
en   to the east of

estende   verbo nontransitiva
Crese per ocupa un area plu vasta o un tempo plu longa; sperde
en   extend, stretch, project, span, splay, sprawl; spread, propagate, expand; reach out (for something)

»  estende   verbo transitiva
Fa ce (un cosa) estende; reti (la corpo, un braso o gama, o un aparato) per ateni o ofre alga cosa
en   extend, stretch; spread, propagate, expand; hold out, proffer

»  estende   nom
en   extent, range, gamut, scope, reach, outreach, extension, spread, expanse, array, propagation, overhang, projection, span

»  estende a   verbo
en   extend to, reach

»  estende de alas   nom
en   wingspan

»  estende de ase   nom
en   wheelbase

»  estende de teto   nom
en   eaves

»  estende tra   verbo
en   spread through, permeate

»  estende tro multe   verbo
en   overextend, overreach

»  estendable   ajetivo
en   extendable, extensible, tensile

»  estendador   nom
en   extensor (muscle)

»  estendeda   ajetivo
en   extended, stretched, outstretched, outspread

»  estendisme   nom
en   expansionism

»  estendiste   nom
en   expansionist

»  estendosa   ajetivo
en   extensive, expansive, far-reaching, sprawling

ester   nom
Un cimical organica, creada par sustitui un alcil o otra grupo organica per un idrojen de un asida
en   ester (chemistry)

esterna   ajetivo
Forminte la surfas o strutur estra la parte major de alga cosa
en   outer, exterior, external, extrinsic, extraneous

»  esterna   nom
en   outside, exterior

»  esterni   verbo nontransitiva
en   externalize/externalise, exteriorize/exteriorise

»  esterni   verbo transitiva
en   externalize/externalise, exteriorize/exteriorise

estetica   nom
La ramo de filosofia cual studia la natur de belia
en   esthetics/aesthetics

»  estetical   ajetivo
en   esthetic/aesthetic

»  esteticiste   nom
en   esthete/aesthete; beautician, esthetician/aesthetician

Esti   nom
Un pais entre Rusia e Lietuva, a este de la Mar Baltica
(capital: Tallinn)
en   Estonia

»  esti   ajetivo
en   Estonian

»  esti   nom
en   Estonian (person, language)

estima   verbo transitiva
Judi o calcula aprosima (la valua, cuantia o estende probable de alga cosa)
en   estimate

»  estima   nom
en   estimate, estimation; budget

»  estima bruta   nom
en   rough estimate

»  estima divinante   nom
en   guesstimate

»  nonestimable   ajetivo
en   inestimable, invaluable, priceless

»  suestima   verbo transitiva
en   underestimate

»  suestima   nom
en   underestimate

»  supraestima   verbo transitiva
en   overestimate

»  supraestima   nom
en   overestimate

estingui   verbo transitiva   (dise ‘estíngui’)
Fa ce (un foco o lumina) sesa arde o brilia
en   extinguish, put out, quench, turn off (lights)

»  estingui   nom
en   extinguishing; extinction, oblivion

»  estinguador   nom
en   fire extinguisher

»  estinguador de candela   nom
en   candle extinguisher, snuffer

»  estinguida   ajetivo
en   extinct

estorse   verbo transitiva
Torse e compresa (alga cosa); estrae (un licuida) de alga cosa en esta modo; oteni (un cosa) par forsa, menasa o otra metodo nonjusta
en   wring, extort

»  estorse   nom
en   extortion, blackmail, shakedown

»  estorsador   nom
en   wringer

»  estorsin   ajetivo
en   extortionate, exorbitant (cost)

»  estorsor   nom
en   extortionist

estra   preposada
1   Situada ultra la bordas o limitas de (un loca, tempo o grupo).   (Leje plu…)
‹ abita estra la site; estra peril; estra la oras de labora; estra la familia ›
en   outside (a place or time)
eo   ekster
2   Movente a ultra la bordas o limitas de (alga cosa)
‹ la gato ia core estra la caxa ›
en   (moving) out of
3   No incluinte, con eseta de, ma no
‹ nun estra la golor pote toca la bal; me ia vide la serie estra la episodio final ›
→ cuando, si
en   except, except for, excepting, with the exception of, apart from, other than
eo   krom, escepte de

»  estra-   prefisa
A estra, a ultra, en ajunta; indicante un person relatada par la resposi de un jenitor
en   extra- (outer, additional); step- (relation)

»  estra comprende   espresa
en   beyond comprehension

»  a estra   ajetivo
en   outward

»  a estra   preposada
en   (moving) out of

»  a estra   averbo
en   outside; outwards

»  de estra   preposada
en   (moving) from outside

»  de estra   averbo
en   (moving) from outside

estracomun   ajetivo
Multe noncomun, nonormal o notable
en   extraordinary

estradi   verbo transitiva
Dona (un person acusada o condenada de un crimin) a la autoria de un pais stranjer do la crimin ia es fada
en   extradite

»  estradi   nom
en   extradition

estrae   verbo transitiva
Prende (alga cosa) de un loca interna o ascondeda
en   extract, remove, bring out, take out, pluck out, excise, excerpt, extricate, glean

»  estrae   nom
en   extraction, excision, removal, resection

»  aida estrae   verbo transitiva
en   help out, help (someone) to climb out

»  estrae de dente   nom
en   tooth extraction

»  estrae fortunas   nom
en   draw lots

»  estrador   nom
en   extractor

»  estraeda   nom
en   extraction, extract, excerpt, clip (thing extracted)

»  nonestrable   ajetivo
en   inextricable

estragon   nom
Un planta perene en familia de margarita, con folias magra e bonodorosa usada en cosini
Artemisia dracunculus
en   terragon (plant)

estragrande   ajetivo
(Un produida comersial) multe grande
en   extralarge, king-size

estralegal   ajetivo
(Un ata o situa) no regulada par lege
en   extralegal, extrajudicial

estralinia   ajetivo
No controlada par o juntada a un computador o rede esterna
en   offline

estramural   ajetivo
Locada estra la mures o bordas de un vila o site; (un curso) separada de la program xef de un scola o universia
en   extramural

estrapola   verbo transitiva
Estende la aplica de (un metodo o conclui, tipal fundida sur statistica) a un situa nonconoseda par suposa ce tendes esistente va continua o metodos simil va funsiona
en   extrapolate

»  estrapola   nom
en   extrapolation

estrasensal   ajetivo
Usante un modo de persepi otra ca la sensas, como telepatia
en   extrasensory

estrasposal   ajetivo
(Un relata sesal) con algun otra ca sua spos
en   extramarital

estrateran   ajetivo
Ultra la Tera o sua atmosfera; no de esta planeta
en   extraterrestrial, alien

»  estrateran   nom
en   extraterrestrial, alien

estrateritorial   ajetivo
Fabricada, locada o comersiante estra sua propre nasion, tipal per esplota custas plu basa o regulas min sever
en   offshore (finance)

estravagante   ajetivo
Noncapas de sesa spende mone o usa recursos; con plu ca la cuantia asetable o conveninte; notable per un stilo multe colorosa o noncomun
en   extravagant, flamboyant, over the top, grandiloquent

»  estravagante   nom
en   extravaganza, spectacle, show

»  estravagantia   nom
en   extravagance, panache

estrema   ajetivo
A grado la plu alta; la plu distante de un sentro o punto spesifada; (un ata) sever o radisal; (un person o opina) promovente tal atas
en   extreme; furthest, outermost; radical, drastic, critical, hardcore

»  estrema   averbo
en   extremely, tremendously

»  estrema   nom
en   extreme, extremity (furthest point)

»  estremi   verbo nontransitiva
en   radicalize/radicalise

»  estremi   verbo transitiva
en   radicalize/radicalise

»  estremi   nom
en   radicalization/radicalisation

»  estremia   nom
en   extremity (quality)

»  estremisme   nom
en   extremism, radicalism, zealotry

»  estremiste   ajetivo
en   extremist, radical

»  estremiste   nom
en   extremist, radical, zealot

»  nonestrema   ajetivo
en   non-extreme, mild, moderate

estremofilia   nom
Un microbio cual abita en situas estrema de temperatur, asidia, alcalinia o consentra cimical
en   extremophilia

»  estremofilica   ajetivo
en   extremophilic

»  estremofilica   nom
en   extremophile

estrildido   nom
Un pinson en un familia de Australia e Asia sude-este, notada per sua nidos grande cupolin
Esterldidae
en   waxbill (bird)

estro   nom
Un periodo reaveninte de interesa sesal e fertilia en multe mamales fema
en   estrus/oestrus

»  en estro   ajetivo
en   in heat, on heat

estrojen   nom
Un ormon steroide cual promove la developa e manteni de cualias fema de la corpo; un ormon simil, artifis produida per usa en contraconsepi e alga maladias de menopausa e menstrua
en   estrogen/oestrogen

estroverti   verbo nontransitiva
Es sosial e espresosa; (en psicolojia) es plu interesada en cosas esterna
en   be extrovert, be extravert

»  estroverti   nom
en   extroversion, extraversion

»  estrovertida   ajetivo
en   extroverted, extraverted, extrovert, extravert

»  estrovertida   nom
en   extrovert, extravert

estrui   verbo transitiva
Puxa o forsa (alga cosa) a estra
en   extrude

»  estrui   nom
en   extrusion

»  estruador   nom
en   extruder; ricer (utensil)

estuario   nom
La boca mareal de un rio grande
en   estuary, delta, tidal mouth, embouchure, firth

esuan   ajetivo
Pertinente a la Statos Unida de America
en   US, American

»  esuan   nom
en   American

esurbe   nom
Un distrito rica ultra la suburbes de un site
en   exurb (rich outlying suburb)

»  esurban   ajetivo
en   exurban

»  esurban   nom
en   exurbanite

»  esurbes   nom, plural
en   exurbia

esvasa   verbo nontransitiva
(Un veste o simil) deveni gradal plu abrida o larga; (un punio) abri
en   flare, open up, open out, spread out; open (hand), unclench (fist); countersink

»  esvasada   ajetivo
en   flared

et-   prefisa
Nominte alcanos e otra idrocarbonos con du atomes de carbono
en   eth- (chemistry)

eta-   prefisa
Sete
en   hepta- (seven)

eta   nom   «Η η»
La letera sete de la alfabeta elinica
en   eta (Greek letter)

etagon   ajetivo
(Un forma plana) con sete lados reta e sete angulos
en   heptagonal

»  etagon   nom
en   heptagon

etametre   nom
Un linia de poesia composada de sete metres
en   heptameter (poetry)

etano   nom
Un gas flamable, sin color e odor, cual es un composante de petrolio e gas natural
en   ethane

etanol   nom
Un licuida flamable e sin color cual on usa como un solvente o carburante e como la ingrediente enebriante de vino, bir e otra bevidas alcolosa
en   ethanol

etatlon   nom
Un sporte en cual on partisipa en sete concursos de core, salta e lansa
en   heptathlon

»  etatlonor   nom
en   heptathlete

etc   corti
E tal cosas, e tal continuante
en   etc., et cetera, and so on, and so forth, and whatnot

eter   nom
Un licuida flamable, bonodorosa e sin color, usada como un solvente e un anestesente
en   ether

»  eteri   verbo transitiva
en   etherize

»  eterin   ajetivo
en   ethereal

etera   nom
Un papilio neotropical
Hetaera
en   hetaera (moth)

eterna   ajetivo
Sempre continuante, sin comensa o fini; valida per tota tempo; continuante per la vive intera de algun
en   eternal, perpetual, ageless, everlasting; lifelong

»  eterni   verbo nontransitiva
en   eternalize/eternalise, memorialize/memorialise

»  eterni   verbo transitiva
en   eternalize/eternalise, memorialize/memorialise

»  eternia   nom
en   eternity, perpetuity

etero-   prefisa
Diferente
en   hetero- (different)

eterodox   ajetivo
No conformante con normas o credes asetada o ortodox
en   heterodox

eterojen   ajetivo
Con cualias o aspetas diversa
en   heterogeneous, motley

eterosesal   ajetivo
Sesal atraeda a persones de la otra seso; pertinente a esta spesie de atrae
en   heterosexual

»  eterosesal   nom
en   heterosexual

»  eterosesalia   nom
en   heterosexuality

eterosiclal   ajetivo
(Un composada) de cual sua molecula conteni un anelo de atomes de minima du elementos
en   heterocyclic

eterotrof   ajetivo
(Un organisme) nurinte se de materias organica complicada
en   heterotrophic (biology)

»  eterotrof   nom
en   heterotroph

»  eterotrofia   nom
en   heterotrophia

etica   nom
La ramo de filosofia cual studia la condui bon o mal de persones
en   ethics

»  etical   ajetivo
en   ethical

»  nonetical   ajetivo
en   unethical

eticeta   nom
Un peso peti de paper, stofa o otra materia, fisada a un ojeto per dona informa sur lo; (en informatica) un cadena de sinias usada per identifia o categori alga cosa en testo o otra datos
en   label, tag, sticker, docket; tag (markup)

»  eticeti   verbo transitiva
en   label, tag

»  eticetida   ajetivo
en   labeled/labelled

»  noneticetida   ajetivo
en   unlabeled/unlabelled

etil   nom
La radical idrocarbonal -C2H5, derivada de etano e presente en multe composadas organica
en   ethyl (chemistry)

etilen   nom
Un gas flamable de idrocarbono, trovada en gas natural, gas de carbon, olio cru e fruta matur, usada en la fabrica de polietilen
en   ethylene, ethene

etimolojia   nom
La studia de la orijina de parolas e sua sinifias cambiante tra istoria
en   etymology

»  etimolojial   ajetivo
en   etymological

etiolojia   nom
La causa o causas de un maladia; un investiga de la causa de alga cosa, tipal espresada en modo istorial o mital
en   etiology/aetiology

etnico   nom
Un popla con un cultur, lingua, relijio o orijina comun, tipal contrastada con la nasion en cual lo abita
en   ethnic group

»  etnical   ajetivo
en   ethnic

»  etnicia   nom
en   ethnicity

etnobiolojia   nom
La studia de la biolojia de un etnico spesifada
en   ethnobiology

etnocoreolojia   nom
en   ethnochoreology

etnografia   nom
La studia de un etnico
en   ethnography

»  etnografiste   nom
en   ethnographer

etnojenese   nom
La jenese de un etnico
en   ethnogenesis

etnolojia   nom
La studia de la cualias de poplas diversa
en   ethnology

»  etnolojial   ajetivo
en   ethnological

»  etnolojiste   nom
en   ethnologist

etnomusicolojia   nom
La studia de musica de etnicos spesifada
en   ethnomusicology

eto-   prefisa
Estra, esterna
en   ecto- (outside)

etolojia   nom
La studia biolojial de la condui de animales o umanas e sua organiza sosial
en   ethology

»  etolojial   ajetivo
en   ethological

»  etolojiste   nom
en   ethologist

Etruria   nom
La rejion en Italia antica entre la rios Arno e Tevere cual ia es la sentro de la sivilia etrusca
en   Etruria

»  etrusca   ajetivo
en   Etruscan

»  etrusca   nom
en   Etruscan

eu-   prefisa
Bon, abundante, rica
en   eu- (good)

eucalipto   nom
Un arbor perene e rapida cresente de Australasia, valuada per sua lenio, olio, goma e resina, e como un arbor ornal
Eucalyptus
en   eucalyptus

eucariota   nom
Un organisme composada de un o plu selulas en cual la adn ave la forma de cromosomas contenida en un nucleo
en   eukaryote, eucaryote (organism)

»  eucariotal   ajetivo
en   eukaryotic, eucaryotic

eucaristia   nom
La rituo cristian cual recorda la Come Ultima, en cual on santi e come pan e vino; esta pan e vino
en   eucharist

Euclide   nom
Un matematiciste de Elas antica ci ia scrive un libro major de aprende jeometria
en   Euclid

»  euclidal   ajetivo
en   Euclidean

»  noneuclidal   ajetivo
en   non-Euclidean

eucre   nom
Un jua de cartas per entre du e cuatro persones, tipal usante la 32 cartas la plu alta, con gol de gania tre o plu de sinco prendes
en   euchre (card game)

eudicota   nom
Un clado multe grande de plantas florinte, incluinte ranunculos, nelumbos, spinaxes, cactos, ribes e peonias
en   eudicot (botany)

eufonia   nom
Un avia tropical, blu a supra e jala a su, en familia de pinson
Euphonia
en   euphonia (bird)

eufonio   nom
Un strumento metal de venta, cual sembla un tuba peti
en   euphonium

euforbia   nom
Un planta o arboreta erbin, con flores peti e verde e un latex letin
Euphorbia
en   euphorbia, spurge (plant)

Eufrates, Rio   nom
Un rio en Asia sude-ueste cual comensa en la montanias de Turcia este e junta se a la Rio Tigris en Irac sude
en   River Euphrates

eujenetica   nom
La siensa de boni un popla par elevas controlada per plu frecuenti la cualias erital cual es desirada
en   eugenics

»  eujenetical   ajetivo
en   eugenetical

»  eujeneticisme   nom
Un filosofia sosial cual crede ce on debe pratica eujenetica
en   eugenics

eumetazon   nom
Un membro de un clado major de tota animales, estra sponjas, placozones e alga otra organismes rara o estinguida
en   eumetazoon (pl. eumetazoa) (organism)

eunuco   nom
Un om castrada, istorial tipal empleada per garda la salas de femes en cortes asian
en   eunuch

Eurasia   nom
La parte de la Tera composada de Europa e Asia
en   Eurasia

»  eurasian   ajetivo
en   Eurasian

eureca   esclama
Espresante joia o sasia a un trova o descovre
en   eureka

euri-   prefisa
Larga
en   eury- (broad)

eurilaimo   nom
Un avia peti con testa grande, beco larga, e tipal plumas colorosa
Eurylaimidae
en   broadbill (bird)

euristica   nom
Un modo de aprende o solve problemes par metodos pratical e sufisinte
en   heuristic

»  euristical   ajetivo
en   heuristic

euro   nom
La unia de mone en la Uni European
en   euro

Europa   nom
Un continente en la emisfera norde, separada de Africa a la sude par la Mar Mediteraneo, e de Asia a la este par la Streta Bosporo, la Montes Caucaso, e la Montes Ural
en   Europe

»  european   ajetivo
en   European

»  european   nom
en   European

»  europeani   verbo nontransitiva
en   Europeanize/Europeanise

»  europeani   verbo transitiva
en   Europeanize/Europeanise

»  europeani   nom
en   Europeanization/Europeanisation

europio   nom   «Eu»
La elemento cimical con numero atomal 63
en   europium (element)

eurosentrisme   nom
Un vista de mundo consentrada sur la cultur o istoria de Europa, iniorante la resta de la mundo
en   Eurocentrism

»  eurosentriste   ajetivo
en   Eurocentric, Eurocentrist

»  eurosentriste   nom
en   Eurocentrist

eurosetica   ajetivo
Oposada a la crese de la potia de la Uni European
en   euroskeptic/eurosceptic

»  eurosetica   nom
en   euroskeptic/eurosceptic

eurozona   nom
La grupo de nasiones de la Uni European de cual sua unia de mone es la euro
en   eurozone, euro area

Euscaleria   nom
La rejion de Frans e Espania sirca la fini ueste de la Montes Pirineo do la popla euscara abita
en   Basque Country

»  euscara   ajetivo
en   Basque (person, language)

»  euscara   nom
en   Basque (person, language)

eutanasia   verbo transitiva
Mata (un organisme) en modo compatiosa
en   euthanize/euthanise, euthanase

»  eutanasia   nom
en   euthanasia

Eva   nom
Un nom fema, incluinte de la fem prima en la Biblia
en   Eve

evacua   verbo transitiva
Move (algun) de un loca perilosa a un loca plu secur; fa ce persones sorti de (un loca perilosa)
en   evacuate

»  evacua   nom
en   evacuation

»  evacuada   nom
en   evacuee

evade   verbo transitiva
Deveni libre de (un prison o simil); evita (un situa nondesirada)
en   escape, flee from

»  evade   nom
en   escape, breakout, getaway

»  evade de prison   nom
en   jailbreak

»  evade de realia   nom
en   escapism

»  evador   nom
en   escapee

»  nonevadable   ajetivo
en   inescapable

evalua   verbo transitiva
Formi un idea de la valua, cuantia o cualia de (alga cosa)
en   evaluate, appraise, assess, measure; screen (for suitability)

»  evalua   nom
en   evaluation, appraisal

»  evalua medical   nom
en   check-up

»  reevalua   verbo transitiva
en   re-evaluate, reappraise, reassess

evanjelio   nom
(En la Biblia) cada de la cuatro libros prima de la Atesta Nova cual nara la vive e instrui de Jesus
en   gospel

»  evanjelial   ajetivo
en   evangelical

»  evanjelialisme   nom
en   evangelicalism

»  evanjelisme   nom
en   evangelism

»  evanjeliste   ajetivo
en   evangelistic

»  evanjeliste   nom
Cada de la cuatro autores de la evanjelios; un person ci atenta converti otras a cristianisme, tipal par proclamas publica
en   evangelist

Everest, Monte   nom
La monte la plu alta de mundo, en Himalaia entre Nepal e Bod
en   Mount Everest, Mount Sagarmatha, Mount Chomolungma

eversa   verbo transitiva
Fa ce la interna de (un cosa) deveni la esterna, e la esterna deveni la interna
en   evert, turn inside-out
fr   retourner, remettre à l’endroit, mettre à l’envers

»  eversa   nom
en   eversion

»  eversada   ajetivo
en   inside-out
fr   à l’enverse

evidente   ajetivo
Clar per vide o comprende
en   evident, in evidence, apparent, obvious, manifest, blatant, flagrant, overt, unmistakable

»  evidente   averbo
en   evidently, obviously, of course

»  evidenti   verbo nontransitiva
en   become evident, turn out (to be), prove (to be)

»  evidenti   verbo transitiva
en   make evident, expose, reveal

»  evidentia   nom
en   obviousness

evita   verbo transitiva
Resta a via de; no vade a o tra (un loca); susede no encontra (un person o situa); preveni (un situa)
en   avoid, evade, elude, dodge, shun, shirk, stay away from, keep away from, bypass, shirk

»  evita   nom
en   evasion, avoidance

»  evita apena   verbo
en   narrowly avoid, have a narrow escape, have a near miss, have a close shave

»  evita de scola   nom
en   truancy

»  evita la scola   verbo
en   avoid school, play truant, play hookie

»  evitable   ajetivo
en   avoidable

»  evitante   ajetivo
en   evasive, elusive, avoiding

»  evitante ce   sujunta
en   avoiding, without (it happening that)

»  evitante lus   ajetivo
en   avoiding light, photonegative

»  evitor   nom
en   avoider, evader

»  evitor de imposta   nom
en   tax dodger

»  nonevitable   ajetivo
en   inevitable, unavoidable, inexorable

evoca   verbo transitiva
(Un cosa) fa ce on recorda (un otra); fa ce algun ofre (un responde o reata)
en   evoke, elicit, remind of, conjure up, call to mind

»  evoca   nom
en   evocation, connotation, resonance

»  evocante   ajetivo
en   evocative

evolui   verbo nontransitiva
(Un forma complicada) developa gradal de un forma simple; developa tra jeneras seguente, tipal par causa de eleje natural
en   evolve

»  evolui   verbo transitiva
en   evolve

»  evolui   nom
en   evolution

»  evolual   ajetivo
en   evolutionary

»  evoluisme   nom
en   evolutionism

»  evoluiste   nom
en   evolutionist

exadesimal   ajetivo
Pertinente a un sistem de aritmetica fundida sur la numero des-ses
en   hexadecimal

exagon   ajetivo
(Un forma plana) con ses lados reta e ses angulos
en   hexagonal

»  exagon   nom
en   hexagon

exametre   nom
Un linia de poesia composada de ses metres
en   hexameter

eziditi   ajetivo
Pertinente a un etnico curdi con relijio e cultur antica
en   Yazidi

»  eziditi   nom
en   Yazidi

»  eziditisme   nom
en   Yazidism (religion)

