= L

l   simbol   (dise ‘el’)
La letera 12 de la alfabeta roman
en   l

»  con forma de L   ajetivo
en   L-shaped

la   determinante
Indicante un o plu persones o cosas ja notada o comun conoseda
en   the
es   el, la, los, las (artículo determinado)

la   nom
La nota ses de la scala de C major, A, en la sistem de solfejo
en   la (musical note)
es   la (nota musical)
fr   la

labia   nom
Un o la otra de la cuatro plias de la vulva
en   labium (pl. labia)

»  labias major   nom
en   labia majora

»  labias minor   nom
en   labia minora

labio   nom
Un o la otra de la du partes spesa cual formi la bordas superior e inferior de la abri de la boca; un parte de la boca de alga insetos e crustaseos
en   lip

»  labio fendeda   nom
en   harelip, cleft lip

»  con labios selida   ajetivo
en   with sealed lips, tight-lipped

»  labial   ajetivo
en   labial

»  labiali   verbo nontransitiva
en   labialize/labialise

»  labiali   verbo transitiva
en   labialize/labialise

»  labiosa   ajetivo
en   thick-lipped

labiodental   ajetivo
(Un sona) fada con la labios e dentes, per esemplo F e V
en   labiodental (consonant)

»  labiodental   nom
en   labiodental (consonant)

labirinto   nom
Un rompetesta de ruetas e sepes, o linias sur paper, tra cual on debe trova un via; cualce rede de vias; (metafor) un masa confusante de informa; un strutur complicada de la orea interna; (en pexes) un strutur complicada per respira
en   maze, labyrinth

»  labirintin   ajetivo
en   labyrinthine

labora   verbo nontransitiva
Ata fisical o mental per reali un intende o resulta, tipal como sua emplea; (en fisica) la usa de fortia per oposa la resiste o produi cambias moleculal
en   work, toil

»  labora   verbo transitiva
en   work, put (someone) to work

»  labora   nom
en   work, labor/labour, toil, effort

»  labora de jardin   nom
en   gardening

»  labora de via   nom
en   roadworks

»  labora en curso   nom
en   work in progress

»  labora fundal   nom
en   groundwork

»  labora nonusosa   nom
en   makework

»  labora par mano   nom
en   manual labour, manual work, handwork
fr   travail manuel

»  labora sin sesa   verbo
en   work incessantly, toil

»  labora sin sesa   nom
en   toil, drudgery, slog

»  labora tro multe   verbo
en   work too much, overwork, overexert oneself, overdo it

»  laboreria   nom
en   workplace, laboratory, workshop, facility; workhouse

»  laboreria siensal   nom
en   laboratory, lab

»  laboreria sindicatida   nom
en   closed shop

»  laboror   nom
en   worker, workman, workingman, laborer/labourer, peasant, journeyman

»  laboror migrante   nom
en   migrant worker, seasonal worker

»  laboror noninstruida   nom
en   unskilled worker, roustabout

»  laboror nonsesante   nom
en   drudge

»  laboror par mano   nom
en   manual laborer/labourer, blue-collar worker

»  laborosa   ajetivo
en   laborious, labored/laboured

»  oras de labora   nom
en   working hours

»  sin labora   ajetivo
en   effortless

laboramania   nom
Un noncapasia de sesa labora
en   workaholism

»  laboramanica   ajetivo
en   workaholic

Labrador   nom
Un rejion norde-este de Canada, e un parte de la provinse de Newfoundland e Labrador
en   Labrador

»  Mar Labrador   nom
Un mar entre Labrador e Calalitnunat, un estende de la Mar Atlantica
en   Labrador Sea

laca   nom
La sava de un arbor, o un sustantia artifis simil, usada como un vernis
en   lacquer

»  laca de capeles   nom
en   hairspray

»  laca de goma   nom
en   shellac

lace   nom
Un servor mas, tipal en uniforma; (insultante) un person ci debe servi e obedi otras
en   footman, lackey, flunkey, stooge

lacrimal   ajetivo
Pertinente a plora o larmas
en   lacrimal, lachrymal

»  oso lacrimal   nom
en   lacrimal bone, lachrymal bone

lacrimojen   ajetivo
Causante la produi de larmas
en   lachrymogenic, lachrymatory
fr   lacrymogène

»  gas lacrimojen   nom
en   tear gas
fr   gaz lacrymogène

lacros   nom
Un jua de ecipos en cual un bal es lansada, portada e caturada con un basto de manico longa con un rede a la fini
en   lacrosse (sport)

ladin   ajetivo
Un lingua de la familia reto-romanica, parlada en partes de Italia norde-este
en   Ladin (language)

»  ladin   nom
en   Ladin (language)

lado   nom
Un loca a sinistra o destra de alga cosa; la parte sinistra o destra de alga cosa; cada de la du duis de un cosa, surfas o loca; un surfas vertical de un cosa o strutur cual no es fronte o retro; un area prosima a la borda e distante de la media; un person o grupo oposante otras en un concurso, debate o disputa
en   side, flank

»  lado de monte   nom
en   mountainside

»  lado de via   nom
en   roadside, wayside, hard shoulder

»  a lado de via   ajetivo
en   roadside, by the roadside

»  a la otra lado   averbo
en   on the other hand

»  a lado   averbo
en   at the side, to the side; to one side, aside, sideways

»  a lado de   preposada
en   beside, next to, alongside, by

»  a un lado   averbo
en   on the one hand

»  con lado a lado   averbo
en   side by side, abreast; neck and neck

»  a lado de lunlotra   averbo
en   next to each other, side by side

»  ladal   ajetivo
en   lateral, side; sideways

»  ladal   nom
en   lateral (consonant)

»  ladal fasante   ajetivo
en   sideways, sideways on

lago   nom
Un area grande de acua ensircada par tera
en   lake

»  lago de reserva   nom
en   reservoir

»  lageta   nom
en   pond, tarn, small lake

»  lagon   nom
en   lagoon

laica   ajetivo
Sin la cualis nesesada per parteni a un grupo profesal o relijial
de   laie
en   lay, nonclerical, nonordained; nonprofessional, nonspecialist, untrained, unqualified, uninitiated
eo   laika
es   laico
fr   laic
it   laico
pt   leigo

»  laica   nom
de   Laie
en   layperson, layman, laywoman
es   lego, laico, seglar
fr   laïc, laïque
it   laico
pt   leigo, laico

»  laicas   nom, plural
de   Laien, Laie
en   laity, lay people
es   laicos, legos
fr   laïcs
it   laicato, laici
pt   leigo

Lakshadib, Mar   nom
Un mar a ueste de Srilanca
en   Lakshadweeb Sea, Laccadive Sea

lama   nom
La borda agu de un cotel, siera, spada, patin o otra util o arma; la parte plata e larga de un aparato como un remo o elica; un peso plata de metal con borda agu; un strumento con borda agu, usada per sutrae capeles de la fas o corpo
en   blade, razor blade, razor

»  lama de arado   nom
en   plowshare/ploughshare

lama   nom
Un titulo onorosa, donada a un monce xef en budisme bod
en   lama (Buddhism)

lambada   nom
Un dansa rapida e erotica de Brasil
en   lambada (dance)

lamda   nom   «Λ λ»
La letera 11 de la alfabeta elinica
en   lambda (Greek letter)

lame   nom
Un stofa entretexeda con fibres oro o arjento
en   lamé (fabric)

lamenta   verbo transitiva
Espresa tristia profonda pos la mori de (algun)
en   lament, mourn, grieve

»  lamenta   nom
en   lamentation, mourning, grief; elegy, dirge, jeremiad

»  lamentada   ajetivo
en   lamented, mourned, late

»  lamentin   ajetivo
en   mournful, plaintive, plangent

»  lamentor   nom
en   mourner

»  lamentosa   ajetivo
en   mournful

lamina   nom
Un strato magra de roca, texeda o otra materia; un materia composada de stratos magra, fisada sur lunlotra; cada de un serie de bandas magra, fisada a intervales en un porte o scermo per permete la pasa de aira o lus; cada de la platas vertical e radial ordinada a la fondo de un xampinion
en   lamina, laminate, plate; louver/louvre, slat; lamella, gill (mushroom)

»  lamini   verbo transitiva
en   laminate

»  lamini   nom
en   lamination

lampa   nom
Un aparato per lumina
en   lamp, light, lantern

»  lampa alojen   nom
en   halogen lamp

»  lampa de calce   nom
en   limelight (literal)

»  lampa de gas   nom
en   gaslight

»  lampa de note   nom
en   nightlight

»  lampa de olio   nom
en   oil lamp

»  lampa de pox   nom
en   torch (electric), flashlight

»  lampa de punto   nom
en   spotlight

»  lampa inondante   nom
en   floodlight

»  lampa retro   nom
en   taillight

»  lampa solin   nom
en   sunlamp

»  lampa ultravioleta   nom
en   ultraviolet lamp, sunlamp

lampeta   nom
Un scarabe notada per sua organos luminosa, produida per atrae la seso oposante
Lampyridaeo
en   firefly, glow-worm, lightning bug

lampo   nom
Un descarga natural de eletrica entre du nubes o entre un nube e la tera
en   lightning, thunderbolt

»  lampi   verbo nontransitiva
en   flash

»  lampi   verbo transitiva
en   flash

»  lampin   ajetivo
en   like lightning, breakneck

»  lamposa   ajetivo
en   full of lightning

lamprea   nom
Un vertebrato acual, simil a un angila, con boca ventosin, dentes e lingua raspante, cual junta se a otra pexes per suca sua sangue
Petromyzonidae
en   lamprey (animal)

lana   nom
La capeles risa e suave de la pelo de un capra, ovea o animal simil, spesial cuando preparada per usa en la fabrica de stofa; la stofa produida con estas
en   wool, fleece

»  lana petenida   nom
en   worsted (yarn, fabric)

»  de lana   ajetivo
en   wool, woollen, woolly

»  lanosa   ajetivo
en   wool-covered, woolly

landsat   nom
Un serie de satelites cual monitori la recursos de la Tera par fotografi la surfas a longias diversa de onda
en   landsat (satellite network)

langobarda   ajetivo
Pertinente a la popla o lingua de un tribu germanica ci ia invade Italia en la sentenio 6
en   Langobardic, Lombardic (person, language)

»  langobarda   nom
en   Langobard, Lombard

langosta   nom
Un crustaseo grande e comable con casca spinosa e antenas longa e pesosa, ma sin la garas grande de omaros
Palinuridae
en   spiny lobster, rock lobster, crawfish

langur   nom
Un simia de Asia con coda longa e vose multe forte
Colobinae
en   langur, leaf monkey

lanio   nom
Un avia cantante con beco oncin e forte
Laniidae
en   shrike (bird)

lanolin   nom
Un sustantia grasosa trovada sur la lana de oveas
en   lanolin (substance)

lansa   verbo transitiva
Propulsa (alga cosa) con forsa tra la aira par un move de la braso e mano; fa ce (un imaje de lus) cade sur un surfas; fa ce (sua vose) es oiable a distantia
en   throw, toss, fling, sling, hurl, chuck, launch, cast, bowl, blast off; project (image, voice)

»  lansa   nom
en   throw, throwing, toss, launch, cast, blast-off, lift-off; projection

»  lansa a mercato   verbo
en   launch onto the market, release, ship

»  lansa alta   verbo
en   lob

»  lansa con dito   verbo
en   flick

»  lansa con dito   nom
en   flick

»  lansa de borda   nom
en   throw-in (football)

»  lansa de fenetra   verbo
en   defenestrate, throw from a window

»  lansa de fenetra   nom
en   defenestration

»  lansa un colpa a   verbo
en   swing at

»  lansada   ajetivo
en   thrown, launched

»  lansada par roceto   ajetivo
en   rocket-propelled

»  lansador   nom
en   launcher

»  lanseria   nom
en   launchpad

»  lansor   nom
en   thrower, bowler, hurler, pitcher

»  relansa   verbo transitiva
en   throw back, throw again

lansadardo   nom, composada (verbo+nom)
Un aparato per lansa un dardo o lansia, composada de un basto con un protende retro cual teni la misil
en   spear thrower, atlatl, woomera

lansaflama   nom, composada (verbo+nom)
Un arma cual ejeta un plumon de foco longa e controlable
en   flamethrower

lansamisil   nom, composada (verbo+nom)
Un aparato cual xuta un misil
en   missile launcher

lansapetra   nom, composada (verbo+nom)
Un macina militar istorial per xuta petras grande
en   catapult

»  lansapetri   verbo transitiva
en   catapult

lansaroceto   nom, composada (verbo+nom)
Un tubo fisada a un arma per xuta rocetos
en   rocket launcher

lansia   nom
Un arma con ase longa e apico puntida, usada per lansa o puxa
en   spear, lance, javelin

»  lansi   verbo transitiva
en   spear, lance, skewer, impale, gore

»  lansieta   nom
en   skewer

lantanido   nom
Cada de la serie de 15 elementos metal de lantano a lutesio en la table periodal
en   lanthanide (chemistry)

lantano   nom   «La»
La elemento cimical con numero atomal 57, un metal blanca arjentin
en   lanthanum (element)

Laozi   nom   (dise ‘lautsi’)
Un filosofiste de Jonguo antica e la autor de la Daodejing, ci ia mori en 531 aec
en   Laozi, Lao-Tze (philosopher)

lapa   nom
Un molusco de mar con conca basa e cono, cual adere a rocas
Patellidae
en   limpet

laparoscopio   nom
Un strumento de fibre otical cual es introduida tra la mur de la adomen per vide organos o permete sirurjia
en   laparoscope (medical)

»  laparoscopi   nom
en   laparoscopy

»  laparoscopial   ajetivo
en   laparoscopic

laparotomio   nom
Un talia sirurjial en la mur de la adomen, cual permete diagnose o sirurjia
en   laparotomy (medical)

lapidario   ajetivo
Pertinente a la atas de grava, talia o brilia petras o jemes
en   lapidary

»  lapidario   nom
en   lapidary (gem worker)

lapis   nom
Un strumento de grafito e lenio o metal per scrive o desinia
en   pencil

»  lapis colorida   nom
en   colored/coloured pencil, coloring/colouring pencil

Laptev, Mar   nom
Un mar a norde de Sibir sentral
en   Laptev Sea

lardo   nom
Carne preparada de la dorso o lados de un porco
en   bacon

larga   ajetivo
Con distantia grande de un lado a la otra
en   wide, broad

»  largi   verbo nontransitiva
en   widen, broaden

»  largi   verbo transitiva
en   widen, broaden, ream

»  largia   nom
en   width

»  largia de banda   nom
en   bandwidth

larinje   nom
Un organo musculosa e vacua cual formi un duto de aira a la pulmones e cual teni la cordas vosal en umanas e otra mamales
en   larynx

»  larinjal   ajetivo
en   laryngeal, guttural

»  larinjal   nom
en   laryngeal, guttural

larinjite   nom
Un inflama de la larinje, tipal causante un vose ru o asente, respira ru e tose dolosa
en   laryngitis

larix   nom
Un arbor conifer con grupos de agos briliante verde e caduca
Larix
en   larch (tree)

larma   verbo transitiva
Un gota de licuida clar e salosa, secreteda par glandes en la oios cuando on plora o cuando la oio es iritada
en   weep, shed tears, tear

»  larma   nom
en   tear, teardrop

»  larmosa   ajetivo
en   tearful, teary, weepy, maudlin

larva   nom
La forma ativa ma nonmatur de un inseto, entre un ovo e un pupa
en   larva, grub (insect)

»  larva de mosca   nom
en   maggot

»  larva xilofaje   nom
en   woodworm

»  larval   ajetivo
en   larval

lasa   verbo transitiva
Permete ce (un person o cosa) resta o aveni; permete (ce on fa alga cosa)
en   leave (in a specified state); allow, let (happen)

»  lasa ce on entra   verbo
en   admit, allow entry

»  lasa ce un cosa cade   verbo
en   let something fall, drop something (deliberately); omit something

lasanie   nom
Pasta con forma de bandas larga; un plato italian fornida de esta e stratida con carne o vejetales, ceso e salsa de tomates
en   lasagne

laser   nom
Un aparato cual jenera un raio intensa de lus coerente e monocromata
en   laser

»  laseri   verbo transitiva
en   laser

lasera   verbo transitiva
Tira fortiosa (un cosa) a pesos; crea un buco o fende en (un cosa) par tira o perfora, tipal sin intende
en   tear, rend, rip, lacerate, maul

»  lasera   nom
en   tear, laceration

»  laserada   ajetivo
en   torn, ripped, ragged, tattered

lasiva   ajetivo
Sentinte o mostrante un desira sesal en modo ofendente
en   lascivious, lecherous, lewd, lustful, licentious, lubricious, salacious, prurient, dissolute; obscene, crude, coarse, dirty, filthy, mucky, naughty, smutty, raunchy

»  lasiveria   nom
en   red-light district, fleshpot

»  lasivia   nom
en   lewdness, lechery

laso   nom
Un anelo de corda con noda liscante cual streti cuando la corda es tirada, usada per catura animales o pende persones
en   lasso, noose, lariat

»  lasi   verbo transitiva
en   lasso

lata   nom
Aser o fero en forma de plato stratida con stanio
en   tinplate, sheet steel

»  laton   nom
Un aliada jala de cupre e zinco
en   brass

»  lator   nom
en   tinsmith

latce   nom
(En cosini iudi) un crepe, tipal de patatas raspada
en   latke (pancake)

latex   nom
Un licuida letin trovada en multe plantas, cual suda cuando la planta es taliada e coagula cuando esposada a aira; un produida artifis cual sembla esta
en   latex

latica   ajetivo
Pertinente a o derivada de lete
en   lactic

latina   ajetivo
Pertinente a la popla o lingua de Roma antica; pertinente a la popla e cultur de la partes de America Norde e Sude en cual linguas romanica es parlada
en   Latin; Latin American, Hispanic, Latina, Latino

»  latina   nom
en   Latin; Latin American, Hispanic, Latina, Latino

»  latina de porcos   nom
en   Pig Latin

»  latina poplal   nom
en   Vulgar Latin

latitude   nom
La distantia angulo de un loca a norde o sude de la ecuator, o de un ojeto sielal a norde o sude de la ecuator sielal, normal espresada en grados e minutos
en   latitude

»  latitude de sielo   nom
en   declination

latolosa   nom
Un zucar artifis cual pote funsiona como un paraconstipa
en   lactulose (sugar)

latosa   nom
Un zucar trovada en lete, un disacarido con unias de glucosa e galatosa
en   lactose (sugar)

latrina   nom
Un vason, o strutur simil, usada en un campa o caserna, tipal estra casa
en   latrine, outhouse, privy

Latvia   nom
Un pais a la costa este de la Mar Baltica
(capital: Riga)
en   Latvia

»  latvisce   ajetivo
en   Latvian, Lettish

»  latvisce   nom
en   Latvian, Lettish

Lau   nom
Un pais sin costa en Asia sude-este
(capital: Vientiane)
en   Laos

»  lau   ajetivo
en   Lao, Laotian (person, language)

»  lau   nom
en   Lao, Laotian (person, language)

laudano   nom
Un disolve de alcol e morfina, usada en la pasada per redui dole
en   laudanum (painkiller)

laurensio   nom   «Lr»
La elemento cimical con numero atomal 103, un metal radioativa
en   lawrencium (element)

lauro   nom
Un planta o arboreta con folias briliante verde
Lauraceae
en   laurel

»  lauro nobil   nom
Laurus nobilis
en   bay laurel

»  folia de lauro   nom
en   bay leaf

»  lauri   verbo transitiva
en   laureate (crown with laurel)

»  laurida   ajetivo
en   laureate

»  laurida   nom
en   laureate

lava   verbo transitiva
Limpi (un person o cosa) con acua e tipal sapon o deterjente
en   wash, launder

»  lava   nom
en   washing (action), ablution

»  lava de serebro   nom
en   brainwashing

»  lava interna   nom
en   lavage, washing out

»  lava la serebro   verbo
en   brainwash

»  lavador   nom
en   washing machine (clothes, dishes)

»  lavador de autos   nom
en   carwash (machine)

»  laveria   nom
en   laundry, laundromat

»  laveria de autos   nom
en   carwash (place)

»  lavor   nom
en   washer, launderer, washwoman, washerwoman

»  prelavada   ajetivo
en   prewashed, preshrunk

»  relava   verbo transitiva
en   rewash

lava   nom
Roca calda e fondeda cual eruta de un volcan o fesur, o la roca solida cual resulta cuando esta fri
en   lava (geology)

lavabo   nom
Un bol fisada, con fonte de acua e tubo de drena
en   sink, washbasin, washstand, washbasin, washbowl

lavanda   ajetivo
Con color pal violeta
en   lavender

»  lavanda   nom
Un arboreta perene e bonodorosa en familia de mentas, usada per parfum
Lavandula
en   lavender

lavaoio   nom
Un disolve usada per limpi la oios
en   eyewash

lavaplato   nom, composada (verbo+nom)
Un macina o person cual lava platos
en   dishwasher

lavaveste   nom, composada (verbo+nom)
Un macina o person cual lava vestes o otra stofas
en   washing machine; washerman, washerwoman

laxe   ajetivo
No firma fisada; no tensada; (un veste) spasiosa e no streta
en   loose, slack, baggy, lax, sloppy

»  laxi   verbo nontransitiva
en   loosen

»  laxi   verbo transitiva
en   loosen

»  laxia   nom
en   looseness, slackness, bagginess; slack, give (in a rope); play, backlash (in a mechanism)

»  laxinte   nom
Un medica per stimula o fasili la vacui de la intestines
en   laxative

le   nom
Un garlanda polinesian de flores
en   lei (garland)

leca   verbo transitiva
Pasa sua lingua sur (alga cosa), tipal per proba, moli o limpi lo; (un flama, onda o venta) move en modo simil
en   lick, lap

»  leca   nom
en   lick

lecabota   nom, composada (verbo+nom)
(Nonformal) un adulor
en   (colloquial) bootlicker (sycophant)

lecaculo   nom, composada (verbo+nom)
(Nonformal) un adulor
en   (colloquial) asskisser/arselicker, kiss-ass (sycophant)

lederhose   nom
Un pantala de cuoro de stilo tradisional alpan, con bretelas con forma de H
en   lederhosen

lega   verbo transitiva
Lasa (sua imobila personal o sua corpo) a un person o otra beneficada par un atesta final
en   bequeath

»  lega   nom
en   legacy, bequest

lega   nom
Un mesura antica de distantia, tipal sirca tre milias
en   league (unit of length)

lege   nom
Un sistem de regulas reconoseda par un nasion o comunia per regula la atas de sua membros, e cual permete la asinia de multas o punis; cada de la regulas en un tal sistem; un declara, deduida de oserva, ce un fenomeno natural o siensal aveni sempre en alga situa spesifada; un corpo de comandas divin, espresada en un testo relijiosa
en   law, statute

»  legal   ajetivo
Pertinente a la lege; elejeda o asiniada par la lege; permeteda par la lege
en   legal, valid, lawful, legitimate; forensic

»  deslegali   verbo nontransitiva
en   illegalize/illegalise, delegitimize/delegitimise, outlaw

»  deslegali   verbo transitiva
en   illegalize/illegalise, delegitimize/delegitimise, outlaw

»  legali   verbo nontransitiva
en   legalize/legalise, legitimize/legitimise

»  legali   verbo transitiva
en   legalize/legalise, legitimize/legitimise

»  legali   nom
en   legalization/legalisation, legitimization/legitimisation

»  legalia   nom
en   legality, legitimacy

»  legalisme   nom
en   legalism

»  legaliste   ajetivo
en   legalistic

»  legaliste   nom
en   legalist

»  legeria   nom
en   legislature, legislative branch (of government)

»  legeria con du salones   nom
en   bicameral legislature

»  legeria con un salon   nom
en   unicameral legislature

»  legeria provinsal   nom
en   statehouse

»  legeria statal   nom
en   statehouse

»  legi   verbo transitiva
en   legislate

»  legi   nom
en   legislation

»  leginte   ajetivo
en   legislative

»  legiste   nom
en   legist, jurist
fr   legiste, juriste

»  legor   nom
en   legislator, lawmaker

»  nonlegal   ajetivo
en   illegal, illicit, unlawful, illegitimate, invalid

»  nonlegalia   nom
en   illegality, illegitimacy

»  par lege   ajetivo
en   by law; de jure, by right

»  sin lege   ajetivo
en   lawless

legum   nom
Cualce planta en familia de piso; la seme o otra parte comable de un de esta plantas
Fabaceae
en   legume

leje   verbo transitiva
Regarda, comprende e cisa vosi (cosas scriveda o primida) par interprete la simboles usada per composa los; vosi
en   read, peruse

»  leje   nom
en   reading (action, interpretation, measurement)

»  leje de labios   nom
en   lip-reading

»  leje rapida   verbo transitiva
en   skim

»  lejable   ajetivo
en   readable, legible

»  lejablia   nom
en   readability, legibility

»  lejador   nom
en   reader, reading device

»  lejor   nom
en   reader

»  maleje   verbo transitiva
en   misread

»  maleje   nom
en   misreading

»  nonlejable   nom
en   unreadable, illegible

»  nonlejablia   nom
en   unreadableness, illegibility

»  releje   verbo transitiva
en   re-read; proofread

lejecarta   nom, composada (verbo+nom)
Un aparato cual leje datos de un media cartin
en   card reader

lejedisco   nom
Un aparato par cual un computador asede la contenida de un disco
en   disk drive

lejemente   nom, composada (verbo+nom)
Un person ci pare capas de sabe la pensas de un otra
en   mind reader, mentalist

lejenda   nom
Un nara tradisional, videda como istorial ma tipal no autenticida
en   legend

»  lejendal   ajetivo
en   legendary

lejera   ajetivo
Con poca o no pesa; no pesosa; fasil levada; de cuantia o intensia basa
en   light, lightweight, weightless

»  lejeri   verbo nontransitiva
en   lighten, become lighter

»  lejeri   verbo transitiva
en   alleviate, relieve, soothe, mitigate

»  lejeri   nom
en   relief

»  lejeria   nom
en   lightness

»  lejeria completa   nom
en   weightlessness, zero gravity

»  tro lejera   ajetivo
en   underweight

lejion   nom
(En la armada roman antica) un unia de entre tre e ses mil soldatos; (en la armada franses) un unia xef composada de soldatos nonfranses
en   legion

»  lejionor   nom
en   legionnaire

lema   nom
Un teorem media en un demostra matematical o filosofial; un titulo indicante un tema; un parola definida en un disionario
en   lemma (mathematics, philosophy); headword (dictionary)

leming   nom
Un rodente peti en familia de campaniol, trovada en la tundra artica
Lemmini
en   lemming (rodent)

lemur   nom
Un primate arboral con beco puntida e coda longa, trovada en Madagasicara
Lemur
en   lemur (primate)

lenio   nom
La materia dur e fibrosa de la tronco e ramos de un arbor o arboreta; esta preparada per usa en construi
en   wood, timber, lumber

»  lenio de foco   nom
en   firewood

»  lenio dur   nom
en   hardwood

»  lenio esterna   nom
en   sapwood, alburnum

»  lenio flotante   nom
en   driftwood

»  lenio interna   nom
en   heartwood, duramen

»  lenio mol   nom
en   softwood

»  lenio presada   nom
en   particleboard, chipboard

»  lenio stratida   nom
en   plywood

»  de lenio   ajetivo
en   wooden, wood

»  lenial   ajetivo
en   wooden, wood

»  lenieria   nom
en   woodyard, timberyard

»  lenior   nom
en   woodcutter, lumberjack

»  leniosa   ajetivo
en   woody

lenta   ajetivo
No rapida
en   slow; lingering

»  lenta   nom
en   slowcoach, slowpoke, laggard, sluggard

»  lenti   verbo nontransitiva
en   slow, slow down, decelerate

»  lenti   verbo transitiva
en   slow, slow down, decelerate

»  lenti   nom
en   deceleration, slowdown

lente   nom
Un peso de vitro o otra materia transparente con lados curva per consentra o sperde lus, usada en telescopios, microscopios, cameras e oculos
en   lens

»  lente de angulo larga   nom
en   wide-angle lens

»  lente de grandi   nom
en   magnifier, magnifying glass

»  lente de ojeto   nom
en   object lens, objective lens

»  lente de regarda   nom
en   eyepiece, ocular lens

»  lente de zuma   nom
en   zoom lens

»  lente macro   ajetivo
en   closeup lens, macro lens

»  lente macro de zuma   nom
en   macro zoom lens

»  lenteta   nom
en   contact lens

»  lentin   ajetivo
en   lenslike, lens-shaped, lenticular

lentil   nom
Un planta en familia de legum, con semes lentin e comable; un seme de esta
Lens culinaris
en   lentil

»  lentil brun   nom
en   brown lentil

»  lentil roja   nom
en   red lentil

leon   nom
Un gato grande e pal brun, trovada en Africa e Barat norde-ueste
Panthera leo
en   lion

»  leon-de-mar   nom
Un otario abitante la costas de la Mar Pasifica, de cual la mas ave un crinera sur sua colo e spadas
Otariidae
en   sea lion

»  leon fema   nom
en   lioness

»  Leon   nom   «♌»
Un constela de la zodiaco
en   Leo (constellation)

»  Leon Peti   nom
Un constela en la sielo norde
en   Leo Minor (constellation)

»  leoneta   nom
en   lion cub

»  leoni   verbo nontransitiva
en   lionize/lionise

»  leoni   verbo transitiva
en   lionize/lionise

leopardo   nom
Un gato grande con pelo brun con manxas negra, trovada en la forestas de Africa e Asia sude
Panthera pardus
en   leopard

»  leopardeta   nom
en   leopard cub

lepidio   nom
Un creson savaje, tipal con folias con odor agu
Lepidium
en   peppercress, peppergrass, pepperwort

lepilemur   nom
Un primate arboral en familia de lemur, trovada en Madagasicara
Lepilemuridae
en   sportive lemur

lepre   nom
Un mamal simil a un coneo, con gamas e oreas longa
Lepus
en   hare

»  Lepre   nom
Un constela ecuatoral en la sielo sude
en   Lepus (constellation)

leprecan   nom
Un elfo peti e turbosa en fables eres
en   leprechaun

lepror   nom
Un can xasante cual trasa prima par vide
en   sighthound

»  lepror afgani   nom
en   Afghan hound

»  lepror engles   nom
en   greyhound

»  lepror eres   nom
en   Irish wolfhound

leprosa   ajetivo
Sufrinte de o pertinente a un maladia de la pel, membranas e nervos, causada par un bateria
en   leprous

»  leprosa   nom
en   leper

»  antileprosa   nom
Un medisin per combate leprosia
en   antileprotic

»  leprosia   nom
en   leprosy

lepton   nom
Un particula suatomal, como un eletron, muon o neutrino, cual no partisipa en la interata forte
en   lepton (particle)

lesbian   ajetivo
en   lesbian, sapphic

»  lesbian   nom
Un fem omosesal
en   lesbian

»  lesbianisme   nom
en   lesbianism

lesion   nom
Un area de un organo o texeda cual ia sufri un dana
en   lesion

»  lesion de arde   nom
en   burn (injury)

lesitina   nom
Un materia composada de fosfolipidos liada a colina, trovada en texedas animal, en jala de ovos e en alga plantas
en   lecithin (substance)

leson   nom
Un periodo de instrui e aprende; un parla instruinte
en   lesson, lecture

»  leson moral   nom
en   moral lesson, moral (of story)

»  leson privata   nom
en   tutorial, private lesson

»  dona un leson   verbo
en   give a lesson, give a lecture

»  lesonor   nom
en   lecturer

Lesoto   nom
Un pais sin costas ensircada par Sudafrica
(capital: Maseru)
en   Lesotho

»  lesoto   ajetivo
en   Lesothan

»  lesoto   nom
en   Lesothan

letarjia   nom
Sin enerjia e zelo; multe dormosa e nonativa
en   lethargy, sluggishness, torpor, torpidity, listlessness, languor

»  letarjiosa   ajetivo
en   lethargic, sluggish, listless, languorous

lete   nom
Un licuida blanca, plen de gras e protena, secreteda par mamales fema per nuri sua enfantes; esta licuida de boves, capras o oveas, bevida par umanas; (metafor) cualce licuida blanca e cremosa, como la jus de alga plantas
en   milk

»  lete bateda   nom
en   milkshake

»  lete densida   nom
en   condensed milk

»  lete de gal   nom
en   eggnog

»  lete de ris   nom
en   rice milk

»  dona lete   verbo
en   nurse, breastfeed

»  leteria   nom
en   dairy

»  leti   verbo transitiva
en   lactate

»  leti   nom
en   lactation

»  letin   ajetivo
en   milky

»  letor   nom
en   milkman

»  prende lete   verbo
en   nurse

»  prende lete de   verbo
en   milk (animal)

letera   nom
Un sinia cual representa un o plu de la sonas usada per parla; un de la simboles de un alfabeta; un comunica scriveda, tapeda o primida, tipal contenida en un envelopa e enviada par posta o mesajor
en   letter (alphabet, postal), epistle, missive

»  letera major   nom
en   uppercase letter, capital letter, majuscule

»  letera minor   nom
en   lowercase letter, small letter, minuscule

»  leteras major o minor   nom
en   case

»  leteral   ajetivo
en   literal

»  leteri   verbo transitiva
en   letter, do lettering

»  leteri con mano   nom
en   hand lettering

»  nonleteral   ajetivo
en   non-literal, figurative

leteratur   nom
Obras scriveda, tipal regardada como arte valuada; libros publicida sur un tema tecnical
en   literature

»  leteratur parlada   nom
en   oral literature

»  leteratural   ajetivo
en   literary

leto   nom
Un mobila o otra surfas usada per dormi o reposa, tipal un strutur con materas e covrentes
en   bed

»  leto ascondeda   nom
en   wall bed, murphy bed, trundle bed

»  leto castelin   nom
en   bunk bed

»  leto de acua   nom
en   waterbed

»  leto de maladia   nom
en   sickbed

»  leto de mori   nom
en   deathbed

»  leto de plumas   nom
en   featherbed

»  leto de sol   nom
en   sunbed

»  leto estragrande   nom
en   king-size bed

»  leto grande   nom
en   queen-size bed

»  leto per du   nom
en   double bed

»  leto per un   nom
en   single bed

»  leto pliable   nom
en   folding bed, cot

»  leto rolante   nom
en   wheeled bed, hospital bed

»  leteta   nom
en   cot, crib, cradle; small bed, berth, bunk

»  letos jemelo   nom
en   twin beds (two single beds)

»  ordina la leto   verbo
en   make the bed

letseburges   ajetivo
Pertinente a un lingua parlada par multe persones luxemburges
en   Luxemburgish, Luxembourgeois

»  letseburges   nom
en   Luxemburgish, Luxembourgeois

letuga   nom
Un planta cultivada en familia de margarita, con folias comable; esta folias usada en saladas
Lactuca
en   lettuce

»  letuga roman   nom
en   romaine lettuce, cos lettuce

leucemia   nom
Un maladia en cual la medula de osos e otra organos cual formi sangue produi tro multe leucosites nonmatur o nonormal
en   leukemia/leukaemia

leuco-   prefisa
Blanca
en   leuco-

leucoplasto   nom
Un selula sin color, trovada en selulas de plantas, usada per reteni amidon o olio
en   leucoplast (biology)

leucosite   nom
Un selula sin color cual sirculi en sangue e otra licuidas de la corpo e partisipa en combate maladias
en   leukocyte (blood cell)

lev   nom
La unia de mone en Balgaria
en   lev (currency)

leva   verbo nontransitiva
Move de un loca plu basa a un loca plu alta
en   rise, lift, levitate, get up, arise

»  leva   verbo transitiva
en   raise, lift, heft, hoist, levitate; hold up; raise, pose (problem, question); promote (in rank), exalt

»  leva   nom
en   rise, levitation; promotion, exaltation, uplift

»  leva de luna   nom
en   moonrise

»  leva de pesas   nom
en   weightlifting

»  leva de sol   nom
en   sunrise, dawn, daybreak

»  leva de spalas   nom
en   shrug

»  leva final   nom
en   proofing (bread)

»  leva sua regarda   verbo
en   look up

»  leva sua spalas   verbo
en   shrug

»  ante leva de sol   ajetivo
en   predawn

»  levada   ajetivo
en   leavened

»  levada natural   nom
en   sourdough
fr   pain au levain

»  levor   nom
en   lifter

»  levor de pesas   nom
en   weightlifter

»  releva   verbo nontransitiva
en   rise again

»  releva   verbo transitiva
en   re-raise, raise again

levacarga   nom, composada (verbo+nom)
Un veculo usada per leva cargas pesosa
en   lift truck, forklift truck, sideloader, stacker truck

Levante   nom
La rejion de Asia sude-ueste bordante la Mar Mediteraneo, tipal incluinte Suria, Lubnan, Israel, Filastin, Urdun e Cipros, e en alga casos ance Turcia e la penisola Sina
en   Levant (Mediterranean region)

»  Mar Levante   nom
La parte de la Mediteraneo este la plu prosima a la Levante
en   Levantine Sea

lever   nom
Un bara cual reposa sur un fulcro, usada per aida move cargas pesosa a un fini cuando on aplica presa a la otra fini
en   lever

»  lever de engrana   nom
en   gearstick, gearshift

»  leveri   verbo transitiva
en   lever, pry, prise

»  leveri   nom
en   leverage

leviatan   nom
Un monstro de mar, tipal en la Biblia
en   leviathan (Biblical sea monster)

lexem   nom
Un unia astrata fundal de un lingua, representante tota formas infletada de un parola
en   lexeme

lexicografia   nom
La arte e siensa de composa disionarios
en   lexicography

»  lexicografial   ajetivo
en   lexicographical

»  lexicografiste   nom
en   lexicographer

lexicolojia   nom
La studia de la formas, sinifias e conduis de parolas
en   lexicology

»  lexicolojial   ajetivo
en   lexicological

»  lexicolojiste   nom
en   lexicologist

lezardo   nom
Un retil ma no un serpente, tipal con corpo e coda longa e pel ru, scamosa o spinosa
Lacertilia, ma no serpentes
en   lizard

»  Lezardo   nom
Un constela de la sielo norde
en   Lacerta (constellation)

lfn   corti
Lingua Franca Nova
nb   Esta lingua ia es orijinal conoseda como "LFN", ma oji la spele "elefen" es prefereda.
en   Elefen, LFN

lia   verbo transitiva
Fisa (un person o cosa) con corda o banda a alga cosa; formi (un noda); crea un junta o relata entre (persones o cosas); junta (cosas) per transmete enerjia, informa, etc
en   tie, bind, strap, tether, moor; connect, link, plug in; liaise; associate (mentally)

»  lia   nom
Un ata de lia; un cosa liante; un bretela per teni un calsa o calseta
en   link, bond, connection, ligation, linkage; liaison; covenant; suspender (UK), garter (US); association (mental)

»  lia a tera   verbo
en   ground, earth (an electrical device)

»  lia con filo   nom
en   wired connection

»  lia la gamas de   verbo
en   bind the legs of, hobble, hogtie

»  lia la manos e pedes de   verbo
en   hogtie

»  lia sin filo   nom
en   wireless connection

»  lia tubal   nom
en   tubal ligation (medical)

»  deslia   verbo transitiva   (dise ‘deslía’)
en   untie, unbind, disconnect, unplug

»  desliada   ajetivo
en   untied, unbound

»  interlia   verbo transitiva
Lia (du cosas) con lunlotra
en   interconnect, interlink

»  interliada   ajetivo
en   interconnected, interlinked

»  liada   ajetivo
en   bound, tied

»  liador   nom
en   plug (electric)

»  liante   ajetivo
en   connecting, connective

»  liante   nom
en   ligature

»  nonliada   ajetivo
en   unconnected, disjointed

»  sulia   verbo transitiva
(Un satelite) transmete (datos) a la tera
en   downlink

»  sulia   nom
en   downlink

»  supralia   verbo transitiva
Transmete (datos) a un satelite o otra comunicador supra la tera
en   uplink

»  supralia   nom
en   uplink

»  verbo liante   nom
Un verbo nontransitiva cual es sempre acompaniada par un completinte ajetivin o nomin, como en `los es libros`, `acel pare riable`, `me senti felis`
en   linking verb, copula

liama   nom
Un mamal en familia de camel, usada per transporta cargas en la Andes e valuada per sua lana suave
Lama glama
en   llama (animal)

liana   nom
Un planta leniosa e trepante cual pende de arbores, tipal en forestas pluvosa tropical
en   liana (plant)

libela   nom
Un inseto rapida volante e xasante, con du duples de alas grande e transparente
Odonata
en   dragonfly, damselfly

Liberia   nom
Un pais a la costa de la Mar Atlantica en Africa ueste
(capital: Monrovia)
en   Liberia

»  liberian   ajetivo
en   Liberian

»  liberian   nom
en   Liberian

Libia   nom
Un pais en Africa norde en la deserto Sahara, con costa a la Mar Mediteraneo
(capital: Tripoli)
en   Libya

»  libi   ajetivo
en   Libyan

»  libi   nom
en   Libyan

libido   nom
La desira sesal
en   libido, sex drive, lust

»  libidal   ajetivo
en   libidinal

»  libidosa   ajetivo
en   libidinous, lustful, randy, horny

»  libidosa   nom
en   sexpot, voluptuary

»  sin libido   ajetivo
en   frigid

»  tro libidosa   ajetivo
en   oversexed

libra   nom
Un unia de pesa usada en alga paises, egal a 0,4536 kg
en   pound (weight)

libre   ajetivo
No controlada par un otra; capas de ata como on desira
en   free, at liberty; freelance

»  libralisme   nom
en   liberalism

»  libraliste   ajetivo
en   liberal, laissez-faire

»  libraliste   nom
en   liberal

»  libre con garantia   ajetivo
en   free on bail, out on bail

»  libri   verbo nontransitiva
en   free, liberate, release, emancipate, unleash, rid

»  libri   verbo transitiva
en   free, liberate, release, emancipate, unleash, rid

»  libri   nom
en   liberation, emancipation, release; quittance

»  libri con garantia   verbo transitiva
en   release on bail

»  libri de sclavia   nom
en   freedom from slavery, manumission

»  libria   nom
en   freedom, liberty, leeway

»  libria de jornalisme   nom
en   freedom of the press

»  libria limitada   nom
en   parole

»  libria oservada   nom
en   probation

»  libror   nom
en   liberator

»  nonlibre   ajetivo
en   unfree, restricted, captive

»  nonlibria   nom
en   captivity

libro   nom
Un obra scriveda o primida, composada de pajes colida o coseda a lunlotra a un lado e reliada
en   book

»  libro anial   nom
en   yearbook, annual

»  libro de aprende   nom
en   textbook

»  libro de cantas   nom
en   songbook

»  libro de consulta   nom
en   reference book

»  libro de contas   nom
en   ledger

»  libro de cuoro   nom
en   leather-bound book

»  libro de eserse   nom
en   exercise book, practice book

»  libro de fables   nom
en   story book

»  libro de fato   nom
en   non-fiction book

»  libro de imajina   nom
en   fiction book

»  libro de imnos   nom
en   hymn book, hymnal

»  libro de mapas   nom
en   atlas

»  libro de modeles   nom
en   copybook

»  libro de notas   nom
en   notebook

»  libro de pox   nom
en   pocketbook, small notebook

»  libro de preas   nom
en   prayer book, book of prayer

»  libro de resetas   nom
en   recipe book, cookbook

»  libro de scola   nom
en   schoolbook

»  libro de stratejia   nom
en   playbook

»  libro de viaja   nom
en   travel guide; travelog/travelogue

»  libro de xeces   nom
en   checkbook/chequebook

»  libro dur   nom
en   hardback, hardcover

»  libro enrolada   nom
en   scroll

»  libro mol   nom
en   paperback, softback

»  libro nonvendeda   nom
en   remaindered book, unsold book

»  libreria   nom
en   bookshop

»  libreta   nom
en   booklet, pamphlet, brochure; libretto

»  libreta de fosfores   nom
en   book of matches, matchbook

»  libron   nom
en   tome

libromanica   ajetivo
Un person ci ama libros e leje
en   book fanatic, bookworm

»  libromanica   nom
en   book fanatic, bookworm

licen   nom
Un planta simple e lenta cresente, tipal abitante sur rocas, mures e arbores
Ascomycota, Basidiomycota
en   lichen (plant)

liciris   nom
Un planta en familia de piso; un materia negra e bonodorinte, produida par vapori la jus de la radis de esta planta; un confeto saborida con esta
Glycyrrhiza glabra
en   licorice/liquorice

licopodio   nom
Un planta cual sembla mos, con talos raminte e folias nondivideda
Lycopodiaceae
en   clubmoss (plant)

licor   nom
Un bevida alcolosa forte e dulse, tipal bevida pos un come
en   liqueur
fr   liqueur

Lictenstain   nom
Un pais peti en la Alpes, entre Suiz e Osteraic
(capital: Vaduz)
en   Liechtenstein

»  lictenstaines   ajetivo
en   Liechtenstein

»  lictenstaines   nom
en   Liechtensteiner

licuida   ajetivo
Con un coere como acua o olio, libre corente ma con volum constante; (metafor) cualce cosa cual move libre
en   liquid (including assets), fluid

»  licuida   nom
en   liquid, fluid

»  licuida de coreti   nom
en   correction fluid, whiteout

»  licuidador   nom
en   liquidizer/liquidiser, blender

»  licuidi   verbo nontransitiva
en   liquefy, liquify, liquidize/liquidise; liquidate

»  licuidi   verbo transitiva
en   liquefy, liquify, liquidize/liquidise; liquidate

»  licuidi   nom
en   liquidation

»  licuidia   nom
en   liquidity

»  licuidor   nom
en   liquidator

Lidia   nom
Un rejion antica de Anatolia ueste, florinte en la sentenio 7 aec
en   Lydia

Lietuva   nom
Un pais a la costa sude-este de la Mar Baltica
(capital: Vilnius)
en   Lithuania

»  lietuvisce   ajetivo
en   Lithuanian

»  lietuvisce   nom
en   Lithuanian

ligamento   nom
Un banda corta de texeda dur, flexable e fibrosa cual junta du osos o cartilajes; un plia membranin cual suporta o manteni la loca de un organo
en   ligament, sinew

lignito   nom
Un carbon brun e mol, formida de torba natural compresada
en   lignite, brown coal

Liguria   nom
La parte de Italia norde-ueste cual estende longo la costa mediteranean de Toscana a la borda de Frans
en   Liguria

»  ligurian   ajetivo
en   Ligurian

»  ligurian   nom
en   Ligurian

»  Mar Liguria   nom
en   Ligurian Sea

ligustro   nom
Un arboreta en familia de olivo, con flores peti e blanca e bacas venenosa
Ligustrum
en   privet (plant)

lil   nom
Un planta cual crese de un bulbo, con flores grande e trompetin
Lilium
en   lily

»  lil-de-mar   nom
Un ecinodermato fisada, con corpo peti sur tronceta longa e sesionida, con brasos plumin per catura comedas
Bourgueticrinida
en   sea lily

»  lil de neva   nom
Galanthus
en   snowdrop

»  lil tigrin   nom
Lilium lancifolium
en   tiger lily

lila   ajetivo
Pal rosin violeta
en   lilac (color/colour)

»  lila   nom
Un arboreta en familia de olivo, con flores violeta, ros o blanca e bonodorosa
Syringa
en   lilac (plant)

lim   nom
Un arbor de la jenero Citrus; la fruta de esta
Citrus × aurantifolia, Citrus × latifollia
en   lime (tree, fruit)

»  limeta   nom
Citrus × limetta
en   sweet lime, sweet lemon, sweet limetta

»  limon   nom
Citrus × limon
en   lemon

»  limonin   ajetivo
en   lemony, lemonlike

»  limonosa   ajetivo
en   lemony

lima   nom
Un util con surfas ru, comun de aser, usada per lisa o formi un materia dur
en   file

»  lima de emeri   nom
en   emery board

»  lima de ungia   nom
en   nail file

»  limi   verbo transitiva
en   file (smoothe)

limasa   nom
Un molusco con pel durante, simil a caracoles ma sin conca
Gastropoda
en   slug

limbica   ajetivo
Pertinente a un sistem de nervos en la serebro cual es asosiada con instintos e emosias
en   limbic

limbo   nom
(En alga formas de cristianisme) la abita de la spiritos de enfantes nonbatizada o de bon persones ci ia mori ante la aveni de Cristo
en   limbo (religion)

limbo   nom
Un dansa de la Indias Ueste en cual on curvi a retro per pasa su un bara orizonal
en   limbo (dance)

Limburg   nom
Un provinse de Nederland e de Beljia
en   Limburg (Dutch or Belgian province)

»  limburgan   ajetivo
en   Limburgish, Limburgian

limeric   nom
Un poesia comica e tipal vulgar, con sinco linias rimante en la sistem AABBA, de cual sua du linias prima e la final es longa e la otras es corta, popularida par Edward Lear
en   limerick

limfa   nom
Un licuida sin color, conteninte selulas blanca de sangue, cual bani la texedas e drena tra la sistem limfal a la sistem sangual
en   lymph

»  limfal   ajetivo
en   lymphatic

limfo-   prefisa
Limfa
en   lympho- (lymph)

limfoblasto   nom
Un selula nonormal, semblante un limfosite grande, produida en cuantias grande en un forma de leucemia
en   lymphoblast (biology)

limfoide   ajetivo
Pertinente a la texedas cual produi limfosites e anticorpos, incluinte la nodas limfal, la timo, la tonsiles e la spleno
en   lymphoid

limfoma   nom
Un canser de la nodas limfal
en   lymphoma

»  limfoma de Hodgkin   nom   (dise ‘hodjcin’)
Un maladia de la texedas limfal, tipal remediable
en   Hodgkin’s lymphoma

limfopoiese   nom
La prosede de jenera limfosites
en   lymphopoiesis (biology)

limfosite   nom
Un forma de leucosite peti con un sola nucleo ronda
en   lymphocyte, white blood cell

»  limfosite B   nom
en   B-cell

»  limfosite NK   nom
en   natural killer cell

»  limfosite T   nom
en   T-cell

»  limfosital   ajetivo
en   lymphocytic

limita   verbo transitiva
No permete ce (un person o cosa) estende ultra un punto, nivel, cuantia o grandia spesifada
en   limit, delimit; cap (price)

»  limita   nom
en   limit, boundary, bound, frontier, delimitation, threshold, cut-off, limitation

»  limita de tempo   nom
en   deadline, time limit

»  limita masima   nom
en   upper limit, cap, ceiling

»  limitada   ajetivo
en   limited, finite, bounded

»  limital   ajetivo
en   borderline (just on the edge, personality disorder)

»  limitas   nom, plural
en   limits, bounds, extent, ambit, scope

»  nonlimitada   ajetivo
en   unlimited, infinite, boundless, unbounded, countless, innumerable

»  pone un limita   verbo
en   impose a limit, draw the line

»  sin limita   ajetivo
en   unlimited, limitless, infinite, boundless, unbounded, countless, innumerable

limonada   nom
Un bevida preparada de jus de limon, acua e zucar
en   lemonade

limpa   ajetivo
Sin susia o manxas; lavada; con bon ijenia; sin contaminantes
en   clean

»  limpi   verbo nontransitiva
en   become clean, clean up

»  limpi   verbo transitiva
en   clean, clean up, wipe; mop; sweep (chimney)

»  limpi etnical   nom
en   ethnic cleansing

»  limpia   nom
en   cleanliness

»  limpida   ajetivo
en   cleaned

»  limpor   nom
en   cleaner (person), scrubwoman, charwoman, charlady

»  limpor de sala   nom
en   chambermaid

»  nonlimpa   ajetivo
en   unclean

limpibota   nom, composada (verbo+nom)
Un person empleada per brilia sapatos e botas
en   bootblack, boots

limusin   nom
Un auto grande e lusosa, spesial con gidor profesal
en   limousine, limo
fr   limousine

lince   nom
Un gato savaje con pelo jalin brun, coda corta e oreas con mexa
Lynx
en   lynx

»  Lince   nom
Un constela en la sielo norde
en   Lynx (constellation)

»  lince rojin   nom
Lynx rufus
en   bobcat

lineta   nom
Un pinson brun e gris con fronte e peto rojin
Linaria
en   linnet, twite (bird)

linga   nom
(En induisme) un simbol de enerjia divin, tipal en la forma de un falo, adorada como un simbol de Xiva
en   linga, lingam (Hinduism)

lingua   nom
La organo musculosa en la boca de un mamal, usada per proba, leca, engoli e (en umanas) parla; la organo corespondente en otra vertebratos; la organo corespondente en insetos; la metodo de comunica umana, parlada o scriveda, composada de la usa de parolas en un modo struturida e costumal
en   tongue; language; speech (ability)

»  lingua aidante   nom
en   auxiliary language

»  lingua construida   nom
en   constructed language, conlang, artificial language

»  lingua de asembla   nom
en   assembly language

»  lingua de programi   nom
en   programming language

»  lingua de sinia   nom
en   sign language
eo   gestlingvo, signolingvo

»  lingua desiniada   nom
en   planned language, artificial language

»  lingua franca nova   nom
en   Lingua Franca Nova

»  interlingua   nom
en   international language; Interlingua

»  lingual   ajetivo
en   lingual (of the tongue); linguistic (of language)

»  linguiste   nom
en   linguist

»  propre lingua   nom
en   native language, native tongue, mother tongue

linguaje   nom
La stilo de vocabulo e frases elejeda per espresa en parla o scrive
en   language (style), wording

linguine   nom
Pasta con forma de bandas streta
en   linguine (food)

linguistica   nom
La siensa de linguas e sua strutur, incluinte la studia de morfolojia, sintatica, fonetica e semantica
en   linguistics

»  linguistica computal   nom
en   computational linguistics

»  interlinguistica   nom
La studia de aspetas diversa de comunica lingual entre persones ci no pote comprende lunlotra en sua propre linguas
en   interlinguistics
eo   interlingvistiko

linia   nom
Un marca o banda longa e streta; (en matematica) un estende continuante de longia sin largia; un cuantia de persones o cosas en un tal forma
en   line, row; rank (chess)

»  duilinia   nom
Un dui de un linia de poesia, segueda par un pausa corta
en   hemistich

»  linia de arbores   nom
en   treeline

»  linia de comandas   nom
en   command line (software)

»  linia de familia   nom
en   lineage, family line, line of descent, bloodline, pedigree

»  linia de neva   nom
en   snowline

»  linia de sangue   nom
en   bloodline, pedigree

»  linia direta   nom
en   direct line, hotline

»  linia media   nom
en   midline

»  linia orizonal   nom
en   horizontal line, dash

»  en linia reta   averbo
en   in a straight line, in a beeline, as the crow flies

»  lini   verbo transitiva
en   line (mark lines on)

»  linial   ajetivo
en   linear, lineal

»  linida   ajetivo
en   lined (marked with lines)

»  nonlinial   ajetivo
en   non-linear

»  sulini   verbo transitiva
en   underline, underscore

»  sulini   nom
en   underlining

»  sulinia   nom
en   underline, underscore (character)

»  vade en linia reta a   verbo
en   make a beeline for

linioio   nom
Un macia aplicada como un linia sirca la oios afin los pare plu grande o notable
en   eyeliner

lino   nom
Un planta con flores blu, cultivada per sua semes e per la fibre de stofa cual on prepara de sua troncetas; un seme de esta, usada per fabrica olio o pasta
Linum usitatissimum
en   flax, linseed (plant)

»  linosa   ajetivo
en   treated with linseed

»  olio de lino   nom
en   linseed oil

»  pasta de lino   nom
en   putty

»  seme de lino   nom
en   linseed

»  stofa de lino   nom
en   linen

linolio   nom
Un materia composada de un fondo de lona, stratida con un prepara de olio de lino e suber polvida, usada per covre la solo en construidas
en   linoleum, lino

lintel   nom
Un suporta orizonal de lenio, petra, beton o aser supra un porte o fenetra
en   lintel, transom

linxa   verbo transitiva
(Un manada de persones) mata (algun), tipal par pende, per un ofende alegada, con o sin litiga
en   lynch

»  linxa   nom
en   lynching

Lion   nom
Un rena antica e provinse presente de Espania norde
en   León (Spanish region)

»  liones   ajetivo
en   Leonese

»  liones   nom
en   Leonese

lipido   ajetivo
Parteninte a un clase de composadas organica cual es asidas grasosa o sua derivadas, e es nondisolvable en acua ma disolvable en solventes organica, incluinte multe olios natural, siras e steroides
en   lipid (chemistry)

»  lipido   nom
en   lipid

lipo-   prefisa
Gras
en   lipo- (fat)

lipoprotena   nom
Cualce de un grupo de protenas disolvable cual combina con lipidos en la sangue e transporta los
en   lipoprotein

liposuca   nom
Un tecnica en sirurjia cosmetica per estrae gras de su la pel par suca
en   liposuction

lira   nom
Un arpa peti con forma de U, usada en Elas antica e Africa este moderna
en   lyre

»  Lira   nom
Un constela peti
en   Lyra (constellation)

lira   nom
La unia de mone en Turcia, e istorial en Italia
en   lira (currency)

lirica   ajetivo
(Leteratur, arte o musica) espresante la emosias de la creor en modo bela e imajinosa
en   lyrical, lyric

liriodendro   nom
Un arbor de America Norde, con folias grande e lobosa e flores grande con forma de tulpas
Liriodendron
en   tulip tree

liron   nom
Un rodente musin, con coda pelosa o brosin, de cual alga spesies es notada per sua invernis estendeda
Gliridae
en   dormouse

lisa   ajetivo
Con surfas o coere sin bultos o indentes persepable
en   smooth, sleek; crisp (cloth, paper)

»  lisador   nom
en   smoother, sander

»  lisador de banda   nom
en   belt sander

»  lisi   verbo nontransitiva
en   smoothe, streamline; sand (wood)

»  lisi   verbo transitiva
en   smoothe, streamline; sand (wood)

»  lisia   nom
en   smoothness

Lisboa   nom
La site capital de Portugal
en   Lisbon

lisca   verbo nontransitiva
Move nonimpedida longo un surfas lisa
en   slide, slip, glide, coast, swipe

»  lisca   verbo transitiva
en   slide, slip, push

»  lisca   nom
en   slip, glide

»  lisca de tera   nom
en   landslide, landslip

»  lisca e pone   verbo
en   drag and drop (software)

»  lisca sur acua   verbo
en   aquaplane

»  liscable   ajetivo
en   slidable, sliding

»  liscador   nom
en   slider; hovercraft

»  liscante   nom
en   glissando

»  lisceta   verbo nontransitiva
en   glitch, goof, slip, slip up

»  lisceta   nom
en   glitch, goof, booboo, boob, slip, slip-up

»  liscosa   ajetivo
(Un cosa) tan lisa, moiada o melmosa ce on no pote fasil teni lo o sta sur lo
en   slippery, slick

»  liscosia   nom
en   slipperiness

»  nonliscosa   ajetivo
en   non-slip

liscasapato   nom, composada (verbo+nom)
en   shoehorn

liscor   nom
Un marsupio peti australasian, con pel entre sua gamas anterior e posterior cual el usa per vola de arbor a arbor
Petaurus
en   flying possum, flying phalanger, glider (marsupial)

lisensa   verbo transitiva
Dona un permete formal o ofisial a (algun) per posese, usa o fa alga cosa
en   license

»  lisensa   nom
en   license/licence, permit

»  lisensa de primi   nom
en   imprimatur

»  lisensada   ajetivo
en   licensed

»  nonlisensada   ajetivo
en   unlicensed

liseo   nom
Un scola per adolesentes con edas cual depende de la nasion, ma tipal completida a 18 anios
en   high school, secondary school, lycee, lyceum

lisosoma   nom
Un organeta en la sitoplasma de selulas eucariotal cual conteni enzimas degradante encluida par un membrana
en   lysosome (biology)

lista   verbo transitiva
Scrive o dise (un cuantia de nomes o otra cosas) en serie
en   list, itemize/itemise

»  lista   nom
en   list

»  lista cadente   nom
en   drop-down list

»  lista de benes   nom
en   inventory

»  lista de contenidas   nom
en   packing slip, (ship’s) manifest

»  lista de desiradas   nom
en   wish list

»  lista de eras   nom
en   errata

»  lista de medisines   nom
en   formulary

»  lista de salarios   nom
en   payroll

»  lista de sertis   nom
en   checklist

»  lista negra   nom
en   blacklist

»  nonlistada   ajetivo
en   unlisted

»  pone en lista negra   verbo
en   blacklist

litania   nom
Un serie de preas o suplicas
en   litany

litiga   verbo transitiva
Prende (un alega o disputa) a un corte legal; comensa un prosede legal contra (algun)
en   litigate, prosecute, sue, take to court, arraign, try, proceed against

»  litiga   nom
da   retsag
en   litigation, suit, lawsuit, trial, prosecution, case (law)
eo   proceso
es   proceso (juicio)
pt   judicial, processo judicial, processo legal, ação

»  litiga falsa   nom
en   mock trial

»  litiga nonconcluinte   nom
en   mistrial

»  litigable   ajetivo
en   accountable, responsible, actionable

»  litigor   nom
en   litigator, litigant

»  litigor de stato   nom
en   state attorney (civil law)
fr   procureur (droit civil)

»  litigosa   ajetivo
en   litigious

»  prelitigal   ajetivo
en   pretrial

litio   nom   «Li»
La elemento cimical con numero atomal 3, un metal mol e arjentin blanca, usada per trata mania
en   lithium

lito-   prefisa
Petra
en   litho- (stone)

litografia   nom
La prosede de primi de un surfas plana, tratada per repulsa inca estra do on intende
en   lithography

»  litografi   verbo transitiva
en   lithograph

»  litografi   nom
en   lithograph

litolojia   nom
La studia de la cualias fisical de rocas
en   lithology

litorina   nom
Un caracol de mar, peti e comable
Littorina
en   winkle, periwinkle (mollusk/mollusc)

litosfera   nom
La parte rijida e esterna de la Tera o otra planetas
en   lithosphere, mantle (geology)

litote   nom
Un espresa ironial cual presenta la negativa de la oposada, como `no mal` per dise `bon`
en   litotes (rhetoric)

litotrof   ajetivo
Atraeda a minerales per nuri
en   lithotrophic (biology)

»  litotrof   nom
en   lithotroph

»  litotrofia   nom
en   lithotrophia

litre   nom
Un unia metral de volum, egal a 1000 sentimetres cubida
en   liter/litre (unit of capacity)

»  cilolitre   nom
en   kiloliter/kilolitre

»  decalitre   nom
en   decaliter/decalitre

»  desilitre   nom
en   deciliter/decilitre

»  ectolitre   nom
en   hectoliter/hectolitre

»  mililitre   nom
en   milliliter/millilitre

»  sentilitre   nom
en   centiliter/centilitre

liturjia   nom
Un ordina per gida la adora relijiosa publica, tipal en cristianisme
en   liturgy

»  liturjial   ajetivo
en   liturgical

litvac   ajetivo
Pertinente a iudis con asendentes en la Duxia Grande de Lietuva
en   Litvak

»  litvac   nom
en   Litvak, Lithuanian Jew

litxi   nom
Un arbor xines; la fruta peti e ronda de esta
Litchi chinensis
en   lychee (tree, fruit)

livermorio   nom   «Lv»
La elemento cimical con numero atomal 116
en   livermorium (element)

lixivia   verbo nontransitiva
(Materia) sorti de un solida par disolve en un licuida
en   leach (drain)

»  lixivia   verbo transitiva
en   leach (drain)

»  lixivia   nom
en   leaching

»  lixiviada   nom
en   leachate

lo   pronom
Representante un cosa o situa; ance usada como un sujeto pupetin cuando la sujeto vera es la clima o ambiente jeneral, o apare plu tarda en la frase como un proposa suordinada
en   it

»  lo cual   espresa
‹ lo cual resta parteni a tu; me va esplica lo cual me crede ›
en   that which, what

lobe   nom
Un parte cuasi ronda e plata de alga cosa, tipal un de un duple juntada o separada par un fesur; cada de la du partes de la serebro o serebreta
en   lobe

»  lobe de orea   nom
en   earlobe

»  lobosa   ajetivo
en   lobed

lobotomia   nom
Un talia sirurjial de la lobe fronte de la serebro, istorial usada per trata alga maladias mental
en   lobotomy

loca   verbo transitiva
Pone (un person o cosa) en un area, ordina, situa o contesto spesifada
en   locate, place, site, position

»  loca   nom
en   place, location, position, spot, site, locale

»  loca bela   nom
en   beauty spot (place with beautiful scenery)

»  loca de nase   nom
en   birthplace

»  loca de note   nom
en   nightclub, night spot

»  loca de orienta   nom
en   landmark (navigation)

»  loca misera   nom
en   wretched place, hellhole, dump

»  loca ueb   nom
en   website

»  en no loca   averbo
en   nowhere

»  en no otra loca   averbo
en   nowhere else

»  en un otra loca   averbo
en   somewhere else

»  desloca   verbo transitiva
en   dislocate, displace, offset, shift

»  desloca   nom
en   dislocation, displacement, offset, shift

»  desloca blu   nom
en   blue shift

»  desloca de vocales   nom
en   vowel shift

»  desloca roja   nom
en   red shift

»  deslocada   ajetivo
en   dislocated, displaced, askew, awry

»  en loca de   preposada
en   instead of, in place of, rather than

»  en loca   averbo
en   instead

»  local   ajetivo
en   local

»  locali   verbo nontransitiva
en   localize

»  locali   verbo transitiva
en   trace, track, pinpoint

»  locali   nom
en   localization/localisation

»  localisme   nom
en   localism, parochialism

»  popla local   nom
en   local people, local population, locals

»  reloca   verbo transitiva
en   move, relocate; translate (geometry)

»  reloca   nom
en   move, relocation; translation (geometry)

»  reloca se   verbo
en   relocate, move house

»  relocali   verbo transitiva
en   relocalize/relocalise, resettle

locativa   ajetivo
en   locative (grammar)

»  locativa   nom
Un caso gramatical cual indica presentia a un loca
en   locative (grammar)

locomotiva   nom
Un veculo propulsada cual move sur reles, usada per tira trenes
en   locomotive, engine

»  locomotiva de vapor   nom
en   steam locomotive

»  locomotivor   nom
en   engine driver, train engineer

locusta   nom
Un inseto grande de la tropicos, con la capasia forte de vola
Caelifera
en   locust, grasshopper

»  locusta solitar   nom
en   grasshopper (when not swarming)

»  locusta xamante   nom
Acridoidea
en   locust

loda   verbo transitiva
Espresa amira o aproba de; espresa bon desiras a (un person) pos un aveni spesial; espresa respeta e grasia a (un dio o diva)
en   praise, laud, glorify, exalt, commend, extol, eulogize/eulogise; compliment, congratulate, flatter

»  loda   nom
en   praise, kudos, compliment, congratulation, glory, exaltation, eulogy, panegyric, encomium, citation, commendation

»  loda duple   verbo transitiva
en   praise twice, give two thumbs up to

»  loda falsa   nom
en   false praise, hype, puffery

»  loda zelosa   verbo
en   praise enthusiastically, rave about

»  con loda masima   averbo
en   with the highest praise, summa cum laude

»  lodable   ajetivo
en   laudable, praiseworthy, commendable

»  lodante   ajetivo
en   praising, flattering

»  lodas   esclama
en   congratulations, my compliments

»  nonlodada   ajetivo
en   unpraised, unsung

»  nonlodante   ajetivo
en   unflattering

loden   nom
Un stofa spesa e secur contra acua, tipal verde oscur
en   loden (fabric)

loes   nom
Un tera laxe compatida, orijinal deponeda par la venta, tipal regardada como la tera la plu bon per cultiva
en   loess (soil)

lofio   nom
Un pex pexorin cual abita la fondos de mares
Lophius
en   monkfish

lofofora   nom
Un strutur coronin con tentaculos de silios, sirca la boca de alga animales de mar peti
en   lophophore (biology)

lofotrocozon   nom
Un membro de un suprafilo cual inclui braciopodos, moluscos e anelidos
en   lophotrochozoon (pl. lophotrochozoa) (organism)

logaritmo   nom
Un cuantia representante la potia a cual on debe leva un numero fisada per produi un numero spesifada
en   logarithm

»  logaritmal   ajetivo
en   logarithmic

logo   nom
Un simbol o otra desinia adotada par un organiza per marca sua produidas, uniformas, veculos, etc
en   logo, emblem

logo-   prefisa
Parolas
en   logo- (words)

logofilia   nom
La ama de parolas
en   logophilia, love of words

»  logofilica   ajetivo
en   logophilic, word-loving

»  logofilica   nom
en   logophile, lover of words

Logudoro   nom
Un rena antica e rejion moderna en Sardinia norde-sentral
en   Logudoro (Sardinian region)

»  logudores   ajetivo
en   Logudorese (person, language)

»  logudores   nom
en   Logudorese (person, language)

lojia   nom
Un galeria o sala con un o plu lados abrida, tipal a la jardin; un area privata de un teatro o simil, reservada per un grupo de persones
en   loggia, veranda; box (theater/theatre)

»  lojia de acusada   nom
en   dock (in court)
fr   banc des accusés

»  lojia de atestor   nom
en   witness stand, witness box

»  lojia de juria   nom
en   jury box

lojica   nom
Un modo de razona cual segue prinsipes sever de validia; un sistem de prinsipes simil a aritmetica, usada per calcula con bitios en computadores
en   logic

»  es lojical   verbo
en   make sense

»  lojical   ajetivo
en   logical; Boolean

»  lojicalia   nom
en   logicality

»  nonlojical   ajetivo
en   illogical

»  nonlojicalia   nom
en   illogicality

lojistica   nom
La coordina detaliosa de un prosede complicada cual envolve multe persones, complesos o furnis
en   logistics

»  lojistical   ajetivo
en   logistical

lolio   nom
Un segal eurasian
Lolium
en   ryegrass, darnel

lom   nom
Un tera fertil de arjila e arena con umo
en   loam (soil)

»  lomosa   ajetivo
en   loamy

Lombardia   nom
Un rejion de Italia norde-sentral, entre la Alpes e la Rio Po
en   Lombardy (Italian region)

»  lombard   ajetivo
en   Lombard

»  lombard   nom
en   Lombard

lombo   nom
La parte de la corpo a ambos lados de la spina dorsal, entre la costelas la plu basa e la osos de anca
en   loin, loins, lower back

»  lombal   ajetivo
en   lumbar

lomen   nom
Un plato xines con talietas de trigo e vejetales
en   lo mein (food)

lona   nom
Un stofa forte, bruta e nonblancida, fabricada de canaba, lino, coton o simil, usada per produi velas, tendas e surfases per depinta con pinta de olio
en   canvas, sailcloth

»  lona catranida   nom
en   tarpaulin, tarp

»  lona de polietilen   nom
en   polythene tarpaulin, polytarp

»  de lona   ajetivo
en   canvas

longa   ajetivo
Con estende grande en spasio o tempo
en   long

»  longa   averbo
en   long, for a long time, for a long way

»  como longa   espresa
en   how long

»  longi   verbo nontransitiva
en   lengthen, elongate, prolong, protract

»  longi   verbo transitiva
en   lengthen, elongate, prolong, protract

»  longi   nom
en   elongation, prolongation

»  longia   nom
en   length, duration

»  longia de onda   nom
en   wavelength

»  par longia   nom
en   lengthwise, lengthways

»  Isola Longa   nom
Un isola a la costa de York Nova, conteninte un parte de la Site York Nova
en   Long Island

longo   preposada
1   Movente o estendente en un dirije constante sur o paralel a.   (Leje plu…)
‹ la folias flota longo la rio; un arania rampe longo mea gama ›
en   along, up, down (following or in parallel with)
eo   laŭ, laŭlonge de
2   En la opina de; como diseda par
‹ longo la predise, doman va es an plu calda ›
en   according to

»  a longo   averbo
en   along

lonjitude   nom
La distantia angulo de un loca, espresada en grados e minutos a este o ueste de la meridiano de Greenwich
en   longitude

»  lonjitude de sielo   nom
La distantia angulo de un ojeto sielal, espresada en grados e minutos a ueste de la meridiano normal
en   right ascension

»  lonjitudal   ajetivo
en   longitudinal

lonxura   nom
Un avia de la tropicos de la mundo vea
Lonchura
en   mannikin (bird)

lori   nom
Un papagaio peti de Australasia e Asia sude-ueste, con un lingua con mexa per come netar e polen
Loriinae
en   lory, lorikeet (bird)

loris   nom
Un primate peti e noturna, con coda corta o mancante, ci move lenta tra la foresta densa de Asia sude
Lorisinae
en   loris (primate)

lorisifero   nom
Un membro de un filo de animales de mar multe peti, tipal abitante en deponeda
Loricifera
en   loricifer (organism)

los   pronom
Representante du o plu persones o cosas
en   they; them

»  los ci   espresa
‹ los ci osa gania ›
en   they who

losa   nom
Un seramica composada de arjila e coceda a un state porosa, cual on pote vernisi per securi lo contra acua
en   earthenware

»  de losa   ajetivo
en   earthenware

losion   nom
Un licuida densa e lisa, desiniada per es aplicada a la pel per razonas medical o cosmetica
en   lotion

»  losion de rasa   nom
en   aftershave

loto   nom
Un jua en cual juores compra biletas numerida e el ci ave un numero acaso elejeda reseta un premio; un jua en cual numeros acaso es clamada e juores marca estas a cartas per completi linias
en   lotto, lottery; bingo, keno

Louisiana   nom   (dise ‘luiziana’)
Un stato en la SUA sude-sentral, a la costa de la Mar Mexico
en   Louisiana (US state)

lsd   nom
Un composada cristal, usada como un droga forte alusinojen
en   LSD (drug)

lua   verbo transitiva
Paia a algun per la usa de (un imobila, propria, auto, etc)
en   rent, hire, lease, let

»  lua   nom
en   rental, hiring, leasing

»  luable   ajetivo
en   rentable, rental, to let

»  luor   nom
en   renter, tenant, lodger

»  ofre per lua   verbo
en   rent out, hire out

»  sulua   verbo transitiva
en   sublease, sublet

luau   nom
Un festa o selebra hawaian, tipal con divertis
en   luau (Hawaiian feast)

Lubnan   nom
Un pais en Asia sude-ueste, con costa a la Mar Mediteraneo
(capital: Beirut)
en   Lebanon

»  lubnani   ajetivo
en   Lebanese

»  lubnani   nom
en   Lebanese

lubrica   verbo transitiva
Aplica un materia como olio o gras a (un motor o otra aparato) per minimi frica e permete ce lo move lisa
en   lubricate, lube

»  lubrica   nom
en   lubrication

»  lubricante   ajetivo
en   lubricating

»  lubricante   nom
en   lubricant, lube

lucarna   nom
Un fenetra cual protende de un teto inclinada
en   dormer (window)

lufa   nom
Un planta tropical en familia de zuca; un ojeto fibrosa, tipal silindre, usada per lava, orijinal preparada de la fruta de esta planta
Luffa
en   luffa, loofah (plant, sponge)

luje   nom
Un treneta lejera usada en concursos
en   luge (toboggan)

»  luji   verbo transitiva
en   luge

lumbago   nom
Dole de lombo
en   lumbago (medical)

lumen   nom
Un unia internasional de lumina
en   lumen (unit of light)

lumina   verbo transitiva
Furni lus a; fa ce (alga cosa) deveni plu lusosa; (metafor) dona sajia a
en   illuminate, light, enlighten, brighten, highlight

»  lumina   nom
en   illumination (action, result), highlight; enlightenment

»  lumina fondal   nom
en   backlight, backlighting

»  Lumina   nom
en   Enlightenment

»  lumina ultravioleta   nom
en   black light, blacklight

»  luminada   ajetivo
en   illuminated, lit

»  luminada par luna   ajetivo
en   moonlit

»  luminada par sol   ajetivo
en   sunlit

»  Luminadas   nom, plural
en   Illuminati

»  luminosa   ajetivo
en   luminous, lucid

»  nonluminada   ajetivo
en   unilluminated; unenlightened, benighted

luna   nom
La satelite natural de la Tera, vidable par la lus refletada de la Sol; un satelite natural de un otra planeta
nb   "Luna" ave un letera major en contestos astronomial, ma no cuando lo refere a un satelite de un otra planeta, o a un fase de nosa satelite.
en   moon

»  luna de miel   nom
en   honeymoon

»  luna oscur   nom
en   new moon

»  luna plen   nom
en   full moon

»  lunal   ajetivo
en   lunar

»  luneta   nom
en   small moon, natural satellite

»  sulunan   ajetivo
en   sublunar (astronomy)

lundi   nom
La dia entre soldi e martedi en cada semana
en   Monday
eo   lundo
fr   lundi

lunlotra   pronom
Mutua; la un (a, con, sur, etc) la otra(s)
‹ la gatos regarda lunlotra; la tre frates xuxa a lunlotra; la calculos en la caxa clica contra lunlotra ›
en   each other, one another
eo   unu la alia(j)n, sin reciproke
fr   se, se ... l’un l’autre, se ... mutuellement

»  con lunlotra   averbo
en   with each other, together

»  pos lunlotra   averbo
en   one after another, one by one

lupa   nom
Un lente cual produi un imaje grandida, tipal en un montur con manico o direta tenida par un oio
en   magnifying glass, magnifier, loupe

lupin   nom
Un planta en familia de piso, con spigas alta de flores colorosa
Lupinus
en   lupin (plant)

lupo   nom
Un carnivor savaje en familia de can
Canis lupus
en   wolf

»  Lupo   nom
Un constela en la sielo sude
en   Lupus (constellation)

lupulo   nom
Un planta trepante, cultivada per sua flores cono, usada per produi bir
Humulus lupulus
en   hop (plant)

lupus   nom
Un de alga maladias marcada par inflama de la pel
en   lupus (medical)

lus   nom
La enerjia natural cual stimula la vide e fa ce cosas deveni vidable, composada de radia eletromagnetal con ondas entre sirca 390 e 740 nanometres
nb   No usa "lus" per dise "lampa".
en   light (illumination)

»  lus clar de dia   nom
en   clear light of day, broad daylight

»  lus de dia   nom
en   daylight; daytime, day

»  lus de lampa   nom
en   lamplight

»  lus de luna   nom
en   moonlight

»  lus de sol   nom
en   sunlight

»  lus de stela   nom
en   starlight

»  lus final   nom
en   dusk, twilight

»  lus prima   nom
en   dawn, twilight

»  lus refletada   nom
en   reflected light, glare

»  duilus   nom
en   twilight, half light

lusio   nom
Un pex longa e xasante, con beco puntida e dentes grande
Esox
en   pike (fish)

luso   nom
Un cosa desirada ma no nesesada, cual es custosa o difisil per oteni
en   luxury (item)

»  estrema lusosa   ajetivo
en   high-end

»  lusosa   ajetivo
en   luxurious, luxuriant, opulent, lavish, sumptuous, sensuous, rich, deluxe, lush, posh, ritzy, swanky

»  lusosia   nom
Un stato de ricia e comforta grande
en   luxury (state)

luta   verbo nontransitiva
Combate sin armas, con gol de forsa sua oposor a la tera, acaso o como un sporte
en   wrestle, rassle, grapple, struggle, contend; falter

»  luta   verbo transitiva
en   cause to struggle

»  luta   nom
en   wrestling, struggle, altercation, contention

»  lutor   nom
en   wrestler, fighter

lutefisc   nom
Un plato scandinavian de gado secida, moiada en alcalin corodente per moli lo e per sutrae la pel e osos, e jelatinida par boli
en   lutefisk (food)

luteran   ajetivo
Pertinente a la forma de cristianisme developada par Martin Luther
en   Lutheran

»  luteran   nom
en   Lutheran

»  luteranisme   nom
en   Lutheranism (Christianity)

lutesio   nom   «Lu»
La elemento cimical con numero atomal 71, un metal arjentin blanca de la serie de lantanidos
en   lutetium (element)

luto   nom
Un strumento de cordetas con colo longa, corpo ronda, e fronte plana como un ovo duida
en   lute

»  luto arabi   nom
en   oud, arabian lute

»  lutiste   nom
en   lutist, lute player

lutra   nom
Un mamal semiacual en familia de mustela, con corpo longa, pelo densa, e pedes membranosa
Lutrinae
en   otter

lux   nom
Un unia internasional de lumina, egal a un lumen per metre cuadrida
en   lux (unit of light)

Luxemburg   nom
Un pais peti en Europa ueste entre Beljia, Deutxland e Frans
(capital: la Site Luxemburg)
en   Luxembourg

»  luxemburges   ajetivo
en   Luxembourgish

»  luxemburges   nom
en   Luxembourger

Luzon   nom
La isola la plu grande e la plu norde de la Pilipinas
en   Luzon (island)

»  Streta Luzon   nom
Un streta a norde de Luzon
en   Luzon Strait

