= A

a   simbol   (dise ‘a’)
La letera prima de la alfabeta roman, e sua nom; la nota ses de la scala diatonica de C major
en   a
fr   la
he   האות הראשונה באלפבית הלטיני

a   preposada
1   Indicante un loca o tempo como un punto simple.   (Leje plu…)
‹ nos senta a la table; la barco es a mar; me va parti a la fini de la semana; a 26 julio 1887; a la ora des-sinco ›
en   at, in, on (a point in space or time)
eo   ĉe, en, je
fr   à
he   ב-, אצל
ru   в, на, за (сидим за столом)
2   Indicante la punto de refere en un relata
‹ tu sta tro prosima a la borda; la pen parteni a me; la forma de Italia es simil a un gama; a la min ›
en   (in relation) to
eo   al
fr   à
he   ל-
ru   к; дательный падеж; на (в выражениях сравнения)
3   Indicante la loca, resetor o state cual on ateni o vole ateni par un move o cambia
‹ el desira viaja a la Luna; de ves a ves; me va dona un oso a tua can; la idea pare bon a me; la sorsor ia cambia se a un capra; on va eleje tu a presidente; el ia pinti sua mures a jala; tradui un poesia a elefen ›
en   in the direction of, to, toward, towards, unto
eo   al, direkte al
fr   à, vers
he   ל-; מסמן שינוי למצב חדש (צביעה בלבן, בחירה לנשיא)
ru   на (как направление); дательный падеж; в (при глаголах превращения в, изменения в)
4   Indicante un ata cual on asinia a la ojeto presedente
nb   Nota la difere entre "me instrui el a comprende" (cual sinifia "me instrui el afin el comprende") e "me instrui el per comprende" (cual sinifia "me instrui el afin me comprende").
‹ el comanda la soldatos a ataca la fortres ›
en   (influencing another) to (do something)
fr   à
he   ל-, למען המטרה ...
5   Clarinte ce un otra preposada, direta seguente, indica un loca cual on ateni o vole ateni
nb   En "me pone la libros en la saco", la sinifia de "pone" sufisi per clari ce la libros no comensa en la saco. Ma si "me move los en la saco", cisa los es ja ala e me fa no plu ca un ajusta. "Me move los a en la saco" dise clar ce los vade a la saco.
‹ la gato ia salta a sur la table; me pone la libros (a) en la saco ›
en   (clarifying, if necessary, that the following preposition indicates motion towards a location)
eo   -n (en -n, sur -n)
he   ל-, בכיוון ל-
6   Cambiante un otra preposada, direta seguente e no segueda par un nom, a un averbo
nb   "A ante" sinifia "ante esta o acel tempo o loca", dependente de la contesto. "Move a su" sinifia "desende".
‹ la saco es a supra; me va pone la saco a supra; la gato ia salta a su; el ia resenia la teatral a pos ›
→ ante, contra, cuando, do, en, entre, pos, sirca, su, supra, sur
en   (converting the following preposition into an adverb indicating location or motion)
eo   -e, -en (poste, supren, malsupren)
he   הופך מילת יחס לתואר הפועל

a   esclama
Espresante ce on es surprendeda, ce on comprende subita, o un otra reata simil
en   ah, aha
eo   ha
he   אה
ru   ааа, ага

a-   prefisa
Non-, sin; en dirije a
en   a-
es   a-
he   (סיומת טכנית) ללא, בלי; בכיוון של

aa   corti
Ante aora
en   before now, before the present, ago
eo   antaŭ nun
he   (קיצור) לפני, בעבר, אז
ru   до сего (этого) момента

[abaco] abaco   nom
Un util per calcula con perletas liscable; un bloco plata sur la capital de un colona, cual suporta la arcitrava
en   abacus
eo   abako
es   ábaco
fr   boulier
he   אבקוס, חשבוניה
ru   счёты

abade   nom
La xef de un grupo de monces mas
en   abbot
eo   abato
es   abad
fr   abbé
he   ראש מנזר
ru   аббат, настоятель, игумен

abaia   verbo transitiva
Cria forte e subita, como un can o avia
‹ abaia un comanda ›
en   bark; squawk, crow, caw
eo   boji
es   ladrar
fr   aboyer
he   לנבוח
ru   лаять; каркать; кричать (о чайках)

[abalon] abalon   nom
Un molusco comable de mares calda, con conca foreda con nacre e perforada per respira
Haliotis
en   abalone
es   abulón, abalone, oreja de mar
he   אבלון (שבלול)

abandona   verbo transitiva
Lasa (algun) en solitaria o sin aida; sesa labora a (un taxe); (un program) sesa espeta (un responde) pos un tempo definida
en   abandon, strand, maroon, desert, orphan; jilt, forsake, relinquish, give up on, leave behind, chuck; time out (software)
es   abandonar, dejar, desertar, salir
fr   abandonner; quitter
he   לזנוח, לנטוש, להפקיר

[Abcazia] Abcazia   nom
Un teritorio autonom de Sacartvelo
(capital: Sukhumi)
en   Abkhazia
es   Abjasia
he   אבחזיה

[abea] abea   nom
Un inseto volante e picante cual colie netar e polen de flores e produi miel e sira
Apis
en   bee, honeybee
eo   abelo
es   abeja
fr   abeille
he   דבורה

[abeto] abeto   nom
Un arbor perene e conifer con conos vertical e folias cual sembla agetas
Abies
en   fir
eo   abio
es   abeto
fr   sapin
he   אשוח (עץ)

Abisinia   nom
Un impero istorial, composada de Ertra moderna e la dui norde de Itiopia
en   Abyssinia, Ethiopian Empire
es   Abisinia
he   חבש

abita   verbo transitiva
Usa (un loca) como sua casa
nb   La ojeto de "abita" es tipal un spesie de casa. On usa "en" per presenta un loca plu jeneral, como un strada o pais.
‹ el abita un aparte; el abita en Moscva; el abita en la campania; el abita un caseta en la campania ›
en   live in, inhabit, reside in, dwell in, settle in
eo   loĝi en
fr   habiter dans/à
he   לגור, להתגורר, לשכון, להשתקע

abitua   verbo nontransitiva
Comensa ave un tende forte (a un condui) pos multe repetes; deveni fisical dependente (de un droga)
‹ el abitua a labora en la note; el ia abitua a eroina ›
en   get used (to), become habituated, become accustomed, become inured; grow addicted; acclimatize/acclimatise, acclimate
eo   kutimi (al, je); maniiĝi (pri)
fr   être habitué (à); être dépendant (à)
he   להתרגל, להסתגל; להתמכר

[abjad] abjad   nom
Un sistem de scrive con sinias per consonantes ma no per vocales
en   abjad (writing system)
eo   abĝado
he   אבגד, כתיב עיצורי

ablativa   ajetivo
en   ablative (grammar)
eo   ablativa
he   שקשור ליחסה בדקדוק שמתארת מקום מוצא

aboli   verbo transitiva
Elimina ofisial la esiste de (un lege o costum)
en   abolish, do away with, get rid of, scrap, axe
eo   abolicii, aboli
fr   abolir
he   לבטל בצורה רשמית, להיפטר מ

aborta   verbo nontransitiva
Sesa prematur; pari prematur un feto noncapas de vive
en   abort, terminate, be canceled/cancelled, come to nothing; miscarry
eo   nuliĝi, aborti
fr   avorter
he   להפיל, לעבור הפלה

abracadabra   esclama
Diseda par un majiste en fa un truco
en   abracadabra, hocus pocus
he   אברקדברה, הוקוס פוקוס

[abrasa] abrasa   verbo transitiva
Teni (algun) entre sua brasos, tipal per mostra ama
en   embrace, hug, cuddle, clinch
eo   brakumi, ĉirkaŭbraki, ĉirkaŭpremi
fr   embrasser, tenir entre ses bras
he   לחבק

abri   verbo nontransitiva
(Un porte o contenador) deveni noncluida, permetente ce on pasa tra lo o asede sua contenidas; (un veste) deveni desfisada o desliada; (un valva o flue eletrical) comensa funsiona
en   open, open up; undo, unfasten, come undone, come unbuttoned, come untied, fall open; turn on, switch on (tap, power)
eo   malfermiĝi, malligiĝi, malbutoniĝi, ŝaltiĝi
fr   s’ouvrir
he   להיפתח; להידלק

[abribote] abribote   nom, composada (verbo+nom)
Un util per abri botes de comeda
en   can opener, tin opener
eo   skatolmalfermilo
fr   ouvre-boîte
he   פותחן קופסאות

[abribotela] abribotela   nom, composada (verbo+nom)
Un util per abri botelas par deseli la covrente
en   bottle opener
he   פותחן בקבוקים

abricoco   nom
Un arbor cual produi abricocas
Prunus armeniaca
en   apricot (tree)
eo   abrikotujo, abrikotarbo
fr   abricotier
he   מישמש (עץ)

abrioio   nom, composada (verbo+nom)
Un descovre surprendente
en   eye-opener, revelation
he   גילוי, חשיפה, שפיכת אור

abrisita   nom, composada (verbo+nom)   «“ ‘»
Un sinia de puntua introduinte un parola o frase sitada
en   opening quotation mark
he   מרכאות פותחות

abrivia   nom, composada (verbo+nom)   (dise ‘abrivía’)
La person prima ci esplora un loca o idea
en   pioneer, pathfinder, trailblazer
eo   pioniro
fr   pionier
he   חלוץ, פורץ דרך

[abrotano] abrotano   nom
Un artemisia brosin de Europa sude
Artemisia abrotanum
en   southernwood (plant)
he   צמח ממשפחת המורכבים מאירופה הדרומית

[abugida] abugida   nom
Un sistem de scrive cual indica vocales par ajunta sinietas a la sinias per consonantes
en   abugida, alphasyllabary (writing system)
eo   abugido
he   אבוגידה, כתב הברתי

abunda   verbo nontransitiva
Esiste en un cuantia grande e sufisinte
en   abound
eo   abundi
fr   être abondant
he   להיות שופע

Acaba   nom
en   Aqaba
es   Áqaba
he   עקבה

[acad] acad   ajetivo
Pertinente a la impero de la site Acad en Mesopotamia antica
en   Akkadian (person, language)
eo   akada
he   אכדי

academia   nom
Un organiza distinguida de espertas, artistes o siensistes; un scola spesialida
en   academy
eo   akademio
he   אקדמיה, מדרשה

Acadia   nom
Un colonia franses en la norde-este de America Norde cual ia inclui partes de Quebec este, la provinses maral de Canada, e la stato Maine asta la Rio Kennebec
en   Acadia (French colony)
fr   Acadie
he   אקדיה (חבל ארץ בצפון אמריקה)

[acantisita] acantisita   nom
Un avia pico e pasarin de Zeland Nova
Acanthisittidae
en   New Zealand wren
eo   akantisitedo
he   סוג של ציפור שיר קטנה שמקורה בניו זילנד

[acanto] acanto   nom
Un planta florinte con folias spinosa, trovada en Asia e la Mediteraneo
Acanthus
en   acanthus (plant)
eo   akanto
he   קוציץ (צמח)

[acantosefalo] acantosefalo   nom
Un membro de un filo de vermes parasital, con spinas e un proboside inversable
Acanthocephala
en   acanthocephalan (worm)
he   סוג של תולעת טפילית

acariase   nom
Un maladia de la pel de mamales, causada par acaros parasital, con pruri, perde de pelo, e formi de crostas
en   mange
he   שחין (בכלבים)

[acaro] acaro   nom
Un aracnido pico cual es un parasito
Acariformes, Parasitiformes
en   mite (arachnid)
eo   akaro
he   קרדית (חרק)

[acasia] acasia   nom
Un arbor o arboreta de climas calda, con flores blanca o jala
Acacia
en   acacia, thorntree, wattle
eo   akacio
he   שיטה (עץ)

acaso   ajetivo
Aveninte en modo o ordina nonpredisable
en   random, arbitrary, erratic, haywire, accidental, incidental, adventitious, fortuitous
eo   hazarda, arbitra
he   אקראי, רנדומלי, שרירותי, מקרי, מזדמן, לא צפוי

acc   corti
Ance conoseda como
en   a.k.a.
eo   alinome
he   הידוע גם כ, הידוע בכינויו

Acea   nom
Un provinse en Elas
(capital: Patra)
en   Achaea (Greek region)
eo   Aĥeo
he   אכאיה (מחוז ביוון)

acel   determinante
Cual nos vide ala; cual nos ia indica ja.   (Leje plu…)
nb   "Acel" es un varia asentuada de "la". Lo contrasta comun con "esta", cual indica un person o cosa plu prosima (fisical o metafor).
en   that, those, yonder, yon
eo   tiu
he   ההוא, זה ששם

[acemenan] acemenan   ajetivo
Pertinente a la Impero Persian Prima entre la sentenios 6 e 4 aec
en   Achaemenid (dynasty)
eo   aĥemenida
he   ששייך לאימפריה האחמנית

acenio   nom
Un fruta peti e seca, con sola un seme, cual no abri per relasa la seme
en   achene (botany)
he   פרי יבש בעל זרע בודד

[Aciten] Aciten   nom
Un rejion e provinse pasada de Frans sude-ueste; un duxia en la eda medieval
en   Aquitaine, Aquitania (French region)
he   אקיטן (חבל ארץ בצרפת)

aclama   verbo transitiva
Loda o coraji con crias zelosa
en   acclaim, cheer, cheer for
eo   aklami
he   להריע, לקלס, לשבח

acne   nom
Un inflama de la glandes sebosa cual crea pustulas roja a la pel
en   acne
eo   aknohaŭto, akneo
he   אקנה, חטטת, פצעי בגרות

acompania   verbo transitiva
Viaja con (algun); aveni a la mesma tempo como; canta o jua un melodia fondal per suporta (la melodia xef)
en   accompany, escort
eo   akompani, eskorti
he   ללוות

Aconcagua, Monte   nom
La monte la plu grande estra Asia, en la Andes de Arjentina
en   Aconcagua
he   אקונגווה (הר בארגנטינה)

[aconito] aconito   nom
Un planta venenosa con flores de forma elmin
Aconitum
en   aconite, monkshood, wolfsbane (plant)
eo   akonito
he   אקוניטון (צמח)

acorda   verbo transitiva
Ave la mesma opina (con algun) sur; es coerente (con alga cosa); dise ce on va (fa un ata)
‹ el ia acorda canta ›
en   agree to, consent, assent, accede, be in agreement (about), concur, accord; agree (grammar); match up, correspond, tally (with); be compatible
eo   konsenti pri
he   להסכים; להתאים, להלום

[acordion] acordion   nom
Un strumento musical de venta cual on compresa e descompresa con sua manos, creante un melodia con teclas
en   accordion
eo   akordiono
he   אקורדיון

acre   nom
Un unia vea de area, con definis diversa, ma aprosima 40% de un ectare, o 1/640 de un milia cuadrida
en   acre
eo   akreo
he   אקר (יחידת מידה לשטח)

acrete   verbo nontransitiva
Crese par cumula o fusa
en   accrete
he   להתרחב על ידי הצטברות הדרגתית

acrilica   ajetivo
en   acrylic
eo   akrila
he   אקרילי

acrofobia   nom
Un teme estrema o nonrazonada de locas alta
en   acrophobia
he   פחד גבהים

acromata   ajetivo
Sin color; (un retina) noncapas de responde a color
en   achromatic, black and white
he   אכרומטי, ללא צבע, שחור לבן

acromion   nom
Un protende ososa sur la scapula
en   acromion
he   (אנטומיה) שיא הכתף

acronim   ajetivo
en   acronymic, acronymous
he   בצורת נוטריקון, ראשי תיבות

[acropoli] acropoli   nom
(En Elas antica) un vila o fortres construida sur tera alta
en   acropolis
he   אקרופוליס, מצודה

acrostica   ajetivo
en   acrostic
he   אקרוסטיכון

acrotera   nom
Un sculta suportada par un plataforma a la apico de la fronton de un construida clasica
en   acroterion, acroterium
he   אקרוטריון

[acrupi] acrupi   verbo nontransitiva
Sta en posa basa con jenos pliada; senta sur sua talones; basi rapida (sua testa o corpo) per evita un colpa o per no es videda par otras
en   crouch, squat, hunker, duck
eo   kaŭri
he   לכרוע, להשתופף

actinica   ajetivo
Capas de causa reatas fotocimical, como en fotografia
en   actinic
he   אקטיני, קרינתי

actinido   nom
Cada de un serie de 15 elementos metal entre actinio e laurensio
en   actinide (chemistry)
he   אקטיניד

actinio   nom   «Ac»
La elemento cimical con numero atomal 89, un metal radioativa
en   actinium (element)
eo   aktinio
he   אקטיניום (יסוד)

acua   nom
La licuida cual formi la mares, la lagos, la rios e la pluve, e es esensal per tota organismes conoseda
ca   aigua
de   Wasser
el   νερό
en   water
eo   akvo
es   agua
fr   eau
it   acqua
he   מים
nl   water
pl   woda
pt   água
ru   вода

acuacultur   nom
La eleva de animales acual o la cultiva de plantas acual per comeda
en   aquaculture
he   חקלאות ימית

[acuaduto] acuaduto   nom
Un ponte sur cual un rio traversa un vale
en   aqueduct
eo   akvedukto
he   אקוודוקט, מוביל מים

[acuamarin] acuamarin   ajetivo
Con color pal bluin verde
en   aquamarine
he   גוון ירוק כחלחל

acuarela   nom
Un pinta artiste composada de un pigmento suspendeda en un sustantia disolvable en acua
en   watercolor/watercolour
eo   akvarelfarbo
he   צבע מים

acuatinje   nom
Un primida cual sembla un depinta de acuarela ma es produida con un plato de cupre gravada con asida; la metodo de produi un tal primida
en   aquatint
he   אקווטינטה (טכניקת הדפס)

acuavit   nom
Un bevida scandinavian de alcol, preparada de patatas
en   aquavit, akvavit (drink)
eo   akvavito
he   אקוויט (משקה אלכוהולי על בסיס תפוחי אדמה)

acuifer   nom
Un strato de roca permeable e capas de porta acua
en   aquifer
eo   grundakvejo
he   אקוויפר

acusa   verbo transitiva
Dise ce (algun) ia ofende o fa un crimin
en   accuse, charge, impeach, indict, arraign, prosecute
eo   akuzi
he   להאשים, להעמיד לדין

acusativa   ajetivo
en   accusative (grammar)
eo   akuzativa
he   שקשור ליחסת את

acustica   nom
La ramo de fisica cual studia sonas e la persepi de los
en   acoustics
eo   akustiko
he   אקוסטיקה

acuta   ajetivo
(Un maladia) intensa ma de dura corta
nb   "Acuta" es un terma tecnical. No usa lo per dise "agu".
en   acute (medical)
eo   akuta
he   (רפואה) אקוטי, קריטי

adajio   ajetivo
(Un musica) lenta juada
en   adagio
he   אדג’יו

Adam   nom
Un nom mas, incluinte de la umana prima en la Biblia
en   Adam
eo   Adamo
he   אדם (שם האדם הראשון ושם לגבר)

Aden   nom
en   Aden
he   עדן

adenoide   nom
Un masa grandida de texeda limfal entre la garga e la retro de la nas
en   adenoid, pharyngeal tonsil
eo   adenoida vegetaĵo
he   פוליפ

adere   verbo nontransitiva
Es colida (a un surfas)
en   stick, adhere, cling
eo   adheri, algluiĝi
he   להידבק, להיצמד

adiabatica   ajetivo
No permetente ce caldia entra a o sorti de un sistem
en   adiabatic (physics)
he   אדיאבטי

adio   esclama
Diseda cuando on parti per un tempo longa
en   goodbye, farewell, adieu
eo   adiaŭ
he   שלום, להתראות, ביי

adipos   ajetivo
(Texeda) usada per reserva gras
en   adipose
he   של רקמה שומנית

adirije   verbo transitiva
en   address
eo   adresi
he   לרשום כתובת

adn   corti
Asida desosiribonucleal
en   DNA
eo   DNA
fr   ADN
he   די-אן-איי, חומצה דאוקסיריבונוקלאית

adobe   nom
Un spesie de arjila usada per crea brices cual on seci su sol
en   adobe
eo   adobo
he   לבנת חימר

adolese   verbo nontransitiva
(Un person) developa de un enfante a un adulte
en   be a teenager, pass through adolescence
eo   adoleski
he   לעבור את גיל ההתבגרות

adomen   nom
La parte de la corpo cual conteni la organos de dijesta e reprodui
en   abdomen, midriff
eo   abdomeno
he   בטן

[adonis] adonis   nom
Un om joven bela
en   adonis
he   אדוניס

adora   verbo transitiva
Mostra onora a (un dio); ama forte
en   adore, worship, revere
eo   adori
he   להעריץ, לסגוד, לעבוד את

adormi   verbo nontransitiva
Comensa dormi
en   fall asleep, go to sleep
eo   endormiĝi, ekdormi
he   להירדם

adota   verbo transitiva
Prende legal (un enfante de otras) e eleva el como sua propre; deside usa (un condui, opina o lingua) como sua propre
en   adopt, espouse; take up
eo   adopti
he   לאמץ, לסגל

adriatica   ajetivo
Pertinente a la rejion composada par la Mar Adriatica e sua costas e isolas, entre Italia e la Balcanes
en   Adriatic
he   אדריאטי

adron   nom
Un particula suatomal, composada de cuarces liada par la forsa nucleal forte
en   hadron (particle)
eo   hadrono
he   הדרון (חלקיק תת-אטומי)

adsorbe   verbo transitiva
(Un solida) teni (moleculas de gas o licuida) como un filma magra a sua surfas
en   adsorb
he   (כימיה) לספח או לצבור על גבי משטח

adui   verbo transitiva
(Un musculo) move (un membro) en dirije a la linia media de simetria de la corpo
en   adduct (muscle)
eo   adukcii
he   למשוך או להזיז לעבר הציר המרכזי של הגוף

adula   verbo transitiva
Loda multe (algun) en modo umil per atenta boni sua situa
en   adulate, flatter, fawn over, grovel to, toady to, suck up to, coax, wheedle, cajole, ingratiate, kowtow
eo   flataĉi, komplezaĉi, rampi antaŭ
he   להחניף, להחמיא, להתרפס כלפי

adulte   ajetivo
Ci ia fini crese e adolese
en   adult, grown-up
eo   plenkreska, plenaĝa
he   בוגר, בשל, מבוגר

adultera   verbo transitiva
Redui la cualia de (un sustantia) par ajunta un otra sustantia; (un person sposida) copula con algun a ci el no es sposida (adulterante la sposia)
en   adulterate, tamper with; commit adultery, fornicate, adulter, philander
eo   adulteri, fuŝmiksi; adulti
he   לחבל באיכות החומר, להוסיף חומרים זרים; לנאוף

adventisme   nom
Un ramo de protestantisme cual crede ce Cristo va reveni
en   Adventism (Christianity)
he   אדוונטיזם

aec   corti
Ante la eda comun
en   BCE (before the common era), BC (before Christ)
eo   aKE (antaŭ la komuna erao), aK (antaŭ Kristo)
he   לפני הספירה

afasia   nom
Un noncapasia de parla o comprende la parla, pos dana serebral
en   aphasia (medical)
eo   afazio
he   אפזיה, שתקת

afelio   nom
La loca en la orbita de un ojeto do lo es la plu distante de la Sol
en   aphelion (astronomy)
eo   afelio
he   אפהליון

afeta   verbo transitiva
Fa un efeto a; cambia la state de
en   affect, have an effect on, influence, impinge on
eo   tuŝi, influi
he   להשפיע

[Afganistan] Afganistan   nom
Un pais en Asia sude e Asia sentral
(capital: Kabul)
da   Afghanistan
de   Afghanistan
el   Αφγανιστάν
en   Afghanistan
eo   Afganio, Afganujo
es   Afganistán
fr   Afghanistan
it   Afghanistan
he   אפגניסטן
ja   アフガニスタン
nl   Afghanistan
pl   Afganistan
pt   Afeganistão
ru   Афганистан

afidavit   nom
Un declara scriveda e jurada, usada como atesta en un corte legal
en   affidavit
he   תצהיר

[afido] afido   nom
Un inseto peti cual suca la sava de plantas
Aphidoidea
en   aphid
eo   afido
he   כנימה

afin   sujunta
Intendente ce, con gol ce
‹ me va leva tu afin tu vide ›
→ car
en   so that, in order that
eo   por ke
he   בשביל ש, כדי ש

afina   ajetivo
Permetente o conservante relatas paralel
en   affine
he   (מתמטיקה) אפיני

afirma   verbo transitiva
Declara formal
en   affirm, state, aver
eo   aserti
he   לאשר, להצהיר

afisa   verbo transitiva
Ajunta (un cosa), fisante lo a un otra cosa; ajunta (un fix) a un eposta; ajunta (un prefisa o sufisa) a un parola per altera sua sinifia
en   affix, attach; mount (a picture)
eo   alfiksi, alligi, alkroĉi; kunsendi (retpoŝte); afiksi
he   לחבר, לצרף

afluente   nom
Un rio o rieta cual flue a un lago o rio plu grande
ca   afluent
da   biflod
de   Nebenfluss
en   tributary
eo   alfluanto
es   afluente
fr   affluent
it   tributario
he   יובל
ja   流路形状
nl   zijrivier
pt   afluente
ru   приток

afoca   verbo nontransitiva
Sofoca pos sumerji en licuida
en   drown
eo   droni
he   לטבוע

afonda   verbo nontransitiva
Sumerji lenta
en   sink, scuttle
eo   sinki
he   לשקוע

afonia   nom
Un noncapasia de parla pos dana a la larinje o boca
en   aphonia (medical)
he   אובדן הקול

[Africa] Africa   nom
La continente du de la plu grandes de mundo, a sude de Europa
en   Africa
eo   Afriko
he   אפריקה

africaner   ajetivo
Pertinente a un etnico blanca de Sudafrica, parlante africans
en   Afrikaner
eo   afrikansa
he   אפריקנר

africans   ajetivo
Pertinente a un lingua de Sudafrica, desendente de un forma de nederlandes
en   Afrikaans
eo   afrikansa
he   אפריקנס

africante   ajetivo
(Un consonante) cual comensa como un esplodente e fini como un fricante
en   affricate
eo   afrikata, ekfrota
he   עיצור מחוכך

[afro] afro   ajetivo
Con capeles cual sembla un nube ronda de risas
en   afro
he   אפרו

afroamerican   ajetivo
en   Afro-American, African American, Negro, black
he   אפרו-אמריקאי

afroasian   ajetivo
Pertinente a un familia grande de linguas, xef parlada en Asia sude-ueste, Africa norde, la Penisola Somali e la Sahel
en   Afro-Asiatic, Afrasian, Hamito-Semitic
he   אפרו-אסיאתי

afrodisica   ajetivo
Stimulante la desira sesal
en   aphrodisiac, aphrodisiacal
eo   afrodiziiga
he   אפרודיזיאק (מעורר תשוקה מינית)

afroeurasian   ajetivo
Pertinente a la mundo vea (Africa, Europa, Asia)
en   Afro-Eurasian
he   מהעולם הישן: אפריקה, אירופה, אסיה

agape   nom
Ama cristian; un come comunial cristian
en   agape (Christianity)
he   אהבה נוצרית

agar   nom
Un materia jelatin de alges, usada per densi comedas o per cultiva baterias
en   agar, agar-agar (substance)
he   אגאר

[agarico] agarico   nom
Un fungo con corpo frutinte cual sembla un xampinion, con xapeta convesa o plata con laminas a la fondo
Agaricales
en   agaric (fungus)
he   פטריה מסדרת הפקועיים

agata   nom
Un varia dur de cuarzo, tipal con aspeta raiosa
en   agate
eo   agato
fr   agathe
he   אכטיס, ברקת

[agave] agave   nom
Un planta suculente de Mexico, con spigas alta florinte e rosetas de folias streta e spinosa
Agave
en   agave (plant)
eo   agavo
fr   agave
he   אגבה

[agila] agila   nom
Un avia xasante, con beco oncin e alas longa e larga
Aquilinae
en   eagle
eo   aglo
fr   aigle
he   עיט

aglutina   verbo transitiva
Combina (morfemes semantical) per formi un parola nova
en   agglutinate
eo   aglutini, alglui
fr   agglutiner
he   ליצור מילים חדשות על ידי חיבור מילים או מיליות

agnostica   ajetivo
Credente ce on no pote sabe esce dios esiste
en   agnostic
eo   agnostika
fr   agnostique
he   אגנוסטי

[ago] ago   nom
Un util de cose, simil a un basteta multe streta, con un punto agu a un fini e un buco per un filo a la otra; la indicador de un orolojo o busola
en   needle, hand (clock, compass)
eo   kudrilo
fr   aiguille
he   מחט; מחוג שעון

[agopuntur] agopuntur   nom
Un tecnica de medica alternativa en cual on pone agos en la pel
en   acupuncture
eo   akupunkturo
fr   acupuncture
he   אקופונקטורה, דיקור סיני

[agora] agora   nom
(En Elas antica) un plaza publica per asemblas e mercatos
en   agora
he   (יוון העתיקה) שוק או כיכר

agorafobia   nom
Un ansia nonormal sentida en locas vasta o publica
en   agoraphobia
eo   agorafobio
he   אגורפוביה, בעת חוצות

agosto   nom
La mense oto de la calendario gregorian
en   August
eo   aŭgusto
fr   Août
he   אוגוסט

agrega   verbo nontransitiva
(Partes diversa) combina per formi un intera
en   aggregate, combine, conglomerate, agglomerate
eo   agregatiĝi, agregiĝi, kombiniĝi, konglomeriĝi
he   להצטרף, להתקבץ, להתאחד, להתלכד, להצטבר

[agrimonia] agrimonia   nom
Un planta en familia de rosa, con spigas magra de flores e frutas spinosa
Agrimonia
en   agrimony
he   אבגר

agronomia   nom
La siensa de maneja la cualia de tera e produi cultivas
en   agronomy
he   אגרונומיה

agu   ajetivo   (dise ‘agú’)
Con lama o punto capas de talia; (un sensa o mente) cual persepi eselente e rapida
en   sharp, pointed, pointy; acute, keen (sense); sharp-tasting, pungent, tangy; acute (angle)
eo   akra, sagaca
fr   aigu, aiguisé, pointu
he   חד, מחודד; פיקח, נבון, חריף, בעל תפיסה חדה

agrocimica   nom
en   agrochemistry
he   אגרוכימיה

[aguti] aguti   nom
Un rodente american con oreas e coda multe corta
Dasyprocta
en   common agouti (rodent)
eo   agutio
he   אגוטי (מכרסם)

aha   esclama   (dise ‘ahá’)
Espresante ce on comprende subita o ia fa un descovre
en   aha
he   אהא

ahimsa   nom
(En budisme, induisme e jainisme) la prinsipe de respeta tota organismes e evita violentia
en   ahimsa (Buddhism, Hinduism)
eo   ahimso
he   (בודהיזם) אהימסה

ai   esclama
Espresante tristia o compatia
en   oh dear, sigh, alas, alack
eo   ve
he   אוי, אבוי

[aiai] aiai   nom
Un lemur con dentes rodente e un dito media longa e streta per estrae larvas de arbores
Daubentonia madagascariensis
en   aye-aye (primate)
eo   fingrobesto, ajajo, daŭbentonio
fr   aye-aye
he   איי איי (סוג של פרימט ממדגסקר)

aiatola   nom
Un autoriosa en islam xia, spesial en Iran
en   ayatollah
he   אייתולה

aicido   nom
Un arte militar o autodefende nion cual redirije la atacas de la oposor
en   aikido
eo   aikido, ajkido
fr   aikido
he   אייקידו

aida   verbo transitiva
Fasili la taxe de (algun) par partisipa en lo; fa ce (un situa o problem) deveni plu bon
en   help, assist, aid, abet, help out; serve (customer); improve
eo   helpi
fr   aider, assister; servir (client)
he   לעזור, לסייע

aidamemoria   nom, composada (verbo+nom)
Un nota per fa ce on recorda
en   reminder, memory aid, aide-mémoire, mnemonic
eo   memorigilo
he   תזכורת

aidaoia   nom, composada (verbo+nom)
Un aparato per aumenta sonas, portada sur la orea de un person partal sorda
en   hearing aid
eo   aŭdaparato, aŭdhelpilo
he   מכשיר שמיעה

aidapasea   nom, composada (verbo+nom)
Un strutur usada per persones descapasida o malada per suporta cuando los pasea
en   walker, walking frame
he   הליכון למבוגרים

aidaservor   nom, composada (verbo+nom)
Un laboror en un restorante ci prepara e limpi la tables
en   busboy, busgirl, busser
he   מפנה שולחנות, פיקולו

[ailanto] ailanto   nom
Un arbor alta e caduca con folias grande, de Asia e Australia
Ailanthus
en   ailanthus (tree)
fr   ailanthe
he   אילנתה בלוטית (עץ)

ainstainio   nom   «Es»
La elemento cimical con numero atomal 99
en   einsteinium (element)
he   איינשטיניום (יסוד)

aira   nom
La gas nonvidable cual ensirca la Tera, xef composada de nitrojen e osijen; (nonformal) la clima
en   air; (colloquial) weather
eo   aero
fr   air
he   אוויר

airo-   prefisa
Aira
en   aero-
he   (סיומת טכנית) קשור לאוויר

airobio   nom
Un organisme capas de crese e survive en osijen
en   aerobe
eo   aerbezonulo, aerobiulo
he   אורגניזם שזקוק לחמצן

airobiolojia   nom
en   aerobiology
he   אירוביולוגיה

airocompania   nom
Un organiza cual transporta par aviones
en   airline
he   חברת תעופה

airodinamica   nom
La siensa de aira movente e de la interatas entre la aira e corpos solida cual move tra lo
en   aerodynamics
he   אווירודינמיקה

airofolia   nom
Un strutur con surfases curvida, la forma fundal de alas e pinas de aviones
en   airfoil/aerofoil
he   (אווירודינמיקה) משטח עילוי

airograf   nom
Un aparato usada par artistes per jeta pinta par aira compresada
en   airbrush
he   מברשת אוויר, ספריי צבע

airojel   nom
Un materia solida con densia multe basa, produida par sutrae la composante licuida de un jel normal
en   aerogel, frozen smoke
he   אירוג’ל

airolito   nom
Un meteorite rocosa, composada xef de silicatos
en   aerolite (meteorite)
he   אירוליט (מטאוריט)

airolojia   nom
La siensa de la atmosfera
en   aerology
eo   aerologio
he   אירולוגיה

aironautica   nom
La pratica o siensa de viaja tra la aira
en   aeronautics
eo   aeronaŭtiko
he   אווירונאוטיקה, תורת התעופה

[airoporto] airoporto   nom
Un loca do aviones enaira e atera, con construidas per organiza la pasajores
en   airport
fr   aéroport
he   נמל תעופה

airoposta   verbo transitiva
Envia (posta) par avion, tipal ultramar
en   airmail
he   לשלוח בדואר אוויר

airosol   nom
Un suspende de particulas solida o licuida en un gas
en   aerosol
eo   aerosolo
he   תרסיס

airospasio   nom
La aira disponable per voladores, spesial la parte governada par un pais spesifada; la ramo de tecnolojia e industria cual pertine a avioni e vola spasial
en   airspace; aerospace
he   מרחב אווירי

airostato   nom
Un balon o otra veculo de aira, suportada par un corpo de gas (tipal elio) cual es plu lejera ca aira
en   aerostat (including balloon)
he   כדור פורח, ספינת אוויר

airotira   verbo transitiva
en   wind-propel
he   להניע על-ידי רוח

[Aiti] Aiti   nom
Un pais de la Mar Caribe
(capital: Port-au-Prince)
en   Haiti
eo   Haitio
he   האיטי

[ajena] ajena   verbo nontransitiva
Ave un posa vertical, suportada sur sua jeno o jenos
en   kneel, kowtow
eo   genui
he   לכרוע ברך

ajenda   nom
Un libro en cual on nota la taxes cual on intende fa
en   agenda, day planner, appointment book, diary; docket, to-do list
eo   agendo
he   יומן יומי, ארגונית

ajenero   ajetivo
(Un person) ci regarda se no como masin, no como femin
en   agender, gender-neutral, unisex
he   ג’נדרקוויר (אדם שאינו מגדיר את עצמו כזכר או כנקבה)

ajente   nom
Un person ci ata per un otra, tipal negosiante entre du persones o organizas
en   agent, broker, intermediary, attaché
eo   agento, makleristo, peranto
he   סוכן, מתווך

ajetivo   nom
Un parola descrivente, tipal usada per altera un nom o formula nomin
en   adjective
eo   adjektivo
he   מילת תואר

ajil   ajetivo
(Un person o animal) capas de move rapida e fasil
en   agile, nimble, sprightly, lithe, limber
eo   facilmova, vigla
he   זריז, מהיר, קל תנועה

ajiografia   nom
La studia istorial de la vives de la santas
en   hagiography
eo   hagiografio
he   ביוגרפיה של קדושים

ajita   verbo transitiva
Fa ce (algun) senti ansia
en   agitate, excite, upset, fluster, worry, trouble, perturb
eo   agiti, ĉagreni, malkvietigi, maltrankviligi
he   להסעיר, לשלהב, להתסיס, להסית

ajitprop   nom
Propaganda political, spesial en arte o leteratur
en   agitprop
he   תעמולה פוליטית

ajunta   verbo transitiva
Pone (un cosa) tal ce lo combina con un otra
‹ ajunta sal a la sopa; ajunta tre nomes nova a un lista; ajunta du e du e fini con sinco ›
en   add, append, annex; impart (quality)
eo   aldoni
fr   ajouter
he   לחבר, לספח, לצרף, להוסיף

ajusta   verbo nontransitiva
Cambia pico (un cosa) per coreti lo
en   adjust, adapt, acclimatize/acclimatise
he   להתאים, להתכוונן, להתרגל

ala   averbo   (dise ‘alá’)
En acel loca
en   there, yonder; to there, thither
he   שם, המקום ההוא

[ala] ala   nom
Un parte de corpo cual un animal move per vola; un strutur rijida e orizonal a cada lado de un avion cual suporta lo en la aira; un parte de un construida grande, tipal protendente; la lado de un stadio teatral, nonvidable per la regardores; un peso plata cual pende o covre un abri, liada a sola un lado
en   wing; fly, flap
eo   flugilo; wing; kuliso; klapo
he   כנף; אגף

Alabama   nom
Un stato en la SUA sude-este
en   Alabama (US state)
he   אלבמה

alabastro   nom
Un forma de jeso diafana, tipal blanca, con venas peti, comun siselida per crea ornas
en   alabaster
he   אלבסטר, בהט

alantoide   nom
La membrana fetal su la corion en multe vertebratos
en   allantois (membrane)
he   אלנטואיס (רקמה קרומית עוברית)

alarma   verbo transitiva
Fa ce (algun) senti asustada, turbada o perilida
en   alarm
he   להדאיג, להבהיל

[alaroja] alaroja   nom, composada (nom+ajetivo)
Un turdo de Eurasia con alas roja
Turdus iliacus
en   redwing (bird)
he   קיכלי לבן גבות (ציפור)

Alaska   nom
La stato la plu grande de la SUA, con costas a la Mar Artica e la Mar Bering
en   Alaska (US state)
he   אלסקה

alaui   ajetivo
Pertinente a un grupo de muslimes xia, de ci la plu abita en Suria
en   Alawite, Alawi (Islam)
he   עלאווי

[Albania] Albania   nom
Un otra nom per Xciperia
→ Xciperia
en   Albania
he   אלבניה

[albatros] albatros   nom
Un avia de mar, multe grande, con alas longa e magra
Diomedeidae
en   albatross
he   אלבטרוס

albedo   nom
La proportio de lus o radia, tipal de un planeta o luna, cual un surfas refleta
en   albedo (astronomy)
he   (אסטרונומיה) אלבדו

[Albert, Lago] Albert, Lago   nom
Un lago en Africa este-sentral entre la Republica Democrata de Congo e Uganda
en   Lake Albert
he   אגם אלברט

Alberta   nom
Un provinse de Canada sentral
en   Alberta (Canadian province)
he   אלברטה

[albino] albino   ajetivo
(Un person o animal) con asentia jenetical de pigmento en sua pel, capeles e oios
en   albino
he   לבקן

[Alboran, Mar] Alboran, Mar   nom
Un mar entre Espania e Magrib
en   Alboran Sea
he   ים אלבוראן

album   nom
Un libro per colie fotos, selos o imajes; un colie de rejistras musical, publicida como un ben singular
en   album, scrapbook
he   אלבום

albumen   nom
La parte blanca de la interna de un ovo; la protena cual lo conteni
en   albumen, egg white
he   חלבון ביצה

albumina   nom
Un protena simple, disolvable en acua e coagulable par caldi, trovada en albumen, lete e sero sangual
en   albumin (protein)
he   אלבומין

alburno   nom
Un pex peti, arjentin e sosial en familia de pexeta
Alburnus, Chalcalburnus
en   bleak (fish)
he   לבנון (דג)

alcalifilia   nom
La capasia de un bateria de vive en ambientes multe alcalin
en   alkaliphilia
he   אלקלופיליה

alcalin   ajetivo
(Un sustantia) cual blui paper de pH, e neutri asidas o bola cuando on misca lo con los
en   alkaline
he   אלקלי, בסיסי

alcaloide   nom
Cualce de alga composadas organica nitrojenosa, derivada de plantas e incluinte multe drogas e venenas, cual ave efetos forte a umanas
en   alkaloid
he   אלקלואיד

alcalose   nom
Un maladia en cual la texedas o licuidas de corpo es tro alcalin, causante debilia o crampos
en   alkalosis (medical)
he   בססת (בסיסיות יתר בדם ובנוזלי הגוף)

alcano   nom
Un idrocarbono saturada nonsiclin (metano, etano, propano)
en   alkane, paraffin
he   (כימיה) אלקאן

alcazar   nom
Un fortres moro en Espania o Portugal
ca   alcàsser
en   alcazar
es   alcázar
fr   alcazar
it   alcazar
pt   alcácer, alcáçar

[alce] alce   nom
Un servo grande con cornos palmin, trovada en paises norde
Alces alces
en   elk (UK), moose
he   אייל קורא

alcen   nom
Un idrocarbono nonsaturada con minima un lia duple de carbono
en   alkene (chemistry)
he   (כימיה) אלקן

alcil   nom
Un radical de idrocarbono derivada de un alcano par sutrae un atom de idrojen
en   alkyl (chemistry)
he   (כימיה) אלקיל

alcimica   nom
La siensa medieval cual ia presede cimica, atentante muta un elemento a un otra
en   alchemy
he   אלכימיה

alcin   nom
Un idrocarbono nonsaturada con minima un lia truple de carbono
en   alkyne (chemistry)
he   (כימיה) אלקין

[alco] alco   nom
Un avia de mar con alas corta, trovada en mares norde, tipal con testa e dorso negra e peto blanca
Pinguinus impennis, Alca torda, Alle alle
en   auk, razorbill, little auk, dovekie (bird)
he   אלקה (ציפור)

alcol   nom
Un licuida volatil, flamable e sin color, cual es la composante enebriante de vino, bir e otra bevidas, ance usada como un disolvente industrial e como un combustable
en   alcohol, booze
he   אלכוהול

alcolomania   nom
Un abitua fisical e mental de la usa de alcol, tipal sin la capasia de sesa sin mal efetos
en   alcoholism
he   אלכוהוליזם, שתיינות

alcolometre   nom
Un aparato usada par la polisia per mesura la cuantia de alcol en la respira de un motoriste
en   breathalyzer/breathalyser
he   מכשיר למדידת רמת האלכוהול בדם, ‘ינשוף’

alcova   nom
Un spasio peti creada par un parte retirada de la resta de un mur; un loca privata o secreta
en   alcove, recess, nook, bay
he   גומחה

aldehido   nom
Un composada organica formida par la osidi de alcoles
en   aldehyde
he   (כימיה) אלדהיד

aldosterona   nom
Un ormon corticosteroide cual stimula la asorbe de sodio par la renes, per regula la ecuilibra de acua e sal
en   aldosterone (hormone)
he   אלדוסטרון

ale   nom
Un spesie de bir preparada par fermenta calda, con sabor dulse e frutosa
en   ale (beer)
he   אייל (בירה)

alef   nom   «א»
La letera prima de la alfabeta ivri
en   aleph (Hebrew letter)
he   אלף (האות הראשונה באלפבית העברי)

alega   verbo transitiva
Declara ce algun ia fa (un ata) mal o criminal, tipal sin atestas
en   allege, claim, adduce
he   לטעון, להאשים

alegoria   nom
Un nara, poesia o imaje cual conteni un sinifia ascondeda, tipal moral o political
en   allegory
he   אלגוריה, משל

alelo   nom
Cada de du o plu formas de un jen cual apare par muta e es trovada a la mesma loca en un cromosoma
en   allele (genetics)
he   (גנטיקה) אלל, גן אללי

aleluia   esclama
Espresante adora de o grasia a Dio
en   hallelujah, alleluia
he   הללויה

alemande   nom
Un dansa deutx; un musica per esta, spesial como un move en un suite; un turna con brasos o manos liada
en   allemande (dance, music)
he   אלמנדה (ריקוד)

[alena] alena   nom
Un util peti e puntida per perfora un materia como cuoro o lenio
en   awl, bradawl
he   מרצע, דוקרן

alerjen   ajetivo
(Un sustantia) causante un alerjia
en   allergenic
he   אלרגני

alerjia   nom
Un reata danante en la sistem imunial a un sustantia vera nonosiva, tipal un comeda o polvo
en   allergy
he   אלרגיה, רגשת

aletera   verbo nontransitiva
(Un frase o linia de poesia) conteni parolas con la mesma sona o letera inisial
en   alliterate
he   להשתמש באליטרציה

aleuron   nom
Protena retenida como granetas en la selulas de semes de plantas
en   aleurone (botany)
he   אלאורון (חלבון)

aleut   ajetivo
Pertinente a la popla de la Isolas Aleutian e otra isolas en la Mar Bering e partes de Alaska ueste, o a sua lingua
en   Aleut (person, language)
he   אלאוטי

aleutian   ajetivo
Pertinente a un cadena de isolas volcanal cual estende a sude-ueste de la penisola alaskan
en   Aleutian
he   שקשור לאיים האלאוטיים

[Alexandria] Alexandria   nom
La porto xef de Misre, fundida en 332 aec par Alexandro la Grande, e un sentro major de la cultur eliniste
en   Alexandria (Egyptian city)
he   אלכסנדריה

alexia   nom
Un noncapasia de reconose o leje parolas, tipal par causa de dana serebral
en   alexia (medical)
he   (רפואה) אלקסיה

alfa   nom   «Α α»
La letera prima de la alfabeta elinica; la membro dominante de un grupo
en   alpha (Greek letter)
he   אלפא (האות הראשונה באלפבית היווני)

[alfabeta] alfabeta   nom
Un serie de leteras o simboles en un ordina fisada, usada per representa la sonas fundal de un lingua, tipal un serie de simboles per e consonantes e vocales
en   alphabet
he   אלפבית

[alfalfa] alfalfa   nom
Un legum con flores bluin e folias simil a trefolias, comun cultivada per nuri bestias
Medicago sativa
en   alfalfa
he   אלפלפה, אספסת

alfanumeral   ajetivo
Composada de sola leteras e dijitos
en   alphanumeric
he   אלפאנומרי (שמכיל אותיות וספרות)

alga   determinante
Referente a un person o cosa nonidentifiada, o un cuantia nonesata ma relativa peti.   (Leje plu…)
en   some, certain, a certain (unspecified identity); some, several, a few, a little, a small amount of (unspecified quantity); any (in a question or negative statement)
he   כמה, מספר מסויים, מספר מועט

[alge] alge   nom
Un planta simple, con clorofila ma sin radises, talos, folias, flores e texeda vascular, tipal trovada en acua
en   alga
he   אצה

algoncian   ajetivo
Pertinente a un familia de linguas de la americanes orijinal, parlada en Canada este e sentral, la SUA norde-sentral, e la costa de la Mar Atlantica
en   Algonquian (language family)
he   אלגונקי, שמשתייך למשפחת השפות האלגונקיות

algoncin   ajetivo
Un lingua en la familia algoncian
en   Algonquin (language)
he   אלגונקי

algoritmo   nom
Un serie de pasos macinal per fa un calcula o solve un problem
en   algorithm
he   אלגוריתם

algun   pronom
Alga person
en   someone, somebody; anyone, anybody (in a question or negative statement)
he   מישהו

alia   verbo nontransitiva
(Un person, grupo o nasion) coopera con un otra per benefica ambos; (metales) misca per formi un metal nova, tipal plu forte o min corodente
en   ally; alloy
he   לבוא בברית, ליצור ברית

alias   nom
Un identia falsa o finjeda; un nom alternativa per un arcivo o comanda en un computador; cada de un grupo de siniales cual deveni identica cuando on sample los
en   alias
he   כינוי, שם בדוי, שם נוסף

alibi   nom
Un declara o atesta ce algun no ia es presente a un ata, tipal criminal
en   alibi
he   אליבי

alidada   nom
Un aparato per determina dirijes o mesura angulos
en   alidade (device)
he   מכשיר למדידת מרחק

aliena   verbo transitiva
Fa ce (algun) senti isolida e separada; dona (diretos de propria) a un otra person o grupo
en   alienate
he   לנכר, לגרום לריחוק; להפקיע

[aligator] aligator   nom
Un retil grande e semiacual, simil a un crocodil ma con testa plu larga e corta, nativa de la Americas e Jonguo
Alligator
en   alligator
he   תנין, אליגטור

alinia   verbo nontransitiva
Es en linia reta; es coreta locada en relata a un otra cosa
en   align, line up
he   להתיישר, להסתדר בשורה; להתייצב לצד

[alio] alio   nom
Un planta en familia de onion; la bulbo de esta, con odor e sabor multe forte, usada en cosini
Allium sativum
en   garlic
he   שום

alise   nom
Un venta, spesial a mar, cual move constante en dirije a la ecuator, de la norde-este en la emisfera norde e de la sude-este en la emisfera sude
en   trade wind
he   רוחות הסחר

alitose   nom
Respira malodorosa
en   halitosis, bad breath
he   ריח רע מהפה, באשת

aljebra   nom
Un ramo de matematica cual usa leteras e otra simboles per representa valuas en formulas e egalis
en   algebra
he   אלגברה

almanaco   nom
Un calendario anial cual inclui datas importante, datos astronomial, tables de mareas, etc
en   almanac
he   אלמנך

[alno] alno   nom
Un arbor comun en familia de betul, con folias dentosa, amentos mas e conos fema
Alnus
en   alder
he   אלנוס, אלמון (עץ)

alo   esclama   (dise ‘aló’)
Salutante algun o revelante sua presentia
en   hello, hi, yo (greeting); hey, yoo-hoo (calling)
he   שלום, היי

alo-   prefisa
Otra
en   allo- (other)
he   (קידומת טכנית) אחר או נוסף

[aloata] aloata   nom
Un simia con coda prensil e un cria forte e ululante, nativa de la tropicos de America
Alouatta
en   howler monkey
he   שאגן (קוף)

[aloda] aloda   nom
Un avia cantante peti, con plumas de bandetas brun, cual canta volante
Alaudidae
en   lark, skylark
he   עפרוני

[aloe] aloe   nom
Un planta suculente, usada en medica, tipal con roseta de folias pulposa e dentosa, e flores tubo o campanin sur talos longa
Aloe
en   aloe (plant)
he   אלווי, אלוורה

alojen   ajetivo
Pertinente a la elementos fluor, cloro, bromo, iodo e astato
en   halogen
he   הלוגן

alopatia   nom
La trata normal de maladias, usante medisines con efetos cual oposa la sintomes
en   allopathy
he   אלופתיה

alora   averbo
A acel ora, a acel tempo, a la tempo pertinente, no aora; donce
nb   No usa "alora" per dise "como la ata seguente". Usa "a pos" per esta.
‹ la vive alora ia es plu simple; si tu come tua vejetales, alora tu pote come un torteta ›
→ a pos
en   then (at that time); therefore, consequently, in that case
he   אז, בזמן ההוא

[alosa] alosa   nom
Un pex, simil a un arenge, cual abita en la mar ma vade a rios per ovipari
Alosa, Caspialosa
en   shad (fish)
he   עלוזה (דג)

[alosauro] alosauro   nom
Un dinosauro grande, bipede e carnivor de la tarda de la jurasica
Allosaurus
en   allosaur, allosaurus
he   אלוסאור

alotropo   ajetivo
(Un elemento) con du o plu formas fisical
en   allotropic
he   אלוטרופי

[alpaca] alpaca   nom
Un mamal domada de America Sude, con capeles longa, relatada a la liama, valuada per sua lana; lana o stofa fabricada de esta
Vicugna pacos
en   alpaca (animal)
he   אלפקה

[alpe] alpe   nom
Un monte alta, tipal con neva a sua apico
en   alp
he   הר גבוה ומושלג

[alsea] alsea   nom
Un planta alta eurasian en familia de malva
Alcea rosea
en   hollyhock (plant)
he   חוטמית (צמח)

[alselafo] alselafo   nom
Un antilope grande de Africa, en familia de gnu, con testa longa e dorso inclinada
Alcelaphus buselaphus
en   hartebeest (antelope)
he   בובאל איילי (אנטילופה)

alta   ajetivo
Con multe estende a supra; situada a un distantia grande supra la tera, la mar, o un otra punto de refere; (un parte) situada supra la loca tipal; con grado o prestijia plu ca la majoria; con custa plu ca normal; (un tono) con frecuentia grande
en   high, lofty; upper, higher; tall; majestic, great
he   גבוה, רם, נישא, עליון

altai   ajetivo
en   Altai, Altay (person, language)
he   אלטאי, שפה אלטאית

altaica   ajetivo   (dise ‘altaïca’)
Pertinente a un familia proposada de linguas cual inclui turces, mongol e otras en Asia norde
en   Altaic
he   ששייך למשפחת השפות האלטאיות

altar   nom
Un table o bloco plana, usada como la foca de rituos relijiosa, incluinte per sacrifias a un dio; un table en un eglesa cristian sur cual la pan e la vino es santida en la rituo de comunia
en   altar
he   מזבח

[altea] altea   nom
Un planta perene de Eurasia, trovada a la rivas de rios e en pantanes salosa
Althea
en   althaea, marshmallow
he   נטופית (צמח)

altera   verbo nontransitiva
Cambia, tipal en modo minor ma sinifiosa
en   alter, modify, customize/customise
he   להשתנות, להתאים

alterna   verbo nontransitiva
(Du o plu cosas) aveni repeteda, la un pos la otra
en   alternate, take turns
he   להתחלף לסירוגין

alternativa   ajetivo
Disponable como un otra posible
en   alternative
he   אלטרנטיבי, חלופי

altimetre   nom
Un aparato per determina altia, tipal en un avion
en   altimeter
he   מד גובה

alto   ajetivo
(Un vose cantante de om) la plu alta; (un vose cantante de fem) la plu basa; (un strumento) con tono cuasi la plu alta en sua familia
en   alto, countertenor (music)
he   (מוזיקה) אלט

altruisme   nom
Un ansia desinteresada e nonegosa per la bonstate de otras; compatia
en   altruism
he   אלטרואיזם, זולתנות

alum   nom
Un composada astrinjente sin color, usada en tinje, tana e medica
en   alum (substance)
he   אלום האשלגן

alula   nom
Un parte peti de un ala de un avia, relatada a la diton de umanas, cual controla alga plumas a la borda distante de la ala
en   alula, bastard wing

aluminio   nom   «Al»
La elemento cimical con numero atomal 13, un metal lejera de gris arjentin
en   aluminum/aluminium
he   אלומיניום (יסוד)

alusina   verbo transitiva
Esperia un persepi parente real de (un cosa) cual no es vera presente, tipal pos usa un droga o par causa de un maladia mental
en   hallucinate
he   להזות

alusinojen   ajetivo
(Un sustantia) causante alusinas
en   hallucinogenic
he   שגורם להזיות

aluvia   nom
Un deponeda de arjila e arena lasada par acua fluente en la vale o delta de un rio, tipal fertilinte la tera
en   alluvium (geology)
he   אדמת סחף

alveolite   nom
Un inflama de la alveolos de la pulmones
en   alveolitis
he   דלקת של נאדיות הנשימה

alveolo   nom
Cada de la multe sacos peti de aira en la pulmones; la caveta ososa cual teni la radis de un dente
en   alveolus, air sac; tooth socket
he   נאדית ריאה; מכתש שן

am   corti
Ante mediadia
en   a.m.
he   לפני הצהריים

ama   verbo transitiva
Gusta profonda e desira la felisia de (algun, tipal un relatada); es forte atraeda a (algun) en modo romantica o sesal; senti multe zelosa sur (un sujeto o ocupa)
en   love, cherish
he   לאהוב, להוקיר

[amaca] amaca   nom
Un leto, fabricada de lona o de un rede de cordas, e suspendeda par cordas a la finis, tipal usada en un jardin o barcon
en   hammock
he   ערסל

[amamelia] amamelia   nom
Un arboreta con flores jala bonodorosa; un losion fabricada de la cortex e folias de esta
Hamamelis
en   witch hazel
he   הממליס (צמח)

[amando] amando   nom
Un arbor en familia de rosa, cual produi un noza comable
Prunus dulcis
en   almond (tree)
he   שקדייה

[amanita] amanita   nom
Un agarico alusinojen, enebriante e alga venenosa, orijinal de la emisfera norde
Amanita muscaria
ca   reig de fageda, reig bord
da   rød fluesvamp
de   fliegenpilz
en   fly agaric, fly amanita
eo   muŝoamanito
es   matamoscas, falsa oronja
fr   amanite tue-mouches, fausse oronge
it   ovolo malefico
he   אמניטה (פטריית הזייה)
ja   ベニテングタケ
nl   vliegenzwam
pt   agário-das-moscas, mata-moscas
ru   мухомо́р кра́сный

amaperil   nom, composada (verbo+nom)
Un person ci gusta fa atas perilosa
en   daredevil
he   נמשך לסכנה

amar   nom
La desende a mar de un veculo spasial reveninte
en   splashdown (of spacecraft)
he   נחיתה בים

[amaranto] amaranto   nom
Cualce planta de la jenero Amaranthus, tipal con flores pico e verde, roja o purpur; un flor mitolojial cual pali nunca
Amaranthus
en   amaranth
he   ירבוז

amarga   ajetivo
Con un sabor o odor agu, no dulse; (un person) coler, doleda o odiosa par causa de mal esperias o un senti de es nonjusta tratada
en   bitter (taste, emotion), acerbic, acrid; embittered, acrimonious, rancorous
he   מר, מריר; ממורמר

[amarilis] amarilis   nom
Un planta bulbal con flores trompetin e folias bandin
Amaryllidaceae
en   amaryllis (plant)
he   אמריליס יפהפה (צמח)

amarina   ajetivo
Pertinente a un popla de Itiopia sentral o a sua lingua semita
en   Amhara, Amharic (person, language)
he   אמהרי

amasa   verbo transitiva
Masaje (pasta) par mano en prepara pan; manipula (arjila, etc) en modo simil
en   knead, work
he   ללוש

amato   nom
Un ata cual on fa frecuente per plaser en sua tempo libre
en   hobby, pastime, avocation
he   תחביב

[amazona] amazona   nom
Un membro de un raza mital de gerores fema; (metafor) un fem grande e forte
en   Amazon (mythology)
he   אמזונה

Amazona   nom
en   Amazon (region)
he   אמזונס

[ambar] ambar   ajetivo
Con color jalin, simil a miel
en   amber (color/colour)
he   צבע ענבר

ambargris   nom
Un materia sirin secreteda en la intestines de la caxalote, cual flota en la mares tropical e es usada en la fabrica de parfum
en   ambergris (substance)
he   ענבר אפור

ambasada   nom
La casa e ofisias de un ambasador
en   embassy, consulate
he   שגרירות, קונסוליה

ambi-   prefisa
Ambos, a ambos lados
en   ambi-
he   (סיומת טכנית) שני הצדדים

ambidestrosa   ajetivo
Capas de usa ambos sua manos a grado egal bon
en   ambidextrous
he   שווה ידיים, שמיומן באותה מידה בשתי ידיו

ambie   verbo transitiva
(Un situa natural) ensirca
en   surround
he   להקיף, לכתר

ambifilia   nom
Un atrae sesal a e omes e femes
en   ambiphilia
he   דו-מיניות

ambigua   ajetivo
Nonclar o nonesata car un eleje entre alternativas no es desideda; con sinifia duple o permetente plu ca un interprete
en   ambiguous, equivocal
he   דו-משמעי; רב-משמעי; מעורפל

ambivale   verbo nontransitiva
Senti emosias miscada o contradisente
en   be ambivalent, have mixed feelings
he   להרגיש אמביוולנטי, דו-ערכי

ambliopia   nom
Un descapasia de vide sin dana fisical a la oio
en   amblyopia, lazy eye (medical)
he   עין עצלה

ambos   determinante
Tota la du en junta; cada de la du a grado egal
‹ ambos formas es coreta ›
en   both
he   שני ה-

[ambrosia] ambrosia   nom
La comeda prefereda de la dios elinica antica; (metafor) un comeda estrema deletosa; un planta de America Norde en familia de margarita, comun causante un responde alerjica; un deser de oranias e coco trinxada; un produida fungal comeda par alga spesies de scarabe
Ambrosia
en   ambrosia
he   אמברוסיה

[ambulansia] ambulansia   nom
Un veculo con aparatos spesial per transporta persones malada o ferida a ospital
en   ambulance
he   אמבולנס

[amburger] amburger   nom
Un masa ronda de carne moleda de bove, fritada o grilida e tipal poneda sur un paneta con spises diversa
en   hamburger, burger
he   המבורגר

[ameba] ameba   nom
Un animal uniselulal, cual estende protoplasma ditin per move e catura comedas
en   ameba/amoeba
he   אמבה

amebiside   nom
Un medisin per mata amebas
en   amebicide/amoebiside
he   תרופה נוגדת אמבות

amen   esclama
Espresante acorda o espera, tipal a la fini de un prea o imno
en   amen, so be it, let it be
he   אמן, אמירת אמן

amento   nom
Un spiga pendente de arbores como nozetos e salses
en   catkin
he   תפרחת

America   nom
Un masa de tera en la emisfera ueste, composada de America Norde e America Sude, juntada par America Sentral
en   America
he   יבשת אמריקה

amerisio   nom   «Am»
La elemento cimical con numero atomal 95
en   americium (element)
he   אמריקיום (יסוד)

ametista   nom
Un jem de cuarzo purpur o violeta
en   amethyst
he   אחלמה

amfetamina   nom
Un droga sinteseda, abituante, e capas de altera la umor, usada per stimula o como medisin per trata maladias de atende e velia
en   amphetamine
he   אמפטמין

amfi-   prefisa
Ambos, a ambos lados
en   amphi-
he   (סיומת טכנית) שני הצדדים

amfibio   nom
Un animal vertebrato con sangue fria, parteninte a la clase de ranas, sapos, tritones e salamandras
Amphibia
en   amphibian
he   דו-חי

amfibraco   nom
Un metre poesial, composada de un silaba longa o asentuada entre du silabas corta o nonasentuada
en   amphibrach
he   מקצב בשירה המורכב מרצף של שתי הברות קצרות שביניהן הברה ארוכה

[amfiteatro] amfiteatro   nom
Un teatro ronda, comun sin teto, con loca sentral per presenta dramas o sportes
en   amphitheater/amphitheatre
he   אמפיתיאטרון

amfora   nom
Un jar o carafa alta e antica, elinica o roman, con colo magra e du manicos
en   amphora
he   אמפורה (כלי קיבול מחרס ביוון ורומא הקדומות)

ami   nom   (dise ‘amí’)
Un person con ci on ave un lia de amosia mutua, tipal nonsesal e estra sua familia
en   friend, mate, pal, chum, buddy, crony
he   חבר, ידיד, רע

amida   nom
Un composada derivada de amonia
en   amide (substance)
he   (כימיה) אמיד

amidon   nom
Un materia sin odor o sabor, comun en texedas de plantas, cual es un reserva de carboidratos e un parte importante de la dieta umana
en   starch
he   עמילן

amigdala   nom
Un masa de materia gris en cada emisfera de la serebro, con forma simil a un amanda, cual partisipa en la esperia de emosias
en   amygdala
he   אמיגדלה

amil-   prefisa
Amidon
en   amyl-
he   (סיומת טכנית) שקשור לעמילן

amilase   nom
Un enzima, trovada en saliva e licuida de la pancreas, cual converti amidon e glicojen a zucares simple
en   amylase
he   עמילז (אנזים)

amiloide   nom
Un protena simil a amidon, deponeda en la figato, renes, spleno o otra texedas en alga maladias
en   amyloid
he   עמילואיד (חלבון)

amiloidose   nom
Un maladia marcada par la depone de amiloide en la corpo
en   amyloidosis
he   עמילואידוזיס

amina   ajetivo
Pertinente a un composada organica derivada de amonia par sustitui grupos organica per atomes de idrojen
en   amine (chemistry)
he   (כימיה) אמין

aminoasida   nom
Un composada organica simple cual conteni e un grupo de carbosil e un grupo amina
en   amino acid
he   חומצה אמינית

aminobutirica   ajetivo
Cualce de tre composadas isomeral (AABA, BABA, GABA)
en   aminobutyric
he   אמינובוטירי

amir   nom
Un renor arabi o muslim, istorial un xef local o un comandor militar
en   emir, amir
he   אמיר (נסיך מוסלמי)

amira   verbo transitiva
Regarda (un person, ojeto o cualia) con respeta, aproba o plaser
en   admire
he   להעריץ, להתפעל

amiral   nom
La comandor de un marina
en   admiral
he   אדמירל

amix   ajetivo
Pertinente a un seta menonita cual ia fundi comunias de cultivores en Pennsylvania, Ohio, e otra rejiones en America Norde, notada per sua usa de cavalos e caros
en   Amish
he   האמיש

amnesia   nom
Un perde partal o completa de memoria
en   amnesia
he   אמנזיה, שיכחון

amnestia   verbo transitiva
Dona un pardona ofisial a (persones condenada per ofendes political)
en   amnesty, grant amnesty to
he   לחון

amnio   nom
La membrana la plu interna cual enclui la embrio de un mamal, avia o retil
en   amnion (membrane)
he   קרום שפיר

amnio-   prefisa
Amnio
en   amnio-
he   (קידומת טכנית) ששייך לשפיר

amniosentese   nom
La esamina de la licuida amnial par la introdui de un ago cavetin a la utero, usada per deteta developas nonormal en un feto
en   amniocentesis
he   בדיקת מי-שפיר

amoc   ajetivo
Conduinte en modo demente, violente e destruinte
en   amok, amuck
he   אמוק, אחוז טירוף

amonia   nom
Un gas sin color ma con odor forte, cual on pote disolve en acua per limpi
en   ammonia
he   אמוניה

amonio   nom
La cation presente en disolves de amonia e en sales derivada de amonia
en   ammonium
he   אמוניום

amorti   verbo transitiva
Fa ce (un cosa) deveni min forte o intensa; fa ce (un sona) deveni plu cuieta o min clar; redui o estingui (un deta) par paias periodal
en   muffle, deaden, dampen; amortize/amortise, absorb (cost)
he   לעמעם, לשכך; להשקיט; לצמצם חוב

amper   nom
Un unia de corente eletrical, egal a un flue de un culom per secondo
en   ampere, amp
he   אמפר

amperimetre   nom
Un strumento per mesura corente eletrical
en   ammeter
he   מד-זרם

[ampola] ampola   nom
Un capsula selida de vitro conteninte un licuida, tipal per injeta; un bulbo de lus
en   ampoule; lightbulb
he   אמפולה

amputa   verbo transitiva
Corti o sutrae (un parte de corpo), tipal par sirurjia
‹ amputa la gama de algun ›
en   amputate
he   לקטוע, לכרות איבר

an   averbo
Asentuante lo cual segue direta, tipal sujestante ce lo es nonespetada
en   even
eo   eĉ
he   אפילו

ana-   prefisa
A supra, a retro, denova
en   ana-
he   (קידומת טכנית) שוב, מכיוון

anabatisme   nom
La prinsipe ce batiza debe es sola per adultes credente
en   Anabaptism (Christianity)
he   אנאבפטיזם

anaboli   verbo nontransitiva
(Un organisme) sintese moleculas complicada de moleculas simple, con reserva de enerjia
en   anabolize/anabolise (biology)
he   להפוך לאנבולי

[anacardio] anacardio   nom
Un arbor american tropical en familia de mango
Anacardium
en   cashew (tree)
he   קשיו (עץ)

[anaconda] anaconda   nom
Un serpente semiacual en familia de boa, nativa de la tropicos de America Sude
Eunectes
en   anaconda
he   אנקונדה

anacron   ajetivo
(Un cosa) parteninte o conveninte a un periodo otra ca lo en cual lo esiste
en   anachronistic
he   אנכרוניסטי

anafase   nom
La fase tre de la divide de selulas
en   anaphase

anafor   ajetivo
(Un parola, tipal un pronom) representante un otra parola plu temprana, per evita repete; (en retorica) (un parola o formula) repete a la comensa de cada de un serie de proposas
en   anaphoric
he   אנאפורי (שיש בו מילה שחוזרת בתחילת כל שורה)

anagram   nom
Un parola, nom o espresa formida par reordina la leteras de un otra
en   anagram
he   אנגרמה, היפוך אותיות

analesica   ajetivo
(Un droga) restorante sania o fortia
en   analeptic
he   (רפואה) מעורר, מחזק

analise   verbo transitiva
Esamina metodosa e detaliosa la strutur o composa de (un ojeto o informa), tipal per esplica e interprete
en   analyze/analyse, dissect; parse
he   לנתח, לבחון

analoja   ajetivo
Comparable en alga modos, tipal en un modo cual clari la natur de la cosas comparada; (un strutur anatomial) con un funsiona simil ma con evolui diferente, como la alas de insetos e avias; (un sinial o dato) espresada como un cuantia fisical capas de varia continuante
en   analogous, analog/analogue
he   מקביל, דומה

anamnese   nom
La recorda de cosas de un esiste suposada ante esta; un reporta par un pasiente de sua istoria medical
en   anamnesis (medical)
he   אנמנזה (תולדות המחלה)

anamorfose   nom
Un desinia o projeta contorseda cual pare normal cuando on regarda lo de un punto spesial o con un miror o lente conveninte; un cambia gradal de forma biolojial a un tipo plu alta
en   anamorphosis (optics, biology)
he   אנמורפיזם (טכניקת ציור בו הפרספקטיבה מעוותת); שינוי הדרגתי לצורה מורכבת יותר

[ananas] ananas   nom
Un planta american con un spiral de folias spinosa sur un tronceta spesa; la fruta grande e jusosa de esta, con pulpa bonodorosa, jala e comable
Ananas
en   pineapple (plant, fruit)
he   אננס

anapesto   nom
Un metre poesial, composada de du silabas corta o nonasentuada, segueda par un silaba longa o asentuada
en   anapest/anapaest
he   משקל בשירה

anarcia   nom
Un state de desordina resultante de un asentia o nonreconose de autoria; la asentia de governa e libria asoluta de la individua, regardada como un ideal political
en   anarchy, lawlessness
he   אנרכיה, אי סדר

anastomose   nom
Un lia traversal entre tubos, fibres o dutos visina
en   anastomosis (anatomy)
he   (אנטומיה) השקה (חיבור בין שני איברים צינוריים)

[Anatolia] Anatolia   nom
La penisola ueste de Asia, a sude de la Mar Negra e a norde de la Mar Mediteraneo, cual formi la plu de Turcia moderna
en   Anatolia, Asia Minor
he   אנטוליה

anatomia   nom
La siensa de la strutur fisical de umanas, animales e otra organismes
en   anatomy
he   אנטומיה

anc   nom
Un ojeto o desinia simil a un crus, ma con un anelo en loca de la braso superior, usada en Egipte antica como simbol de vive
en   ankh (cross)
he   ענח, מפתח החיים (סמל דמוי צלב במצרים העתיקה)

[anca] anca   nom
Un estende de la pelvis e la femor en umanas e cuatropedes
en   hip, rump
he   עצם הירך

ancaran   ajetivo
(Un capra, coneo o gato) de un raza con pelo longa
en   angora (cat, goat, rabbit)
he   אנגורה

ance   averbo
En ajunta
en   also, as well, too, likewise
he   גם

[ancilosauro] ancilosauro   nom
Un dinosauro erbivor e cuatropede con armur de laminas ososa, de la cretasica
Ankylosauria
en   ankylosaurus
he   אנקילוזאורוס

ancilose   nom
Un rijidia nonormal de un junta, causada par un fusa de osos
en   ankylosis (medical)
he   קושי בתנועה של מפרק עקב איחוי עצמות

[ancilostoma] ancilostoma   nom
Un nematodo parasital cual abita la intestines de umanas e otra animales, comente sangue
Ancylostoma
en   hookworm
he   תולעת קרס

ancilostomiase   nom
Un maladia resultante de un infesta par ancilostomas, comun causante anemia grave
en   hookworm, ancylostomiasis
he   מחלה הנגרמת על-ידי תולעי קרס

[ancor] ancor   nom
Un ojeto pesosa, liada a un cordon e usada per fisa un barcon a la fondo de mar
en   anchor
he   עוגן

ancora   averbo
Asta e incluinte la presente o un tempo spesifada
en   still (ongoing); even (more, less)
he   עדיין

[Andalusia] Andalusia   nom
Un rejion autonom de Espania sude; un rena moro en la eda medieval
en   Andalusia (Spanish region)
he   אנדלוסיה

Andaman   nom
en   Andaman
he   אנדמן

[Andes] Andes   nom, plural
Un cadena de montes en America Sude, cual estende longo la costa de la Pasifica
en   Andes
es   Andes
he   הרי האנדים

[Andora] Andora   nom
Un pais peti e autonom en Europa sude-ueste, entre Frans e Espania
en   Andorra
es   Andorra
he   אנדורה

andro-   prefisa
Mas, om
en   andro- (male)
he   (קידומת טכנית) שקשור למין זכר

androfilia   nom
Un atrae sesal a omes
en   androphilia
he   אנדרופיליה, משיכה לגברים

androfobia   nom
Un teme estrema o nonrazonada de omes o cosas mas
en   androphobia
he   אנדרופוביה, הירתעות מגברים

androide   ajetivo
en   android
he   אנדרואיד

androjen   nom
Un ormon sesal mas, como testosterona
en   androgen
he   אנדרוגן (הורמון)

androjine   ajetivo
Con aspeta partal mas e partal fema; con seso nondeterminable; con cualias fisical de ambos sesos
en   androgynous, hermaphroditic, epicene
he   אנדרוגיני (בעל תכונות זכריות ונקביות כאחד)

[andromeda] andromeda   nom
Un arboreta perene en familia de erica, con grupos de flores campanin e peti
Andromeda, Pieris
en   andromeda, pieris (plant)
he   אנדרומדה (צמח)

Andromeda   nom
(En mitos elinica) un prinsesa itiopian, fisada a un roca asta cuando Perseo ia salva el; un constela grande entre Perseo e Pegaso
en   Andromeda (mythology, constellation)
he   הנסיכה אנדרומדה; קבוצת הכוכבים אנדרומדה

androseo   nom
La grupo completa de stames de un flor
en   androecium (botany)
he   כלל האבקנים בפרח אחד

anela   verbo transitiva
Desira profonda o forte
en   long for, yearn for, pine for, hanker for, crave, deeply desire, covet
he   לערוג, להשתוקק, לחשוק, לכמוה

[anelido] anelido   nom
Un membro de un filo grande de vermes sesionida, incluinte vermes de tera e sucasangues
Annelida
en   annelid (worm)
he   תולעת טבעתית

anelo   ajetivo
Con forma de O
en   ring-shaped, annular
he   טבעתי, בצורת טבעת

anemia   nom
Un maladia marcada par un manca de selulas roja o de emoglobina en la sangue, causante palia e fatiga
en   anemia/anaemia
he   אנמיה

anemometre   nom
Un aparato per mesura la rapidia de la venta o de cualce corente de gas
en   anemometer
he   מד-רוח

[anemone] anemone   nom
Un planta en familia de ranunculo, con flores briliante colorida
Anemone
en   anemone
he   כלנית

anestese   verbo transitiva
Dona un medisin a (algun) per redui dole
en   anesthetize/anaesthetise
he   לאלחש, להרדים

[aneto] aneto   nom
Un erba bonodorosa en familia de persil, con folias blu-verde e flores jala; la folias e semes de esta, usada en cosini e medica
Anethum graveolens
en   dill (plant)
he   שמיר, שבת ריחני

aneurisme   nom
Un grandi local de un arteria, causada par un debili de la mur arterial
en   aneurysm
he   מפרצת

[angila] angila   nom
Un pex serpentin con corpo longa e magra e pinas mal developada
Anguilliformes
en   eel
he   צלופח

anglican   ajetivo
Pertinente a la Eglesa de England o cualce eglesa liada con lo
en   Anglican
he   אנגליקני

[anglosason] anglosason   ajetivo
Pertinente a la abitores germanica de England o sua lingua
en   Anglo-Saxon, Old English
he   אנגלו-סקסי

[Angola] Angola   nom
Un pais a la costa ueste de Africa sude
(capital: Luanda)
en   Angola
he   אנגולה

[angostura] angostura   nom
Un planta de America Sude, de cual sua cortex produi un licuida bonodorosa e amarga, usada en bevidas e per redui febre
Angostura, Galipea
en   angostura
he   אנגוסטורה (צמח שמשמש להכנת משקה אלכוהולי מר)

[Anguila] Anguila   nom
Un isola e teritorio ultramar brites en la Mar Caribe
en   Anguilla
he   אנגווילה

angulo   ajetivo
en   angular
he   זוויתי

[angulometre] angulometre   nom
Un strumento per mesura angulos
en   protractor
he   מד-זווית

angusa   verbo transitiva
Fa ce (algun) sufri multe en sua mente par un xoca o preocupa ansiosa
en   distress, appal/appall, harrow
he   לגרום לייסורים, לגרום למצוקה

[ani] ani   nom
Un avia briliante negra de America Sentral e Sude, en familia de cucu, con coda longa e beco grande e profonda
Crotophaga
en   ani (bird)
he   אני (ציפור)

anilina   nom
Un licuida oliosa sin color, presente en catran de carbon, usada per fabrica tinjentes, medisines e plasticas
en   aniline (substance)
he   אנילין

anima   verbo nontransitiva
Deveni vivente o parente vivente
en   animate, come to life
he   להתעורר לחיים

animal   ajetivo
(Un organisme) ci nuri se con materia organica, tipal con organos de sensa e sistem de nervos spesialida, e capas de responde rapida a stimulas
en   animal
he   חיה, בעל חיים

anime   nom
Un anima nion, tipal un nara siensal, e violente o sesosa a veses
en   anime (animation)
he   אנימה, אנימציה יפנית

animisme   nom
La crede ce spiritos esiste en cosas nonumana (animales, plantas, fenomenos natural)
en   animism
he   אנימיזם

[aninga] aninga   nom
Un avia de acua dulse, con colo e beco longa, cual catura pexes par lansi los con sua beco
Anhinga
en   darter, snakebird
he   נחשון (ציפור)

anio   nom
Un periodo de 365 o 366 dias; la periodo en cual un planeta completi un orbita sirca la Sol
en   year
he   שנה

anion   nom
Un ion con carga negativa
en   anion (chemistry)
he   (כימיה) אניון

[anis] anis   nom
Un planta mediteranean en familia de persil, cultivada per sua semes; esta semes, usada en cosini e medisin
Pimpinella anisum
en   anise, aniseed (plant)
he   אניס (צמח)

aniso-   prefisa
Diferente, nonegal
en   aniso- (unequal)
he   (קידומת טכנית) שונה, לא שווה

aniversario   nom
Un selebra a cada anio a la dia de un aveni pasada, per esemplo un nase, sposi o institui
en   anniversary, birthday, jubilee
he   יום השנה; יום הולדת

[anjel] anjel   nom
(En alga credes) un spirito cual es un aidor o mesajor de Dio, tipal representada como un umana con alas e un roba longa; un spirito atendente, spesial un bonvolente
en   angel
he   מלאך

[anjelica] anjelica   nom
Un planta alta e bonodorosa en familia de persil, con folias grande e flores jalin verde, usada en cosini e medisin erbal
Angelica
en   angelica (plant)
he   מלאכית (צמח)

anjina   nom
Un maladia marcada par dole intensa en la peto, e tipal ance a la spalas, brasos e colo, causada par un flue nonsufisinte de sangue a la cor
en   angina
he   אנגינה

anjio-   prefisa
Dutos sangual
en   angio- (blood vessels)
he   (קידומת טכנית) שקשור לכלי הדם

anjioma   nom
Un tumor nonosiva, produida par la dilata o formi nova de dutos sangual
en   angioma
he   (רפואה) אנגיומה

anjiopatia   nom
Cualce maladia de la dutos sangual
en   angiopathy
he   מחלה של כלי הדם

anjioplastia   nom
La repara o desbloci de un duto sangual par sirurjia
en   angioplasty
he   אנגיופלסטיה

anjiosperma   nom
Un planta con flores cual produi semes encluida en un carpel
en   angiosperm
he   צמח תרמילי

anjiotensina   nom
Un protena de cual sua presentia en la sangue aida la secrete de aldosterona e leva la presa sangual
en   angiotensin
he   אנגיוטנסין

ano   nom
La abri tra cual feces sorti de la corpo
en   anus
he   פי הטבעת

anodo   nom
Un eletrodo positiva cargada, par cual eletrones entra a un aparato eletrical; la eletrodo negativa cargada de un aparato eletrical cual furni corente
en   anode
he   אנודה

anomal   ajetivo
Deviante de lo cual es normal o espetada
en   anomalous
he   אנומלי, חריג

[anomalur] anomalur   nom
Un scural peti con pel entre sua gamas anterior e posterior cual el usa per vola de arbor a arbor
Pteromyinae, Anomaluridae
en   flying squirrel, anomalure
he   סנאי מעופף

anomia   nom
Un forma de afasia en cual on no recorda la nomes de ojetos comun
en   anomia (medical)
he   אנומיה (שכחה של שמות)

[anona] anona   nom
Un planta florinte en familia de asimina, con frutas comable
Annona
en   annona (plant)
he   אנונה (צמח, פרי)

anonim   ajetivo
No identifiada par nom; sin marcas o cualias cual aida identifia
en   anonymous, faceless, incognito
he   אנונימי, אלמוני

[anorac] anorac   nom
Un jaca nonpermeable, tipal con un capeta, orijinal usada en zonas polal
en   anorak
he   מעיל עם ברדס

anorexia   nom
Un asentia o perde de apetito per comedas; un maladia emosial, marcada par un desira osesente per perde pesa par refusa come
en   anorexia
he   אנורקסיה

anosia   nom
Un asentia o manca de osijen en la texedas
en   anoxia (medical)
he   חוסר חמצן

anota   verbo transitiva
Ajunta notas a (un testo o scema) cual esplica o comenta sur lo
en   annotate
he   להוסיף הערות, לפרש

ansia   nom
Un senti de ajita, preocupa o turba, tipal sur un aveni prosiminte de cual sua resulta es nonserta
en   anxiety, worry, unease, nervousness, apprehension, dread, angst, trepidation
he   חרדה, דאגה, חשש, מתיחות

anstrom   nom
Un unia de longia egal a 10^-10 metres, xef usada per espresa longias de ondas eletromagnetal e distantias interatomal
en   angstrom (unit of length)
he   אנגסטרום

antartica   ajetivo
Pertinente a la continente sirca la polo sude, de cual la plu es a sude de la sirculo antartica e cuasi tota es covreda par glasias
en   Antarctic
he   אנטרקטי

ante   preposada
1   A, o prosima a, la fronte de (alga cosa), o plu fronte ca lo.   (Leje plu…)
nb   Multe cosas ave un lado evidente major con cual los fasa la mundo. En otra casos, "ante" indica simple la lado plu prosima a la parlor.
‹ mea peto es ante mea dorso; un can dormi ante la boteca; la casa sta ante un colina ›
en   in front of, before (in space)
eo   antaŭ
fr   devant
he   לפני, מלפנים, מול
2   Movente per ateni la fronte de (alga cosa)
nb   Per espresa esta en modo plu clar, on pote dise "a ante".
‹ me veni ante tu per demanda per tua pardona ›
en   (moving) to the front of, in front of
eo   antaŭ -n
he   ללפני, בפני
3   En la tempo presedente (alga cosa)
nb   Per introdui un proposa suordinada, usa "ante cuando" en loca. La averbo con la sinifia "a un tempo plu temprana" es "a ante".
‹ janero veni ante febrero; me espera fini la labora ante la reposa de sol ›
→ cuando
en   before (in time), earlier than, prior to, ahead of
eo   antaŭ
fr   avant
he   לפני, בטרם, קודם

antena   nom
Cada de du apendises longa e magra de sensa sur la testa de insetos, crustaseos e alga otra artropodos; un bara, filo o otra aparato usada per transmete o reseta siniales de radio o televisa
en   antenna; aerial
he   אנטנה, משושה

antera   nom
La parte de un stame cual conteni la polen
en   anther
he   מאבק (החלק בצמח שמכיל את האבקן)

anterior   ajetivo
Prosima a la fronte
en   anterior, rostral
he   קודם, מקדים

anti-   prefisa
Ajuntada a ajetivos e nomes per formi ajetivos de oposa o ataca, o per nomi la cosa corespondente ma oposada
‹ antisosial; antiavional; antifungal; antieroe; antiproton ›
en   anti- (opposition)
he   (קידומת) נגד, נוגד

antica   ajetivo
Parteninte a la pasada distante e tipal no plu esistente
en   ancient, antique
he   עתיק, קדמון

anticalia   nom
Un ojeto coliable, como un mobila o obra de arte, con valua alta par causa de sua eda grande
en   antique (object), vintage item
he   ענתיקה

anticorpo   nom
Un protena de sangue produida per oposa un antijen spesifada
en   antibody
he   נוגדן

antifona   nom
Un frase corta, cantada o resitada ante o pos un salmo; un musica per esta
en   antiphon (music)
he   אנטיפון, מזמור נוצרי

Antigua   nom
Un de la du isolas major de la pais Antigua e Barbuda
en   Antigua
he   אנטיגואה

antijen   ajetivo
Un venena o otra materia esterna cual indui un responde imunial en la corpo, spesial la produi de anticorpos
en   antigenic
he   אנטיגני

Antiles   nom, plural
La grupo de isolas ensircante la Mar Caribe
en   Antilles
he   האיים האנטילים

[antilocapra] antilocapra   nom
Un mamal servin de America Norde, con corpo spesa, gamas longa e magra, e cornos negra
Antilocapra
en   pronghorn antelope
he   אנטילוקפרה

[antilope] antilope   nom
Un mamal remasticante simil a un servo, rapida corente, con pelo lisa e cornos dirijeda a supra, nativa de Africa e Asia
Alcelaphinae, Antilopinae, Hippotraginae, Reduncinae, Cephalophinae
en   antelope
he   אנטילופה

antimonio   nom   «Sb (stibium)»
La elemento cimical con numero atomal 51
en   antimony
he   אנטימון (יסוד)

antinomia   nom
Un contradise entre du credes o concluis cual pare individua asetable; un paradox
en   antinomy
he   אנטינומיה (סתירה בין שתי טענות)

antipatia   nom
Un senti profonda de ofende o repulsa
en   antipathy, aversion, deep dislike
he   אנטיפתיה, סלידה

antipoda   ajetivo
Pertinente a o situada a la lado oposada de la Tera
en   antipodean, antipodal
he   אנטיפוד

antisistemal   ajetivo
Oposante la sistem instituida de autoria e potia
en   antiestablishment
he   נגד הממסד

antitese   nom
Un person o cosa cual es la oposada de un otra; un contrasta entre du cosas
en   antithesis
he   אנטיתזה, סתירה

antolojia   nom
Un colie publicida de poesias o otra pesos de scrive; un colie publicida de cantas o composas musical en un album
en   anthology
he   אנתולוגיה, קובץ

antonim   ajetivo
(Un parola) con sinifia oposada de un otra
en   antonymous, opposite
es   antónimo, opuesto
he   אנטונים, דבר והיפוכו

[antoserotal] antoserotal   nom
Un planta acual sumerjida con folias magra e divideda, cual deveni diafana e cornin cuando lo es vea
Anthoceros
en   hornwort (plant)
he   אנתוצרוטה (צמח)

antrasita   nom
Un carbon dur, conteninte carbono cuasi pur, cual arde con flama e fuma minima
en   anthracite (substance)
he   פחם אבן

antrax   nom
Un maladia baterial de oveas e boves, tipal afetante la pel e pulmones, e cual pote es transmeteda a umanas
en   anthrax
he   אנתרקס, גחלת

antro   nom
Un caveta natural en un oso o otra strutur anatomial; la parte de la stomaco apena en la piloro
en   antrum (anatomy)
he   (אנטומיה) מערה

antropo-   prefisa
Umanas
en   anthropo-
he   (סיומת טכנית) שקשור בבני אדם

antropolojia   nom
La studia de umanas, spesial la compara de sosias e cultures umana e sua developa; la siensa de zolojia, evolui e ecolojia de umanas
en   anthropology
he   אנתרופולוגיה

antropometria   nom
La studia de la mesuras e proportios de la corpo umana
en   anthropometry
he   אנתרופומטריה

antropomorfe   ajetivo
(Un dio, animal o cosa) con cualias umana
en   anthropomorphic
he   אנתרופומורפי, מואנש

antroposentral   ajetivo
Regardante umanas como la elemento sentral o la plu importante de esiste, spesial en contrasta con dios o animales
en   anthropocentric, anthropic
he   אנתרופוצנטרי

antrostomo   nom
Un jenero de caprimuljo noturna de la mundo nova
Antrostomus
en   whippoorwill (bird)
he   סוג של ציפור לילית

anunsia   verbo transitiva
Fa un declara publica sur (un fato, aveni o intende); descrive o atrae atende a (un produida, servi o aveni) en un media publica per promove vende o partisipa
en   announce, advertise, publicize/publicise
he   להכריז, לפרסם

anura   nom
Un ordina de amfibios sin codas, incluinte ranas e sapos
Anura
en   anura (amphibian)
he   סדרה של דו-חיים

[anxa] anxa   nom
Un peso magra de cana o metal cual vibra en un corente de aira per crea sonas en un strumento musical
en   reed
es   lengüeta
fr   anche
it   ancia
he   (מוזיקה) לשונית
pt   palheta

anxo   nom
Un varia bonodorosa de txili, secida per usa en comedas mexican
en   ancho (chili)
he   אנצ’ו (פלפל חריף)

[anxoa] anxoa   nom
Un pex peti mediteranean en familia de arenge, tipal conservada en olio e comeda en saladas
Engraulis
en   anchovy
he   אנשובי

aora   averbo
A esta ora, a la tempo presente o direta seguente
en   now, currently, at present, at this time; right now, immediately, at once
he   עכשיו, ברגע זה, כרגע

aoristo   nom
Un tempo pasada de un verbo cual conteni no refere a la longia o completi de la ata
en   aorist (grammar)
he   אחד מזמני העבר ביוונית קלאסית

aorta   nom
La arteria major de la corpo
en   aorta (anatomy)
he   אב העורקים

aortite   nom
Un inflama de la mur de la aorta
en   aortitis
he   דלקת אב העורקים

[aoto] aoto   nom
Un simia noturna con oios grande, trovada en America Sude
Aotus
en   night monkey, owl monkey, douroucouli
he   דורוקולי, קוף הלילה

ap   nom
Un program desiniada per fa taxes per aida sua usor
en   application, app (software)
he   אפליקציה, ישומון

Apalatxia   nom
Un rejion montaniosa en la SUA este
en   Appalachia
he   אזור הרי האפלצ’ים

aparato   nom
Un ojeto construida o ajustada per un intende spesifada, tipal tecnical; un util o macina simple o peti ma injeniosa
en   device, gadget, piece of apparatus
he   מכשיר, מתקן, התקן, חפיץ

apare   verbo nontransitiva
Deveni vidable o notable
en   appear, become visible, show up, turn up, surface
he   להופיע, להתגלות, לצוץ

apartait   nom
Un sistem de separa e distingui par raza, istorial usada en Sudafrica; un sistem simil usada en otra locas
en   apartheid
he   אפרטהייד

[aparte] aparte   nom
Un grupo de salas per un familia o coabitores, tipal en un construida cual conteni multe de estas; cada de la partes luable de un construida comersial
en   apartment, flat, tenement; unit (commercial, residential)
he   דירה

apatia   nom
Un asentia de interesa, zelo o cura
en   apathy
he   אפתיה, אדישות

[apatosauro] apatosauro   nom
Un dinosauro erbivor enorme de la jurasica, con coda e colo longa
Apatosaurus
en   apatosaurus, brontosaurus
he   אפטוזאורוס

apatxe   ajetivo
Pertinente a un popla de la americanes orijinal ci vive xef en Mexico Nova e Arizona en la SUA sude-ueste, o a sua lingua
en   Apache (person, language)
he   שקשור לשבט האפצ’י

apela   verbo transitiva
Fa un solisita seria o urjente, tipal a la popla jeneral; solisita, a un corte de lege alta, un reversa de un deside par un corte basa
nb   La ojeto, si espresada, es la parolas usada.
en   appeal, say in appeal
he   לפנות לציבור; לערער

apena   averbo
Cuasi no; no plu ca; sola con multe difisilia; par un cuantia multe peti; a un tempo multe corta a ante
en   hardly, scarcely, barely, just, by a small amount, with difficulty
eo   apenaŭ
he   בקושי, כמעט שלא

apendis   nom
Un saco peti, liada a e abrinte a la fini plu basa de la intestin spesa en umanas e alga otra mamales; un parte protendente de un organisme, con aspeta o funsiona distinguida; un cosa liada a un otra plu grande o plu importante; un parte a la fini de un documento, ajuntante plu informa
en   appendix (anatomy, publishing), appendage
he   תוספתן; נספח, תוספת

apendisectomia   nom
Un sirurjia per estrae la apendis
en   appendectomy (surgery)
he   ניתוח לכריתת התוספתן

apendisite   nom
Un inflama dolosa de la apendis, tipal nesesante sirurjia
en   appendicitis
he   דלקת התוספתן

apesta   verbo nontransitiva
Odori forte e nonplasente
en   stink, reek, pong, niff
he   להסריח, להצחין

apetito   nom
Un desira natural per sasia la corpo, tipal par come; un desira o gusta multe grande per alga cosa
en   appetite
he   תיאבון

apico   nom
La punto la plu alta de un cosa; un state o tempo de fortia, enerjia o susede masima en la vive de un person
en   apex, tip, peak, vertex; heyday, prime, zenith
he   שיא, פסגה

apicomplexa   nom
Cualce de un filo de protozones parasital cual formi sporas, incluinte la microbios cual causa malaria
Apicomplexa
en   sporozoon (pl. sporozoa) (organism)
he   ספורוזואה (טפיל חד-תאי)

aplanata   ajetivo
(Un surfas) refletante sin devia
en   aplanatic
he   ללא עיוות אופטי

aplasia   nom
Un fali de developa o funsiona normal en un organo o texeda
en   aplasia (medical)
he   אפלזיה (אי-יכולת של רקמה או איבר להתפתח)

aplaudi   verbo transitiva
Aproba o loda (un presenta) par palmi la manos contra lunlotra
en   applaud, clap
he   למחוא כפיים

aplica   verbo transitiva
Ajunta (un sustantia o simil) a un surfas; enforsa (un regula) a algun
en   apply (substance, physical force), spread; exact, inflict (revenge)
he   ליישם, להחיל, להוציא לפועל; למרוח, למשוח

aplo-   prefisa
Solitar, singular
en   haplo- (single)
he   (קידומת טכנית) יחיד

aploide   ajetivo
(Un selula o nucleo) con un colie singular de cromosomas nonduplida; (un organisme) composada de tal selulas
en   haploid
he   (ביולוגיה) הפלואיד

apnea   nom
Un sesa tempora de respira, spesial en dormi
en   apnea/apnoea (medical)
he   דום נשימה

apo-   prefisa
A via de
en   apo-
he   (קידומת טכנית) מ-, שוב

apocalise   nom
La destrui completa e final de la mundo, spesial como descriveda en la Biblia; un aveni cual inclui destruis desastrosa
en   apocalypse, armageddon, doomsday, catastrophe; revelation (religious)
he   אפוקליפסה, ארמגדון, יום הדין, קטסטרופה

apocrifa   ajetivo
Pertinente a naras cual alga setas no aseta per inclui en la Biblia; (un nara o declara) de autoria dutada, an si popular
en   apocryphal
he   שקשור לספרים החיצוניים של התנ"ך; בעל מקור מפוקפק

[apoia] apoia   verbo nontransitiva
Inclina a via de la perpendicular; diverje de la vertical o orizonal
en   lean, tilt, slant, tip, skew, prop (position, movement); bank (aircraft); italicize/italicise
he   לנטות הצידה

apojeo   nom
La punto en la orbita de la Luna o un satelite do lo es la plu distante de la Tera; (metafor) la punto la plu alta en la developa de alga cosa
en   apogee (astronomy)
he   אפוגיאון; הנקודה הגבוהה ביותר

apone   verbo transitiva
Pone (vestes o joalas) sur se
en   put on (garment), don
he   ללבוש, לענוד

aponeurose   nom
Un telon de texeda fibrosa e perlin blanca, cual sustitui per un tendon en musculos telonin cual ave un area larga de lia
en   aponeurosis (anatomy)
he   (אנטומיה) אלל

apoptose   nom
La mori de selulas como un parte normal de la developa de un organisme
en   apoptosis, programmed cell death
he   אפופטוזיס (מוות תאי מתוכנן)

aposa   verbo transitiva
Pone (du o plu cosas) prosima a lunlotra, o tocante lunlotra
en   appose, juxtapose, collocate
he   להציב זה לצד זה

aposta   verbo transitiva
Risca (alga cosa, tipal mone) contra lo de un otra sur la resulta de un aveni futur, como un curso o jua
‹ aposta sento euros ce esta va aveni ›
en   bet, wager, gamble
he   להמר, להתערב

aposteriori   ajetivo
Pertinente a razona o sabe cual progresa de oservas o esperias asta la dedui de sua causas probable; (un lingua construida) cual imita la vocabulo o gramatica de otra linguas
en   a posteriori
he   לאחר מעשה, בדיעבד

apostol   nom
Cada de la des-du disiplos xef de Jesus Cristo; cualce instruor importante en cristianisme; (metafor) un mesajor
en   apostle
he   (נצרות) שליח, מבשר

aprende   verbo transitiva
Gania sabes o capasias en (alga campo) par studia o esperia
en   learn
fr   apprendre
he   ללמוד

april   nom
La mense cuatro de la calendario gregorian
en   April
he   אפריל

apriori   ajetivo
Pertinente a razona o sabe cual comensa con deduis teorial en loca de oservas o esperias; (un lingua construida) cual inventa sua propre vocabulo o gramatica
en   a priori
he   אפריורי, מלכתחילה, מראש

aproba   verbo transitiva
Acorda ofisial o aseta como sasiante; crede ce (un person o cosa) es bon o asetable
en   approve, approve of, assent to, endorse; confirm (action on computer)
he   לאשר, להסכים ל-

aprosima   ajetivo
Prosima a la realia, ma no completa esata
en   approximate, rough
he   מקורב, משוער

[apside] apside   nom
Un alcova grande semisirculo o poligon en un eglesa, con arcos o cupola, tipal a la fini este e conteninte la altar; cada de la du puntos en la orbita de un planeta o satelite do lo es la plu prosima o la plu distante de la corpo sirca cual lo move
en   apse; apsis
he   אפסיס (גומחה חצי מעגלית בכנסייה); אפסיד (הנקודה הרחוקה ביותר או הקרובה ביותר של גרם שמים מהעצם אותו הוא מקיף)

apto-   prefisa
Juntante
en   hapto- (attachment)
he   (קידומת טכנית) צמוד, מחובר

[ara] ara   nom
Un papagaio neotropical grande con coda longa e plumas briliante
Ara e jeneros relatada
en   macaw
he   מקאו (תוכי)

arabesca   ajetivo
Un desinia ornal, composada de linias fluente e entretexeda, orijinal trovada en decora arabi o moro; un pasaje o composa musical con melodia ornada; un posa de dansa en cual la corpo es suportada par un gama e la otra gama estende orizonal a retro
en   arabesque
he   ערבסקי

Arabia   nom
Un penisola en Asia sude-ueste, xef composada de deserto, entre la Mar Roja e la Golfo Persian, conteninte sete paises de cual la plu grande es Arabia Saudi
en   Arabia
he   חצי האי ערב

arabis   nom
Un planta erbin de crese basa, tipal con flores blanca o ros, comun trovada en rocerias
Arabis
en   arabis, rockcress

arac   nom
Un bevida alcolosa, tipal distilada de ris o de la sava de palma de coco
en   arrack, arak (drink)
he   ערק (משקה אלכוהולי)

[aracide] aracide   nom
Un planta en familia de piso, produinte un seme oval cual es usada per produi olio; esta seme, tipal rostada e salida como un cometa
Arachis hypogaea
en   peanut
he   בוטן

aracnido   nom
Un artropodo de la clase cual conteni aranias e scorpiones
Arachnida
en   arachnid
he   חבר במשפחת העכבישיים

aracno-   prefisa
Arania, aracnido
en   arachno- (spider)
he   (קידומת טכנית) שקשור לעכבישים

aracnofobia   nom
Un teme estrema o nonrazonada de aranias
en   arachnophobia
he   פחד מעכבישים

aracnoide   nom
Un membrana delicata entre la duramadre e la piamadre de la serebro e medula spinal
en   arachnoid
he   (אנטומיה) קרום הקורים

[arado] arado   nom
Un aparato grande de cultiva con un o plu laminas pesosa, tirada sur tera per crea ranures ante planta semes
en   plow/plough
he   מחרשה

[Arafura, Mar] Arafura, Mar   nom
Un mar entre Australia e Papua indonesian
en   Arafura Sea
he   ים אראפורה

[Aragon] Aragon   nom
Un rejion autonom en Espania norde-este; un rena autonom en la eda medieval
en   Aragon (Spanish region)
he   אראגון

[Aral, Mar] Aral, Mar   nom
Un mar interna en Asia sentral entre Cazacstan e Uzbecistan, multe diminuida par iriga
en   Aral Sea
he   ימת אראל

[Aram] Aram   nom
Un rejion antica do Suria es aora situada, e un parte de Babilonia entre la sentenios 11 e 8 aec
en   Aram (biblical region)
he   ארם

[aramo] aramo   nom
Un avia vadante en familia de ral, con gamas e beco longa
Aramus guarauna
en   limpkin (bird)
he   לימפקין, העגור הבוכה

aranca   verbo transitiva
Tira subita e forte
en   wrench, jerk, yank, snatch, wrest, tug, heave
he   למשוך בכוח

[arania] arania   nom
Un artropodo xasante, con oto gamas e dentones cual injeta venena en sua preda, tipal capas de texe redes per catura insetos
Araneae
en   spider
he   עכביש

aranja   verbo transitiva
Ajusta (un obra musical) per presenta par strumentos o voses nova
en   arrange (music)
he   (מוזיקה) לעבד

arbitra   verbo transitiva
(Un person o grupo autonom) fa un judi o acorda autoriosa sur (un demanda o problem)
en   arbitrate on, mediate on
he   לתווך, לפשר, לגשר

arbitraje   nom
La compra e vende simultan de titulos, mone o benes en mercatos diversa, o en formas derivada, per esplota la custas diversa
en   arbitrage
he   ארביטראז’

arbor   nom
Un planta leniosa, tipal con tronco singular cual crese alta e ave ramos ladal alga distante de la tera
en   tree
he   עץ

[arboran] arboran   nom
Un corvo asian con coda longa e plumas negra o brun e gris
Crypsirina, Dendrocitta, Platysmurus, Temnurus
en   treepie (bird)
he   סוג של ציפור

[arbuto] arbuto   nom
Un planta perene en familia de erica
Arbutus, Epigaea
en   arbutus (plant)
he   קטלב (צמח)

arca   nom
(En la Biblia) la barcon construida par Noa per proteje sua familia e un duple de cada tipo de animal contra la deluvia; un barcon grande con fondo plana; un caxa cual conteni la tora en un sinagoga
en   ark
eo   arkeo
he   תיבת נוח; ארון הקודש

[arcabus] arcabus   nom
Un tipo temprana de fusil portable, suportada sur un trepede o un suporta forcin
en   arquebus, hackbut
he   ארקבוז (רובה עתיק)

arcada   nom
Un coredor covreda, con arcos o botecas longo un o ambos lados
en   arcade
he   ארקדה, מעבר מקומר

arcanjel   nom
Un anjel major
en   archangel
he   המלאך הראשי

arcea   nom
Microbios simil a baterias par grandia e simplia de strutur, ma con organiza moleculal multe diferente, regardada como un grupo entre baterias e eucariotas
en   archaeon, archaea, archaebacterium (organism)
he   (ביולוגיה) ארכאון

arcenemi   nom   (dise ‘arcenemí’)
Un person ci oposa un person o cosa en modo estrema e unica
en   archenemy, nemesis
he   אויב מושבע, יריב מר

arceo-   prefisa
Antica
en   archeo-/archaeo-
he   (קידומת טכנית) עתיק

arceolojia   nom
La studia de istoria e preistoria umana par la escava de locas e la analise de fabricadas e otra restantes fisical
en   archeology/archaeology
he   ארכאולוגיה

[arceopterix] arceopterix   nom
La fosil la plu antica conoseda de un avia de la tarda de la jurasica, un organisme con plumas, alas e osos cavetin como un avia moderna, ma con dentes, coda ososa e gamas como un spesie de dinosauro peti
Archaeopteryx
en   archaeopteryx
he   ארכאופטריקס

arcetipo   nom
Un esemplo multe tipal de un person o cosa spesifada; un orijinal cual on ia imita; un simbol o motif en leteratur, arte o mitolojia
en   archetype
he   ארכיטיפ, אב-טיפוס

arci-   prefisa
Xef, major
en   archi-, arch- (chief)
he   (קידומת טכנית) ראשי, עיקרי

arcibispo   nom
Un bispo major
en   archbishop
he   ארכיבישופ

arciduxe   nom
Un duxe xef
en   archduke
he   ארכידוכס

arcipelago   nom
Un grupo o cadena de isolas
en   archipelago
he   ארכיפלג

arciprete   nom
La prete xef de un grupo relijiosa
en   high priest, high priestess
he   כהן גדול

arciteta   nom
La arte o pratica de desinia e construi construidas; un strutur fisical o lojical cual es complicada o desiniada en modo atendente
en   architecture
es   arquitectura
he   ארכיטקטורה, אדריכלות
ru   архитектура

[arcitrava] arcitrava   nom
Un faxon major, reposante sur la culminas de colonas; un moldur sirca un fenetra, porte o arco
en   architrave
he   ארכיטרב (קורת אבן אופקית על שורת עמודים)

arcivo   nom
Un colie de informa rejistrada; un portapaper; un spesie de fix cual grupi otra fixes o suarcivos
en   record (information), register, log; file, folder, document wallet; folder, directory
he   רשומה

arcivolta   nom
Un banda de moldures simil a un arcitrava, longo la curva su un arco
en   archivolt, voussure (architecture)
he   ארכיוולט

[arco] [arco] arco   nom
Un parte de la perimetre de un sirculo o otra curva; un forma o strutur curva; la curso curvinte de un ojeto movente; un curso developante en un nara; un strutur curva cual estende simetre supra un abri, tipal suportante un teto, ponte o mur; un descarga eletrical luminosa entre du puntos; un arma per xuta flexas, tipal fabricada de un peso curva de lenio, de cual sua finis es juntada par un corda tensada; un basto longa portante filos tensada, usada per jua strumentos de cordetas
en   arc (geometry, electrical, narrative); arch, archway (architecture); bow (weapon, music)
he   קשת

arconte   nom
Cada de la nove judores xef en Atina antica; (metafor) un renor
en   archon (Athenian judge)
he   ארכון (שופט ביוון העתיקה)

arde   verbo nontransitiva
Produi un flama o brilia en consuma un materia como carbon o lenio; (un candela o otra fonte de lus) emete lus; (un person, sua pel o un parte de corpo) es roja e dolosa pos esposa a la sol o par causa de un maladia o feri; (metafor) es saisida par un desira multe forte
en   burn, blaze
he   להישרף, לבעור, להתלקח; להיכוות

ardosia   nom
Un roca de venas magra, gris, verde o blu, fasil per fende a pesos plata e lisa
en   slate
he   ציפחה

are   nom
Un unia de area internasional, egal a 100 metres cuadrida
en   are (unit of area)
he   עשירית דונם

area   nom
La grandia de un surfas o peso de tera; un parte de un site, construida, jardin, etc, con usas o cualias distinguida; un parte de la surfas de la corpo
en   area
he   איזור, שטח

[areca] areca   nom
Un palma de Asia tropical
Areca
en   areca palm
he   דקל ארקה

[arem] arem   nom
(Istorial) un parte separada de un casa muslim, reservada per sposas, concubinas e servores fema; la sposas o concubinas de un om poligama; un grupo de animales fema cual comparti un sola mas
en   harem, seraglio
he   הרמון

[aremon] aremon   nom
Un pinson cual abita la forestas de America Sentral e la ueste de America Sude
Arremon, Atlapetes, etc
en   brush finch
he   פרוש (ציפור)

[arena] arena   nom
Un materia granetin, tipal pal jala o brun, resultante de la erode de rocas e forminte un composante major de plaias, fondos de rios e mares, e desertos
en   sand, grit
he   חול

arenga   verbo transitiva
Parla coler o criticante a (algun) tra un tempo estendeda
en   harangue, rant at
he   להביע תרעומת, להתבטא בכעס

[arenge] arenge   nom
Un pex arjentin cual abunda en acuas costal e es comersial multe importante como un comeda en multe partes de la mundo
Clupea
en   herring
he   מליח, הרינג

arenito   nom
Un roca composada de granes de arena o cuarzo, aderente a lunlotra
en   sandstone
he   אבן חול

areola   nom
Un sirculo de lus mostrada sirca o supra la testa de un person santa en arte; un sirculo de lus refratada sirca un ojeto luminosa; un area sirculo de pel tinjeda sirca un teta; un manxa rojida sirca un pustula o papula
en   halo, nimbus; areola
he   הילה; הרקמה שמסביב לפטמה

aresta   verbo transitiva
Saisi (algun) par autoria legal
en   arrest, seize, apprehend
he   לעצור, להביא למעצר

argon   nom   «Ar»
La elemento cimical con numero atomal 18, un gas inerte
en   argon
he   ארגון (יסוד)

arhat   nom
(En budisme e jainisme) un person santa de grado alta
en   arhat (saint)
he   בודהיסט שהגיע לנירוונה

aria   nom
(En un opera) un canta longa e acompaniada per un vose solo
en   aria
eo   ario
fr   aria
he   (מוזיקה) אריה

arianisme   nom
Un eresia influente de cristianisme, cual nega ce Cristo es Dio
en   Arianism (Christianity)
he   אריאניות

[ariete] ariete   nom
Un ojeto pesosa, usada per colpa e rompe un porte
en   battering ram
he   אייל ברזל

aril   nom
Un covrente ajuntada de un seme, tipal colorida e pelosa o pulposa, como la copa roja sirca un seme de taxo
en   aril, arillus (botany)
he   מעטה זרע הפרי, ציפת הפרי

aristocrata   ajetivo
Pertinente a la clase la plu alta en alga sosias, tipal lo cual posese titulos o postos eritada
en   aristocratic, highborn
he   אצילי, אריסטוקרטי

[aristolocia] aristolocia   nom
Un planta erbin o trepante, tipal con folias corin e flores con abri profonda, istorial usada per aida paris e indui abortas
Aristolochia
en   aristolochia, birthwort, pipevine (plant)
he   ספלול (צמח)

aritmetica   nom
La ramo de matematica cual studia la cualias e manipula de numeros; la usa de numeros per conta e calcula
en   arithmetic
he   אריתמטיקה

aritmia   nom
Un maladia en cual la cor bate con ritmo nonormal
en   arrhythmia
he   הפרעה בקצב הלב

ariva   verbo nontransitiva
Ateni la loca a la fini de un viaja; ateni un conclui o deside; (un bebe) nase; (un tecnica o produida) comensa es usada; (un momento prevideda) aveni; (nonformal) orgasma
en   arrive; (colloquial) come (orgasm)
he   להגיע

Arizona   nom
Un stato en la SUA sude-ueste
en   Arizona (US state)
he   אריזונה

arjentifer   ajetivo
(Un roca o mineral) conteninte arjento
en   argentiferous
he   שמכיל את המתכת כסף

[Arjentina] Arjentina   nom
Un pais cual ocupa la plu de la parte sude de America Sude, entre Txile e la Mar Atlantica
(capital: Buenos Aires)
en   Argentina
he   ארגנטינה

[arjento] arjento   ajetivo
Con color briliante gris-blanca
en   silver (color/colour)
he   צבע כסף

arjila   nom
Un tera deponeda, rijida e aderente, cual es moldable cuando lo es moiada, e cual on seci e forni per crea brices e seramicas
en   clay
he   חימר

Arkansas   nom   (dise ‘árkansa’)
Un stato en la SUA sude-sentral
en   Arkansas (US state)
he   ארקנסו

[arlecin] arlecin   nom
Un carater tradisional de teatro european, tipal muda, mascida e en vestes con motif de diamantes
en   harlequin
he   ליצן בתיאטרון האירופאי המסורתי

arma   nom
Un cosa desiniada o usada per feri corpos o causa otra dana fisical
en   weapon
he   נשק

arma   verbo transitiva
Furni armas a (algun)
en   arm
he   לחמש

[armadilo] armadilo   nom
Un mamal omnivor e noturna, con corpo covreda par laminas de oso, e garas grande per escava
Cingulata, Dasypodidae
en   armadillo
he   ארמדיל

[armario] armario   nom
Un mobila con scafales, caxetas o portes, usada per reteni o esibi ojetos
en   cupboard, cabinet, armoire
he   ארון, שידה

armatur   nom
Un strutur sur cual on moldi un sculta; la strutur formal de un obra de leteratur; la indica de tonalia a la comensa de un peso de musica scriveda; un ambiente reusable de funsionas cual un program individua pote altera o spesifa plu
en   armature (literature, sculpture); key signature; framework (software)
he   תבנית (ספרות, פיסול)

[Armenia] Armenia   nom
Un otra nom per Haiastan
→ Haiastan
en   Armenia
he   ארמניה

arminian   ajetivo
Pertinente a la prinsipes e credes de Jacobus Arminius (1560-1609), un teolojiste nederlandes ci ia rejeta la idea de predestina
en   Arminian
he   ארמיניאני

armonia   nom
La efeto plasente produida par un combina simultan de notas musical, o par un misca artal de otra cosas; (metafor) acorda
en   harmony
he   הרמוניה

[armonica] armonica   nom
Un strumento peti e retangulo con un linia de anxas metal, a cual la juor sofla o suca, produinte notas diversa par move lo de lado a lado
en   harmonica, mouth organ, mouth harp
he   הרמוניקה, מפוחית פה

[armonio] armonio   nom
Un strumento de teclas cual produi sonas cuando aira es puiada tra anxas par un soflador operada par la pedes
en   harmonium (musical instrument)
he   הרמוניום

[armur] armur   nom
Un colie de covrentes metal, istorial portada par soldatos per proteje sua corpo en combate; la strato o casca protejente de alga animales e plantas
en   (suit of) armor/armour; carapace, shell (animal, plant)
he   שיריון

arn   corti
Asida ribonucleal
en   RNA
he   חומצה ריבונוקלאית

[arnes] arnes   nom
Un colie de bandas par cual un bestia es liada a un caro o arado e es controlada par sua gidor; un colie de bandas per lia un cosa como un paracade a la corpo, o per restrinje un enfante joven; un banda flexable usada en la forma de un anelo per suporta o leva un cosa pesosa; un banda sirca la colo o spalas per suporta un braso ferida o per porta un bebe
en   harness, sling
he   רתמה, מנשא

[arnica] arnica   nom
Un planta en familia de margarita cual produi flores jala, usada per trata contusas
Arnica
en   arnica (plant)
he   ארניקה (צמח)

[arpa] arpa   nom
Un strumento musical, cuasi triangulo, composada de un strutur cual suporta un serie gradal de cordetas paralel, juada par toca los con la ditos
en   harp
he   (מוזיקה) נבל

arpejio   nom
Un jua rapida de la notas de un acorda musical, la un pos la otra en ordina asendente o desendente
en   arpeggio
he   (מוזיקה) אפרג’ו

arpia   nom
Un monstro con testa de fem e corpo, alas e garas de avia xasante; (metafor) un fem vea e sever, avar o enemin
en   harpy; harridan, hag, gorgon, crone
he   (מיתולוגיה) הרפיה; מרשעת, אישה זקנה ומרושעת

[arpon] arpon   nom
Un misil simil a un lansia con spinas, liada a un cordon longa e xutada par mano o fusil, usada per catura balenas o otra animales grande de mar
en   harpoon
he   צלצל, הרפון

arsenico   nom   «As»
La elemento cimical con numero atomal 33, con composadas usada en semicondutadores, en conserva de lenio, e como un venena potiosa
en   arsenic
he   ארסן, זרניך (יסוד)

arte   nom
La espresa o aplica de la creosia e imajina umana, produinte obras cual plase xef par sua belia o potia emosial; la obras produida en esta modo; cada de la ramos de tal creosia, como depinta, sculta, musica, leteratur e dansa
en   art
he   אמנות

[artemisia] artemisia   nom
Un planta en familia de margarita, con folias divideda e bonodorosa cual es oscur verde a supra e blancin a su
Artemisia
en   mugwort, sagebrush (plant)
he   לענה מצויה (צמח)

arteria   nom
Cada de la tubos con mures musculosa en la sistem par cual sangue osijenida es moveda de la cor a tota partes de la corpo
en   artery
he   עורק

arteriografia   nom
La radiografia de un arteria
en   arteriography
he   צילום עורקים

arteriosclerose   nom
Un duri de la mures de arterias, tipal en senese
en   arteriosclerosis
he   טרשת העורקים

arterite   nom
Un inflama de la mures de un arteria
en   arteritis
he   דלקת עורקים

artesian   ajetivo
Pertinente a acuiferes nonorizonal, o a posos perpendicular forada en estas afin la presa natural furni constante la acua con poca nesesa de pompi
en   artesian (well)
he   ארטזי

artica   ajetivo
Pertinente a la zona sirca la polo norde
en   Arctic
he   ארקטי

article   nom
Cada de la testos diversa en un jornal, libro de consulta, o otra publici; un grupo de datos relatada e tratada como un unia; un linia en un table de datos
en   article (document); record, row (data)
he   מאמר, כתבה; רשומה בבסיס נתונים

artifis   ajetivo
Fabricada par umanas, tipal de materias ance fabricada par umanas, en contrasta con cosas plu biolojial
en   artificial, synthetic, manmade
he   מלאכותי, סינטתי

artileria   nom
Fusiles de calibre multe grande, usada en gera
en   artillery, ordnance
he   ארטילריה, תותחנות

artisan   nom
Un laboror capas de fabrica cosas par mano
en   artisan, craftsman, craftswoman, tradesman, tradeswoman
he   אומן, בעל מלאכה

artrite   nom
Un inflama dolosa, rijidinte la juntas
en   arthritis (medical)
he   דלקת פרקים

artro-   prefisa
Juntas de corpo
en   arthro-
he   (סיומת טכנית) שקשור למפרקים

artropodo   nom
Un animal nonvertebrato de la filo grande cual conteni insetos, aranias e crustaseos
Arthropoda
en   arthropod
he   פרוקי רגליים

artrose   nom
La dejenera de la cartilaje e osos de la juntas, tipal en persones matur o vea, cual causa dole e rijidia
en   arthrosis, osteoarthritis
he   דלקת מפרקים ניוונית

[Aruba] Aruba   nom
Un isola en la Mar Caribe, prosima a la costa de Venezuela, e un teritorio autonom de Nederland
en   Aruba (island)
he   ארובה (אי)

[arum] arum   nom
Un planta con folias flexin e un gaina cual enclui un spiga, cual produi bacas briliante roja en la tarda de estate
Arum
en   arum (plant)
he   לוף (צמח)

[as] as   nom
Un carta de jua con sola un simbol, indicante en la plu de juas ce lo es la plu valuosa en sua familia
en   ace (card)
he   אס (קלפים)

[asafetida] asafetida   nom
Un planta eurasian en familia de persil; un goma resinosa otenida de sua radis, usada en medica erbal e en cosini barati
Apiaceae
en   asafetida (plant)
he   חלתית, אספטידה (צמח)

[Asam] Asam   nom
Un stato en Barat norde-este, xef locada en la vale de la Rio Brahmaputra
en   Assam (Indian state)
he   אסאם

[asana] asana   nom
Cada de la posas en ioga
en   asana (yoga)
he   אסאנה (יוגה)

[asaro] asaro   nom
Un planta de America Norde con folias grande e corin e troncetas pelosa, de cual sua radis es usada como un sustitua per jinjer
Asarum
en   wild ginger
he   אסארום (צמח)

asasina   verbo transitiva
Mata (un person major) en un ataca surprendente, per razonas political o relijial
en   assassinate, murder
he   להתנקש

asbesto   nom
Un mineral de silicato cual pote es texeda o usada per resiste foco o isoli
en   asbestos
he   אזבסט

asbestose   nom
Un maladia de la pulmones pos enspira particulas de asbesto, marcada par fibrose grave e un risca alta de mesotelioma
en   asbestosis
he   אזבסטוזיס

[ascarido] ascarido   nom
Un nematodo parasital cual vive tipal en la intestines de vertebratos
Ascarididae
en   ascarid (worm)
he   סוג של תולעת טפילה

[asclepia] asclepia   nom
Un planta american con sava letin
Asclepias
en   milkweed (plant)
he   אסקלפיאס (צמח)

asconde   verbo nontransitiva
(Un person) preveni ce otras vide o trova el
en   hide, be in hiding, lurk, skulk
he   להתחבא, להסתתר

ase   nom
Un palo pasante tra la sentro de un rota o grupo de rotas; un palo magra cual formi un parte de un flexa, un arbor de maniveles, un capel, etc; un linia imajinal sirca cual un corpo jira
en   axle, shaft; axis
he   ציר, סרן

asecura   verbo transitiva
Organiza, par paias periodal a un compania o ajenteria governal, ce on va es compensada si (sua propria) es danada o perdeda o si (un person) mori o deveni ferida
en   insure
he   לבטח

asede   verbo transitiva
Prosimi o entra a (un loca o posto); oteni o estrae (datos o un arcivo)
en   access; accede to
he   לגשת; להיכנס, לפתוח (אתר, קובץ, מערכת מידע)

aseja   verbo transitiva
Ensirca (un loca) con fortes militar per catura lo o forsa ce lo sede
en   besiege
he   לכתר, לצור

aselera   verbo nontransitiva
(Un veculo o otra ojeto) comensa move plu rapida; crese en cuantia o estende
en   accelerate, speed up; expedite, hasten
he   להאיץ

[aselomorfo] aselomorfo   nom
Un membro de un filo de animales de mar con corpos mol e plata
Acoelomorpha
en   acelomorph/acoelomorph (organism)
he   סוג של חסרי חוליות

asembla   verbo nontransitiva
(Persones o partes) veni con otras a un loca per un intende o usa comun
en   assemble, gather, meet, come together, muster
he   להתאסף, להתכנס, להתקבץ

asende   verbo transitiva
Vade en dirije a la punto la plu alta de (un cosa)
en   ascend, rise, climb, go up, mount
he   לעלות, להתרומם

asendeplato   nom, composada (verbo+nom)
Un asendador peti cual porta platos e comedas entre la niveles de un construida
en   dumb waiter
he   מעלית צלחות במסעדה או מלון

asente   ajetivo
No presente a un loca o aveni, o como un parte de alga cosa
en   absent, missing
he   נעדר, חסר, נפקד

[asentor] asentor   nom
Un avia cantante peti de Eurasia con plumas sombre
Prunella
en   accentor (bird)
he   סוג של ציפור שיר

asentua   verbo transitiva
Dona un importa spesial a (alga cosa) en parla o scrive; fa ce (alga cosa) es plu clar persepable
en   emphasize/emphasise, accentuate, stress, prioritize
he   להדגיש, להבליט, להטעים

aser   nom
Un aliada de fero con carbono e tipal otra elementos, dur, forte e gris o bluin gris, usada como un materia en construi e fabrica
en   steel; frizzen (gun)
he   פלדה

[asero] asero   nom
Un arbor con folias lobosa, frutas con alas, e folias briliante en autono, usada per lenio e per xirope
Acer
en   maple
he   אדר, מייפל (עץ)

asesal   ajetivo
Sin seso o sentis sesal; no reproduinte par la fusa de gametas o organos sesal
en   asexual, non-sexual
he   א-מיני

aseso   nom
Un parte inflada en un texeda de corpo, conteninte un cumula de pus
en   abscess
he   מורסה, כיב, אבצס

aseta   verbo transitiva
Reseta volente (un cosa); responde positiva a (un ofre); permete ce (un person) entra o partisipa; bonveni (algun); crede o comensa crede ce (un opina o esplica) es valida o coreta
en   accept, condone, abide by; admit, acknowledge, grant, concede (point in an argument); pass (a law)
he   לקבל; להסכים, להודות, להכיר בעובדה

asetato   nom
Un sal o ester de asida asetica; un composada usada per fabrica plastica o fibres per stofas
en   acetate
he   אצטט

asetica   ajetivo
Simil a vinagra
en   acetic
he   שקשור לחומץ או לחומצת חומץ

asetilcolina   nom
Un composada cual apare tra tota la sistem de nervos, do lo funsiona como un neurotransmetador
en   acetylcholine
he   אצטילכולין

asetilen   nom
Un idrocarbono sin color ma malodorosa, cual arde con flama briliante, usada en solda e istorial per lumina
en   acetylene
he   אצטילן

asetona   nom
Un cetona licuida, sin color e volatil, usada como un disolve organica e un reatante sinteseda
en   acetone
he   אצטון

asfalto   nom
Un misca de bitume con arena o calculos, usada como un surfas per vias, solos e tetos
en   asphalt, tarmac, macadam, blacktop, asphalt concrete
he   אספלט

asfixia   verbo nontransitiva
Mori par manca de aira
ca   asfixiar
de   ersticken
en   asphyxiate
eo   asfiksiiĝi; asfiksii
es   asfixiar
fr   asphyxier
it   asfissiare
he   להיחנק
pt   asfixiar

[asfodelo] asfodelo   nom
Un planta eurasian en familia de lil, con spigas florinte e folias longa e magra; (en mitos elinica) la flor nonmortal cual crese en la campos de Elisia
Asphodelus, Asphodeline
en   asphodel (plant)
he   עירית

asi   averbo   (dise ‘así’)
En esta loca; movente a esta loca
en   here; to here, hither
he   כאן, פה; לכאן, לפה

[Asia] Asia   nom
La continente la plu grande, a ueste de la Mar Pasifica e a este de Europa e Africa
en   Asia
he   אסיה

asiamania   nom
Un interesa intensa a la cultures de Asia; un representa de Asia en un modo stereotipal; (istorial) un representa de Asia sude-ueste colorida par un disposa colonialiste
en   orientalism
he   אוריינטליזם

asida   ajetivo
Pertinente a, o con cualias de, la cimicales cual neutri alcalines, disolve alga metales, corode otras, e roji paper de pH; con la sabor de esta cimicales; (metafor) con disposa o vose coler o odiosa
en   acid, acidic, sour, tart, acerbic
he   חומצי, חמוץ, חמצמץ

asidente   nom
Un aveni nonfortunosa cual no es prevideda o intendeda, tipal causante un dana o feri
nb   Un aveni simil ma fortunosa es un "acaso".
→ acaso
en   accident (mishap)
he   תאונה, תקרית; מקרה

asidofilia   nom
en   acidophilia
he   היכולת לגדול היטב בסביבה חומצית

asidua   ajetivo
Mostrante cura e persiste grande; enerjiosa laborante
en   assiduous, diligent, hardworking, industrious
he   חרוץ, שקדן

[asilido] asilido   nom
Un mosca grande e potiosa cual vola subita per saisi insetos per come
Asilidae
en   robber fly
he   זבוב שודד

[asimina] asimina   nom
Un arbor de America Norde en familia de anona, con flores purpur e frutas jala con pulpa dulse; la fruta de esta
Asimina
en   pawpaw (tree, fruit)
he   פפאיה (צמח, פרי)

asinia   verbo transitiva
Dona (un taxe o recurso) a algun; identifia o reserva (un recurso) per un usa intendeda; regarda (alga cosa) como causada par un otra
‹ asinia roles a la juores ›
en   assign, allocate, allot, appoint (tasks, resources), deploy; earmark; ascribe
he   להקצות, להקציב, לייעד

[asino] asino   nom
Un mamal domada en familia de cavalo, con oreas longa e un cria xiliante
Asinus
en   donkey, ass, jackass
he   חמור

[asinto] asinto   nom
Un arboreta leniosa con un sabor amarga ma bonodorosa, usada como un ingrediente en alga bevidas e medisines; un licor forte e verde, con sabor de anis, cual deveni letin cuando on ajunta acua
en   wormwood, absinthe (plant, drink)
he   לענה; אבסינת

asintota   nom
Un linia reta cual prosimi sempre a un curva ma toca nunca lo a distantias finita
en   asymptote (mathematics)
he   אסימפטוטה

asion   nom
Un de la partes egal de la capital de un compania, permetente ce sua posesor reseta un proportio de la profitas
en   stock, share
he   מניה

[Asiria] Asiria   nom
Un pais antica, do Irac norde es aora situada, la sentro de un serie de imperos en la temprana de la milenio du aec
en   Assyria (ancient region)
he   אשור

asma   nom
Un maladia de respira, marcada par spasmas en la broncos
en   asthma
he   אסתמה, קצרת

asoluta   ajetivo
No restrinjeda; (un renor) con potia completa; no relativa o comparada
en   absolute, utter
he   מוחלט, אבסולוטי

ason   nom
Un parte longa e filin de un neuron, longo cual impulsas es transmeteda a otra selulas
en   axon (anatomy)
he   (אנטומיה) אקסון

asona   verbo nontransitiva
(Un sona de vocal o diftongo) es repeteda en un serie de silabas asentuada tan prosima a lunlotra ce on oia un efeto ecosa
en   assonate
he   מתחרז עם תנועה

asorbe   verbo transitiva
Prende (enerjia, un licuida o un otra materia) a en se par ata cimical o fisical, tipal en modo gradal; prende (informa, ideas, esperia) a en se
en   absorb, assimilate, ingest, soak up, incorporate, entrain
he   לספוג, להטמיע, לקלוט לתוכו

[Asores] Asores   nom, plural
Un grupo de isolas volcanal en la Mar Atlantica, a ueste de Portugal e parteninte a lo
en   Azores
he   האיים האזוריים

asosia   verbo nontransitiva
Lia se (con algun); tende asembla (con algun); comersia (con algun); (un conseta) ave un lia (con un otra conseta) en la mente; (un elemento de un colie matematical) ave un lia (con un elemento de un otra colie)
en   associate, hobnob; be involved; map (to)
he   להתחבר, להתרועע; להשתייך

[asparago] asparago   nom
Un planta alta en familia de lil, con folias plumin, cultivada per sua rametas; sua rametas joven, comeda como un vejetal
Asparagus officinalis
en   asparagus (plant, vegetable)
he   אספרגוס

asparajina   nom
Un aminoasida idrofilica cual es un composante de la plu de protenas
en   asparagine (amino acid)
he   אספרגין (חומצת אמינו)

aspartame   nom
Un materia multe dulse, usada como un dulsinte artifis
en   aspartame (sweetener)
he   אספרטיים

aspartato   nom
Un aminoasida cual es un composante de la plu de protenas, importante en la metaboli de nitrojen en organismes
en   aspartate (amino acid)
he   אספרטט (חומצת אמינו)

asperula   nom
Un jenero de plantas florinte
Asperula
en   asperula (plant)
he   חספסנית (צמח)

aspeta   verbo nontransitiva
Pare a la oio
nb   "Aspeta" pote lia ance direta a un ajetivo.
‹ el aspeta como un capra; tua capeles aspeta bela ›
en   look (have a certain appearance), appear
he   להיראות, להיות בעל מראה מסוים

aspica   nom
Un jelatin saborosa preparada de bulion de carne e conteninte pesos de carne o ovo
en   aspic
he   תבשיל בשר בג’לטין

aspira   verbo transitiva
Dirije sua esperas o intendes a ateni (alga cosa)
en   aspire to, dream of
he   לשאוף ל-, לחלום על

[aspirina] aspirina   nom
Un composada sinteseda, usada como un medisin per redui dole, febre e inflama
en   aspirin
he   אספירין

asta   preposada
1   Indicante la loca o state do un move o cambia fini.   (Leje plu…)
nb   "Asta" implica ce la move ateni la loca spesifada e no vade ultra lo. "A" es plu jeneral, e pote es usada an cuando la move no ateni sua fini intendeda.
‹ me va acompania tu asta la porte; moiada asta sua pel; la preso ia cade asta sento euros; studia pajes 25 asta 42 ›
en   as far as, up to, down to, until (reaching a point but going no further)
eo   ĝis
he   עד
2   Indicante la tempo cuando un ata fini
‹ el ia dormi asta mediadia ›
→ cuando
en   until, till, up to (in time)
eo   ĝis
he   עד

astatica   ajetivo
No adotante un loca o dirije stable
en   astatic
he   א-סטטי, לא יציב

astato   nom   «At»
La elemento cimical con numero atomal 85
en   astatine (element)
he   אסטטין (יסוד)

[asteca] asteca   ajetivo
Pertinente a la americanes orijinal ci ia domina Mexico ante sua concista par la espanioles en la sentenio 16, o a sua linguas
en   Aztec
eo   azteka
he   אצטקי

asteni   verbo nontransitiva
Restrinje se de fa o joia un condui spesifada, como seso o la bevi de alcol
en   abstain, refrain, desist, eschew, forbear, deny oneself, forgo, recuse
he   להימנע, להתנזר

astenia   nom
Un debilia o asentia nonormal de enerjia
en   asthenia (medical)
he   חולשה

[aster] aster   nom
Un planta en familia de margarita cual ave flores briliante, tipal purpur o ros
en   aster (plant)
he   אסתר (צמח)

asterida   nom
Un clado grande de plantas florinte, incluinte tomates, tabaco, cafe, lilas e menta
en   asterid (plant)
he   אסטרידים

asteroide   nom
Un corpo peti e rocosa cual orbita la Sol
en   asteroid
he   אסטרואיד

astigmata   ajetivo
(Un oio o lente) con un defeto causada par un devia de curvia sfera, produinte imajes contorseda
en   astigmatic
he   אסטיגמטי

[astragalo] astragalo   nom
Un jenero grande de sirca tre mil spesies de erbas e arboretas en familia de fava
Astragalus
en   astragalus, milkvetch (plant)
he   קדד (סוג צמחים)

astral   ajetivo
(En alga credes paranormal) pertinente a un loca de esiste nonfisical
en   astral
he   אסטראלי

astrata   ajetivo
Esistente en pensa o como un idea, sin esiste fisical; tratante ideas en loca de avenis; no fundida sur un aveni; teorial; pertinente a arte cual no representa cosas o persones fisical
en   abstract
he   אבסטרקטי, מופשט, ערטילאי, לא מוחשי

astrinje   verbo transitiva
Causa la contrae de (texedas de corpo, tipal la pel); afeta (alga cosa) en manera o stilo sever
en   cause to contract, be astringent (anatomy)
he   (רפואה) לחסום, לכבול, לגרום לכיווץ

astro-   prefisa
Stelas
en   astro-
he   (קידומת טכנית) שקשור לכוכבים

astrobiolojia   nom
La ramo de biolojia cual studia organismes sur la Tera e en spasio
en   astrobiology
he   אסטרוביולוגיה

astrocimica   nom
en   astrochemistry
he   אסטרוכימיה

astrofisica   nom
La ramo de astronomia cual studia la natur fisical de stelas e otra ojetos sielal, e la aplica de leges e teorias de fisica a la interprete de oservas astronomial
en   astrophysics
he   אסטרופיזיקה

astrolabio   nom
Un aparato istorial usada per mesura avenis astronomial, tipal la altias de ojetos sielal, e en naviga per calcula latitude, ante la developa de la sestante
en   astrolabe (device)
he   אצטרולב

astrolojia   nom
La studia de la moves e locas relativa de ojetos sielal, interpretente los como afetante la mundo natural e umana
en   astrology
he   אסטרולוגיה

[astronauta] astronauta   nom
Un person instruida per viaja en spasio
en   astronaut, cosmonaut, spaceman, spacewoman
he   אסטרונאוט

astronautica   nom
en   astronautics
he   אסטרונאוטיקה

astronomia   nom
La siensa cual studia la spasio, ojetos sielal, e la universo fisical intera
en   astronomy
he   אסטרונומיה

[astruzo] astruzo   nom
Un avia de Africa cual pote core rapida ma no pote vola, con colo longa, gamas longa, e du ditos a cada pede
Struthio camelus
en   ostrich
he   יען

astur   ajetivo
Parteninte a un popla de xasores-coliores ci ia abita en la norde de Espania asta la sentenio prima aec
en   Astur, Astyr

[Asturias] Asturias   nom, plural
Un rejion autonom e un prinsia pasada en Espania norde
en   Asturias (Spanish region)
he   אסטוריאס

astuta   ajetivo
Capas de comprende, aprende e aplica ideas; capas de evalua situas o persones sin era; capas de ateni sua goles en modos intelijente o rusosa; capas de fa bromas verbal en modo rapida e inventosa
en   astute, clever, smart, cunning, savvy, shrewd, witty, incisive, punchy
he   פיקח, נבון, מתוחכם, שנון, מפולפל, ממולח, חריף

asurda   ajetivo
Multe nonrazonada, nonlojical o nonconveninte; fol; causante rie o burla
en   absurd, nonsensical, ludicrous, preposterous, ridiculous, risible, far-fetched
he   אבסורדי, מגוחך, לא הגיוני, שטותי

asusta   verbo transitiva
Causa multe teme o ansia
en   frighten, scare, terrify, horrify
he   להפחיד, להבהיל, להבעית, לזעזע, להטיל אימה

asustavia   nom, composada (verbo+nom)
Un ojeto semblante un figur umana, usada per asusta avias a via de un campo cultivada
en   scarecrow
he   דחליל

ata   verbo nontransitiva
Es ativa; fa alga cosa; presenta un rol en un teatro o filma
en   act
he   לפעול; לשחק (סרט, הצגה)

ataca   verbo transitiva
Ata forte combatosa o violente contra (un person, animal, loca o forte)
en   attack, assault, charge, storm, besiege, raid, aggress, assail, tackle, belabor/belabour
he   לתקוף, להסתער

[Atacama, Deserto] Atacama, Deserto   nom
Un rejion seca en Txile ueste cual estende a sirca mil cilometres de la frontera con Peru
en   Atacama Desert
he   מדבר אטקמה

[atalanta] atalanta   nom
Un papilio migrante con alas oscur cual ave bandas roja-orania e puntos blanca
Vanessa atalanta
en   red admiral (butterfly)
he   נימפיד הסרפד (פרפר)

atavisme   nom
Un retrosede (de un cualia) a un state antica
en   atavism
he   (ביולוגיה) אטביזם

ataxia   nom
La perde de controla de moves de la corpo
en   ataxia (medical)
he   אטקסיה, שיגשון, חוסר שליטה בשרירים

ateisme   nom   (dise ‘ateïsme’)
La crede ce no dio o dios esiste
en   atheism
he   אתאיזם

atende   verbo transitiva
Dirije sua sensas e pensas a (un person o cosa) cual on regarda como importante; acompania (algun) como un servor
nb   No usa "atende" per dise "cura".
→ cura
en   pay attention to, attend to, heed, take into account; keep an eye on, mind, look after, take care of (temporarily); attend, serve (master)
he   לשים לב ל-, לשים עין, להשגיח

ateni   verbo transitiva
Ariva a (un loca o conclui); reali (un gol) par labora, capasia o coraje; susede a (alga cosa)
en   reach, attain, achieve, accomplish, score; catch up with
he   להשיג, להגשים

atenta   verbo transitiva
Labora per fa (un taxe o ata difisil)
nb   No usa "atenta" per dise "proba".
→ proba
en   attempt, try, endeavor/endeavour, essay
he   לנסות

atera   verbo nontransitiva
(Un barcon o volador) ariva a la tera o un porto
en   land, make landfall, arrive at port
he   לנחות

ateroma   nom
Un dejenera de la mures de la arterias, causada par la cumula de deponedas grasosa e sicatrises
en   atheroma (medical)
he   רובד טרשתי

aterosclerose   nom
Un maladia en cual materia grasosa es deponeda sur la mures de arterias
en   atherosclerosis
he   טרשת העורקים

atesta   verbo transitiva
Declara la veria de (alga cosa) pos esperia mesma lo; furni informa como un indica clar de (alga cosa); serti ce (algun) es la person indicada, o ce el es un bon person
nb   No usa "atesta" per dise "vide".
en   attest, testify, give as evidence; vouch, acknowledge
he   להעיד, לאמת, לתמוך, לאשר

Atica   nom
Un promontania en Elas este, prosima a Atina
en   Attica (Greek region)
he   אטיקה (חבל ארץ ביוון)

Atina   nom
La site capital de Elas
en   Athens
he   אתונה

ativa   ajetivo
Partisipante en atas fisical enerjiosa; movente frecuente o enerjiosa; partisipante en alga campo de labora o sporte; pertinente a verbos de cual sua sujeto es tipal la faor de la ata, e cual pote aseta un ojeto direta
en   active, busy
he   אקטיבי, פעיל, פעלתני

atlantica   ajetivo
Pertinente a la Mar Atlantica o a la paises con costas a lo
en   Atlantic
he   אטלנטי

[Atlantida] Atlantida   nom
Un isola imajinada par Platon; la loca imajinada de un sivilia antica avansada e no plu esistente
en   Atlantis
he   אטלנטיס

Atlas   nom
en   Atlas
he   אטלס

atleta   nom
Un person ci es capas en sportes e otra formas de eserse fisical
en   athlete
he   אתלט

atmosfera   nom
La covrente de gases cual ensirca la Tera o un otra planeta
en   atmosphere
he   אטמוספירה

atol   nom
Un resife, isola o cadena de isolas anelo, formida de coral
en   atoll
he   אטול, שונית אלמוגים

atom   nom
La unia fundal de un elemento cimical, composada de un nucleo de protones e neutrones, ensircada par un nube de eletrones
en   atom
he   אטום

atonia   nom
Un maladia marcada par la asentia de tono musculal
en   atony (medical)
he   ריפיון שרירים

atrae   verbo transitiva
Fa ce (un person o cosa) veni o partisipa, par ofre un esperia o resulta desirable, o par la aplica de un forte nonvidable
en   attract, allure, entice
he   למשוך, לפתות

atribui   verbo transitiva
Opina ce (un cosa) es causada o scriveda o diseda par; opina ce (un cualia) parteni a
‹ atribui un cualia a algun; atribui esta obra a acel autor ›
en   attribute, credit (with)
he   לייחס, לזקוף, לתת קרדיט

[atricorno] atricorno   nom
Un avia cantante secretosa de Australia, con plumas brun e coda longa
Atrichornis
en   scrub-bird
he   ציפור שיחים

[atrio] atrio   nom
Un salon o patio sentral, con salas o galerias a cada lado; un salon a la entra de un construida publica; cada de la du cavetas superior de la cor, de cual sangue es pasada a la ventriculos
en   atrium, hall, lobby, foyer, vestibule
he   אטריום, מבואה, לובי, טרקלין, אולם כניסה; עליה (של הלב)

atrofia   verbo nontransitiva
(Un organo o texeda) dejenera e diminui, tipal par causa de dejenera de selulas, o deveni vestijial en evolui; (un capasia de mente o corpo) diminui gradal par causa de usa minima o descura
en   atrophy, wither
he   להדלדל, להתנוון

atropina   nom
Un composada venenosa, trovada en solano e plantas relatada, usada en medica per destensa musculos, per esemplo per dilata pupiles
en   atropine (substance)
he   אטרופין

atuario   nom
Un person ci colie e analise statisticas e usa los per calcula riscas en deside la custa de asecura
en   actuary
he   אקטואר

[aturdi] aturdi   verbo transitiva
Fa ce (algun) perde consensia o entra a un state duiconsensa; surprende (algun) ci deveni tempora noncapas de responde o reata
en   stun, daze, bewilder, bedazzle, befuddle, stupefy, knock out
he   להמם, להדהים, לתת נוקאאוט

au   esclama
Espresante un dole subita
en   ow, ouch
he   אוי, אאוצ’

[Auad] Auad   nom
Un rejion de Barat norde, aora un parte de Uttar Pradesh
en   Awadh, Audh, Oudh (Indian region)
he   אווד (איזור בצפון הודו)

audio   ajetivo
Pertinente a sona, spesial cuando rejistrada, transmeteda o reproduida
en   audio
he   שקשור לאודיו

audiolojia   nom
La ramo de siensa e medica cual studia la oia
en   audiology
he   אודיולוגיה

audiomanica   nom
Un person zelosa sur la bon reprodui de musica e otra sonas rejistrada
en   audiophile
he   אודיופיל

audiometre   nom
Un aparato per mesura la estende e sensosia de la sensa de oia de algun
en   audiometer
he   אודיומטר

audiovideo   ajetivo
(Un presenta) usante e imajes e sonas rejistrada
en   audiovisual
he   אודיו-ויזואלי

augur   nom
(En Roma antica) un ofisior relijial ci ia oserva sinias natural, spesial la condui de avias, e ia interprete estas como indicas de aproba o desaproba par la dios
en   augur
he   נביא, בעל אוב

[aulacode] aulacode   nom
Un rodente grande e ratin, trovada en la zona umida a sude de la Sahara, a veses un pesta per cultiverias de zucar
Thryonomys
en   cane rat
he   חולדת קנים

aulo   nom
Un strumento de venta de Elas antica, tipal con anxa duple, con sona forte e xiliante
en   aulos (musical instrument)
he   אאולוס (כלי נגינה)

aumenta   verbo nontransitiva
Deveni plu grande o forte par ajuntas
en   augment, increase, increment, supplement, boost, surge, redouble; appreciate (in value); tighten (rules)
he   להגדיל, להרחיב, להגביר, להוסיף

aura   nom
(En spiritisme) un emete nonvidable ma esensal cual ensirca un corpo vivente; un sensa avertinte esperiada ante un aveni de epilesia o migrania
en   aura
he   הילה; תחושה מקדימה להתקף מיגרנה או אפילפסיה

[aurora] aurora   nom
Un fenomeno de eletrica natural, marcada par bandas de lus rojin o verdin en la sielo, tipal prosima a la polo magnetal norde o sude
en   aurora
he   זוהר קוטבי

Australasia   nom
La parte de la Tera composada de Australia, Zeland Nova, Gine Nova, e la isolas visina en la Mar Pasifica
en   Australasia
he   אוסטרלאסיה

[Australia] Australia   nom
Un continente, isola e pais en la emisfera sude, en la Mar Pasifica sude-ueste
en   Australia
he   אוסטרליה

[australopiteco] australopiteco   nom
Un primate bipede con alga cualias umana, trovada como fosiles en Africa, en deponedas de la temprana de la pliosene e plestosene
Australopithecus
en   australopithecus (primate)
he   אוסטרולופיתקוס

austronesian   ajetivo
Pertinente a la familia de linguas parlada en la isolas de Asia sude-este e la Mar Pasifica, e en Madagasicara
en   Austronesian
he   אוסטרונזי

autentica   ajetivo
Con orijina nondisputada; con vera la identia o cualias cual on declara
en   authentic, genuine
fr   authentique, certifié
he   אותנטי, מקורי

autisme   nom
Un maladia mental, presente de la temprana de enfantia, marcada par difisiles en comunica e formi relatas con otras e en la usa de lingua e consetas astrata
en   autism
he   אוטיזם

[auto] auto   nom
Un veculo de strada, tipal con cuatro rotas, propulsada par motor, e capas de porta un cuantia peti de persones
→ automobil
en   car, automobile, auto
he   מכונית, רכב, אוטו

auto-   prefisa
Ajuntante la idea de automati o de pertine a se mesma
‹ autopilote; autodestrui ›
en   auto-, self- (reflexive or automatic action)
he   (קידומת) אוטומציה; ביחס לעצמו

[autoarpa] autoarpa   nom
Un tipo de sitra con aparato macinal cual permete la jua de un acorda par amorti tota otra cordetas
en   autoharp
he   אוטוהארפ (כלי נגינה)

[autocaravan] autocaravan   nom
Un veculo motorida per abita, conteninte letos e un cosina
en   motor home, recreational vehicle, RV, campervan
he   קרוואן, מעונוע, מגורון

autoclave   nom
Un contenador forte per produi reatas cimical e otra prosedes par usa presas e temperatures alta
en   autoclave
he   אוטוקלב

autocrata   ajetivo
Pertinente a un governa o renor con potia asoluta
en   autocratic, dictatorial, sovereign, totalitarian
he   אוטוקרטי, דיקטטורי

autoevidente   ajetivo
Tan evidente ce on no nesesa ajunta un esplica
en   self-evident
he   מובן מאליו, מדבר בעד עצמו

autogol   nom
(En futbal) un punto ganiada cuando un juor colpa la bal a en sua propre gol
en   own goal

[autojiro] autojiro   nom
Un veculo volante, simil a un elicotor, ma de cual sua veletas no es motorida ma es jirada par sua move tra aira, e de cual sua propulsa es furnida par un motor con elica
en   autogyro, autogiro, gyroplane, gyrocopter
he   אוטוג’ירו

automanica   nom
Un person multe interesada a autos
en   car enthusiast, automobilist
he   חובב מכוניות

automata   ajetivo
(Un aparato o prosede) operante par se mesma, con controla minima par umanas
en   automated, automatic
he   אוטומטי

[automobil] automobil   nom
Un auto
en   automobile, car
he   מכונית, רכב, אוטו

automorfe   ajetivo
(Un mineral) de cual sua forma esterna es controlada sola par sua strutur cristal interna; isomorfe a se
en   automorphic
he   אוטומורף (מינרל שצורתו החיצונית נקבעת על-ידי המבנה הגבישי הפנימי שלו)

autono   nom
La saison tre de la anio, cuando vejetales, sereales e frutas es colieda e folias cade, de setembre a novembre en la emisfera norde, e de marto a maio en la emisfera sude; la periodo de la ecuinote autonal a la solstisio invernal
en   autumn, fall
he   סתיו

autonom   ajetivo
Libre de controla par persones o cosas esterna; no dependente de la autoria de un otra; no dependente de un otra per comedas, abiteria, etc
en   autonomous, independent, self-governing, sovereign
he   אוטונומי, ריבוני

autopsia   nom
Un esamina de un corpo mor per determina la causa de mori, la estende de un maladia, etc
en   autopsy, postmortem
he   ניתוח לאחר המוות

autor   nom
La scrivor de un libro, article, o reporta; la creor de un idea o scema
en   author, writer, creator
he   מחבר, יוצר, סופר

autoria   nom
Un potia o direto de comanda, deside e forsa la obedi
en   authority, mandate, jurisdiction
fr   (l’) autorité
he   סמכות, מנדט

autoritar   ajetivo
(Un personalia) credente ce sua autoria debe es asoluta obedida
en   authoritarian, high-handed, bossy, officious
fr   autoritaire
he   אוטוריטרי, אדנותי, שתלטני

autostopa   verbo nontransitiva
Viaja par oteni pasaje libre en veculos acaso pasante
en   hitchhike
he   לתפוס טרמפ, לנסוע בטרמפ

autotrof   ajetivo
Pertinente a organismes capas de formi materias nurinte de materias nonorganica como diosido de carbono
en   autotrophic
he   (ביולוגיה) אוטוטרופי

[autovia] autovia   nom   (dise ‘autovía’)
Un strada major, tipal liante sites
en   motorway, highway, carriageway, superhighway, turnpike
he   כביש מהיר

a-uu   esclama
Un sona longa e lamentin como lo fada par un lupo
en   awhoo (howling)
he   יללת זאב

avalanxa   verbo nontransitiva
Un masa de neva, jela e rocas rapida cadente de la lado de un monte
en   avalanche
he   מפולת שלגים

avansa   verbo nontransitiva
Move a ante, tipal en modo fidante
en   advance, go forward, surge
he   להתקדם, ללכת קדימה

[avar] avar   ajetivo
Desirante forte e egoiste un cosa, tipal ricia e potia; protejente forte sua ricia
en   avaricious, greedy, acquisitive, grasping, rapacious; miserly, stingy, mean, grubby, close-fisted, tight-fisted
he   רודף בצע, חמדני; קמצן

avatar   nom
(En induisme) un incarne de un dio, diva o otra spirito con forma de person; un figur cual representa un person spesifada en juas o en foros de interede
en   avatar
he   אווטאר

ave   verbo transitiva
Posese, teni (un cosa); es marcada par (un cualia); es relatada a (un person)
en   have, own
he   להיות בעל דבר או תכונה, להחזיק ברשות דבר כלשהו

[avena] avena   nom
Un planta sereal, cultivada en climas fria; la gran de esta, comeda par umanas e animales
Avena
en   oat, oats
he   שיבולת שועל

aveni   verbo nontransitiva
(Un ata) es fada, o reali se
en   happen, occur, take place, transpire
he   לקרות, להתרחש

aventura   verbo nontransitiva
Partisipa en un ata stimulante, noncomun o perilosa; esplora un teritorio nonconoseda
en   adventure
he   להשתתף בהרפתקה

averbo   nom
Un parola descrivente, tipal usada per altera un verbo o formula verbin, un ajetivo o formula ajetivin, o un otra averbo o formula averbin
en   adverb
he   תואר הפועל

averti   verbo transitiva
Informa (algun) de un peril, problem o situa nonplasente cual el ta pote esperia en la futur
en   warn (of danger), caution
he   להזהיר, להתרות

avesta   nom
La scrivedas santa de zoroastrisme, scriveda en la sentenio 4 ec
en   avesta (scripture)
he   אווסתה

avi   nom
Un jenitor de un padre o madre
en   grandparent
he   סב, סבא, סבתא (כללי)

avia   nom
Un vertebrato oviparinte con sangue calda, plumas, alas, beco e tipal la capasia de vola
en   bird
he   ציפור

avicultur   nom
La eleva de avias
en   aviculture
he   גידול ציפורים, גידול עופות

[avion] avion   nom
Un veculo propulsada e volante, con alas fisada, cual pesa plu ca la aira cual lo desloca
en   airplane/aeroplane, aircraft
he   מטוס, אווירון

avionica   nom
Eletronica aplicada a aviones
en   avionics
he   אוויוניקה (מערכות אלקטרוניות במטוסים)

avisa   verbo transitiva
Informa (algun) sur alga cosa, tipal en modo formal, ofisial o automata
en   advise, notify, give notice, alert
he   לייעץ; להודיע

[avocado] avocado   nom
Un arbor perene de la tropicos de America Sentral; la fruta de esta, formida como un pera con pel ru e cuorin, pulpa comable, e seme grande
Persea americana
en   avocado (tree, fruit)
he   אבוקדו (עץ, פרי)

avocato   nom
Algun ci studia la lege per aida persones e organizas en casos legal
en   lawyer, barrister, solicitor, attorney, counsel
fr   avocat
he   עורך-דין

[avoseta] avoseta   nom
Un avia vadante, con gamas longa, beco magra e curvida a supra, e plumas con motifes cual saisi la oio
Recurvirostra
en   avocet (bird)
he   סייפן (ציפור)

ax   nom   «Æ æ»
Un letera vocal anglosason, oji usada en alga linguas scandinavian
en   ash, æsc

[axa] axa   nom
Un util tipal usada per talia lenio, tipal composada de un lamina pesosa de aser liada en angulo reta a un manico de lenio
en   axe/ax
he   גרזן

axcenazi   ajetivo
Pertinente a la iudis desendente de los en Europa sentral o este, ci conserva la tradisiones iudi de Filastin en loca de los de Babilonia
en   Ashkenazi (Judaism)
he   אשכנזי

axi   esclama   (dise ‘axí’)
La sona de un stornui peti
en   atishoo
he   אפצ’י (צליל התעטשות)

[axia] axia   nom
Un util simil a un axa, ma con lamina arcida, usada per talia o formi pesos grande de lenio
en   adze (tool)
he   קרדום

[axila] axila   nom
La caveta su la braso a la spala
en   armpit, underarm
he   בית-שחי

axiom   nom
Un declara o proposa cual on regarda como bon fundida, asetada o evidente; un declara o proposa sur cual un strutur astrata es fundida
en   axiom, convention, postulate
he   אקסיומה, הנחת יסוד, הנחה מוקדמת

axisa   nom
Un coordinada de ase x
en   abscissa (coordinate)
he   הציר המאוזן, ציר ה-x

Axoca   nom
La imperor de Barat en la sentenio 3 aec, ci ia institui budisme como la relijio de la stato
en   Ashoka (Indian emperor)
he   אשוקה (קיסר הודי)

[axolote] axolote   nom
Un salamandra mexican cual reteni tipal sua forma acual tra sua vive, ma es capas de reprodui
Ambystoma mexicanum
en   axolotl (amphibian)
he   אקסולוטל מקסיקני (דו-חי)

axram   nom
Un eremiteria o monceria, tipal en Asia sude
en   ashram (hermitage)
he   אשראם

axu   esclama   (dise ‘axú’)
La sona de un stornui forte
en   achoo
he   אפצ’י (צליל התעטשות)

[Axum] Axum   nom
Un site en Itiopia norde, la capital de la Rena de Axum entre la sentenios 1 e 6 ec
en   Aksum (Ethiopian city)
he   אקסום (עיר באתיופיה)

[azalea] azalea   nom
Un arboreta caduca con grupos de flores briliante colorida
Rhododendron, Pentanthera, Tsutsuji
en   azalea (plant)
es   azalea (planta)
he   אזליאה (צמח)

[Azerbaidjan] Azerbaidjan   nom
Un pais en Asia sude-ueste en la Caucasos a la costa ueste de la Mar Caspio
(capital: Baku)
en   Azerbaijan
es   Azerbaiyán
he   אזרבייג’ן

azimuta   nom
La dirije de un ojeto sielal, espresada como la distantia angulo entre la punto norde o sude de orizon e la punto do un sirculo vertical tra la corpo crusa la orizon
en   azimuth (astronomy)
es   acimut, azimut
he   אזימוט

[azor] azor   nom
Cualce de alga spesies grande de avias xasante de la emisfera norde
membros grande de
ca   astor
en   goshawk, hawk
es   azor
fr   autour
it   astori
he   נץ (ציפור)
pt   açor

azospermia   nom
La manca de spermas capas de move en la semin
en   azoospermia (medical)
he   (רפואה) אזוספרמיה

azotemia   nom
Un maladia marcada par grados nonormal alta de composadas conteninte nitrojen en la sangue
en   azotemia (medical)
es   azotemia, azoemia
he   (רפואה) אזוטמיה

[Azov, Mar] Azov, Mar   nom
Un estende de la Mar Negra, a sude de Ucraina
en   Sea of Azov
es   Mar de Azov
he   ים אזוב

[azul] azul   ajetivo
Briliante blu, como la sielo sin nubes
en   light blue, sky blue, baby blue, powder blue, azure
es   azul
fr   bleu clair, bleu ciel, azur
he   תכלת
